### ISSUE TITLE
Profile TGI with nsys launch/start/stop lead to Error: ShardCannotStart

### ISSUE THREAD

**Issue by Sxy-17** [huggingface/text-generation-inference#1014]
### System Info

Hardware: A100
Cargo version: 1.70.0
text-generation-launcher 1.0.3

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

I wanted to profile the Llama2 70B model and noticed in issue #863 that I could use the nsys launch tool. However, when I followed the same steps, I couldn't run the server successfully. However, it works perfectly if I run it without using nsys. 

The instruction is as follows: `CUDA_VISIBLE_DEVICES=2,3 nsys launch --session-new=test text-generation-launcher --model-id xxx --port 8080 --num-shard 2`

Currently, I have encountered two versions of error messages, one of which is:
```bash
2023-09-12T10:26:35.806859Z  INFO text_generation_launcher: Args { ...... }
2023-09-12T10:26:35.806897Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-09-12T10:26:35.807090Z  INFO download: text_generation_launcher: Starting download process.
2023-09-12T10:26:39.703370Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-09-12T10:26:41.012848Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-12T10:26:41.013379Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-12T10:26:41.013477Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-09-12T10:26:51.024346Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-12T10:26:51.024477Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-09-12T10:26:55.928813Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors. rank=0
2023-09-12T10:26:55.928864Z ERROR shard-manager: text_generation_launcher: Shard process was signaled to shutdown with signal 11 rank=0
2023-09-12T10:26:55.987215Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "xxx/anaconda3/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "yyy/text-generation-inference/server/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "yyy/text-generation-inference/server/text_generation_server/server.py", line 201, in serve
    asyncio.run(
  File "xxx/anaconda3/envs/tgi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "xxx/anaconda3/envs/tgi/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "xxx/anaconda3/envs/tgi/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "xxx/anaconda3/envs/tgi/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "xxx/anaconda3/envs/tgi/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "yyy/text-generation-inference/server/text_generation_server/server.py", line 148, in serve_inner
    model = get_model(
  File "yyy/text-generation-inference/server/text_generation_server/models/__init__.py", line 188, in get_model
    return FlashLlama(
  File "yyy/text-generation-inference/server/text_generation_server/models/flash_llama.py", line 61, in __init__
    torch.distributed.barrier(group=self.process_group)
  File "xxx/anaconda3/envs/tgi/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3330, in barrier
    work = group.barrier(opts=opts)
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue.

2023-09-12T10:26:56.023558Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-12T10:26:56.023582Z  INFO text_generation_launcher: Shutting down shards
2023-09-12T10:26:56.417566Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=1
Error: ShardCannotStart
```

The other is:
```bash
2023-09-12T10:29:41.434083Z  INFO text_generation_launcher: Args {......}
2023-09-12T10:29:41.434129Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-09-12T10:29:41.434310Z  INFO download: text_generation_launcher: Starting download process.
2023-09-12T10:29:45.977303Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-09-12T10:29:46.840226Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-12T10:29:46.840713Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-09-12T10:29:46.840736Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-12T10:29:56.851643Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-09-12T10:29:56.851643Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-12T10:29:59.754381Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors. rank=0
2023-09-12T10:29:59.754396Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors. rank=1
2023-09-12T10:29:59.754443Z ERROR shard-manager: text_generation_launcher: Shard process was signaled to shutdown with signal 11 rank=0
2023-09-12T10:29:59.754452Z ERROR shard-manager: text_generation_launcher: Shard process was signaled to shutdown with signal 11 rank=1
2023-09-12T10:29:59.854516Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-12T10:29:59.854553Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart

```

### Expected behavior

Successfully profiled the llama model service launched by TGI.

**Comment by Narsil** [comment]
Thanks for sharing the solution
