### ISSUE TITLE
how to text-generation-benchmark through the local tokenizer 

### ISSUE THREAD

**Issue by jessiewiswjc** [huggingface/text-generation-inference#1015]
The command i run in docker is

```
text-generation-benchmark --tokenizer-name /data/checkpoint-5600/
```

The error log is

```
2023-09-12T11:22:01.245495Z  INFO text_generation_benchmark: benchmark/src/main.rs:132: Loading tokenizer
2023-09-12T11:22:01.245966Z  INFO text_generation_benchmark: benchmark/src/main.rs:141: Downloading tokenizer
2023-09-12T11:22:31.270784Z  WARN cached_path::cache: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cached-path-0.6.1/src/cache.rs:564: ETAG fetch failed for https://huggingface.co//data/checkpoint-5600//resolve/main/tokenizer.json, retrying in 1957 milliseconds...    
2023-09-12T11:23:03.228297Z  WARN cached_path::cache: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cached-path-0.6.1/src/cache.rs:564: ETAG fetch failed for https://huggingface.co//data/checkpoint-5600//resolve/main/tokenizer.json, retrying in 2202 milliseconds...    
2023-09-12T11:23:35.430766Z  WARN cached_path::cache: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cached-path-0.6.1/src/cache.rs:564: ETAG fetch failed for https://huggingface.co//data/checkpoint-5600//resolve/main/tokenizer.json, retrying in 4671 milliseconds...    
2023-09-12T11:24:10.102170Z ERROR cached_path::cache: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cached-path-0.6.1/src/cache.rs:555: Max retries exceeded for https://huggingface.co//data/checkpoint-5600//resolve/main/tokenizer.json    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Model \"/data/checkpoint-5600/\" on the Hub doesn't have a tokenizer"', benchmark/src/main.rs:153:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
``` 

I notice `Downloading tokenizer` in error log, and i feel very strange about it beacause `/data/checkpoint-5600/` is my local model path. So i find the src code as following:

https://github.com/huggingface/text-generation-inference/blob/1f69fb9ed4fb91fe0bb9b94edda5729c67e6f02a/benchmark/src/main.rs#L134-L154

But i notice that only `tokenizer_config.json` in my local model path but no `tokenizer.json`. And i see that it is the same is as the hub model, for example https://huggingface.co/openlm-research/open_llama_7b_v2/tree/main

Then i want to bypass by renaming `tokenizer_config.json` to `tokenizer.json` in my local model path, it still doesn't work:

```
2023-09-12T11:29:52.461487Z  INFO text_generation_benchmark: benchmark/src/main.rs:132: Loading tokenizer
2023-09-12T11:29:52.462513Z  INFO text_generation_benchmark: benchmark/src/main.rs:138: Found local tokenizer
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 2, column: 18)', benchmark/src/main.rs:139:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

Finally i want to know the `tokenizer_config.json` and `tokenizer.json` expressed here are the same thing?

**Comment by Fr4nk1inCs** [comment]
Same issue while trying to use local Baichuan-7B tokenizer.

**Comment by Narsil** [comment]
The tokenizer is `tokenizer.json` not `tokenizer_config.json`. You need to convert them first (Usually as simple as `tokenizer = AutoTokenizer.from_pretrained('xxx"); tokenizer.save_pretrained("yyyyy")`

**Comment by LMX-xin** [comment]
> The tokenizer is `tokenizer.json` not `tokenizer_config.json`. You need to convert them first (Usually as simple as `tokenizer = AutoTokenizer.from_pretrained('xxx"); tokenizer.save_pretrained("yyyyy")`

I tried to convert them,but  tokenizer.json was not generated
```
tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/Baichuan2-13B-Chat", use_fast=False, trust_remote_code=True)
tokenizer.save_pretrained("./tokenizer/")
```
output:
```
('./tokenizer/tokenizer_config.json',
 './tokenizer/special_tokens_map.json',
 './tokenizer/tokenizer.model',
 './tokenizer/added_tokens.json')
```

**Comment by OlivierDehaene** [comment]
text-generation-benchmark expects a fast tokenizer (aka a Rust one). In your case `use_fast=False` when you export the tokenizer.

**Comment by pengliaochirs** [comment]
> text-generation-benchmark expects a fast tokenizer (aka a Rust one). In your case `use_fast=False` when you export the tokenizer.

I set `use_fast=True`, but still generate tokenizer_config.json and tokenizer.model files.

**Comment by Revo-Future** [comment]
same issue, the issue should reopen
