### ISSUE TITLE
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by a1164714** [huggingface/text-generation-inference#1026]
### System Info

```
$ text-generation-launcher --env
2023-09-14T12:55:48.432383Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.72.0
Commit sha: 4cce84301b9f0f3472cf8b54e3119afd87caa09e
Docker label: N/A
nvidia-smi:
Thu Sep 14 20:55:48 2023       
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                               |                      |               MIG M. |
   |===============================+======================+======================|
   |   0  A100-SXM4-40GB      On   | 00000000:CB:00.0 Off |                    0 |
   | N/A   32C    P0    53W / 400W |      0MiB / 40537MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
   |   1  A100-SXM4-40GB      On   | 00000000:D0:00.0 Off |                    0 |
   | N/A   32C    P0    54W / 400W |      0MiB / 40537MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
                                                                                  
   +-----------------------------------------------------------------------------+
   | Processes:                                                                  |
   |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
   |        ID   ID                                                   Usage      |
   |=============================================================================|
   |  No running processes found                                                 |
   +-----------------------------------------------------------------------------+

$ cargo version
cargo 1.72.0 (103a7ff2e 2023-08-15)

$ pip list
Package                                Version    Editable project location
-------------------------------------- ---------- --------------------------------------
accelerate                             0.20.3
aiohttp                                3.8.5
aiosignal                              1.3.1
anyio                                  3.7.1
async-timeout                          4.0.3
attrs                                  23.1.0
backoff                                2.2.1
certifi                                2023.7.22
charset-normalizer                     3.2.0
click                                  8.1.7
cmake                                  3.27.4.1
custom-kernels                         0.0.0
datasets                               2.14.4
Deprecated                             1.2.14
dill                                   0.3.7
dropout-layer-norm                     0.1
einops                                 0.6.1
exceptiongroup                         1.1.3
fastapi                                0.103.1
filelock                               3.12.3
flash-attn                             1.0.8
frozenlist                             1.4.0
fsspec                                 2023.6.0
googleapis-common-protos               1.60.0
grpc-interceptor                       0.15.3
grpcio                                 1.57.0
grpcio-reflection                      1.57.0
grpcio-status                          1.57.0
grpcio-tools                           1.51.1
h11                                    0.14.0
hf_transfer                            0.1.3
huggingface-hub                        0.16.4
idna                                   3.4
Jinja2                                 3.1.2
jsonschema                             4.19.0
jsonschema-specifications              2023.7.1
lit                                    16.0.6
loguru                                 0.6.0
MarkupSafe                             2.1.3
mpmath                                 1.3.0
msgpack                                1.0.5
multidict                              6.0.4
multiprocess                           0.70.15
mypy-protobuf                          3.4.0
networkx                               3.1
ninja                                  1.11.1
numpy                                  1.25.2
nvidia-cublas-cu11                     11.10.3.66
nvidia-cuda-cupti-cu11                 11.7.101
nvidia-cuda-nvrtc-cu11                 11.7.99
nvidia-cuda-runtime-cu11               11.7.99
nvidia-cudnn-cu11                      8.5.0.96
nvidia-cufft-cu11                      10.9.0.58
nvidia-curand-cu11                     10.2.10.91
nvidia-cusolver-cu11                   11.4.0.1
nvidia-cusparse-cu11                   11.7.4.91
nvidia-nccl-cu11                       2.14.3
nvidia-nvtx-cu11                       11.7.91
opentelemetry-api                      1.15.0
opentelemetry-exporter-otlp            1.15.0
opentelemetry-exporter-otlp-proto-grpc 1.15.0
opentelemetry-exporter-otlp-proto-http 1.15.0
opentelemetry-instrumentation          0.36b0
opentelemetry-instrumentation-grpc     0.36b0
opentelemetry-proto                    1.15.0
opentelemetry-sdk                      1.15.0
opentelemetry-semantic-conventions     0.36b0
packaging                              23.1
pandas                                 2.0.3
peft                                   0.4.0
Pillow                                 10.0.0
pip                                    23.2.1
protobuf                               4.24.2
psutil                                 5.9.5
pyarrow                                13.0.0
pydantic                               1.10.12
python-dateutil                        2.8.2
pytz                                   2023.3
PyYAML                                 6.0.1
ray                                    2.6.3
referencing                            0.30.2
regex                                  2023.8.8
requests                               2.31.0
rotary-emb                             0.1
rpds-py                                0.10.2
safetensors                            0.3.3
scipy                                  1.11.2
sentencepiece                          0.1.99
setuptools                             68.1.2
six                                    1.16.0
sniffio                                1.3.0
starlette                              0.27.0
sympy                                  1.12
text-generation-server                 1.0.3      /root/text-generation-inference/server
texttable                              1.6.7
tokenizers                             0.13.3
torch                                  2.0.1
tqdm                                   4.66.1
transformers                           4.32.1
triton                                 2.0.0
typer                                  0.6.1
types-protobuf                         4.24.0.1
typing_extensions                      4.7.1
tzdata                                 2023.3
urllib3                                1.26.6
uvicorn                                0.23.2
vllm                                   0.0.0
wheel                                  0.41.2
wrapt                                  1.15.0
xformers                               0.0.21
xxhash                                 3.3.0
yarl                                   1.9.2
```

### Information

- [ ] Docker
- [x] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
$ text-generation-launcher --model-id /root/models--meta-llama--Llama-2-13b-chat-hf/snapshots/0ba94ac9b9e1d5a0037780667e8b219adde1908c --trust-remote-code --port 8081
2023-09-14T12:53:54.063737Z  INFO text_generation_launcher: Args { model_id: "/root/models--meta-llama--Llama-2-13b-chat-hf/snapshots/0ba94ac9b9e1d5a0037780667e8b219adde1908c", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "ts-dc50230b1fad435b965e837287be6a7c-launcher", port: 8081, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-09-14T12:53:54.063771Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `/root/models--meta-llama--Llama-2-13b-chat-hf/snapshots/0ba94ac9b9e1d5a0037780667e8b219adde1908c` do not contain malicious code.
2023-09-14T12:53:54.063852Z  INFO download: text_generation_launcher: Starting download process.
2023-09-14T12:53:56.046735Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-09-14T12:53:56.465306Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-14T12:53:56.465524Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-14T12:54:00.208179Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/usr/local/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/usr/local/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/text-generation-inference/server/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/root/text-generation-inference/server/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/root/text-generation-inference/server/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(
  File "/root/text-generation-inference/server/text_generation_server/models/__init__.py", line 187, in get_model
    return FlashLlama(
  File "/root/text-generation-inference/server/text_generation_server/models/flash_llama.py", line 32, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()
  File "/root/text-generation-inference/server/text_generation_server/utils/dist.py", line 54, in initialize_torch_distributed
    torch.cuda.set_per_process_memory_fraction(MEMORY_FRACTION, device)
  File "/usr/local/lib/python3.9/site-packages/torch/cuda/memory.py", line 118, in set_per_process_memory_fraction
    torch._C._cuda_setMemoryFraction(fraction, device)
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2023-09-14T12:54:00.767765Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Traceback (most recent call last):

  File "/usr/local/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/root/text-generation-inference/server/text_generation_server/cli.py", line 81, in serve
    server.serve(

  File "/root/text-generation-inference/server/text_generation_server/server.py", line 195, in serve
    asyncio.run(

  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/root/text-generation-inference/server/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(

  File "/root/text-generation-inference/server/text_generation_server/models/__init__.py", line 187, in get_model
    return FlashLlama(

  File "/root/text-generation-inference/server/text_generation_server/models/flash_llama.py", line 32, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()

  File "/root/text-generation-inference/server/text_generation_server/utils/dist.py", line 54, in initialize_torch_distributed
    torch.cuda.set_per_process_memory_fraction(MEMORY_FRACTION, device)

  File "/usr/local/lib/python3.9/site-packages/torch/cuda/memory.py", line 118, in set_per_process_memory_fraction
    torch._C._cuda_setMemoryFraction(fraction, device)

RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

 rank=0
2023-09-14T12:54:00.866399Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-14T12:54:00.866433Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

### Expected behavior

launch success

**Comment by WinwayJia** [comment]
+1

**Comment by OlivierDehaene** [comment]
Can you upgrade your nvidia drivers? `Driver Version: 450.80.02` is very old and only support cuda up to 11.0 while TGI uses cuda 11.8.
