### ISSUE TITLE
GPTQ config not picked up

### ISSUE THREAD

**Issue by srka99** [huggingface/text-generation-inference#1027]
### System Info

`docker run --gpus all -e GPTQ_BITS=4 -e GPTQ_GROUPSIZE=32  -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id TheBloke/CodeLlama-34B-Instruct-GPTQ --revision gptq-4bit-32g-actorder_True --quantize gptq`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Just run the docker command from above.
### Logs
```
2023-09-08T02:41:23.437900Z  INFO text_generation_launcher: Args { model_id: "TheBloke/CodeLlama-34B-Instruct-GPTQ", revision: Some("gptq-4bit-32g-actorder_True"), validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Gptq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "hostname", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-09-08T02:41:23.438009Z  INFO download: text_generation_launcher: Starting download process.
2023-09-08T02:41:25.850890Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-09-08T02:41:26.240869Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-08T02:41:26.241382Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-08T02:41:30.648305Z  INFO text_generation_launcher: Using exllama kernels

2023-09-08T02:41:30.654582Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 187, in get_model
    return FlashLlama(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 68, in __init__
    model = FlashLlamaForCausalLM(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 461, in __init__
    self.model = FlashLlamaModel(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 399, in __init__
    [
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 400, in <listcomp>
    FlashLlamaLayer(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 336, in __init__
    self.self_attn = FlashLlamaAttention(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 218, in __init__
    self.o_proj = TensorParallelRowLinear.load(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 361, in load
    get_linear(weight, bias, config.quantize),
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 233, in get_linear
    linear = Ex4bitLinear(qweight, qzeros, scales, g_idx, bias, bits, groupsize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/exllama.py", line 114, in __init__
    assert groupsize == self.groupsize
AssertionError
2023-09-08T02:41:31.245302Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-08T02:41:31.245320Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

### Workaround
I reversed the change in `Weights._get_gptq_params()` in file `server/text_generation_server/utils/weights.py` made in [this commit](https://github.com/huggingface/text-generation-inference/commit/a0d55358d20cf3f86083b79765b80704ce9d8404), so it loads from env vars instead of reading conifg files. That worked, and is fine for my use case, but loading from files should probably be fixed and I didn't have enough time to debug why it's not working. `config.json` [from the model repo](https://huggingface.co/TheBloke/CodeLlama-34B-Instruct-GPTQ/blob/gptq-4bit-32g-actorder_True/config.json) looks good.

### Expected behavior

Model should be loaded succesfully, and GPTQ config should be picked up from `config.json`

**Comment by Pyroserenus** [comment]
Loading models with act-order false seems to be working correctly, There is some issue with act-order either not being supported correctly or not being read from config
