### ISSUE TITLE
Error launching bloom-560m

### ISSUE THREAD

**Issue by rohithkrn** [huggingface/text-generation-inference#104]
Steps to reproduce:
Followed local install steps in README.md
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

conda create -n text-generation-inference python=3.9 
conda activate text-generation-inference


PROTOC_ZIP=protoc-21.12-linux-x86_64.zip
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP
```

```
BUILD_EXTENSIONS=False make install
```

```
make run-bloom-560m
```

Error log:

```
2023-03-07T16:29:23.429743Z  INFO text_generation_launcher: Successfully downloaded weights.                                                                                                                  
2023-03-07T16:29:23.429988Z  INFO text_generation_launcher: Starting shard 0                                                                                                                                  
2023-03-07T16:29:23.430031Z  INFO text_generation_launcher: Starting shard 1                                                                                                                                  
2023-03-07T16:29:28.535903Z ERROR text_generation_launcher: Shard 1 failed to start:                                                                                                                          
We're not using custom kernels.                                                                                                                                                                               
thread '<unnamed>' panicked at 'range end index 1091153541 out of range for slice of length 1048576000', src/lib.rs:817:29                                                                                    
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                            
  File "/home/ubuntu/rubikon/py39_env/bin/text-generation-server", line 8, in <module>                                                                                                                        
    sys.exit(app())                                                                                                                                                                                           
  File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/typer/main.py", line 311, in __call__ 
    return get_command(self)(*args, **kwargs)
  File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/rubikon/py39_env/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/ubuntu/rubikon/text-generation-inference/server/text_generation/cli.py", line 55, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File "/home/ubuntu/rubikon/text-generation-inference/server/text_generation/server.py", line 130, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ubuntu/rubikon/text-generation-inference/server/text_generation/server.py", line 99, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File "/home/ubuntu/rubikon/text-generation-inference/server/text_generation/models/__init__.py", line 57, in get_model
    return BLOOMSharded(model_id, revision, quantize=quantize)
  File "/home/ubuntu/rubikon/text-generation-inference/server/text_generation/models/bloom.py", line 86, in __init__
    self.load_weights(
  File "/home/ubuntu/rubikon/text-generation-inference/server/text_generation/models/bloom.py", line 156, in load_weights
    tensor = slice_[:]
pyo3_runtime.PanicException: range end index 1091153541 out of range for slice of length 1048576000

2023-03-07T16:29:28.535989Z  INFO text_generation_launcher: Shutting down shards
make: *** [Makefile:25: run-bloom-560m] Error 1
```

**Comment by OlivierDehaene** [comment]
Can you delete the huggingface hub cache and re-try? I think this is because you have a corrupted weight file.
Could you also link your `hf_transfer` version?

```shell
pip freeze |grep hf_transfer
```

**Comment by rohithkrn** [comment]
Thanks. Deleting the cache and re-trying fixed the above failure. However, its strange why it failed the first time because it downloaded the model on the fly and it did not have anything in the cache before.
I have `hf_transfer==0.1.2` installed.

I am running into connection refused error when trying to run inference.

Steps:
Below command succeeds
```
BUILD_EXTENSIONS=False make install
make run-bloom-560m
```

Below command returns error - `curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused`
```
curl 127.0.0.1:8080/generate \
    -X POST \
    -d '{"inputs":"Testing API","parameters":{"max_new_tokens":9}}' \
    -H 'Content-Type: application/json'
```

I also tried to run 
```
make server-dev
make router-dev
```
curl request fails after this as well.

**Comment by OlivierDehaene** [comment]
The webserver is running on port 3000 by default.

**Comment by rohithkrn** [comment]
Thanks, works now.

**Comment by rohithkrn** [comment]
Also, I was trying to use `generate_stream` api.
Example request:
`curl 127.0.0.1:3000/generate_stream     -X POST     -d '{"inputs":"Amazon is","parameters":{"max_new_tokens":20}}'     -H 'Content-Type: application/json'`

I only see generated text in the last result. With stream api, isn't it supposed to return token by token?
Output:
```
data:{"token":{"id":267,"text":" a","logprob":-2.046875,"special":false},"generated_text":null,"details":null}                                                                                                 
                                                                                                                                                                                                               
data:{"token":{"id":10087,"text":" great","logprob":-2.234375,"special":false},"generated_text":null,"details":null}                                                                                           
                                                                                                                                                                                                               
data:{"token":{"id":4676,"text":" way","logprob":-1.9453125,"special":false},"generated_text":null,"details":null}                                                                                             
                                                                                                                                                                                                               
data:{"token":{"id":427,"text":" to","logprob":-0.16210938,"special":false},"generated_text":null,"details":null}                                                                                              
                                                                                                                                                                                                               
data:{"token":{"id":2213,"text":" get","logprob":-2.84375,"special":false},"generated_text":null,"details":null}                                                                                               
                                                                                                                                                                                                               
data:{"token":{"id":267,"text":" a","logprob":-2.984375,"special":false},"generated_text":null,"details":null}                                                                                                 
                                                                                                                                                                                                               
data:{"token":{"id":2084,"text":" new","logprob":-3.953125,"special":false},"generated_text":null,"details":null}                                                                                              
                                                                                                                                                                                                               
data:{"token":{"id":39222,"text":" iPhone","logprob":-2.515625,"special":false},"generated_text":null,"details":null}                                                                                          
                                                                                                                                                                                                               
data:{"token":{"id":15,"text":",","logprob":-1.5078125,"special":false},"generated_text":null,"details":null}                                                                                                  

data:{"token":{"id":530,"text":" and","logprob":-2.359375,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":267,"text":" a","logprob":-3.046875,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":2084,"text":" new","logprob":-1.828125,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":99607,"text":" iPad","logprob":-0.4609375,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":15,"text":",","logprob":-1.3828125,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":530,"text":" and","logprob":-1.65625,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":267,"text":" a","logprob":-1.140625,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":2084,"text":" new","logprob":-0.11328125,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":10677,"text":" Mac","logprob":-1.6484375,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":15,"text":",","logprob":-1.7734375,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":530,"text":" and","logprob":-0.35351562,"special":false},"generated_text":" a great way to get a new iPhone, and a new iPad, and a new Mac, and","details":null}
```

**Comment by rohithkrn** [comment]
sorry, my bad - the text field has token by token information.

**Comment by OlivierDehaene** [comment]
No, text-generation-inference does not support beam search and might never support it.

**Comment by stalkermustang** [comment]
> No, text-generation-inference does not support beam search and might never support it.

Hey @OlivierDehaene , could you please tell us the reason behind this? For many (not that large) LMs, this will be VERY useful. As for now, the only way to get candidates from LMs is to send multiple requests with different seeds, which lacks caching and algo optimizations.

**Comment by Narsil** [comment]
Have you tried `best_of` ?

**Comment by stalkermustang** [comment]
> Have you tried `best_of` ?

yes, and it returns only one candidate. I'd like to apply filters & ranker (another model) on top of the generated candidates. So what am I asking is there a way to get several candidates at once

**Comment by McDonnellJoseph** [comment]
Hello, why does TGI not support beam_search is there a design reason behind this ?
