### ISSUE TITLE
ValueError: gptq quantization is not supported for AutoModel

### ISSUE THREAD

**Issue by aresa7796** [huggingface/text-generation-inference#1053]
### System Info

GPU: T4

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

> model=csdc-atl/Baichuan2-7B-Chat-GPTQ-Int4
volume=$PWD/data
docker run --gpus all  -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id $model --trust-remote-code --quantize gptq

I got a log:
```
(python3) sh-4.2$ docker run --gpus all  -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-infer.3 --model-id /data/$model --trust-remote-code --quantize gptq
2023-09-25T06:23:05.806032Z  INFO text_generation_launcher: Args { model_id: "/data/Baichuan2-7B-Chat-GPTQ-Int4", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Gptq), dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "632143116f1d", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-09-25T06:23:05.806062Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `/data/Baichuan2-7B-Chat-GPTQ-Int4` do not contain malicious code.
2023-09-25T06:23:05.806160Z  INFO download: text_generation_launcher: Starting download process.
2023-09-25T06:23:08.643467Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-09-25T06:23:09.109102Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-25T06:23:09.109321Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-25T06:23:12.028987Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

2023-09-25T06:23:12.105201Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 268, in get_model
    raise ValueError(
ValueError: gptq quantization is not supported for AutoModel, you can try to quantize it with `text-generation-server quantize ORIGINAL_MODEL_ID NEW_MODEL_ID`

2023-09-25T06:23:12.612666Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 268, in get_model
    raise ValueError(

ValueError: gptq quantization is not supported for AutoModel, you can try to quantize it with `text-generation-server quantize ORIGINAL_MODEL_ID NEW_MODEL_ID`
 rank=0
2023-09-25T06:23:12.711767Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-25T06:23:12.711800Z  INFO text_generation_launcher: Shutting down shards
```

### Expected behavior

Can you help me ? @Narsil @OlivierDehaene

**Comment by abhinavkulkarni** [comment]
@aresa7796: GPT-Q is not supported for `AutoModel`, but only for specific models such as Llama, Falcon, MPT, etc. If your model is not one of those, then you can't use GPT-Q.

**Comment by Narsil** [comment]
At least until/if there's support in `transformers` directly through optimum that is correct.

**Comment by Narsil** [comment]
But it's odd, since Baichuan should be supported.

On Compute 7.5 you need to install Flash V1 (not v2, it cannot be run on such cards)

**Comment by MachLearnPort** [comment]
I am getting this error when running the TGI container on Sagemaker. To my understanding, it should be able to work after selecting the appropriate model and setting the quantize flag. Am I missing something - or could this be Sagemaker specific?

**Comment by WernerDreierB** [comment]
> On Compute 7.5 you need to install Flash V1 (not v2, it cannot be run on such cards)
@Narsil what dou you mean "install Flash V1"? isn't it bundled already within the TGI-Docker-Image?
