### ISSUE TITLE
AWQ Out of Memory (but not really) Cuda Error

### ISSUE THREAD

**Issue by HarmonyTechLabs** [huggingface/text-generation-inference#1067]
# Issue Summary
When launching AWQ model, the model loads successfully, but fails allocation of memory during warm-up. This does not happen with nf4/fp4 no testing done on GPTQ.

# System info
**OS:**
`Linux version 6.1.55-1-lts (linux-lts@archlinux) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.41.0) #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 16:57:15 +0000`

**TGI --env:**
```
2023-09-26T21:45:57.990023Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: N/A
Docker label: N/A
nvidia-smi:
Tue Sep 26 21:45:57 2023
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  NVIDIA GeForce RTX 3090        Off | 00000000:27:00.0 Off |                  N/A |
   |  0%   25C    P8              20W / 420W |      2MiB / 24576MiB |      0%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+
   |   1  NVIDIA GeForce RTX 3090        Off | 00000000:28:00.0 Off |                  N/A |
   |  0%   25C    P8              34W / 370W |      2MiB / 24576MiB |      0%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+

   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   |  No running processes found                                                           |
   +---------------------------------------------------------------------------------------+
2023-09-26T21:45:57.990063Z  INFO text_generation_launcher: Args { model_id: "TheBloke/Llama-2-70B-AWQ", revision: None, validation_workers: 2, sharded: None, num_shard: Some(2), quantize: Some(Awq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "9766b879ae44", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: true }
```

**Run Command:**
`docker run --gpus all --shm-size 1g -p 8085:80 -e HF_HUB_ENABLE_HF_TRANSFER=1 -v ssdStorage/docker/STATIC/tgi-data:/data registry.braingoo.int/text-generation-inference:latest --model-id TheBloke/Llama-2-70B-AWQ --quantize awq --num-shard 2`

# Error output

```
2023-09-26T21:47:44.470545Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-09-26T21:47:44.470706Z  INFO download: text_generation_launcher: Starting download process.
2023-09-26T21:47:46.639392Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-09-26T21:47:46.973998Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-26T21:47:46.974552Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-09-26T21:47:46.974555Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-26T21:47:56.994024Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-26T21:47:56.994296Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-09-26T21:47:57.912469Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-09-26T21:47:57.928594Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-1

2023-09-26T21:47:57.994931Z  INFO shard-manager: text_generation_launcher: Shard ready in 11.019594826s rank=0
2023-09-26T21:47:57.995207Z  INFO shard-manager: text_generation_launcher: Shard ready in 11.020084236s rank=1
2023-09-26T21:47:58.086545Z  INFO text_generation_launcher: Starting Webserver
2023-09-26T21:47:58.499085Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2023-09-26T21:47:58.499108Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2023-09-26T21:47:58.718359Z  INFO text_generation_router: router/src/main.rs:371: Serving revision 59a09b9076e7ff721fe1d4332a912e5c605c01cb of model TheBloke/Llama-2-70B-AWQ
2023-09-26T21:47:58.850881Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-09-26T21:48:00.969056Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 753, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 851, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 839, in generate_token
    out = self.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 815, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 493, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 452, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 396, in forward
    mlp_output = self.mlp(normed_attn_res_output)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 340, in forward
    gate_up_states = self.gate_up_proj(hidden_states)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 277, in forward
    return self.linear.forward(x)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/awq/quantize/qmodule.py", line 46, in forward
    out = awq_inference_engine.gemm_forward_cuda(x.reshape(-1, x.shape[-1]), self.qweight, self.scales, self.qzeros, 8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.75 GiB (GPU 0; 23.69 GiB total capacity; 18.15 GiB already allocated; 1.24 GiB free; 23.69 GiB allowed; 22.08 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 82, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 66, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 755, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

2023-09-26T21:48:00.969072Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 753, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 851, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 839, in generate_token
    out = self.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 815, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 493, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 452, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 396, in forward
    mlp_output = self.mlp(normed_attn_res_output)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 340, in forward
    gate_up_states = self.gate_up_proj(hidden_states)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 277, in forward
    return self.linear.forward(x)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/awq/quantize/qmodule.py", line 46, in forward
    out = awq_inference_engine.gemm_forward_cuda(x.reshape(-1, x.shape[-1]), self.qweight, self.scales, self.qzeros, 8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.75 GiB (GPU 1; 23.69 GiB total capacity; 18.15 GiB already allocated; 1.24 GiB free; 23.69 GiB allowed; 22.08 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 82, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 66, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 755, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

2023-09-26T21:48:00.969429Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
2023-09-26T21:48:00.969462Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))
2023-09-26T21:48:00.991300Z ERROR text_generation_launcher: Webserver Crashed
2023-09-26T21:48:00.991310Z  INFO text_generation_launcher: Shutting down shards
2023-09-26T21:48:01.059931Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
2023-09-26T21:48:01.103149Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=1
Error: WebserverFailed
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Steps to reproduce:

1. Build or pull image
2. Run with `docker run --gpus all --shm-size 1g -p 8085:80 -e HF_HUB_ENABLE_HF_TRANSFER=1 -v ssdStorage/docker/STATIC/tgi-data:/data registry.braingoo.int/text-generation-inference:latest --model-id TheBloke/Llama-2-70B-AWQ --quantize awq --num-shard 2`

memory use is well below the requirements, over 4 gigs of memory left per card.
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.75 GiB (GPU 1; 23.69 GiB total capacity; 18.15 GiB already allocated; 1.24 GiB free; 23.69 GiB allowed; 22.08 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Expected behavior

Launches with AWQ model loaded.

**Comment by Narsil** [comment]
Is this constant ? 

Could be just a lot of fragmentation (which would be odd, but it could happen)

**Comment by HarmonyTechLabs** [comment]
> Does this happen every single time ?
> 
> Could be just a lot of fragmentation (which would be odd, but it could happen)

Correct, this is every time with every AWQ model I've tried. I've even tried setting the allowed/max tokens to 1 and it OOMs.

**Comment by HarmonyTechLabs** [comment]
I have tried with commit #1045 and have the same error output.

**Comment by abhinavkulkarni** [comment]
@HarmonyTechLabs: Can you please try specifying a range of values for `--max-input-length`, `--max-total-tokens` and  `--max-batch-prefill-tokens` command line parameters?

For e.g., here's how you could bring up TGI:

```
$ text-generation-launcher \
  --model-id abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
  --trust-remote-code --port 8080 \
  --max-input-length 5376 --max-total-tokens 6144 --max-batch-prefill-tokens 6144 \
  --quantize awq
```

Start from low values and try going up as much as you can before you hit OOM issues.

**Comment by HarmonyTechLabs** [comment]
This is very odd. I can load AWQ models with max-total and max-batch at 2048, anything higher and I OOM with well over 4 gigs of vRAM left on both cards, where as with both GPTQ and BnB-hf4 I can run up to 12k Total/prefill context without issue. Is this an inefficiency with the AWQ quantization format?

**Comment by abhinavkulkarni** [comment]
@HarmonyTechLabs, @Narsil: I can confirm that I am also facing the same issue with Llama-7B on RTX 3060 (12GiB VRAM).

Before I could easily load it with full 4096 context size, but now I can't. I think it was working after AWQ branch was merged, probably the later commits have caused some issue.

**Comment by abhinavkulkarni** [comment]
@Narsil: In fact, I can confirm that I am facing similar problems with GPTQ as well with latest commits.

**Comment by abhinavkulkarni** [comment]
@HarmonyTechLabs: I can confirm that I able to restore the order by checking out commit `2f51645ad7274f8d533a211804b74507263a946c` on `main` branch and building from it.

**Comment by HarmonyTechLabs** [comment]
@abhinavkulkarni much appreciated! I'll get that building.

**Comment by HarmonyTechLabs** [comment]
I do have good news, the command below launches fine and is able to process on commit `2f51645ad7274f8d533a211804b74507263a946c`:
`docker run --gpus all --shm-size 1g -p 8085:80 -e HF_HUB_ENABLE_HF_TRANSFER=1 -v ssdStorage/docker/STATIC/tgi-data:/data registry.braingoo.int/text-generation-inference:latest --model-id TheBloke/Xwin-LM-70B-V0.1-AWQ --quantize awq --num-shard 2 --max-batch-prefill-tokens 3072 --max-input-length 3000 --max-total-tokens 3072`

The only issue is that the context size is tiny compared to what can be run via hf4 and gptq which can run with `--max-batch-prefill-tokens 12000 --max-input-length 10000 --max-total-tokens 12000` on the same hardware.

**Comment by Narsil** [comment]
@OlivierDehaene Could mistral integration have changed this ? This is the only commit I see having an effect on memory requirements, with the 1.1.0 prep which contains a bunch of dependency upgrade.

**Comment by HarmonyTechLabs** [comment]
I can confirm the current main (`664c3d8ba2aae1e5ff817c57af192d34c864337f`) I can load AWQ models at 3300 max prefill/total. Still much lower than I would expect with the remaining memory across cards.

**Comment by abhinavkulkarni** [comment]
@HarmonyTechLabs, @Narsil: I am still facing the OOM problem with AWQ with the latest commit.

**Comment by dcruiz01** [comment]
Any updates here? Running into the same issue on my end with AWQ vs. GPTQ. Specifically, I can run inference on `Llama-2-7b-Chat-GPTQ` with default settings (e.g. not specifying max-prefill, total-tokens, etc), while `Llama-2-7B-chat-AWQ` gives me OOM issues on max prefill tokens.

**Comment by RawthiL** [comment]
The same is happening to me, I think. I can load a Llama-2-70B-Chat-GPTQ with 4096 tokens of context in 2x A10, but I cannot do the same with Llama-2-70B-Chat-AWQ.
The GPTQ reaches 20288MiB / 23028MiB  VRAM on each GPU.

The curious thing is that this does not happen with Llama-2-13B-Chat-XXX, these the GPTQ VRAM consumption is higher...:
- 13B GPTQ : 21534MiB / 23028MiB
- 13B AWQ : 19610MiB / 23028MiB

Any clue?
I'm using the docker image of TGI 1.1.0

**Comment by HarmonyTechLabs** [comment]
> Any updates here? Running into the same issue on my end with AWQ vs. GPTQ. Specifically, I can run inference on `Llama-2-7b-Chat-GPTQ` with default settings (e.g. not specifying max-prefill, total-tokens, etc), while `Llama-2-7B-chat-AWQ` gives me OOM issues on max prefill tokens. This is running on a 2080Ti using the main branch and latest TGI image.
> 
> Edit: added more details on local hardware.

Unfortunately it doesn't appear this is being looked at. I've tried with a fresh pull every 3 days to see if there is a resolution. I've had luck with the Aphrodite project that is being put together by the Pygmalion team (they also have support built in for ooba, kobold, and OpenAI APIs.) It can also just be installed via pip which makes it extremely easy to containerize.

**Comment by HarmonyTechLabs** [comment]
I am getting the same issue with the aphrodite project, so I am wondering if this is an AWQ issue. I have logged this ticket with them in hopes of getting this more attention.

https://github.com/mit-han-lab/llm-awq/issues/106

**Comment by HarmonyTechLabs** [comment]
Closing due to lack of interest

**Comment by codelion** [comment]
I had similar issue while using the HF inference endpoint service, but moving to A10 GPU instead of T4 seems to have fixed it.
