### ISSUE TITLE
GPTQ Models Failing to load In Kubernetes due to WarmUp Errors But Works in Docker

### ISSUE THREAD

**Issue by jrsperry** [huggingface/text-generation-inference#1085]
### System Info

TGI Version - 1.1.0

Models - 
TheBloke/Llama-2-7b-Chat-GPTQ

Nvidia SMI 
Kubernetes Env (L4 GPU) - NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
L4 GPU Docker (GCP Compute Instance) - NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0

OS
Docker - Debian GNU/Linux 11 (bullseye)
Kubernetes - Ubuntu 20.04.6 LTS (GKE Container-Optimized OS with containerd (cos_containerd))

Kubernetes Version - v1.26.6-gke.1700
Docker Version - Docker version 20.10.17, build 100c701

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Docker Command (Run on a L4 GPU in GCP) - 
`docker run --name bloke --gpus all -p 80:80 -e GPTQ_BITS="4" -e GPTQ_GROUPSIZE="128" -v /home/joshuasperry:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id TheBloke/Llama-2-7B-chat-GPTQ --quantize gptq --revision main`

Kubernetes Deployment 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thebloke
  namespace: text-gen-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: thebloke
  template:
    metadata:
      labels:
        component: thebloke
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          value: present
          effect: NoSchedule
      containers:
        - name: thebloke-container
          image: ghcr.io/huggingface/text-generation-inference:1.1.0
          command: ["text-generation-launcher", "--model-id", "TheBloke/Llama-2-7b-Chat-GPTQ", "--quantize", "gptq", "--num-shard", "1", "--revision", "main"]
          env:
          - name: GPTQ_BITS
            value: "4"
          - name: GPTQ_GROUPSIZE
            value: "128"
          ports:
            - containerPort: 80
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
```

### Expected behavior

I can't get the kubernetes deployment to work, It results in WarmUp/KeyError errors (pasted below). Interestingly the Docker command works just fine on the same hardware. I've done similar tests with the TheBloke/Llama-2-70B-GPTQ and TheBloke/Llama-2-13B-chat-GPTQ models as well with the same results. It doesn't really make any sense. Additionally, in kubernetes the meta-llama/Llama-2-7b-chat-hf model loads perfectly fine. Because that model and the docker versions both load I don't believe it is actually resource related. I'm not positive what the KeyError means but appears to be related to the triton kernel?

Full Error Logs from Kubernetes: 

```
2023-10-02T01:48:19.611288Z  INFO text_generation_launcher: Starting Webserver
2023-10-02T01:48:20.513126Z  INFO text_generation_router: router/src/main.rs:371: Serving revision d5ad9310836dd91b6ac6133e2e47f47394386cea of model TheBloke/Llama-2-7b-Chat-GPTQ
2023-10-02T01:48:20.519673Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-10-02T01:48:21.374358Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "<string>", line 21, in matmul_248_kernel
KeyError: ('2-.-0-.-0--d6252949da17ceb5f3a278a70250af13-1af5134066c618146d2cd009138944a0-235b7327308f95b8bc50ee7abd94d0ab-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.int32, torch.float16, torch.float16, torch.int32, torch.int32, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (64, 256, 32, 8), (True, True, True, True, True, True, (True, False), (True, False), (True, False), (False, False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (True, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 672, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 753, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 750, in generate_token
    out = self.forward(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 717, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 497, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 456, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 383, in forward
    attn_output = self.self_attn(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 258, in forward
    qkv = self.query_key_value(hidden_states)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 351, in forward
    return self.linear.forward(x)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 349, in forward
    out = QuantLinearFunction.apply(
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 106, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 244, in forward
    output = matmul248(input, qweight, scales, qzeros, g_idx, bits, maxq)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 216, in matmul248
    matmul_248_kernel[grid](
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 110, in run
    timings = {
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 111, in <dictcomp>
    config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 90, in _bench
    return triton.testing.do_bench(
  File "/opt/conda/lib/python3.9/site-packages/triton/testing.py", line 143, in do_bench
    fn()
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 80, in kernel_call
    self.fn.run(
  File "<string>", line 41, in matmul_248_kernel
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 1587, in compile
    so_path = make_stub(name, signature, constants)
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 1476, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 1391, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmp479lb0kz/main.c', '-O3', '-I/opt/conda/lib/python3.9/site-packages/triton/third_party/cuda/include', '-I/opt/conda/include/python3.9', '-I/tmp/tmp479lb0kz', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp479lb0kz/matmul_248_kernel.cpython-39-x86_64-linux-gnu.so']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 72, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 674, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

2023-10-02T01:48:21.375021Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))
2023-10-02T01:48:21.413794Z ERROR text_generation_launcher: Webserver Crashed
2023-10-02T01:48:21.413824Z  INFO text_generation_launcher: Shutting down shards
2023-10-02T01:48:21.625597Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
Error: WebserverFailed
```

**Comment by Narsil** [comment]
> subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmp479lb0kz/main.c', '-O3', '-I/opt/conda/lib/python3.9/site-packages/triton/third_party/cuda/include', '-I/opt/conda/include/python3.9', '-I/tmp/tmp479lb0kz', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp479lb0kz/matmul_248_kernel.cpython-39-x86_64-linux-gnu.so']' returned non-zero exit status 1.

Seems cuda is having an issue compiling the kernel..

**Comment by jrsperry** [comment]
The only thing that comes to mind could be the OS as everything else was identical (docker image, model config) one is run in kubernetes and the other in a standalone server. I tested several other gptq models and they all had the similar problem, but the raw non quantized versions were fine.

**Comment by Narsil** [comment]
> KeyError: ('2-.-0-.-0--d6252949da17ceb5f3a278a70250af13-1af5134066c618146d2cd009138944a0-235b7327308f95b8bc50ee7abd94d0ab-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.int32, torch.float16, torch.float16, torch.int32, torch.int32, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (64, 256, 32, 8), (True, True, True, True, True, True, (True, False), (True, False), (True, False), (False, False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (True, False)))

This is the true error, this is Triton trying to locate its compiled kernel cache and not finding it.
I have no idea why it might fail tough.

**Comment by jrsperry** [comment]
I imagine the triton kernels are different between the gptq models and the non quantized versions?

**Comment by Narsil** [comment]
There is only 1 triton kernel and it's being used only for GTPQ when exllama cannot be used (too old hardware or cuda, or model wasn't quantized with supported options)

**Comment by jrsperry** [comment]
that's interesting since there's a ton of log statements stating it's using exllama kernels. Here's a sample, the exllama kernel is repeated a lot. 

```
2023-10-03T16:09:08.124249Z  INFO text_generation_launcher: Using exllama kernels

2023-10-03T16:09:08.166203Z  INFO text_generation_launcher: Using exllama kernels

2023-10-03T16:09:08.458415Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-10-03T16:09:08.539125Z  INFO shard-manager: text_generation_launcher: Shard ready in 12.114356911s rank=0
2023-10-03T16:09:08.635642Z  INFO text_generation_launcher: Starting Webserver
2023-10-03T16:09:09.368753Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2023-10-03T16:09:09.368786Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2023-10-03T16:09:09.593721Z  INFO text_generation_router: router/src/main.rs:371: Serving revision fd55a8ca80cf9c70510360b961a5e5c0ade72287 of model TheBloke/vicuna-13B-v1.5-GPTQ
2023-10-03T16:09:09.598261Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-10-03T16:09:10.352670Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "<string>", line 21, in matmul_248_kernel
KeyError: ('2-.-0-.-0--d6252949da17ceb5f3a278a70250af13-1af5134066c618146d2cd009138944a0-235b7327308f95b8bc50ee7abd94d0ab-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.int32, torch.float16, torch.float16, torch.int32, torch.int32, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (64, 256, 32, 8), (True, True, True, True, True, True, (True, False), (True, False), (True, False), (False, False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (True, False)))

During handling of the above exception, another exception occurred:
```

**Comment by Narsil** [comment]
> matmul_248_kernel

Is definitely the triton one, not the exllama one.
Have you tried upgrading your ubuntu version ? Could be a too old libc ? (Although we're also running on 20.04 on EKS so I doubt it's that..)

**Comment by jrsperry** [comment]
We are running with GKE, they manage the OS system. So I don't really have control over it.

**Comment by jrsperry** [comment]
With GKE I don't have much control as it's managed by them, I may be able to switch to a Debian runtime. Don't believe I can mess with the Ubuntu version though.

**Comment by jrsperry** [comment]
closing this issue as it turns out the GKE's container optimized OS just sucks. We switched node images from that to the "ubuntu with containerd" and it works fine.
