### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half' on CPU

### ISSUE THREAD

**Issue by UYousafzai** [huggingface/text-generation-inference#1104]
### CPU Details:
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  12
  On-line CPU(s) list:   0-11
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    CPU family:          6
    Model:               63
    Thread(s) per core:  2
    Core(s) per socket:  6
    Socket(s):           1
    Stepping:            2
    CPU max MHz:         3800,0000
    CPU min MHz:         1200,0000
    
### OS Details:
Linux serv-4102 5.15.0-84-generic #93-Ubuntu SMP  x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

## Command:
docker run --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id $model --disable-custom-kernels

### Stack Trace:

2023-10-05T11:59:09.465814Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-7b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "9eb8eef55da3", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: true, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-05T11:59:09.465956Z  INFO download: text_generation_launcher: Starting download process.
2023-10-05T11:59:13.115693Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-05T11:59:13.571361Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-05T11:59:13.571733Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-05T11:59:16.481529Z  WARN text_generation_launcher: We're not using custom kernels.

2023-10-05T11:59:16.486454Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2023-10-05T11:59:16.488869Z  WARN text_generation_launcher: Could not import Mistral model: CUDA is not available

2023-10-05T11:59:23.584416Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T11:59:33.595632Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T11:59:43.607386Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T11:59:53.618983Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:00:03.630826Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:00:13.642436Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:00:23.653955Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:00:33.665630Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:00:43.677224Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:00:53.689059Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:01:03.700559Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:01:13.712353Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:01:23.724068Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-05T12:01:26.554214Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-10-05T12:01:26.627999Z  INFO shard-manager: text_generation_launcher: Shard ready in 133.055259616s rank=0
2023-10-05T12:01:26.707790Z  INFO text_generation_launcher: Starting Webserver
2023-10-05T12:01:27.536106Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2023-10-05T12:01:27.536128Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2023-10-05T12:01:28.076175Z  INFO text_generation_router: router/src/main.rs:371: Serving revision 08751db2aca9bf2f7f80d2e516117a53d7450235 of model meta-llama/Llama-2-7b-chat-hf
2023-10-05T12:01:28.082136Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-10-05T12:01:28.190080Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 72, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/model.py", line 65, in warmup
    self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 568, in generate_token
    logits, past = self.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 558, in forward
    outputs = self.model.forward(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 820, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 708, in forward
    layer_outputs = decoder_layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 424, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 321, in forward
    query_states = self.q_proj(hidden_states)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

2023-10-05T12:01:28.190295Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: "addmm_impl_cpu_" not implemented for 'Half'
Error: Warmup(Generation("\"addmm_impl_cpu_\" not implemented for 'Half'"))
2023-10-05T12:01:28.210989Z ERROR text_generation_launcher: Webserver Crashed
2023-10-05T12:01:28.211005Z  INFO text_generation_launcher: Shutting down shards
Error: WebserverFailed
2023-10-05T12:01:28.841520Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0

### Current Behavior:
ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: "addmm_impl_cpu_" not implemented for 'Half'

### Expected Behavior:
For the Container to launch.

**Comment by Narsil** [comment]
Try `--dtype bfloat16`
