### ISSUE TITLE
Fails to load Mistral models finetuned with additional tokens

### ISSUE THREAD

**Issue by olliestanley** [huggingface/text-generation-inference#1132]
### System Info

Script to run TGI (using `latest` to avoid bug with `eetq` dependency described in #1122):

```
model="Open-Orca/Mistral-7B-OpenOrca"
volume="$PWD/data"
docker run --name tgi_server -d --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model --quantize eetq --max-total-tokens 4096 --max-input-length 2048
```

Same issue occurs with model `ehartford/dolphin-2.1-mistral-7b` but **not** with base Mistral or `mistralai/Mistral-7B-Instruct-v0.1`

nvidia-smi

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    On  | 00000000:00:1E.0 Off |                    0 |
|  0%   31C    P0              59W / 300W |  21378MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

Ubuntu 22.04.2 LTS

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Error occurs on startup when executing the script shared above.

```
2023-10-11T11:01:03.657935Z  INFO text_generation_launcher: Args { model_id: "Open-Orca/Mistral-7B-OpenOrca", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Bitsandbytes), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 4096, max_total_tokens: 6500, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "8965171f2861", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-11T11:01:03.658094Z  INFO download: text_generation_launcher: Starting download process.
2023-10-11T11:01:06.858251Z  WARN text_generation_launcher: No safetensors weights found for model Open-Orca/Mistral-7B-OpenOrca at revision None. Downloading PyTorch weights.

2023-10-11T11:01:06.957503Z  INFO text_generation_launcher: Download file: pytorch_model-00001-of-00002.bin

2023-10-11T11:01:37.660297Z  INFO text_generation_launcher: Downloaded /data/models--Open-Orca--Mistral-7B-OpenOrca/snapshots/8f934b2bd2d4484b846a7faf1c53093b9d956367/pytorch_model-00001-of-00002.bin in 0:00:30.

2023-10-11T11:01:37.660374Z  INFO text_generation_launcher: Download: [1/2] -- ETA: 0:00:30

2023-10-11T11:01:37.660670Z  INFO text_generation_launcher: Download file: pytorch_model-00002-of-00002.bin

2023-10-11T11:01:53.915066Z  INFO text_generation_launcher: Downloaded /data/models--Open-Orca--Mistral-7B-OpenOrca/snapshots/8f934b2bd2d4484b846a7faf1c53093b9d956367/pytorch_model-00002-of-00002.bin in 0:00:16.

2023-10-11T11:01:53.915169Z  INFO text_generation_launcher: Download: [2/2] -- ETA: 0

2023-10-11T11:01:53.915272Z  WARN text_generation_launcher: No safetensors weights found for model Open-Orca/Mistral-7B-OpenOrca at revision None. Converting PyTorch weights to safetensors.

2023-10-11T11:02:59.867821Z  INFO text_generation_launcher: Convert: [1/2] -- Took: 0:01:05.534698

2023-10-11T11:03:21.097468Z  INFO text_generation_launcher: Convert: [2/2] -- Took: 0:00:21.229358

2023-10-11T11:03:21.678619Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-11T11:03:21.679276Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-11T11:03:26.841294Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 252, in get_model
    return FlashMistral(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_mistral.py", line 297, in __init__
    tokenizer = LlamaTokenizerFast.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1886, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2073, in _from_pretrained
    raise ValueError(
ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.

2023-10-11T11:03:27.486566Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 252, in get_model
    return FlashMistral(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_mistral.py", line 297, in __init__
    tokenizer = LlamaTokenizerFast.from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1886, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2073, in _from_pretrained
    raise ValueError(

ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.
 rank=0
2023-10-11T11:03:27.583872Z ERROR text_generation_launcher: Shard 0 failed to start
```

### Expected behavior

Model should load as it does with base Mistral or Mistral-Instruct.

**Comment by Stealthwriter** [comment]
I'm having the same issue

**Comment by hlo-world** [comment]
Same issue, tested on sagemaker with a g5 instance.

Was attempting to deploy ```ehartford/dolphin-2.1-mistral-7b``` and errored on:
```
ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.
```

Made sure that transformers >= 4.34, which I initially thought was the culprit.

**Comment by Stealthwriter** [comment]
> Same issue, tested on sagemaker with a g5 instance.
> 
> Was attempting to deploy `ehartford/dolphin-2.1-mistral-7b` and errored on:
> 
> ```
> ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.
> ```
> 
> Made sure that transformers >= 4.34, which I initially thought was the culprit.

what are you using for fine tuning? try axolotl , then delete added_tokens file from the model's folder

**Comment by ssmi153** [comment]
I've also had the same issue. I've been using Axolotl to do a QLORA training run and then merging the LORA into the main model using Axolotl's CLI script. The only reliable workaround that I've found so far is after this merge to delete added_tokens.json and replace special_tokens_map.json, tokenizer.json and tokenizer_config.json with the files from the original model.

One note: this is not a Mistral-specific problem. I've also been having the same issues with Llama-2 models.

Not sure at this stage whether this is an Axolotl issue or a TGI issue. My guess is that TGI is running an older version of HuggingFace's tokenizer libs and that this is causing incompatibility issues.

**Comment by freegheist** [comment]
Bump - identical issue to the OP on Mistral-7b-OpenOrca. deleting added_tokens.json as @Stealthwriter said is my workaround.

**Comment by thomas-schillaci** [comment]
@Stealthwriter 's workaround is also working for me

**Comment by sam-ulrich1** [comment]
Deleting the added_tokens.json will interfere with the fine-tuning since there are special tokens (chatml format) that it has now been trained on.

Instead remove the following lines form the added_tokens.json file and your model will load. This preserves the special tokens for chatml
```
"</s>": 2,
"<s>": 1,
"<unk>": 0,
```

**Comment by OlivierDehaene** [comment]
@ArthurZucker, are you aware of this in transformers?

**Comment by hahmad2008** [comment]
@OlivierDehaene  @ArthurZucker faced the same issue with a finetuned model, is there any solution for that instead of the workaround?
```

site-packages/transformers/tokenization_utils_base.py", line 2073, in _from_pretrained
    raise ValueError(
ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.
```

**Comment by olliestanley** [comment]
Yes this is fixed in recent versions, closing
