### ISSUE TITLE
NotImplementedError: Sharded Santacoder requires Flash Attention enabled models.

### ISSUE THREAD

**Issue by coder-xieshijie** [huggingface/text-generation-inference#1138]
### System Info

- OS version: Debian GNU/Linux 11 (bullseye)
- Commit sha: 00b8f36fba62e457ff143cce35564ac6704db860
- Cargo version: 1.70.0
- model: Starcoder
- nvidia-smi:
```
Thu Oct 12 18:23:03 2023
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  NVIDIA A800-SXM4-80GB          On  | 00000000:4B:00.0 Off |                    0 |
   | N/A   29C    P0              73W / 400W |  36679MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   1  NVIDIA A800-SXM4-80GB          On  | 00000000:51:00.0 Off |                    0 |
   | N/A   31C    P0              62W / 400W |      5MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   2  NVIDIA A800-SXM4-80GB          On  | 00000000:6A:00.0 Off |                    0 |
   | N/A   31C    P0              61W / 400W |      5MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   3  NVIDIA A800-SXM4-80GB          On  | 00000000:6F:00.0 Off |                    0 |
   | N/A   29C    P0              61W / 400W |      5MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   4  NVIDIA A800-SXM4-80GB          On  | 00000000:8D:00.0 Off |                    0 |
   | N/A   28C    P0              61W / 400W |      5MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   5  NVIDIA A800-SXM4-80GB          On  | 00000000:92:00.0 Off |                    0 |
   | N/A   30C    P0              62W / 400W |      5MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   6  NVIDIA A800-SXM4-80GB          On  | 00000000:C9:00.0 Off |                    0 |
   | N/A   32C    P0              67W / 400W |  78233MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   7  NVIDIA A800-SXM4-80GB          On  | 00000000:CF:00.0 Off |                    0 |
   | N/A   29C    P0              58W / 400W |      5MiB / 81920MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+

   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   +---------------------------------------------------------------------------------------+
```

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

My command:
```
CUDA_VISIBLE_DEVICES=0,1 /workspace/xieshijie/text-generation-inference/target/release/deps/text_generation_launcher-b64a71565ded74a5 --model-id /workspace/xieshijie/huggingface-models/starcoder2/models--bigcode--starcoder/snapshots/e117ab3b3d0769fd962bd48b099de711757a3d60 --port 6006 --max-input-length 8000 --max-total-tokens 8192 --max-batch-prefill-tokens 8000 --num-shard 2
```

Before executing the above command, I installed tgi via
```
# install cargo
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# create python virtual environment and activate
conda create -n tgi python=3.9
conda activate tgi

# install protoc
PROTOC_ZIP=protoc-21.12-linux-x86_64.zip
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP

# install tgi
BUILD_EXTENSIONS=True make install

# my model is too large, so i download it by transformers in my local dir
# download model ...
```

error log: 
```
2023-10-12T10:07:47.788833Z  INFO text_generation_launcher: Args { model_id: "/workspace/xieshijie/huggingface-models/starcoder2/models--bigcode--starcoder/snapshots/e117ab3b3d0769fd962bd48b099de711757a3d60", revision: None, validation_workers: 2, sharded: None, num_shard: Some(2), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 8000, max_total_tokens: 8192, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 8000, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "0.0.0.0", port: 6006, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-12T10:07:47.788861Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-10-12T10:07:47.788939Z  INFO download: text_generation_launcher: Starting download process.
2023-10-12T10:07:50.447312Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-12T10:07:50.891210Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-12T10:07:50.891427Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-10-12T10:07:50.891464Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-12T10:07:53.420079Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'

2023-10-12T10:07:53.424851Z  WARN text_generation_launcher: Could not import Mistral model: No module named 'dropout_layer_norm'

2023-10-12T10:07:53.486732Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/envs/starcoder2/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/models/__init__.py", line 144, in get_model
    raise NotImplementedError(
NotImplementedError: Sharded Santacoder requires Flash Attention enabled models.

2023-10-12T10:07:53.509899Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'

2023-10-12T10:07:53.513608Z  WARN text_generation_launcher: Could not import Mistral model: No module named 'dropout_layer_norm'

2023-10-12T10:07:53.600788Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/envs/starcoder2/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/starcoder2/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/models/__init__.py", line 144, in get_model
    raise NotImplementedError(
NotImplementedError: Sharded Santacoder requires Flash Attention enabled models.

2023-10-12T10:07:53.894165Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/envs/starcoder2/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/envs/starcoder2/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/workspace/xieshijie/huggingface/text-generation-inference/server/text_generation_server/models/__init__.py", line 144, in get_model
    raise NotImplementedError(

NotImplementedError: Sharded Santacoder requires Flash Attention enabled models.
 rank=0
2023-10-12T10:07:53.993191Z ERROR text_generation_launcher: Shard 0 failed to start
2023-10-12T10:07:53.993214Z  INFO text_generation_launcher: Shutting down shards
2023-10-12T10:07:54.012978Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=1
Error: ShardCannotStart
```

### Expected behavior

When I start the model on multiple GPUs through `--num-shard 2`, I can see the error log above:`NotImplementedError: Sharded Santacoder requires Flash Attention enabled models`. However, when i run model by `--num-shard 1`, it can work normally! What is the cause of this? How should I solve it? I would be very grateful if there is any answer to fix it.

**Comment by coder-xieshijie** [comment]
i solved it  by commands:
```
cd server
make -f Makefile-vllm install-vllm
make -f Makefile-flash-att install-flash-attention
```

if you failed when installing, you can [this](https://github.com/huggingface/text-generation-inference/issues/1145)

**Comment by HenryYuen128** [comment]
> i solved it by commands:
> 
> ```
> cd server
> make -f Makefile-vllm install-vllm
> make -f Makefile-flash-att install-flash-attention
> ```
> 
> if you failed when installing, you can [this](https://github.com/huggingface/text-generation-inference/issues/1145)

Hi @coder-xieshijie , i tried this, but got 
```
RuntimeError:
The detected CUDA version (11.3) mismatches the version that was used to compile
PyTorch (10.2). Please make sure to use the same CUDA versions.
```
while it is CUDA 11.4 on my system
