### ISSUE TITLE
Running starcoderbase using eetq in docker throws value error

### ISSUE THREAD

**Issue by zhongzeyu-fish** [huggingface/text-generation-inference#1144]
### System Info

OS version: ubuntu 20.04.6 LTS
Commit sha: [sha-20ee71d](https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference/136287824?tag=sha-20ee71d)
Cargo version: no install
model: Starcoderbase
nvidia-smi:
```
Fri Oct 13 16:33:58 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:1B:00.0 Off |                    0 |
| N/A   52C    P0              75W / 300W |  76719MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          Off | 00000000:1C:00.0 Off |                    0 |
| N/A   50C    P0              67W / 300W |  76733MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe          Off | 00000000:1F:00.0 Off |                  Off |
| N/A   55C    P0              71W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe          Off | 00000000:23:00.0 Off |                    0 |
| N/A   54C    P0              77W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA A100 80GB PCIe          Off | 00000000:35:00.0 Off |                    0 |
| N/A   56C    P0              78W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA A100 80GB PCIe          Off | 00000000:36:00.0 Off |                  Off |
| N/A   55C    P0              73W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA A100 80GB PCIe          Off | 00000000:39:00.0 Off |                    0 |
| N/A   54C    P0              68W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA A100 80GB PCIe          Off | 00000000:3D:00.0 Off |                    0 |
| N/A   55C    P0              80W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   2186617      C   /opt/conda/bin/python3.9                  76706MiB |
|    1   N/A  N/A   2186618      C   /opt/conda/bin/python3.9                  76720MiB |
+---------------------------------------------------------------------------------------+
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

The content of the sh script I ran is as follows：
```
external_port=${1:-9202}
model_path=/home/workspace/src/starcodebase

docker run -d \
    --gpus '"device=7"' \
    --shm-size 1g \
    --name example-1 \
    -p ${external_port}:80 \
    -v $model_path:/data/star \
    text-generation-inference:latest \
    --weights-cache-override="/data/star" \
    --model-id "/data/star" \
    --sharded false \
    --max-best-of 5 \
    --max-input-length 4096 \
    --max-total-tokens 12288 \
    --quantize eetq
```

### Expected behavior

error log:
```
2023-10-13T06:40:44.240578Z  INFO download: text_generation_launcher: Starting download process.
2023-10-13T06:40:51.250192Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-13T06:40:52.547296Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-13T06:40:52.547656Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-13T06:41:00.778780Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 136, in get_model
    return FlashSantacoderSharded(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_santacoder.py", line 68, in __init__
    model = FlashSantacoderForCausalLM(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 450, in __init__
    self.transformer = FlashSantacoderModel(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 397, in __init__
    [
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 398, in <listcomp>
    Block(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 339, in __init__
    self.attn = FlashMQAttention(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 224, in __init__
    self.c_attn = load_multi_mqa(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 32, in load_multi_mqa
    return _load_multi_mqa(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 171, in _load_multi_mqa
    return TensorParallelColumnLinear(get_linear(weight, bias, config.quantize))
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 278, in get_linear
    linear = EETQLinear(weight, bias)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 158, in __init__
    if bias:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

2023-10-13T06:41:02.155897Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 136, in get_model
    return FlashSantacoderSharded(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_santacoder.py", line 68, in __init__
    model = FlashSantacoderForCausalLM(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 450, in __init__
    self.transformer = FlashSantacoderModel(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 397, in __init__
    [

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 398, in <listcomp>
    Block(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 339, in __init__
    self.attn = FlashMQAttention(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 224, in __init__
    self.c_attn = load_multi_mqa(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 32, in load_multi_mqa
    return _load_multi_mqa(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_santacoder_modeling.py", line 171, in _load_multi_mqa
    return TensorParallelColumnLinear(get_linear(weight, bias, config.quantize))

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 278, in get_linear
    linear = EETQLinear(weight, bias)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 158, in __init__
    if bias:

RuntimeError: Boolean value of Tensor with more than one value is ambiguous
 rank=0
2023-10-13T06:41:02.253837Z ERROR text_generation_launcher: Shard 0 failed to start
2023-10-13T06:41:02.253871Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

**Comment by vakker** [comment]
I'm having the same issue with another model. I believe in the class definition instead of `if bias` it should be `if bias is not None` [here](https://github.com/huggingface/text-generation-inference/blob/3af1a1140141245c20df20a787831ec71b124eae/server/text_generation_server/utils/layers.py#L158).

Also, shouldn't the `bias` also go through the `quant_weights` call, just like `weight`?
@SidaZh and @Narsil might be able to help out better here.

**Comment by zhongzeyu-fish** [comment]
@vakker 
Thanks for your help, it does look like the issue here.

**Comment by SidaZh** [comment]
> I'm having the same issue with another model. I believe in the class definition instead of `if bias` it should be `if bias is not None` [here](https://github.com/huggingface/text-generation-inference/blob/3af1a1140141245c20df20a787831ec71b124eae/server/text_generation_server/utils/layers.py#L158).
> 
> Also, shouldn't the `bias` also go through the `quant_weights` call, just like `weight`? @SidaZh and @Narsil might be able to help out better here.

> I'm having the same issue with another model. I believe in the class definition instead of `if bias` it should be `if bias is not None` [here](https://github.com/huggingface/text-generation-inference/blob/3af1a1140141245c20df20a787831ec71b124eae/server/text_generation_server/utils/layers.py#L158).
> 
> Also, shouldn't the `bias` also go through the `quant_weights` call, just like `weight`? @SidaZh and @Narsil might be able to help out better here.

Yes, it should be `if bias is not None` [here](https://github.com/huggingface/text-generation-inference/blob/3af1a1140141245c20df20a787831ec71b124eae/server/text_generation_server/utils/layers.py#L158).
And `bias` don‘t need go through the `quant_weights` because the data type of matrix output is float16.

**Comment by SidaZh** [comment]
@Narsil [PR#1176](https://github.com/huggingface/text-generation-inference/pull/1176) should fix this issue, could you help review and merge it.
