### ISSUE TITLE
Error while running text-generation-launcher on OpenShift

### ISSUE THREAD

**Issue by pkoppa** [huggingface/text-generation-inference#1156]
### System Info

root@tgi-deployment-596cc7bb98-wcg72:/usr/src# curl 127.0.0.1:8080/info | jq
bash: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

I ahve OpenShift environment wth each worker nodes exposed with 2 vGPUs
I created a deployment config using image: ghcr.io/huggingface/text-generation-inference
The pod is getting created. When I bash into the pod and try to run text-generation-launcher, I am getting error. 
------------- 
root@tgi-deployment-596cc7bb98-wcg72:/usr/src# text-generation-launcher --model-id tiiuae/falcon-7b-instruct --json-output --sharded=false 
{"timestamp":"2023-10-16T06:44:03.670755Z","level":"INFO","fields":{"message":"Args { model_id: \"tiiuae/falcon-7b-instruct\", revision: None, validation_workers: 2, sharded: Some(false), num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: \"tgi-deployment-596cc7bb98-wcg72\", port: 80, shard_uds_path: \"/tmp/text-generation-server\", master_addr: \"localhost\", master_port: 29500, huggingface_hub_cache: Some(\"/data\"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: true, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }"},"target":"text_generation_launcher"}
{"timestamp":"2023-10-16T06:44:03.670889Z","level":"INFO","fields":{"message":"Starting download process."},"target":"text_generation_launcher","span":{"name":"download"},"spans":[{"name":"download"}]}
{"timestamp":"2023-10-16T06:44:06.039527Z","level":"INFO","fields":{"message":"Files are already present on the host. Skipping download.\n"},"target":"text_generation_launcher"}
{"timestamp":"2023-10-16T06:44:06.473413Z","level":"INFO","fields":{"message":"Successfully downloaded weights."},"target":"text_generation_launcher","span":{"name":"download"},"spans":[{"name":"download"}]}
{"timestamp":"2023-10-16T06:44:06.473662Z","level":"INFO","fields":{"message":"Starting shard"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2023-10-16T06:44:11.155462Z","level":"ERROR","fields":{"message":"Error when initializing model\nTraceback (most recent call last):\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n  File \"/opt/conda/lib/python3.9/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1157, in __call__\n    return self.main(*args, **kwargs)\n  File \"/opt/conda/lib/python3.9/site-packages/typer/core.py\", line 778, in main\n    return _main(\n  File \"/opt/conda/lib/python3.9/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1688, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 783, in invoke\n    return __callback(*args, **kwargs)\n  File \"/opt/conda/lib/python3.9/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py\", line 83, in serve\n    server.serve(\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 207, in serve\n    asyncio.run(\n  File \"/opt/conda/lib/python3.9/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 634, in run_until_complete\n    self.run_forever()\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n    self._run_once()\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n    handle._run()\n  File \"/opt/conda/lib/python3.9/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 159, in serve_inner\n    model = get_model(\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py\", line 234, in get_model\n    return FlashRWSharded(\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_rw.py\", line 67, in __init__\n    model = FlashRWForCausalLM(config, weights)\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py\", line 627, in __init__\n    self.lm_head = TensorParallelHead.load(\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py\", line 372, in load\n    weight = weights.get_tensor(f\"{prefix}.weight\")\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py\", line 83, in get_tensor\n    tensor = tensor.to(device=self.device)\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB (GPU 0; 20.00 GiB total capacity; 12.92 GiB already allocated; 636.06 MiB free; 20.00 GiB allowed; 13.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n"},"target":"text_generation_launcher"}
{"timestamp":"2023-10-16T06:44:11.981049Z","level":"ERROR","fields":{"message":"Shard complete standard error output:\n\nYou are using a model of type falcon to instantiate a model of type . This is not supported for all configurations of models and can yield errors.\nTraceback (most recent call last):\n\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py\", line 83, in serve\n    server.serve(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 207, in serve\n    asyncio.run(\n\n  File \"/opt/conda/lib/python3.9/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 647, in run_until_complete\n    return future.result()\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 159, in serve_inner\n    model = get_model(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py\", line 234, in get_model\n    return FlashRWSharded(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_rw.py\", line 67, in __init__\n    model = FlashRWForCausalLM(config, weights)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py\", line 627, in __init__\n    self.lm_head = TensorParallelHead.load(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py\", line 372, in load\n    weight = weights.get_tensor(f\"{prefix}.weight\")\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py\", line 83, in get_tensor\n    tensor = tensor.to(device=self.device)\n\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB (GPU 0; 20.00 GiB total capacity; 12.92 GiB already allocated; 636.06 MiB free; 20.00 GiB allowed; 13.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2023-10-16T06:44:12.078622Z","level":"ERROR","fields":{"message":"Shard 0 failed to start"},"target":"text_generation_launcher"}
{"timestamp":"2023-10-16T06:44:12.078651Z","level":"INFO","fields":{"message":"Shutting down shards"},"target":"text_generation_launcher"}
Error: ShardCannotStart
root@tgi-deployment-596cc7bb98-wcg72:/usr/src# text-generation-launcher --model-id tiiuae/falcon-7b-instruct --json-output --sharded=false 

### Expected behavior

text-generation-launcher should just work fine.

Same issue with -- sharded true

**Comment by pkoppa** [comment]
Deployment Configuration
-------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-deployment
spec:
  strategy:
    type: Recreate
  # Replicas controls the number of instances of the Pod to maintain running at all times
  replicas: 1
  selector:
    matchLabels:
      app: tgi
  template:
    metadata:
      labels:
        app: tgi
      name: tgi-pod
    spec:
      volumes:
        - name: tgi
          persistentVolumeClaim:
            claimName: tgi-pvc

        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi

      restartPolicy: Always
      containers:
        - name: tgi-container
          image: ghcr.io/huggingface/text-generation-inference
          imagePullPolicy: Always
          #command: [ "/bin/bash", "-c", "--" ]
          #args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: tgi
              mountPath: /data
            - name: shm
              mountPath: /dev/shm

          resources:
            limits:
              nvidia.com/gpu: 2 # requesting 1 GPU

**Comment by pkoppa** [comment]
[pkoppa@rhods-client ~]$ oc exec -it tgi-deployment-596cc7bb98-wcg72 -- bash
root@tgi-deployment-596cc7bb98-wcg72:/usr/src# text-generation-launcher --env
2023-10-16T06:54:22.050932Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 3af1a1140141245c20df20a787831ec71b124eae
Docker label: sha-3af1a11
nvidia-smi:
Mon Oct 16 06:54:22 2023       
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  GRID A100D-20C                 On  | 00000000:02:00.0 Off |                    0 |
   | N/A   N/A    P0              N/A /  N/A |   4433MiB / 20480MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   1  GRID A100D-20C                 On  | 00000000:02:01.0 Off |                    0 |
   | N/A   N/A    P0              N/A /  N/A |   4413MiB / 20480MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
                                                                                            
   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   +---------------------------------------------------------------------------------------+
2023-10-16T06:54:22.050971Z  INFO text_generation_launcher: Args { model_id: "bigscience/bloom-560m", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "tgi-deployment-596cc7bb98-wcg72", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: true }
2023-10-16T06:54:22.050998Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-10-16T06:54:22.051123Z  INFO download: text_generation_launcher: Starting download process.
2023-10-16T06:54:24.522975Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-16T06:54:24.957031Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-16T06:54:24.957281Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-16T06:54:24.957332Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-10-16T06:54:27.516917Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 157, in get_model
    return BLOOMSharded(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/bloom.py", line 48, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/dist.py", line 71, in initialize_torch_distributed
    torch.distributed.init_process_group(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

2023-10-16T06:54:27.960194Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 157, in get_model
    return BLOOMSharded(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/bloom.py", line 48, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/dist.py", line 71, in initialize_torch_distributed
    torch.distributed.init_process_group(

  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)

  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)

  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(

RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
 rank=0
2023-10-16T06:54:28.059380Z ERROR text_generation_launcher: Shard 0 failed to start
2023-10-16T06:54:28.059423Z  INFO text_generation_launcher: Shutting down shards
2023-10-16T06:54:28.106837Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=1
Error: ShardCannotStart
root@tgi-deployment-596cc7bb98-wcg72:/usr/src#

**Comment by pkoppa** [comment]
I added to wait on bash in deployment config.
  containers:
        - name: tgi-container
          image: ghcr.io/huggingface/text-generation-inference
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]


With this, it runs but at the end it shows 2023-10-16T07:30:41.490618Z  WARN text_generation_router: router/src/main.rs:252: Invalid hostname, defaulting to 0.0.0.0.

I am still not able to connect.


Snippet
------
root@tgi-deployment-6948b74cd4-ffdsh:/usr/src# text-generation-launcher --env
2023-10-16T07:30:27.737029Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 3af1a1140141245c20df20a787831ec71b124eae
Docker label: sha-3af1a11
nvidia-smi:
Mon Oct 16 07:30:27 2023       
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  GRID A100D-20C                 On  | 00000000:02:00.0 Off |                    0 |
   | N/A   N/A    P0              N/A /  N/A |      0MiB / 20480MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   1  GRID A100D-20C                 On  | 00000000:02:01.0 Off |                    0 |
   | N/A   N/A    P0              N/A /  N/A |      0MiB / 20480MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
                                                                                            
   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   |  No running processes found                                                           |
   +---------------------------------------------------------------------------------------+
2023-10-16T07:30:27.737066Z  INFO text_generation_launcher: Args { model_id: "bigscience/bloom-560m", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "tgi-deployment-6948b74cd4-ffdsh", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: true }
2023-10-16T07:30:27.737089Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-10-16T07:30:27.737213Z  INFO download: text_generation_launcher: Starting download process.
2023-10-16T07:30:30.240412Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-16T07:30:30.639799Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-16T07:30:30.640042Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-16T07:30:30.640119Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-10-16T07:30:39.171398Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-10-16T07:30:39.221152Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-1

2023-10-16T07:30:39.246947Z  INFO shard-manager: text_generation_launcher: Shard ready in 8.606267954s rank=0
2023-10-16T07:30:39.246951Z  INFO shard-manager: text_generation_launcher: Shard ready in 8.605990744s rank=1
2023-10-16T07:30:39.345635Z  INFO text_generation_launcher: Starting Webserver
2023-10-16T07:30:40.076665Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2023-10-16T07:30:40.076699Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2023-10-16T07:30:40.433268Z  INFO text_generation_router: router/src/main.rs:371: Serving revision ac2ae5fab2ce3f9f40dc79b5ca9f637430d24971 of model bigscience/bloom-560m
2023-10-16T07:30:40.439271Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-10-16T07:30:41.490584Z  WARN text_generation_router: router/src/main.rs:224: Model does not support automatic max batch total tokens
2023-10-16T07:30:41.490610Z  INFO text_generation_router: router/src/main.rs:246: Setting max batch total tokens to 16000
2023-10-16T07:30:41.490614Z  INFO text_generation_router: router/src/main.rs:247: Connected
2023-10-16T07:30:41.490618Z  WARN text_generation_router: router/src/main.rs:252: Invalid hostname, defaulting to 0.0.0.0

**Comment by OlivierDehaene** [comment]
This seems to be an issue with your env, not TGI.
