### ISSUE TITLE
Cannot load local model

### ISSUE THREAD

**Issue by seanbenhur** [huggingface/text-generation-inference#1158]
### System Info

Currently I am using docker directly

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I am trying to host my local Flan-t5 model with the tgi and I am getting error

This is my script,

```
volume=$PWD/data/ # share a volume with the Docker container to avoid downloading weights every run
model=summarize/checkpoint/flan-t5-base-oct-11-run-5-epochs/checkpoint-6250
sudo docker run --shm-size 1g -p 8000:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id $model
```

But when I try to run this, I am getting this error

```
2023-10-16T14:08:08.169890Z  INFO text_generation_launcher: Args { model_id: "summarize/checkpoint/flan-t5-base-oct-11-run-5-epochs/checkpoint-6250", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "78509e886eb3", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-16T14:08:08.170095Z  INFO download: text_generation_launcher: Starting download process.
Error: DownloadError
2023-10-16T14:08:12.306012Z ERROR download: text_generation_launcher: Download encountered an error: /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 115, in download_weights
    utils.weight_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 96, in weight_files
    filenames = weight_hub_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 25, in weight_hub_files
    info = api.model_info(model_id, revision=revision)

  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)

  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'summarize/checkpoint/flan-t5-base-oct-11-run-5-epochs/checkpoint-6250'. Use `repo_type` argument if needed.
```

I get the same error even if I use the Python client library

### Expected behavior

Ideally it should run

**Comment by OlivierDehaene** [comment]
Yes, you are not giving a correct path to the docker container as your volume is not mounted in the correct place. Please read on docker volumes. This is unrelated to TGI.
