### ISSUE TITLE
ERROR shard-manager: You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.

### ISSUE THREAD

**Issue by danilyef** [huggingface/text-generation-inference#1163]
### System Info

- huggingface/text-generation-inference version: 1.1.0
- The full command line used that causes issues: `docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id /data/llama_2_chat_hf/ --num-shard 1`

- OS version: Ubuntu 18.04

- Model (locally - downloaded from hugging face) being used: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

- Hardware used (GPUs, how many, on which cloud):
![Screenshot 2023-10-17 150446](https://github.com/huggingface/text-generation-inference/assets/12939044/371dc77e-98c4-4988-a583-00cb4eb97edf)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Create a run.sh file as follows:

```
model="llama_2_chat_hf"
volume="$PWD/data"

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id /data/llama_2_chat_hf/ --num-shard 1

```
2. Folder structure:

run.sh
data
--llama_2_chat_hf

3. ` bash run.sh`

4. logs:

```
2023-10-17T16:06:19.538353Z  INFO text_generation_launcher: Args { model_id: "/data/llama_2_chat_hf", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "d93612b7a499", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-17T16:06:19.538590Z  INFO download: text_generation_launcher: Starting download process.
2023-10-17T16:06:21.937368Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-17T16:06:22.443620Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-17T16:06:22.444025Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-17T16:06:24.913470Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

2023-10-17T16:06:24.930181Z  WARN text_generation_launcher: Could not import Mistral model: Mistral model requires flash attn v2

2023-10-17T16:06:25.080393Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 201, in get_model
    return FlashLlama(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 64, in __init__
    weights = Weights(filenames, device, dtype, process_group=self.process_group)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 22, in __init__
    with safe_open(filename, framework="pytorch") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

2023-10-17T16:06:25.650048Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 201, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 64, in __init__
    weights = Weights(filenames, device, dtype, process_group=self.process_group)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 22, in __init__
    with safe_open(filename, framework="pytorch") as f:

safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
 rank=0
Error: ShardCannotStart
2023-10-17T16:06:25.748276Z ERROR text_generation_launcher: Shard 0 failed to start
2023-10-17T16:06:25.748311Z  INFO text_generation_launcher: Shutting down shards
```

### Expected behavior

Tu run TGI using llama-2-7b-chat-hf

**Comment by danilyef** [comment]
If I remove --num-shard 1 I get the same error.

**Comment by danilyef** [comment]
Problem solved. The reason of the error was incorrect download of the lfs files.
