### ISSUE TITLE
ERROR warmup{max_input_length=64 max_prefill_tokens=256}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 256 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

### ISSUE THREAD

**Issue by danilyef** [huggingface/text-generation-inference#1164]
### System Info

- huggingface/text-generation-inference version: 1.1.0
- The full command line used that causes issues: `docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id $model --sharded true --num-shard 2 --max-batch-prefill-tokens 256 --max-total-tokens 128 --max-input-length 64`

- OS version: Ubuntu 18.04

- Model (directly downloaded from hugging face using hf_token) being used: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

- Hardware used (GPUs, how many, on which cloud):
![Screenshot 2023-10-17 150446](https://github.com/huggingface/text-generation-inference/assets/12939044/371dc77e-98c4-4988-a583-00cb4eb97edf)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [x] My own modifications

### Reproduction

1. Create a run.sh file as follows:

```
model=meta-llama/Llama-2-7b-chat-hf
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run
token=<hf_token>

docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id $model --sharded true --num-shard 2 --max-batch-prefill-tokens 256 --max-total-tokens 128 --max-input-length 64
```

2. Run run.sh script:

3. Logs:

```
2023-10-17T15:53:13.402112Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-7b-chat-hf", revision: None, validation_workers: 2, sharded: Some(true), num_shard: Some(2), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 64, max_total_tokens: 128, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 256, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "8c6fc37dfdbe", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-17T15:53:13.402175Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-10-17T15:53:13.402381Z  INFO download: text_generation_launcher: Starting download process.
2023-10-17T15:53:17.126481Z  INFO text_generation_launcher: Download file: model-00001-of-00002.safetensors

2023-10-17T15:59:21.921438Z  INFO text_generation_launcher: Downloaded /data/models--meta-llama--Llama-2-7b-chat-hf/snapshots/af6df14e494ef16d69ec55e9a016e900a2dde1c8/model-00001-of-00002.safetensors in 0:06:04.

2023-10-17T15:59:21.921580Z  INFO text_generation_launcher: Download: [1/2] -- ETA: 0:06:04

2023-10-17T15:59:21.922295Z  INFO text_generation_launcher: Download file: model-00002-of-00002.safetensors

2023-10-17T16:01:40.648990Z  INFO text_generation_launcher: Downloaded /data/models--meta-llama--Llama-2-7b-chat-hf/snapshots/af6df14e494ef16d69ec55e9a016e900a2dde1c8/model-00002-of-00002.safetensors in 0:02:18.

2023-10-17T16:01:40.649107Z  INFO text_generation_launcher: Download: [2/2] -- ETA: 0

2023-10-17T16:01:41.149836Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-17T16:01:41.150177Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-17T16:01:41.150233Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-10-17T16:01:43.759639Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

2023-10-17T16:01:43.759648Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

2023-10-17T16:01:43.776844Z  WARN text_generation_launcher: Could not import Mistral model: Mistral model requires flash attn v2

2023-10-17T16:01:43.776855Z  WARN text_generation_launcher: Could not import Mistral model: Mistral model requires flash attn v2

2023-10-17T16:01:50.724224Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-10-17T16:01:50.766286Z  INFO shard-manager: text_generation_launcher: Shard ready in 9.61510049s rank=0
2023-10-17T16:01:50.835911Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-1

2023-10-17T16:01:50.866349Z  INFO shard-manager: text_generation_launcher: Shard ready in 9.714605649s rank=1
2023-10-17T16:01:50.963495Z  INFO text_generation_launcher: Starting Webserver
2023-10-17T16:01:51.766850Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2023-10-17T16:01:51.766874Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2023-10-17T16:01:52.420075Z  INFO text_generation_router: router/src/main.rs:371: Serving revision af6df14e494ef16d69ec55e9a016e900a2dde1c8 of model meta-llama/Llama-2-7b-chat-hf
2023-10-17T16:01:52.430593Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-10-17T16:01:52.490921Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 672, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 753, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 750, in generate_token
    out = self.forward(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 717, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 497, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 456, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 383, in forward
    attn_output = self.self_attn(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 282, in forward
    attention(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/flash_attn.py", line 84, in attention
    raise NotImplementedError(
NotImplementedError: window_size_left is only available with flash attn v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 72, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 674, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 256 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

2023-10-17T16:01:52.491299Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 672, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 753, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 750, in generate_token
    out = self.forward(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 717, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 497, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 456, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 383, in forward
    attn_output = self.self_attn(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 282, in forward
    attention(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/flash_attn.py", line 84, in attention
    raise NotImplementedError(
NotImplementedError: window_size_left is only available with flash attn v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 72, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 674, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 256 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

2023-10-17T16:01:52.491319Z ERROR warmup{max_input_length=64 max_prefill_tokens=256}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 256 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
2023-10-17T16:01:52.491577Z ERROR warmup{max_input_length=64 max_prefill_tokens=256}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 256 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 256 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))
2023-10-17T16:01:52.567651Z ERROR text_generation_launcher: Webserver Crashed
2023-10-17T16:01:52.567696Z  INFO text_generation_launcher: Shutting down shards
2023-10-17T16:01:52.671125Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=1
2023-10-17T16:01:52.716209Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
Error: WebserverFailed
```

### Expected behavior

I decreased initial parameters of `--max-batch-prefill-tokens 256 --max-total-tokens 128 --max-input-length 64` by a lot and I expected it to fit into 2 GPUs.

**Comment by pranavbhat12** [comment]
I am also facing the same issue.Did not get any luck. Tried changing various parameters.

**Comment by danilyef** [comment]
I tried `-e DISABLE_EXLLAMA=True`, but unfortunatelly it didn't help, I am getting the same error.

**Comment by OlivierDehaene** [comment]
Can you try the `latest` image instead? This bug was fixed but we didn't release a new version yet.
