### ISSUE TITLE
Not enough memory on four T4 for gptq quantized models

### ISSUE THREAD

**Issue by federicocagnola** [huggingface/text-generation-inference#1168]
### System Info

Target: `x86_64-unknown-linux-gnu`
Cargo version: `1.70.0`
Commit sha: `3af1a1140141245c20df20a787831ec71b124eae`
Docker label: `sha-3af1a11`
Docker image: `ghcr.io/huggingface/text-generation-inference:latest` (1.1.0)
Nvidia-smi: 
![Screenshot from 2023-10-18 10-12-31](https://github.com/huggingface/text-generation-inference/assets/96195209/c608cef1-7061-4adf-b9e2-1856b3b72a04)
Hardware: GKE 95GB memory with four `nvidia-tesla-t4` (15G each)
Container runtime: `containerd://1.7.0`
Deployed on GKE with helmv3

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Helm chart produces this configuration:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-llm
spec:
    spec:
      containers:
        - name: conversation-llm
          image: "ghcr.io/huggingface/text-generation-inference:latest"
          imagePullPolicy: Always
          args:
            - "--sharded"
            - "true"
            - "--model-id"
            - "TheBloke/Llama-2-70B-chat-GPTQ"
            - "--num-shard"
            - "4"
            - "--quantize"
            - "gptq"
            - "--port"
            - "80"
            - "-e"
          resources:
            limits:
              nvidia.com/gpu: 4
            requests:
              memory: 90Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
      volumes:
        - emptyDir:
            medium: Memory
          name: shm
```

The deployment works, but whatever model I try to load i get into this stack:
```
2023-10-18T08:11:32.392656Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2023-10-18T08:11:32.590293Z  INFO text_generation_router: router/src/main.rs:371: Serving revision ac53ed5e8ebdbbe6db22ecf816e21f55905418df of model TheBloke/Llama-2-70B-chat-GPTQ
2023-10-18T08:11:32.596834Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-10-18T08:11:33.169170Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "<string>", line 21, in matmul_248_kernel
KeyError: ('2-.-0-.-0--d6252949da17ceb5f3a278a70250af13-1af5134066c618146d2cd009138944a0-235b7327308f95b8bc50ee7abd94d0ab-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.int32, torch.float16, torch.float16, torch.int32, torch.int32, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (64, 256, 32, 8), (True, True, True, True, True, True, (True, False), (True, False), (True, False), (False, False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (True, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 672, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 753, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 750, in generate_token
    out = self.forward(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 717, in forward
    return self.model.forward(
```
which causes 
```
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 244, in forward
    output = matmul248(input, qweight, scales, qzeros, g_idx, bits, maxq)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 216, in matmul248
    matmul_248_kernel[grid](
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 110, in run
    timings = {
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 111, in <dictcomp>
    config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 90, in _bench
    return triton.testing.do_bench(
  File "/opt/conda/lib/python3.9/site-packages/triton/testing.py", line 143, in do_bench
    fn()
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 80, in kernel_call
    self.fn.run(
  File "<string>", line 41, in matmul_248_kernel
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 1587, in compile
    so_path = make_stub(name, signature, constants)
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 1476, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 1391, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpfxbrg6hv/main.c', '-O3', '-I/opt/conda/lib/python3.9/site-packages/triton/third_party/cuda/include', '-I/opt/conda/include/python3.9', '-I/tmp/tmpfxbrg6hv', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpfxbrg6hv/matmul_248_kernel.cpython-39-x86_64-linux-gnu.so']' returned non-zero exit status 1.
```
which in turn results in
```
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 72, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 674, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
```

I tried:

- loading lighter models (13b. 7b)
- following the error's advice and reducing max-batch-prefill-tokens

but nothing seems to work, i always end up with `Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens``

### Expected behavior

1. Quantized model loaded correctly onto a machine with 4 T4
2. Inference server to be available

**Comment by federicocagnola** [comment]
Update: tried with an AWQ quantized model instead of GPTQ and there was a slightly different error in the stack trace:

```
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/awq/quantize/qmodule.py", line 46, in forward
    out = awq_inference_engine.gemm_forward_cuda(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

could it be that the CUDA libraries were compiled for another GPU (A100) and won't work on my T4s?

**Comment by mbuet2ner** [comment]
It does say so in the [README](https://github.com/huggingface/text-generation-inference#cuda-kernels):

> The custom CUDA kernels are only tested on NVIDIA A100s

I also have a lot of issues with T4s at the moment (especially with quantised models). There are also a couple of other issues referencing T4s. A A40 works fine for me though.

**Comment by OlivierDehaene** [comment]
Yeah sorry the Turing support is not great =/

**Comment by mbuet2ner** [comment]
Thanks for the confirmation! So I guess the best option right now is to stick to Ampere then. Hope this saves someone some troubleshooting.

**Comment by OlivierDehaene** [comment]
Turing is a bit of a headache because a lot of the kernels that come out today simply ignore it. Flash attn V2 is a famous example.
For now we can continue supporting it on a best-effort basis but we might be forced to drop it soon-ish.

**Comment by mbuet2ner** [comment]
Sounds very reasonable to drop it then. And yes – there were a lot of errors related to Flash Attention v2 in the logs as well. Thank you so much for the context :slightly_smiling_face:!

**Comment by federicocagnola** [comment]
> Turing is a bit of a headache because a lot of the kernels that come out today simply ignore it. Flash attn V2 is a famous example. For now we can continue supporting it on a best-effort basis but we might be forced to drop it soon-ish.

thank you for the quick response!

for people interested in using T4s I managed to get vLLM to serve a quantized llama-70b-AWQ on four T4
