### ISSUE TITLE
ValueError: weight is on the meta device, we need a `value` to put in on 0.

### ISSUE THREAD

**Issue by mpskex** [huggingface/text-generation-inference#1177]
### System Info

I am using `ghcr.io/huggingface/text-generation-inference:latest` with locally prepared model `cerebras/btlm-3b-8k-base`.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Using bash script which uses the latest text-generation-inference image:
```bash
model=/data/cerebras/btlm-3b-8k-base
volume=<place to store my local model>

docker run --gpus all \
    --shm-size 1g \
    -p 8080:80 \
    -e MAX_TOTAL_TOKENS=4096 \
    -e MAX_INPUT_LENGTH=4095 \
    -e CUDA_VISIBLE_DEVICES=1,2,3,4 \
    -e DTYPE=bfloat16 \
    -v $volume:/data ghcr.io/huggingface/text-generation-inference \
    --sharded false \
    --trust-remote-code \
    --model-id $model \
    --max-batch-prefill-tokens 4095
```
2. You will get 
```
2023-10-19T08:12:13.888633Z  INFO text_generation_launcher: Args { model_id: "/data/cerebras/btlm-3b-8k-base", revision: None, validation_workers: 2, sharded: Some(false), num_shard: None, quantize: None, dtype: Some(BFloat16), trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 4095, max_total_tokens: 4096, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4095, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "79076d6124f5", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-19T08:12:13.888717Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `/data/cerebras/btlm-3b-8k-base` do not contain malicious code.
2023-10-19T08:12:13.888979Z  INFO download: text_generation_launcher: Starting download process.
2023-10-19T08:12:17.612097Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-19T08:12:18.294754Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-19T08:12:18.295205Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-19T08:12:21.964292Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

2023-10-19T08:12:21.989485Z  WARN text_generation_launcher: Could not import Mistral model: Mistral model requires flash attn v2

2023-10-19T08:12:28.377286Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-19T08:12:36.884861Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 322, in get_model
    return CausalLM(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 504, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3246, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/big_modeling.py", line 373, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 527, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 527, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 497, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 154, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on 0.

2023-10-19T08:12:38.389830Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-19T08:12:38.490638Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 322, in get_model
    return CausalLM(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 504, in __init__
    model = AutoModelForCausalLM.from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3246, in from_pretrained
    dispatch_model(model, **device_map_kwargs)

  File "/opt/conda/lib/python3.9/site-packages/accelerate/big_modeling.py", line 373, in dispatch_model
    attach_align_device_hook_on_blocks(

  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 527, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(

  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 527, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(

  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 497, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)

  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)

  File "/opt/conda/lib/python3.9/site-packages/accelerate/hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)

  File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 154, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")

ValueError: weight is on the meta device, we need a `value` to put in on 0.
 rank=0
Error: ShardCannotStart
2023-10-19T08:12:38.587984Z ERROR text_generation_launcher: Shard 0 failed to start
2023-10-19T08:12:38.588025Z  INFO text_generation_launcher: Shutting down shards
```

### Expected behavior

Launches the model correctly.

I guess this is linked to [this issue](https://github.com/huggingface/accelerate/issues/1197) in `accelerate`

**Comment by mpskex** [comment]
By the way, `ghcr.io/huggingface/text-generation-inference:1.0.1` works like a charm.

**Comment by OlivierDehaene** [comment]
Thanks we will update accelerate.
