### ISSUE TITLE
GPTQ warming up is breaking at v1.2 but working at v1.1

### ISSUE THREAD

**Issue by jazken** [huggingface/text-generation-inference#1310]
### System Info

Running text-generation-inference on kubernetes.
GPUs - A100 x 8
Cuda 12.2

Running llama2 -- https://huggingface.co/TheBloke/Llama-2-70B-GPTQ/tree/gptq-4bit-32g-actorder_True

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Running with args as follows

- rope-scaling - "dynamic"
- rope-factor - "4.0"
- quantize - "gptq"
- revision - "gptq-4bit-32g-actorder_True
- max-batch-prefill-tokens - "16000"
- max-input-length - "16000"
- max-total-tokens - "16384"

Environment vars as follows:

- DISABLE_EXLLAMA - "true"

### Expected behavior

Expected to work on both versions - v1.1 and v1.2

**Comment by OlivierDehaene** [comment]
Can you share your stacktrace?

**Comment by jazken** [comment]
`Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>

    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__

    return get_command(self)(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__

    return self.main(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main

    return _main(

  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main

    rv = self.invoke(ctx)

  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke

    return __callback(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper

    return callback(**use_params)  # type: ignore

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve

    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve

    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete

    self.run_forever()

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever

    self._run_once()

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once

    handle._run()

  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run

    self._context.run(self._callback, *self._args)

  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method

    return await self.intercept(

> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept

    return await response

  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor

    raise error

  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor

    return await behavior(request_or_iterator, context)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 121, in Decode

    generations, next_batch = self.model.generate_token(batch)

  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner

    return func(*args, **kwds)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 753, in generate_token

    raise e

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 750, in generate_token

    out = self.forward(batch)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 717, in forward

    return self.model.forward(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 497, in forward

    hidden_states = self.model(

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl

    return forward_call(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 456, in forward

    hidden_states, residual = layer(

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl

    return forward_call(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 383, in forward

    attn_output = self.self_attn(

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl

    return forward_call(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 308, in forward

    return self.o_proj(attn_output.view(-1, self.num_heads * self.head_size))

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl

    return forward_call(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 473, in forward

    out = super().forward(input)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 351, in forward

    return self.linear.forward(x)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 349, in forward

    out = QuantLinearFunction.apply(

  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply

    return super().apply(*args, **kwargs)  # type: ignore[misc]

  File "/opt/conda/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 106, in decorate_fwd

    return fwd(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 244, in forward

    output = matmul248(input, qweight, scales, qzeros, g_idx, bits, maxq)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quant_linear.py", line 216, in matmul248

    matmul_248_kernel[grid](

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 110, in run

    timings = {

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 111, in <dictcomp>

    config: self._bench(*args, config=config, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/custom_autotune.py", line 90, in _bench

    return triton.testing.do_bench(

  File "/opt/conda/lib/python3.9/site-packages/triton/testing.py", line 177, in do_bench

    cache.zero_()

RuntimeError: CUDA error: invalid argument

Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`
