### ISSUE TITLE
Error `weight gptq_bits does not exist` when running `TheBloke/alfred-40B-1023-AWQ` model

### ISSUE THREAD

**Issue by tlevyaleia** [huggingface/text-generation-inference#1322]
### System Info

I am using the docker image ghcr.io/huggingface/text-generation-inference:1.2
On H100 GPU with Ubuntu 22.04.3 LTS

The command raises the error `weight gptq_bits does not exist` (see below).
Does that means that the AWQ version generated by TheBloke is not compatible with tgi inference?
If yes, how could I generate it in a proprer way?
Thanks for your advices,

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Running the following commands:
```
model=TheBloke/alfred-40B-1023-AWQ
docker run --gpus all --shm-size 1g -p 8080:3000 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.2 --model-id $model --quantize awq
```
Does the error `weight gptq_bits does not exist` means that the AWQ model generated by TheBloke is not compatible with tgi inference or anything else?

Result:
```
2023-12-08T16:01:13.639274Z  INFO text_generation_launcher: Args { model_id: "TheBloke/alfred-40B-1023-AWQ", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Awq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "d27b1f3d1d55", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-12-08T16:01:13.639369Z  INFO download: text_generation_launcher: Starting download process.
2023-12-08T16:01:18.835654Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-12-08T16:01:19.246954Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-12-08T16:01:19.247345Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-12-08T16:01:22.879154Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 322, in _get_gptq_params
    bits = self.gptq_bits
AttributeError: 'Weights' object has no attribute 'gptq_bits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 236, in get_model
    return FlashRWSharded(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_rw.py", line 67, in __init__
    model = FlashRWForCausalLM(config, weights)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 614, in __init__
    self.transformer = FlashRWModel(config, weights)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 548, in __init__
    [
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 549, in <listcomp>
    FlashRWLargeLayer(layer_id, config, weights)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 482, in __init__
    self.self_attention = FlashRWLargeAttention(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 265, in __init__
    self.query_key_value = TensorParallelColumnLinear.load(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py", line 448, in load
    return cls.load_multi(config, [prefix], weights, bias, dim=0)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py", line 452, in load_multi
    weight = weights.get_multi_weights_col(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 214, in get_multi_weights_col
    bits, groupsize = self._get_gptq_params()
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 325, in _get_gptq_params
    raise e
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 318, in _get_gptq_params
    bits = self.get_tensor("gptq_bits").item()
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 75, in get_tensor
    filename, tensor_name = self.get_filename(tensor_name)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 63, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight gptq_bits does not exist

2023-12-08T16:01:23.453146Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using a model of type RefinedWeb to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:602: UserWarning: You are using a Backend <class 'text_generation_server.utils.dist.FakeGroup'> as a ProcessGroup. This usage is deprecated since PyTorch 2.0. Please use a public API of PyTorch Distributed instead.
  warnings.warn(
Traceback (most recent call last):

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 322, in _get_gptq_params
    bits = self.gptq_bits

AttributeError: 'Weights' object has no attribute 'gptq_bits'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 236, in get_model
    return FlashRWSharded(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_rw.py", line 67, in __init__
    model = FlashRWForCausalLM(config, weights)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 614, in __init__
    self.transformer = FlashRWModel(config, weights)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 548, in __init__
    [

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 549, in <listcomp>
    FlashRWLargeLayer(layer_id, config, weights)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 482, in __init__
    self.self_attention = FlashRWLargeAttention(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 265, in __init__
    self.query_key_value = TensorParallelColumnLinear.load(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py", line 448, in load
    return cls.load_multi(config, [prefix], weights, bias, dim=0)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py", line 452, in load_multi
    weight = weights.get_multi_weights_col(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 214, in get_multi_weights_col
    bits, groupsize = self._get_gptq_params()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 325, in _get_gptq_params
    raise e

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 318, in _get_gptq_params
    bits = self.get_tensor("gptq_bits").item()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 75, in get_tensor
    filename, tensor_name = self.get_filename(tensor_name)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 63, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")

RuntimeError: weight gptq_bits does not exist
 rank=0
Error: ShardCannotStart
2023-12-08T16:01:23.551003Z ERROR text_generation_launcher: Shard 0 failed to start
2023-12-08T16:01:23.551053Z  INFO text_generation_launcher: Shutting down shards
```

### Expected behavior

I would have expected to run the server for alfred-40B-1023-AWQ model.

**Comment by RonanKMcGovern** [comment]
Yes, I'm having the same issue on an A6000 with TheBloke/Yi-34B-200K-AWQ

**Comment by RonanKMcGovern** [comment]
@tlevyaleia did you have any joy finding a fix to this?

**Comment by RonanKMcGovern** [comment]
unstale.
