### ISSUE TITLE
TGI v1.3.1 Docker container Mixtral 8x7b not running

### ISSUE THREAD

**Issue by abatilo** [huggingface/text-generation-inference#1330]
### System Info

Running `ghcr.io/huggingface/text-generation-inference:1.3.1` with model `mistralai/Mixtral-8x7B-Instruct-v0.1` in a GKE cluster using 2x80gb A100s.

I've been running the Llama2 and Mistral 7b models with my same setup and these are working fine. I believe it's something new with the `megablocks` changes that just got integrated.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Try to load the `mistralai/Mixtral-8x7B-Instruct-v0.1` model in the docker container

```
2023-12-11T16:23:43.337331Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 72, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 692, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 823, in generate_token
    raise e
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 820, in generate_token
    out = self.forward(batch)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 398, in forward
    logits = self.model.forward(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 704, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 648, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 594, in forward
    block_sparse_moe_output = self.block_sparse_moe(normed_attn_res_output)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 494, in forward
    x = ops.padded_gather(x, indices, bin_ids, bins, padded_bins, self.top_k)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/stk/backend/autocast.py", line 28, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/megablocks/ops/padded_gather.py", line 14, in forward
    return kernels.padded_gather(
  File "/opt/conda/lib/python3.10/site-packages/megablocks/backend/kernels.py", line 123, in padded_gather
    _padded_copy[(indices.shape[0],)](
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/opt/conda/lib/python3.10/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 63, in _padded_copy
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/opt/conda/lib/python3.10/site-packages/triton/common/build.py", line 61, in _build
    cuda_lib_dirs = libcuda_dirs()
  File "/opt/conda/lib/python3.10/site-packages/triton/common/build.py", line 30, in libcuda_dirs
    assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg
AssertionError: libcuda.so cannot found!


2023-12-11T16:23:43.338120Z ERROR warmup{max_input_length=32767 max_prefill_tokens=32767 max_total_tokens=32768}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: libcuda.so cannot found!

Error: Warmup(Generation("libcuda.so cannot found!\n"))
```

### Expected behavior

I'd expect the model to load correctly

**Comment by OlivierDehaene** [comment]
Can you run --env ?

**Comment by OlivierDehaene** [comment]
That seems to be an issue with Triton. 
Maybe [this comment](https://github.com/pytorch/pytorch/issues/107960#issuecomment-1783432552) can help?

**Comment by abatilo** [comment]
Yeah, something fishy is going on here.

The container is built with triton 2.1.0

```
root@mixtral:~# pip freeze | grep "triton"
triton==2.1.0
```

So then I can go look at that code in the triton repo:
https://github.com/openai/triton/blob/v2.1.0/python/triton/common/build.py#L30

If I execute this function on its own directly on the node's output for `ldconfig -p`, the assertion doesn't fail.

It looks like what's happening is that even though `LD_LIBRARY_PATH` is set at the root process for `text-generation-launcher`, it's not propagating to the `subprocess` that's being ran as part of the `ldconfig -p`, which is causing `ldconfig -p` to not return the location of `libcuda.so`. Hmm.

**Comment by abatilo** [comment]
I found a solution. If you're running in Kubernetes, you need to re-run `ldconfig` before `text-generation-inference` runs.

```
  - command:
    - bash
    - -c
    - |
      ldconfig
      text-generation-launcher --model-id mistralai/Mixtral-8x7B-Instruct-v0.1 --sharded "true" --num-shard "2"
```

This works. I'm not sure why `ldconfig` needs to be reran for this but not for others.

**Comment by Blair-Johnson** [comment]
We've run into this issue as well. On a cluster environment, `ldconfig` would typically access root-owned directories. I'm still interested in finding a fix that doesn't require escalated privileges.

**Comment by abatilo** [comment]
It looks like in the latest version of `triton`, that there's a different env variable that you can set to specify where to find `libcuda.so`:

https://github.com/openai/triton/blob/720d12c1433e5b13eb3a18d1e065c1d3d25a32f1/python/triton/common/build.py#L21-L23

**Comment by OlivierDehaene** [comment]
Weird. We run all our deployments in k8s and don't run into this issue. I will have a look.

**Comment by abatilo** [comment]
@OlivierDehaene could you share a typical manifest that's used?

**Comment by Blair-Johnson** [comment]
Still present in 1.3.3. I tested out adding a `RUN ldconfig` step to the docker build, but I wasn't able to resolve the issue.

**Comment by OlivierDehaene** [comment]
- Do you guys deploy in EKS, GKE, something else?
- Do you use the Nvidia Operator, Nvidia device plugin?
- Do you overwrite the NVIDIA_DRIVER_CAPABILITIES, or LD_LIBRARY_PATH env var for some reason?

**Comment by Blair-Johnson** [comment]
We aren't using Kupernetes; we convert the public docker image to singularity to run on our HPC system.

Triton looks for `libcuda.so` using `/sbin/ldconfig -p`. This searches for the shared libraries included in `/etc/ld.so.conf`, which includes all the conf files in `/etc/ld.so.conf.d/`. If we take a look at `/etc/ld.so.conf.d`, we can see that several cuda paths are included, but none points to `libcuda.so`:

In `/etc/ld.so.conf.d/000_cuda.conf`:
`/usr/local/cuda/targets/x86_64-linux/lib`
Which contains a cuda runtime `libcudart.so.12`, `libcudart.so.12.1.55`

`/etc/ld.so.conf.d/988_cuda-12.conf` points to:
`/usr/local/cuda-12/targets/x86_64-linux/lib`
Which also contains `libcudart.so.12` and `libcudart.so.12.1.55`

Finally `/etc/ld.so.conf.d/nvidia.conf` points to:
```
/usr/local/nvidia/lib
/usr/local/nvidia/lib64
```
Which don't exist.

`libcuda.so` exists in:
```
/usr/local/cuda/compat/
/usr/local/cuda-12/compat/
/usr/local/cuda-12.1/compat/
```

**Comment by Blair-Johnson** [comment]
I was able to solve the issue locally. There's currently no `.conf` file in `/etc/ld.so.conf.d/` which points to one of the locations of `libcuda.so`. To solve this, you need to add a `.conf` file pointing to the directory of a `libcuda.so`, and then run `ldconfig` to update the ld cache with the new search location.

First I created a new conf file in `/etc/ld.so.conf.d`:
```
echo "/usr/local/cuda-12.1/compat" > /etc/ld.so.conf.d/libcuda.conf
```
Then I updated the ldcache:
```
ldconfig
```
In singularity, this required a temporary writable file system, binding a local version of `libcuda.conf` into the container's `/etc/ld.so.conf.d`, and then running `ldconfig && text-generation-launcher`

I'll see if I can update the dockerfile to address this issue and submit a PR for others to test.

**Comment by OlivierDehaene** [comment]
> We aren't using Kupernetes; we convert the public docker image to singularity to run on our HPC system.

I think the original issue came from trouble running the image in GKE though. @abatilo do you still have issues?

> Triton looks for libcuda.so using /sbin/ldconfig -p. [...] we can see that several cuda paths are included, but none points to libcuda.so

Yes, the [nvidia container toolkit](https://github.com/NVIDIA/nvidia-container-toolkit) mounts this shared object. The runtime makes sure that the node .so is used inside the container then [updates the conf](https://github.com/NVIDIA/nvidia-container-toolkit/blob/a2262d00cc6d98ac2e95ae2f439e699a7d64dc17/cmd/nvidia-ctk/hook/update-ldcache/update-ldcache.go#L132).

I think the `nvidia-container-cli` equivalent in singularity is missing part/all this logic.

**Comment by dr3s** [comment]
In GKE driver installs have been a mess for at least 3 months.  I don't know where I got the daemonset that is working but the instructions point to this:
`kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded-latest.yaml`

However that is missing this block from a daemonset that I have working on another node group
```
      echo "Waiting for GPU driver libraries to be available."

      while ! [[ -f /usr/local/nvidia/lib64/libcuda.so ]]; do

        sleep 5

      done

      echo "GPU driver is installed."
```

Judging by the fact that the node group that has this sleep works, I'm guessing there's a race condition when bootstrapping the node with the init container for the nvidia installer.

**Comment by NielsRogge** [comment]
Hi,

I've successfully deployed Mistral-7B on GKE by following this guide: https://medium.com/google-cloud/serving-mistral-7b-on-l4-gpus-running-on-gke-25c6041dff27. The guide uses 2 L4 GPUs, each with 24GB of RAM, so a total of 48GB is available.

However, when only changing 1 line in the YAML file (namely mistralai/Mistral-7B-Instruct-v0.1 by mistralai/Mixtral-8x7B-Instruct-v0.1):

```
containers:
      - name: mixtral-8x7b
        image: ghcr.io/huggingface/text-generation-inference:1.3.4
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - name: server-port
          containerPort: 8080
        env:
        - name: MODEL_ID
          value: mistralai/mixtral-8x7b-Instruct-v0.1
        - name: NUM_SHARD
          value: "1"
        - name: PORT 
          value: "8080"
        - name: QUANTIZE
          value: bitsandbytes-nf4
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
```

, I get CUDA OOMs:

```
ile \"/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py\", line 333, in __init__\n    model = model_cls(config, weights)\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py\", line 812, in __init__\n    self.model = MixtralModel(config, weights)\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py\", line 749, in __init__\n    [\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py\", line 750, in <listcomp>\n    MixtralLayer(\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py\", line 689, in __init__\n    self.moe = moe_cls(f\"{prefix}.block_sparse_moe\", config, weights)\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py\", line 615, in __init__\n    self.w1 = [\n\n  File \"/opt/conda/lib/python3.10/site-
packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py\", line 616, in <listcomp>\n    TensorParallelColumnLinear.load(\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py\", line 456, in load\n    return cls.load_multi(config, [prefix], weights, bias, dim=0)\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py\", line 460, in load_multi\n    weight = weights.get_multi_weights_col(\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py\", line 224, in get_multi_weights_col\n    weight = torch.cat(w, dim=dim)\n\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 21.99 GiB of which 5.69 MiB is free. Process 33090 has 21.98 GiB memory in use. Of the allocated memory 20.60 GiB is allocated by PyTorch, and 390.84 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
```
I assume this is because one should provide an already quantized model and add the QUANTIZE flag to tell TGI you're using a quantized model? The guide above written by Google does not provide a quantized model and adds the QUANTIZE flag. @OlivierDehaene could you clarify this?

Next I tried this:
```
containers:
      - name: mixtral-8x7b-gptq
        image: ghcr.io/huggingface/text-generation-inference:1.3.4
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - name: server-port
          containerPort: 8080
        env:
        - name: MODEL_ID
          value: ybelkada/mixtral-8x7b-gptq-Instruct-v0.1-AWQ
        - name: NUM_SHARD
          value: "1"
        - name: PORT 
          value: "8080"
        - name: QUANTIZE
          value: gptq
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
```
Since people [reported](https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ/discussions/1#659d86e3ec9f8f337f105cd0) succcessfully deploying this model using TGI. This model is about 25GB in size so this should work. But this errors with:
```
Error: DownloadError
{"timestamp":"2024-01-12T10:17:24.249139Z","level":"ERROR","fields":{"message":"Download encountered an error: Traceback (most recent call last):\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py\", line 270, in hf_raise_for_status\n    response.raise_for_status()\n\n  File \"/opt/conda/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n\nrequests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/ybelkada/mixtral-8x7b-gptq-Instruct-v0.1-AWQ\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py\", line 128, in download_weights\n    utils.weight_files(model_id, revision, extension)\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py\", line 149, in weight_files\n    filenames = weight_hub_files(model_id, revision, extension)\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py\", line 108, in weight_hub_files\n    info = api.model_info(model_id, revision=revision)\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py\", line 118, in _inner_fn\n    return fn(*args, **kwargs)\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py\", line 1922, in model_info\n    hf_raise_for_status(r)\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py\", line 320, in hf_raise_for_status\n    raise RepositoryNotFoundError(message, response) from e\n\nhuggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-65a111b3-37bfef2214bb472c74c7f872;0bd22834-7a6f-461b-8752-408d121e1d8e)\n\nRepository Not Found for url: https://huggingface.co/api/models/ybelkada/mixtral-8x7b-gptq-Instruct-v0.1-AWQ.\nPlease make sure you specified the correct `repo_id` and `repo_type`.\nIf you are trying to access a private or gated repo, make sure you are authenticated.\nInvalid username or password.\n\n"},"target":"text_generation_launcher","span":{"name":"download"},"spans":[{"name":"download"}]}
```
This is odd since the model is public. There's also https://huggingface.co/ybelkada/Mixtral-8x7B-Instruct-v0.1-bnb-4bit (same model but quantized using bitsandbytes rather than GPTQ) but since 4-bit serialization is brand new I'm not sure this is already supported.

**Comment by nolwennz** [comment]
Hello, was anyone able to fix the issue or to find a workaround? 
I'm also trying to deploy mistralai/Mixtral-8x7B-v0.1 with TGI on GKE and I also get `AssertionError: libcuda.so cannot found!` despite adding the `ldconfig` command before launching the server
