### ISSUE TITLE
"CUDA is not available" on 1.3.2 Docker image

### ISSUE THREAD

**Issue by gameveloster** [huggingface/text-generation-inference#1339]
### System Info

Using Docker image `ghcr.io/huggingface/text-generation-inference:1.3.2`
Using RTX 3090

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
version: "3.5"

  tgi:
    container_name: tgi
    image: ghcr.io/huggingface/text-generation-inference:1.3.2
    command: [
        "--quantize",
        "awq",
        "--model-id",
        "/data/TheBloke_Yi-34B-Chat-AWQ",
    ]
    volumes:
      - /llm/:/data/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
    shm_size: "4g"
```

```
2023-12-13T03:16:21.518741Z  INFO text_generation_launcher: Args { model_id: "/data/TheBloke_Yi-34B-Chat-AWQ", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Awq), speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 2500, max_total_tokens: 3400, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 2500, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "323ed61165af", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-12-13T03:16:21.518904Z  INFO download: text_generation_launcher: Starting download process.
2023-12-13T03:16:24.595808Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-12-13T03:16:25.326439Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-12-13T03:16:25.327071Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-12-13T03:16:28.381947Z  WARN text_generation_launcher: We're not using custom kernels.

2023-12-13T03:16:28.424953Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2023-12-13T03:16:28.426838Z  WARN text_generation_launcher: Could not import Mistral model: CUDA is not available

2023-12-13T03:16:28.427444Z  WARN text_generation_launcher: Could not import Mixtral model: CUDA is not available

2023-12-13T03:16:28.491469Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 258, in get_model
    return CausalLM(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 491, in __init__
    raise ValueError("quantization is not available on CPU")
ValueError: quantization is not available on CPU

2023-12-13T03:16:29.232603Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /opt/conda/conda-bld/pytorch_1699449201336/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 258, in get_model
    return CausalLM(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 491, in __init__
    raise ValueError("quantization is not available on CPU")

ValueError: quantization is not available on CPU
 rank=0
2023-12-13T03:16:29.330149Z ERROR text_generation_launcher: Shard 0 failed to start
2023-12-13T03:16:29.330181Z  INFO text_generation_launcher: Shutting down shards
```

### Expected behavior

It should start up without crashing, like it did on 1.1.1

**Comment by OlivierDehaene** [comment]
Can you send us the output of `--env`?

**Comment by gameveloster** [comment]
Works now after updating CUDA version to 12.2.
