### ISSUE TITLE
exllama v2: problem with Mixtral-8x7B GPTQ

### ISSUE THREAD

**Issue by AIexanderDicke** [huggingface/text-generation-inference#1345]
### System Info

GPU: A6000 48 GB
Image: ghcr.io/huggingface/text-generation-inference:1.3.2
Model: TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ & TheBloke/Mixtral-SlimOrca-8x7B-GPTQ

Running `docker run --gpus '"device=0"' ghcr.io/huggingface/text-generation-inference:1.3.2 --model-id TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ --num-shard 1 --max-input-length 3696 --max-total-tokens 4096 --max-batch-prefill-tokens 4096 --max-best-of 1 --quantize gptq` throws an error: 
````
/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:602: UserWarning: You are using a Backend <class 'text_generation_server.utils.dist.FakeGroup'> as a ProcessGroup. This usage is deprecated since PyTorch 2.0. Please use a public API of PyTorch Distributed instead.
  warnings.warn(
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 310, in get_model
    return FlashMixtral(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mixtral.py", line 21, in __init__
    super(FlashMixtral, self).__init__(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 333, in __init__
    model = model_cls(config, weights)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 820, in __init__
    self.model = MixtralModel(config, weights)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 757, in __init__
    [

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 758, in <listcomp>
    MixtralLayer(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 692, in __init__
    self.self_attn = MixtralAttention(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 232, in __init__
    self.query_key_value = load_attention(config, prefix, weights)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 125, in load_attention
    return _load_gqa(config, prefix, weights)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 158, in _load_gqa
    get_linear(weight, bias=None, quantize=config.quantize)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py", line 330, in get_linear
    linear = ExllamaQuantLinear(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/gptq/exllamav2.py", line 145, in __init__
    assert qzeros.shape == (

AssertionError
````

This seems to be a problem with exllama kernels v2: It is possible to start the GPTQ Version by explicitly setting EXLLAMA_VERSION=1, i.e. `docker run --gpus '"device=0"' --shm-size 1g -e EXLLAMA_VERSION=1 ghcr.io/huggingface/text-generation-inference:1.3.2 --model-id TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ --num-shard 1 --max-input-length 3696 --max-total-tokens 4096 --max-batch-prefill-tokens 4096 --max-best-of 1 --quantize gptq`.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

Run `docker run --gpus '"device=0"' ghcr.io/huggingface/text-generation-inference:1.3.2 --model-id TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ --num-shard 1 --max-input-length 3696 --max-total-tokens 4096 --max-batch-prefill-tokens 4096 --max-best-of 1 --quantize gptq`

### Expected behavior

Works with exllama v2.

**Comment by nathan-az** [comment]
Maybe related to https://github.com/huggingface/text-generation-inference/issues/1355, attempting the same with sharding.

**Comment by RonanKMcGovern** [comment]
I don't believe TGI supports Mixtral yet.

There are added parameters - like number of chosen experts - that would need to be added to the code. Probably at a more abstracted level than Exllama.

I also don't see Mixtral mentioned in the exllamav2 repo

**Comment by nathan-az** [comment]
@RonanKMcGovern https://huggingface.co/blog/mixtral#using-text-generation-inference

TGI definitely has base support for Mixtral. I expect the issue is on the quantization/exllama side.

**Comment by RonanKMcGovern** [comment]
@nathan-az , yes, sorry. I meant TGI using GPTQ/exllama quantization.

TGI works with bnb nf4 and also eetq and also bf16.

**Comment by donaldseah** [comment]
I am encountering the same error, with the same cards. Sharding is working.

**Comment by vdedejski** [comment]
Having the same issue when running: TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ
