### ISSUE TITLE
microsoft/phi-2: Unsupported model type phi-msft

### ISSUE THREAD

**Issue by walkacross** [huggingface/text-generation-inference#1365]
### System Info

ghcr.io/huggingface/text-generation-inference:1.3.3

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

~~~
model="microsoft/phi-2"
volume=$PWD/data
sudo docker run --rm --shm-size 1g -p 8080:80 -v $volume:/data  ghcr.io/huggingface/text-generation-inference:1.3.3 --model-id $model --disable-custom-kernels
~~~

~~~
2023-12-20T08:51:21.936190Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 228, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 174, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 398, in get_model
    raise ValueError(f"Unsupported model type {model_type}")
ValueError: Unsupported model type phi-msft

2023-12-20T08:51:22.515233Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

~~~

### Expected behavior

normal output

**Comment by tmandal** [comment]
I had to use `--trust-remote-code ` to work around above issue. The TGI server comes up OK.

However TGI runs into error when a request is sent.

>>> _curl 127.0.0.1:8080/generate -X POST -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}'  -H 'Content-Type: application/json'_
{"error":"Request failed during generation: Server error: output with shape [1, 1] doesn't match the broadcast shape [1, 6]","error_type":"generation"}

**Comment by ArthurZucker** [comment]
Hey! This model is not part of the transformers library yet, see #28163 for following the integration !

**Comment by walkacross** [comment]
Hi @ArthurZucker, Thanks for feedback.
i saw the model phi-2 has already been supported by transformer library. https://huggingface.co/microsoft/phi-2 and I can load it locally.

could you please tell me: does the text-generation-inference supports all the models in transformer library or part of them? I am a little bit confused.

**Comment by abatilo** [comment]
I would also appreciate support for the `phi` family of models!

**Comment by drbh** [comment]
resolved by https://github.com/huggingface/text-generation-inference/pull/1442
