### ISSUE TITLE
Mixtral Error on Docker

### ISSUE THREAD

**Issue by donaldseah** [huggingface/text-generation-inference#1375]
Hi,

I have a machine with 4 X A6000 cards and am trying to run Mixtral 8x7B but there seems to be sharding problem.

```
sudo docker run --gpus 4 --shm-size 1g -p 8080:80 -v /mixtral/data:/data ghcr.io/huggingface/text-generation-inference:1.3.0 --model-id mistralai/Mixtral-8x7B-Instruct-v0.1 --num-shard 4 --max-batch-total-tokens 1024000 --max-total-tokens 32000
```

The error I get:
```
2023-12-22T05:32:06.792540Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-12-22T05:32:06.792866Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-12-22T05:32:06.792902Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-12-22T05:32:06.793322Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2023-12-22T05:32:06.793721Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2023-12-22T05:32:09.950682Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-22T05:32:09.991184Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-22T05:32:10.003198Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-22T05:32:10.037138Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-22T05:32:11.865903Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 310, in get_model
    return FlashMixtral(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mixtral.py", line 21, in __init__
    super(FlashMixtral, self).__init__(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 318, in __init__
    SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOCK_SIZE)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
 rank=2
2023-12-22T05:32:12.496795Z ERROR text_generation_launcher: Shard 2 failed to start
2023-12-22T05:32:12.496817Z  INFO text_generation_launcher: Shutting down shards
2023-12-22T05:32:12.499723Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 310, in get_model
    return FlashMixtral(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mixtral.py", line 21, in __init__
    super(FlashMixtral, self).__init__(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 318, in __init__
    SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOCK_SIZE)

TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
 rank=1
2023-12-22T05:32:12.726710Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
Error: ShardCannotStart
2023-12-22T05:32:12.778861Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=3
```

**Comment by RonanKMcGovern** [comment]
16-bit does work on TGI but the downloading can get stuck and have to be re-started a few times.

Here's a [runpod template](https://runpod.io/gsc?template=1ydpo4766w&ref=jmfkcdio).

AWQ doesn't seem to work yet on TGI - it loads but gives an empty response. See [here](https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ/discussions/1)

**Comment by RonanKMcGovern** [comment]
@OlivierDehaene I just ran [this template](https://runpod.io/gsc?template=546m57v73a&ref=jmfkcdio) again, specifically with 1.3.4 and have the same issue of no text in the response.

**Comment by OlivierDehaene** [comment]
I'm talking about this specific issue regarding `TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'`.

**Comment by RonanKMcGovern** [comment]
Howdy @QLutz - I can't replicate this. That template works for me on an A6000 with this request:
```
curl https://g6x63zok6ixqr9-8080.proxy.runpod.net/generate \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
    -H 'Content-Type: application/json'
```
