### ISSUE TITLE
CUDA out of memory (4-bit quantization issue?)

### ISSUE THREAD

**Issue by DmitriiCM** [huggingface/text-generation-inference#1378]
### System Info

INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: N/A
Docker label: N/A
nvidia-smi:
Sat Dec 23 14:08:56 2023       
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  NVIDIA GeForce RTX 3060 Ti     On  | 00000000:0A:00.0  On |                  N/A |
   |  0%   40C    P8              25W / 200W |    867MiB /  8192MiB |      1%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+
                                                                                            
   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   |    0   N/A  N/A      3250      G   /usr/lib/xorg/Xorg                          443MiB |
   |    0   N/A  N/A      3385      G   /usr/bin/gnome-shell                        199MiB |
   |    0   N/A  N/A      5964    C+G   ...seed-version=20231218-080113.411000      206MiB |
   +---------------------------------------------------------------------------------------+
2023-12-23T13:08:57.015394Z  INFO text_generation_launcher: Args { model_id: "bigscience/bloom-560m", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "0.0.0.0", port: 3000, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: true }
2023-12-23T13:08:57.015518Z  INFO download: text_generation_launcher: Starting download process.
2023-12-23T13:08:59.902611Z  INFO text_generation_launcher: Download file: model.safetensors

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Hi all, and thanks for the cool project.

I am trying to run _text-generation-launcher_ on a 8GB GeForce RTX 3060 GPU:

```
volume=$PWD/data

text-generation-launcher --model-id tiiuae/falcon-7b-instruct --quantize bitsandbytes-nf4 --port 8080 --huggingface-hub-cache=$volume
```

As an output, I only get the "torch.cuda.OutOfMemoryError: CUDA out of memory" error:

```
2023-12-23T13:07:54.671921Z  INFO download: text_generation_launcher: Starting download process.
2023-12-23T13:07:58.465740Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-12-23T13:07:58.977471Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-12-23T13:07:58.977679Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-12-23T13:08:01.235187Z  WARN text_generation_launcher: We're not using custom kernels.

2023-12-23T13:08:01.788692Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2023-12-23T13:08:08.986788Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-12-23T13:08:15.887731Z ERROR text_generation_launcher: Error when initializing model

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 158.00 MiB. GPU 0 has a total capacty of 7.78 GiB of which 87.31 MiB is free.
```

This is weird, because I can load the same model directly in Python, and it works well:

```
model_id = "tiiuae/falcon-7b-instruct"

bnb_config = BitsAndBytesConfig(
                                load_in_4bit=True,
                                bnb_4bit_quant_type="nf4",
                                bnb_4bit_compute_dtype=torch.float16  # bnb_4bit_compute_dtype=torch.bfloat16
                               )
model = AutoModelForCausalLM.from_pretrained(model_id,
                                             quantization_config=bnb_config,
                                             device_map='auto',
                                             cache_dir="data",
                                             trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(model_id,
                                          cache_dir="data"
                                          )
```

What can be a difference?
Thanks

### Expected behavior

The model should work on the same GPU because it works normally from Python.

**Comment by DmitriiCM** [comment]
A small addition to the previous post. 

Today, I did a test in Colab Pro with A100. 
Running a 7B model using this command

`text-generation-launcher --model-id "meta-llama/Llama-2-7b-chat-hf" --quantize bitsandbytes-fp4 --port 5000 --hostname 127.0.0.1 --huggingface-hub-cache=/content/data`

requires 16.6GB of VRAM. It looks like for some reason quantization does not work, despite "bitsandbytes-fp4" being enabled.

![image](https://github.com/huggingface/text-generation-inference/assets/49151031/63f65216-2795-4596-a223-b896e5dc8285)

**Comment by Narsil** [comment]
Did you install FlashAttention ? I notice it's missing in your logs, and this can affect the happy path.

When missing FlashAttention you'll end up in this code https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/__init__.py#L350-L357 which indeed doesn't have bnb support.

**Comment by DmitriiCM** [comment]
Thanks for the answer. The flash attention is not installed indeed. I'm using Google Colab, there is no Docker support there. I will try to build flash attention from source later and see if it helps.

Without flash attention, the result with 7B Llama model and 16GB VRAM looks like this:
--quantize=bitsandbytes (8 bit) - works
--quantize=bitsandbytes-nf4 or fp4 (4bit) - does not work, CUDA out of memory
--quantize=awq (4bit) - works

AWQ 4-bit is good enough for me, not critical to use bitsandbytes-fp4 though.

**Comment by DmitriiCM** [comment]
I did another test today in Colab Pro.
After running the command `cd /content/text-generation-inference-1.3.4/server && make install install-flash-attention` flash attention was compiled and installed (the process took about an hour:).

Now a command `text-generation-launcher --model-id "meta-llama/Llama-2-7b-chat-hf" --quantize bitsandbytes-fp4 --port 5000 --hostname 127.0.0.1 --huggingface-hub-cache=/content/data` gives now another error:

```
2024-01-11T20:42:35.221224Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-01-11T20:42:39.787168Z  WARN text_generation_launcher: We're not using custom kernels.

2024-01-11T20:42:40.391046Z  WARN text_generation_launcher: Unable to use Flash Attention V2: Flash Attention V2 is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention v2 with `cd server && make install install-flash-attention-v2`

2024-01-11T20:42:42.767834Z  WARN text_generation_launcher: Mixtral: megablocks is not installed

2024-01-11T20:42:45.235030Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-01-11T20:42:50.451917Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2024-01-11T20:42:50.541855Z  INFO shard-manager: text_generation_launcher: Shard ready in 15.319764545s rank=0
2024-01-11T20:42:50.638566Z  INFO text_generation_launcher: Starting Webserver
2024-01-11T20:42:51.375167Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2024-01-11T20:42:51.375195Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2024-01-11T20:42:51.550590Z  WARN text_generation_router: router/src/main.rs:182: Could not retrieve model info from the Hugging Face hub.
2024-01-11T20:42:51.550612Z  WARN text_generation_router: router/src/main.rs:194: no pipeline tag found for model meta-llama/Llama-2-7b-chat-hf
2024-01-11T20:42:51.555973Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2024-01-11T20:42:52.202859Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/usr/local/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 778, in main
    return _main(
  File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/content/text-generation-inference-1.3.4/server/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/server.py", line 95, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/flash_causal_lm.py", line 693, in warmup
    _, batch, _ = self.generate_token(batch)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/flash_causal_lm.py", line 825, in generate_token
    raise e
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/flash_causal_lm.py", line 822, in generate_token
    out = self.forward(batch)
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/flash_causal_lm.py", line 788, in forward
    return self.model.forward(
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 431, in forward
    hidden_states = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 390, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 317, in forward
    attn_output = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 209, in forward
    paged_attention.reshape_and_cache(
  File "/content/text-generation-inference-1.3.4/server/text_generation_server/utils/paged_attention.py", line 17, in reshape_and_cache
    cache_ops.reshape_and_cache(key, value, key_cache, value_cache, slots)
RuntimeError: expected scalar type Long but found Int

2024-01-11T20:42:52.203556Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096 max_total_tokens=2048}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: expected scalar type Long but found Int
Error: Warmup(Generation("expected scalar type Long but found Int"))
2024-01-11T20:42:52.241154Z ERROR text_generation_launcher: Webserver Crashed
2024-01
```

As an aside note, a recommended `install flash attention v2 with `cd server && make install install-flash-attention-v2` in the output command does nothing:

`make: *** No rule to make target 'install-flash-attention-v2'.  Stop.`

Anyway, AWK 4-bit model works, so _bitsandbytes-fp4_ support does not look critical.
