### ISSUE TITLE
NotImplementedError: Sharded Llama requires Flash Attention enabled models.

### ISSUE THREAD

**Issue by fancyerii** [huggingface/text-generation-inference#1392]
### System Info

docker  ghcr.io/huggingface/text-generation-inference:1.3.4
ubuntu 18.04 
NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

docker run --gpus 2,3 --shm-size 1g -p 3344:80 -v /nas/lili/:/data/:ro ghcr.io/huggingface/text-generation-inference:1.3.4 --model-id /data/models_hf/70B-chat-awq/ --quantize awq --num-shard 2 --sharded true

```
$ CUDA_VISIBLE_DEVICES=2,3 docker run --shm-size 1g -p 3344:80 -v /nas/lili/:/data/:ro ghcr.io/huggingfa
ce/text-generation-inference:1.3.4 --model-id /data/models_hf/70B-chat-awq/ --quantize awq --num-shard 2 --sharded true
2024-01-03T02:24:47.068577Z  INFO text_generation_launcher: Args { model_id: "/data/models_hf/70B-chat-awq/", revision: None, validation_work
ers: 2, sharded: Some(true), num_shard: Some(2), quantize: Some(Awq), speculate: None, dtype: None, trust_remote_code: false, max_concurrent_
requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_rat
io: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "b2dd93c07186", port: 80, shard_uds_
path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_overri
de: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint:
 None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false
 }
2024-01-03T02:24:47.068602Z  INFO text_generation_launcher: Sharding model on 2 processes
2024-01-03T02:24:47.068676Z  INFO download: text_generation_launcher: Starting download process.
2024-01-03T02:24:49.894140Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2024-01-03T02:24:50.371145Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-01-03T02:24:50.371558Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-01-03T02:24:50.371634Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2024-01-03T02:24:53.417440Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2024-01-03T02:24:53.421891Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2024-01-03T02:24:53.457646Z  WARN text_generation_launcher: We're not using custom kernels.

2024-01-03T02:24:53.458178Z  WARN text_generation_launcher: We're not using custom kernels.

2024-01-03T02:24:53.498612Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-01-03T02:24:53.498982Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-01-03T02:24:53.565021Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)  
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs) 
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 242, in get_model
    raise NotImplementedError(FLASH_ATT_ERROR_MESSAGE.format("Sharded Llama"))
NotImplementedError: Sharded Llama requires Flash Attention enabled models.

```
I have found [this issue](https://github.com/huggingface/text-generation-inference/issues/714). And I haved installed Fabric Manager and Datacenter GPU Manager. And I don't find errors such as " Could not import Flash Attention enabled models: CUDA is not available"

### Expected behavior

start up correctly.

**Comment by Pedrochem** [comment]
I still have that issue on servers with 8 GPUs (never experienced it on a server with 4 or less). Although, every time it happens, installing the Fabric Manager and Datacenter GPU Manager solves the issue, so I would suggest making sure you installed them correctly (rebooting the system is always necessary if you haven't done it). 

Also, you mentioned you didn't find the errors "Could not import Flash Attention enabled models: CUDA is not available" but this message appears on the beginning of the logs you shared. 

Maybe you can also share a bit more about your system's GPU configuration.

**Comment by fancyerii** [comment]
My system info:
ubuntu 18.04
NVIDIA-SMI 535.104.12 Driver Version: 535.104.12 CUDA Version: 12.2
a100 40GBx8

I installed dcgm following [user-guide](https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/getting-started.html) step by step:

```
sudo apt-key del 7fa2af80
distribution=$(. /etc/os-release;echo $ID$VERSION_ID | sed -e 's/\.//g')
wget https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/cuda-keyring_1.0-1_all.deb

sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt-get update
sudo apt-get install -y datacenter-gpu-manager
```

And also run "sudo systemctl --now enable nvidia-dcgm"

And I installed fabric-manager by dpkg with nvidia-fabricmanager-535_535.104.12-1_amd64.deb and nvidia-fabricmanager-dev-535_535.104.12-1_amd64.deb.
