### ISSUE TITLE
Assertion Error on Finetuned mistral model

### ISSUE THREAD

**Issue by itsmeashutosh43** [huggingface/text-generation-inference#1396]
I fine-tuned a mistral model with peft but I get an assertion error while trying to serve it on tgi

**command**

`docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.3 --model-id $model --quantize bitsandbytes --max-input-length $MAX_NEW_TOKENS --max-total-tokens $MAX_TOTAL_TOKENS --trust-remote-code `

**Error**

```
2024-01-03T22:50:33.556882Z ERROR text_generation_launcher: Error when initializing model
(task, pid=14698) Traceback (most recent call last):
(task, pid=14698)   File "/opt/conda/bin/text-generation-server", line 8, in <module>
(task, pid=14698)     sys.exit(app())
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
(task, pid=14698)     return get_command(self)(*args, **kwargs)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
(task, pid=14698)     return self.main(*args, **kwargs)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
(task, pid=14698)     return _main(
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
(task, pid=14698)     rv = self.invoke(ctx)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
(task, pid=14698)     return _process_result(sub_ctx.command.invoke(sub_ctx))
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
(task, pid=14698)     return ctx.invoke(self.callback, **ctx.params)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
(task, pid=14698)     return __callback(*args, **kwargs)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
(task, pid=14698)     return callback(**use_params)  # type: ignore
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
(task, pid=14698)     server.serve(
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
(task, pid=14698)     asyncio.run(
(task, pid=14698)   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
(task, pid=14698)     return loop.run_until_complete(main)
(task, pid=14698)   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
(task, pid=14698)     self.run_forever()
(task, pid=14698)   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
(task, pid=14698)     self._run_once()
(task, pid=14698)   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
(task, pid=14698)     handle._run()
(task, pid=14698)   File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
(task, pid=14698)     self._context.run(self._callback, *self._args)
(task, pid=14698) > File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
(task, pid=14698)     model = get_model(
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 288, in get_model
(task, pid=14698)     return FlashMistral(
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 430, in __init__
(task, pid=14698)     super(FlashMistral, self).__init__(
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 333, in __init__
(task, pid=14698)     model = model_cls(config, weights)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 421, in __init__
(task, pid=14698)     self.model = MistralModel(config, weights)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 356, in __init__
(task, pid=14698)     [
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 357, in <listcomp>
(task, pid=14698)     MistralLayer(
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 291, in __init__
(task, pid=14698)     self.self_attn = MistralAttention(
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 168, in __init__
(task, pid=14698)     self.query_key_value = load_attention(config, prefix, weights)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 97, in load_attention
(task, pid=14698)     return _load_gqa(config, prefix, weights)
(task, pid=14698)   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 124, in _load_gqa
(task, pid=14698)     assert list(weight.shape) == [
(task, pid=14698) AssertionError: [12582912, 1] != [6144, 4096]
(task, pid=14698) 
(task, pid=14698) 2024-01-03T22:50:34.451329Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
(task, pid=14698) 
```

This is the code I use to merge and upload it to the hub.

```
base_model_id = "mistralai/Mistral-7B-Instruct-v0.2"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model = AutoModelForCausalLM.from_pretrained(base_model_id  ,  quantization_config=bnb_config)

ft_model = PeftModel.from_pretrained(
        model,
        f"{path}/checkpoint-100",
        device_map="auto",
)

merged_model= ft_model.merge_and_unload()
merged_model.push_to_hub(f"{run_name}")

```

And this is the merged model,

```
MistralForCausalLM(
  (model): MistralModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): MistralRotaryEmbedding()
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): MistralRMSNorm()
        (post_attention_layernorm): MistralRMSNorm()
      )
    )
    (norm): MistralRMSNorm()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)
```

The model works on a colab environment. So my guess is it has to do something with the docker command

**Comment by hxssgaa** [comment]
Hi, I ecountered the same issue, please reopen the issue.

**Comment by nguyenhoanganh2002** [comment]
same issue here

**Comment by kasakh** [comment]
Hi, I am encountering the same issue. Please reopen the issue.
