### ISSUE TITLE
Method Warmup encountered an error.

### ISSUE THREAD

**Issue by ahqzy** [huggingface/text-generation-inference#1409]
### System Info

(tgi) root@e4f81ee9472d:/workspace# text-generation-launcher --env
2024-01-06T02:41:23.130896Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 630800eed37b15c4b0c9eb8e6ab47212026720f7
Docker label: N/A
nvidia-smi:
Sat Jan  6 02:41:22 2024       
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 12.1     |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                               |                      |               MIG M. |
   |===============================+======================+======================|
   |   0  NVIDIA A100 80G...  On   | 00000000:81:00.0 Off |                  Off |
   | N/A   31C    P0    63W / 300W |      0MiB / 81920MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
                                                                                  
   +-----------------------------------------------------------------------------+
   | Processes:                                                                  |
   |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
   |        ID   ID                                                   Usage      |
   |=============================================================================|
   |  No running processes found                                                 |
   +-----------------------------------------------------------------------------+

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

...
BUILD_EXTENSIONS=True make install 
after make install, I can start server normally. But it doesn't support FlashAttension， so I do something as below:
1 cd server
2 make -f Makefile-flash-att install-flash-attention
3 make -f Makefile-flash-att-v2 build-flash-attention-v2-cuda
4 make -f Makefile-vllm install-vllm-cuda

after above operation，it can  support flashattention， but when I start text-generation-launcher like this:
# text-generation-launcher --model-id HuggingFaceH4/zephyr-7b-beta

it failed, some error info:
2024-01-06T02:50:38.149362Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-01-06T02:50:38.149682Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-01-06T02:50:48.160966Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-01-06T02:50:48.850014Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2024-01-06T02:50:48.861594Z  INFO shard-manager: text_generation_launcher: Shard ready in 10.710679778s rank=0
2024-01-06T02:50:48.961325Z  INFO text_generation_launcher: Starting Webserver

2024-01-06T02:51:19.005001Z  WARN text_generation_router: router/src/main.rs:166: Could not find a fast tokenizer implementation for HuggingFaceH4/zephyr-7b-beta
2024-01-06T02:51:19.005042Z  WARN text_generation_router: router/src/main.rs:169: Rust input length validation and truncation is disabled
2024-01-06T02:51:19.005051Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2024-01-06T02:51:19.005058Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2024-01-06T02:51:19.359166Z  WARN text_generation_router: router/src/main.rs:182: Could not retrieve model info from the Hugging Face hub.
2024-01-06T02:51:19.359189Z  WARN text_generation_router: router/src/main.rs:194: no pipeline tag found for model HuggingFaceH4/zephyr-7b-beta
2024-01-06T02:51:19.365975Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2024-01-06T02:51:19.885037Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/root/anaconda3/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/root/anaconda3/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/anaconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/root/anaconda3/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1434, in invoke

### Expected behavior

So， if I want to use FlashAttention， How can I do?

**Comment by ahqzy** [comment]
If  I only do 
make -f Makefile-flash-att install-flash-attention
and
make -f Makefile-vllm install-vllm-cuda, it can work well

But if I do 
make -f Makefile-flash-att-v2 build-flash-attention-v2-cuda
it happens error like above.  The problem seems to flash-attention-v2.

**Comment by OlivierDehaene** [comment]
The stacktrace you linked is trucated. Can you show the entire stacktrace?

**Comment by ahqzy** [comment]
@OlivierDehaene  detail in tgi_error.log.
[tgi_error.log](https://github.com/huggingface/text-generation-inference/files/13896298/tgi_error.log)
