### ISSUE TITLE
GPU with CUDA capability 7 5 is not supported for Flash Attention V2 & awq quantization is not supported for AutoMode

### ISSUE THREAD

**Issue by joaomsimoes** [huggingface/text-generation-inference#1573]
### System Info

I'm trying to use a AWQ model for inference with text-generation-inference but I'm having this error `Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2`

It also says `NotImplementedError("awq quantization is not supported for AutoModel")`

```llm-1        | 2024-02-19T04:30:46.198276Z  INFO text_generation_launcher: Args { model_id: "joaomsimoes/zephyr_gema", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Awq), speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "5d3086bacbbe", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }

llm-1        | 2024-02-19T04:30:46.198423Z  INFO download: text_generation_launcher: Starting download process.

llm-1        | 2024-02-19T04:30:49.308604Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

llm-1        | 

llm-1        | 2024-02-19T04:30:49.809379Z  INFO download: text_generation_launcher: Successfully downloaded weights.

llm-1        | 2024-02-19T04:30:49.809678Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0

llm-1        | 2024-02-19T04:30:54.097648Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

llm-1        | 

llm-1        | 2024-02-19T04:30:54.617819Z ERROR text_generation_launcher: Error when initializing model

llm-1        | Traceback (most recent call last):

llm-1        |   File "/opt/conda/bin/text-generation-server", line 8, in <module>

llm-1        |     sys.exit(app())

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__

llm-1        |     return get_command(self)(*args, **kwargs)

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__

llm-1        |     return self.main(*args, **kwargs)

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main

llm-1        |     return _main(

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main

llm-1        |     rv = self.invoke(ctx)

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke

llm-1        |     return _process_result(sub_ctx.command.invoke(sub_ctx))

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke

llm-1        |     return ctx.invoke(self.callback, **ctx.params)

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke

llm-1        |     return __callback(*args, **kwargs)

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper

llm-1        |     return callback(**use_params)  # type: ignore

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve

llm-1        |     server.serve(

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve

llm-1        |     asyncio.run(

llm-1        |   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run

llm-1        |     return loop.run_until_complete(main)

llm-1        |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete

llm-1        |     self.run_forever()

llm-1        |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

llm-1        |     self._run_once()

llm-1        |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

llm-1        |     handle._run()

llm-1        |   File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run

llm-1        |     self._context.run(self._callback, *self._args)

llm-1        | > File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner

llm-1        |     model = get_model(

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 409, in get_model

llm-1        |     raise NotImplementedError("awq quantization is not supported for AutoModel")

llm-1        | NotImplementedError: awq quantization is not supported for AutoModel

llm-1        | 

llm-1        | 2024-02-19T04:30:55.317169Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

llm-1        | 

llm-1        | Traceback (most recent call last):

llm-1        | 

llm-1        |   File "/opt/conda/bin/text-generation-server", line 8, in <module>

llm-1        |     sys.exit(app())

llm-1        | 

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve

llm-1        |     server.serve(

llm-1        | 

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve

llm-1        |     asyncio.run(

llm-1        | 

llm-1        |   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run

llm-1        |     return loop.run_until_complete(main)

llm-1        | 

llm-1        |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete

llm-1        |     return future.result()

llm-1        | 

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner

llm-1        |     model = get_model(

llm-1        | 

llm-1        |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 409, in get_model

llm-1        |     raise NotImplementedError("awq quantization is not supported for AutoModel")

llm-1        | 

llm-1        | NotImplementedError: awq quantization is not supported for AutoModel

llm-1        |  rank=0

llm-1        | Error: ShardCannotStart

llm-1        | 2024-02-19T04:30:55.417346Z ERROR text_generation_launcher: Shard 0 failed to start

llm-1        | 2024-02-19T04:30:55.417397Z  INFO text_generation_launcher: Shutting down shards
```

I'm using a T4 with CUDA 12.3.

The command I'm using `docker run --gpus all --shm-size 1g -p 8080:80 ghcr.io/huggingface/text-generation-inference:latest --model-id $my_model --quantize awq`

Has anyone had the same problem? It is related with the GPU I'm using?

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

docker run --gpus all --shm-size 1g -p 8080:80 ghcr.io/huggingface/text-generation-inference:latest --model-id $my_model --quantize awq

### Expected behavior

Run the model

**Comment by ZJaume** [comment]
I also had the same issue. Compute capability is something tied to the GPU model ([see here](https://developer.nvidia.com/cuda-gpus), so it cannot be solved unless FlashAttentionV2 is implemented for that compute capability. Which I do not know if it is possible.
