### ISSUE TITLE
Support for Gemma models

### ISSUE THREAD

**Issue by vitalyshalumov** [huggingface/text-generation-inference#1590]
### System Info

tgi 1.4

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

run TGI using google/gemma-7b-it

### Expected behavior

served model.

**Comment by zmerlynn** [comment]
I don't think the Docker image is quite working. I'm seeing:

```
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 333, in get_model
    return CausalLM(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 498, in __init__
    tokenizer = AutoTokenizer.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 811, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class GemmaTokenizer does not exist or is not currently imported.
```

which looks like the `transformers` requirement needs to be updated.

**Comment by dongxiaolong** [comment]
When I try to launch gemma, I get error below:

`(tgi) root:~/tmp# text-generation-launcher --model-id "/root/autodl-tmp/gemma-7b-it/" --port 6006
2024-02-23T06:26:41.737255Z  INFO text_generation_launcher: Args { model_id: "/root/autodl-tmp/gemma-7b-it/", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "0.0.0.0", port: 6006, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }
2024-02-23T06:26:41.737353Z  INFO download: text_generation_launcher: Starting download process.
2024-02-23T06:26:44.071146Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2024-02-23T06:26:44.540701Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-02-23T06:26:44.540971Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-02-23T06:26:48.020494Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-02-23T06:26:48.041622Z  WARN text_generation_launcher: We're not using custom kernels.

2024-02-23T06:26:48.148699Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: cannot import name 'cache_ops' from 'vllm' (/root/miniconda3/envs/tgi/lib/python3.11/site-packages/vllm/__init__.py)

2024-02-23T06:26:48.149349Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-02-23T06:26:48.896100Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1390, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/miniconda3/envs/tgi/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/gemma/modeling_gemma.py", line 48, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/models/__init__.py", line 333, in get_model
    return CausalLM(
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/models/causal_lm.py", line 505, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 381, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 732, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 746, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 690, in getattribute_from_module
    if hasattr(module, attr):
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1380, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1392, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gemma.modeling_gemma because of the following error (look up to see its traceback):
/root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_

2024-02-23T06:26:49.547263Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1390, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 940, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/gemma/modeling_gemma.py", line 48, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda

ImportError: /root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/root/miniconda3/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/cli.py", line 89, in serve
    server.serve(

  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/server.py", line 235, in serve
    asyncio.run(

  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(
            ^^^^^^^^^^

  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/models/__init__.py", line 333, in get_model
    return CausalLM(
           ^^^^^^^^^

  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/models/causal_lm.py", line 505, in __init__
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 381, in _get_model_class
    supported_models = model_mapping[type(config)]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 732, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 746, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 690, in getattribute_from_module
    if hasattr(module, attr):
       ^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1380, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/miniconda3/envs/tgi/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1392, in _get_module
    raise RuntimeError(

RuntimeError: Failed to import transformers.models.gemma.modeling_gemma because of the following error (look up to see its traceback):
/root/miniconda3/envs/tgi/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_
 rank=0
2024-02-23T06:26:49.644973Z ERROR text_generation_launcher: Shard 0 failed to start
2024-02-23T06:26:49.645009Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart`

**Comment by OlivierDehaene** [comment]
TGI supports Gemma for all GPUs that support Flash Attention. 
We will had support for the remaining targets soon.
