### ISSUE TITLE
TGI saturates GPU memory on L40s

### ISSUE THREAD

**Issue by amessina71** [huggingface/text-generation-inference#1599]
### System Info

TGI version 1.4, Ubuntu 22.04 LTS, 4 NVIDIA L40s,  mistralai/Mixtral-8x7B-Instruct-v0.1, quantized 8bit, docker with nvidia runtime, NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

`docker run -ti --runtime nvidia --shm-size 1g -p 8080:80 ghcr.io/huggingface/text-generation-inference:1.4 --model-id mistralai/Mixtral-8x7B-Instruct-v0.1 --quantize bitsandbytes`

The server downloads (or reuse) weights and starts up shards. As soon as the shards are set up, the GPU memory gets immediately filled up (all 4 cards for a total of >190Gbyte). Same behaviour with smaller models too - i.e. does not depend on Mixtral.

### Expected behavior

Server set up, running, GPU memory used correctly.

**Comment by OlivierDehaene** [comment]
TGI will always use all available memory for its cache. If you want to limit the amount of memory used by TGI, you can use the `--cuda-memory-fraction` arg.

**Comment by amessina71** [comment]
Indeed - thank you. However IMHO it remains rather much of an art to understand how to configure things in order not to go OOM at inference time. For example, the max-batch-size parameter would have been much useful to limit the amount of preallocated memory (I suppose) - but this has been deprecated for flash attention models. Is there a rule of thumb to determine a good combination of cmd line parameters given a certain GPU configuration?

**Comment by amessina71** [comment]
See my example above (edited comment). The `Connected` log appears indeed. But the server goes OOM at runtime.

**Comment by OlivierDehaene** [comment]
Can you try with `--enable-cuda-graphs`?

**Comment by amessina71** [comment]
Tired. A lot of exceptions, the most important probably is:

- `Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 397, in cuda_graph_warmup
    self.cuda_graphs[bs]["logits"] = self.model.forward(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 847, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 789, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 717, in forward
    attn_output = self.self_attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 250, in forward
    qkv = self.query_key_value(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py", line 380, in forward
    return self.linear.forward(x)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/layers.py", line 237, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 562, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 327, in forward
    CA, CAt, SCA, SCAt, coo_tensorA = F.double_quant(A.to(torch.float16), threshold=state.threshold)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py", line 2132, in double_quant
    nnz = nnz_row_ptr[-1].item()
RuntimeError: CUDA error: operation not permitted when stream is capturing
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

Nevertheless the server starts, but gets stuck indefinitely with 100% GPU utilization on all 4 cards.

I suggest to reopen the issue.

**Comment by farzanehnakhaee70** [comment]
Is there any update for this issue?
