### ISSUE TITLE
Errors when concurrent requests with json grammar 

### ISSUE THREAD

**Issue by puppetm4st3r** [huggingface/text-generation-inference#1601]
### System Info

I am seeing traces of error and crash of the generation process when there is a text generation process in progress and another request that has a definition of json grammar is sent in parallel. I am using TGI from docker. I have tried several models and the problem persists.

The request with json grammar that causes the crash if I send it alone (without any other generation process running) works perfectly and returns the expected structure. Also parallel requests without grammar work without problems.

error stack:
2024-02-27T01:11:23.250875Z ERROR text_generation_launcher: Method Decode encountered an error.
```
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 146, in Decode
    batch = self.model.batch_type.concatenate(batches)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 591, in concatenate
    next_token_chooser = HeterogeneousNextTokenChooser.from_pb(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/tokens.py", line 470, in from_pb
    return HeterogeneousNextTokenChooser(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/tokens.py", line 269, in __init__
    HeterogeneousGrammarLogitProcessor(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/logits_process.py", line 558, in __init__
    fsm = GrammarLogitProcessor._cached_compile_fsm(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/logits_process.py", line 518, in _cached_compile_fsm
    fsm = RegexFSM(schema, tokenizer)
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 121, in __init__
    self.states_to_token_maps, self.empty_token_ids = create_states_mapping(
  File "/opt/conda/lib/python3.10/site-packages/outlines/caching.py", line 74, in wrapper
    result = cached_function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 103, in create_states_mapping
    regex_fsm, _ = make_deterministic_fsm(regex_pattern.to_fsm().reduce())
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/regex.py", line 165, in make_deterministic_fsm
    new_alphabet = BetterAlphabet(new_symbol_mapping)
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/regex.py", line 17, in __init__
    assert anything_else in self._symbol_mapping
AssertionError

2024-02-27T01:11:23.262549Z ERROR batch{batch_size=2}:decode:decode{size=2}:decode{size=2}: text_generation_client: router/client/src/lib.rs:33: Server error: 
2024-02-27T01:11:23.266346Z ERROR compat_generate{default_return_full_text=true compute_type=Extension(ComputeType("2-nvidia-geforce-rtx-4090"))}:generate_stream{parameters=GenerateParameters { best_of: None, temperature: Some(0.3), repetition_penalty: Some(1.1), frequency_penalty: None, top_k: Some(30), top_p: Some(0.95), typical_p: Some(0.95), do_sample: true, max_new_tokens: Some(2000), return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None, top_n_tokens: None, grammar: Some(Json(String("{\"properties\": {\"task_result\": {\"description\": \"Indica el resultado de la funci\\u00f3n de clasificaci\\u00f3n binaria de texto.\", \"examples\": [true], \"title\": \"Resultado de la Clasificaci\\u00f3n Binaria\", \"type\": \"boolean\"}}, \"required\": [\"task_result\"]}"))) }}:async_stream:generate_stream:infer:send_error: text_generation_router::infer: router/src/infer.rs:705: Request failed during generation: Server error: 
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Running the 1.4.2 image on docker with this dynamic script:
docker run --network llm_network --rm -e HF_HUB_ENABLE_HF_TRANSFER="true" --name llm_server $GPU_OPTION --shm-size 1g \
-p 3000:3000 -v "$(pwd)/tokenizers:/tokenizers" -v "$(pwd)/datafolder:/data" ghcr.io/huggingface/text-generation-inference:1.4.2 \
--tokenizer-config-path $tokenizer \
--model-id $MODEL_ID --port 3000 --quantize awq $NUM_SHARD \
$MAX_INPUT_LENGTH $MAX_TOTAL_TOKENS $MAX_BATCH_PREFILL_TOKENS $MAX_BATCH_TOTAL_TOKENS \
--revision main \
--validation-workers 8  --max-best-of 1  \
--cuda-memory-fraction 0.9 \
--trust-remote-code --max-concurrent-requests 10 --hostname 0.0.0.0

But the concrete execution was with this parameters:
2024-02-27T00:47:11.739605Z  INFO text_generation_launcher: Args { model_id: "LoneStriker/Smaug-34B-v0.1-AWQ", revision: Some("main"), validation_workers: 8, sharded: None, num_shard: Some(2), quantize: Some(Awq), speculate: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 10, max_best_of: 1, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 8000, max_total_tokens: 10000, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 8000, max_batch_total_tokens: Some(10000), max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "0.0.0.0", port: 3000, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 0.9, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: Some("/tokenizers/models--LoneStriker--Smaug-34B-v0.1-AWQ/tokenizer_config.json"), disable_grammar_support: false, env: false }

With any request with grammar defined falls when another request is running the generation of tokens.

### Expected behavior

To run soft with concurrent request with grammar definitions

**Comment by puppetm4st3r** [comment]
thanks
