### ISSUE TITLE
Version 1.4: Startup error

### ISSUE THREAD

**Issue by lihan** [huggingface/text-generation-inference#1625]
### System Info

Trying to run `ghcr.io/huggingface/text-generation-inference:1.4` with the following parameter
```
  web:
    args:
      - --model-id
      - TheBloke/zephyr-7B-beta-AWQ
      - --port
      - "7860"
      - --quantize
      - awq
      - --env
    replicaCount: 1
  extraEnv:
    MAX_INPUT_LENGTH: "3696"
    MAX_TOTAL_TOKENS: "4096"
    MAX_BATCH_PREFILL_TOKENS: "4096"
    TRUST_REMOTE_CODE: "true"
    HF_HUB_DISABLE_TELEMETRY: "0"
    HF_HUB_ENABLE_HF_TRANSFER: "1"
```

`nvidia-smi`
![image](https://github.com/huggingface/text-generation-inference/assets/655051/f586d24a-79d5-4132-879a-4eb38da480d1)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

```
   |  No running processes found                                                 |

2024-03-06T03:53:53.954393Z  INFO text_generation_launcher: Args { model_id: "TheBloke/zephyr-7B-beta-AWQ", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Awq), speculate: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 3696, max_total_tokens: 4096, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "bwchat-web-84bbf6549b-hq75s", port: 7860, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: true }

2024-03-06T03:53:53.954409Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `TheBloke/zephyr-7B-beta-AWQ` do not contain malicious code.
2024-03-06T03:53:53.954614Z  INFO download: text_generation_launcher: Starting download process.

Error: DownloadError
2024-03-06T03:53:57.258644Z ERROR download: text_generation_launcher: Download encountered an error: 
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 124, in download_weights
    from text_generation_server import utils

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/__init__.py", line 13, in <module>
    from text_generation_server.utils.tokens import (

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/tokens.py", line 8, in <module>
    from text_generation_server.utils.logits_process import (

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/logits_process.py", line 8, in <module>
    from outlines.fsm.fsm import RegexFSM

  File "/opt/conda/lib/python3.10/site-packages/outlines/__init__.py", line 2, in <module>
    import outlines.generate

  File "/opt/conda/lib/python3.10/site-packages/outlines/generate/__init__.py", line 1, in <module>
    from .api import SequenceGenerator

  File "/opt/conda/lib/python3.10/site-packages/outlines/generate/api.py", line 6, in <module>
    from outlines.fsm.fsm import FSMState

  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 9, in <module>
    from outlines.fsm.regex import create_fsm_index_tokenizer, make_deterministic_fsm

  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/regex.py", line 96, in <module>
    def create_fsm_info(

  File "/opt/conda/lib/python3.10/site-packages/numba/core/decorators.py", line 229, in wrapper
    disp.enable_caching()

  File "/opt/conda/lib/python3.10/site-packages/numba/core/dispatcher.py", line 856, in enable_caching
    self._cache = FunctionCache(self.py_func)

  File "/opt/conda/lib/python3.10/site-packages/numba/core/caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)

  File "/opt/conda/lib/python3.10/site-packages/numba/core/caching.py", line 337, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "

RuntimeError: cannot cache function 'create_fsm_info': no locator available for file '/opt/conda/lib/python3.10/site-packages/outlines/fsm/regex.py'
2024-03-06T03:53:57.259052823Z
```

### Expected behavior

Model should start downloading and start the process

**Comment by lihan** [comment]
Let's close this, once running under root, then this issue is resolved.

**Comment by markkofler** [comment]
I have the same issue. Any solution to this problem?

**Comment by giladd123** [comment]
Is there any update? Experiencing the same issue

**Comment by rocketb** [comment]
It's probably something permissions related. Try to set the environment variable `NUMBA_CACHE_DIR` to somewhere like `/tmp/` .

**Comment by nigelmathes** [comment]
Also still experiencing this issue with a Docker deployment on v2.0.2
