### ISSUE TITLE
NotImplementedError: Sharded Qwen2(Qwen1.5-72B-Chat) requires Flash Attention enabled models.

### ISSUE THREAD

**Issue by majestichou** [huggingface/text-generation-inference#1640]
### System Info

```
Target: x86_64-unknown-linux-gnu
Cargo version: 1.75.0
Model being used: Qwen2(Qwen1.5-72B-Chat)
Commit sha: 8a5bcba227fcddff40385e8707ef94c7d6b3b561
Docker label: sha-8a5bcba-rocm
nvidia-smi:
Wed Mar 13 17:26:06 2024
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  NVIDIA A100-SXM4-40GB          On  | 00000000:07:00.0 Off |                    0 |
   | N/A   32C    P0              54W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   1  NVIDIA A100-SXM4-40GB          On  | 00000000:0A:00.0 Off |                    0 |
   | N/A   30C    P0              53W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   2  NVIDIA A100-SXM4-40GB          On  | 00000000:47:00.0 Off |                    0 |
   | N/A   30C    P0              52W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   3  NVIDIA A100-SXM4-40GB          On  | 00000000:4D:00.0 Off |                    0 |
   | N/A   32C    P0              55W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   4  NVIDIA A100-SXM4-40GB          On  | 00000000:87:00.0 Off |                    0 |
   | N/A   32C    P0              56W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   5  NVIDIA A100-SXM4-40GB          On  | 00000000:8D:00.0 Off |                    0 |
   | N/A   30C    P0              54W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   6  NVIDIA A100-SXM4-40GB          On  | 00000000:C7:00.0 Off |                    0 |
   | N/A   30C    P0              55W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   7  NVIDIA A100-SXM4-40GB          On  | 00000000:CA:00.0 Off |                    0 |
   | N/A   32C    P0              59W / 400W |      4MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+

   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   |  No running processes found                                                           |
   +---------------------------------------------------------------------------------------+

```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Loading a Qwen Model Using the TGI Container 
`docker run --gpus 8 --rm -p 8080:80 -v /home/llm-test/serving/data:/data huggingface/text-generation-inference:sha-8a5bcba-rocm --model-id /data/models/Qwen1.5-72B-Chat`
2. An error is reported. The error information is as follows:
```
2024-03-13T15:34:04.192800Z  INFO text_generation_launcher: Args { model_id: "/data/models/Qwen1.5-72B-Chat", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "481fe5e6d02a", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }
2024-03-13T15:34:04.192876Z  INFO text_generation_launcher: Sharding model on 8 processes
2024-03-13T15:34:04.193068Z  INFO download: text_generation_launcher: Starting download process.
2024-03-13T15:34:06.962303Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2024-03-13T15:34:07.797404Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-03-13T15:34:07.798059Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2024-03-13T15:34:07.798053Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-03-13T15:34:07.798228Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2024-03-13T15:34:07.799025Z  INFO shard-manager: text_generation_launcher: Starting shard rank=4
2024-03-13T15:34:07.800198Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2024-03-13T15:34:07.800221Z  INFO shard-manager: text_generation_launcher: Starting shard rank=5
2024-03-13T15:34:07.800967Z  INFO shard-manager: text_generation_launcher: Starting shard rank=6
2024-03-13T15:34:07.801143Z  INFO shard-manager: text_generation_launcher: Starting shard rank=7
2024-03-13T15:34:11.187063Z  WARN text_generation_launcher: We're not using custom kernels.

2024-03-13T15:34:11.190676Z  WARN text_generation_launcher: We're not using custom kernels.

2024-03-13T15:34:11.192050Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-03-13T15:34:11.192615Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-03-13T15:34:11.195587Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-03-13T15:34:11.196125Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-03-13T15:34:11.213050Z  WARN text_generation_launcher: We're not using custom kernels.

2024-03-13T15:34:11.218237Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-03-13T15:34:11.218814Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-03-13T15:34:11.250114Z  WARN text_generation_launcher: We're not using custom kernels.

2024-03-13T15:34:11.254410Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 480, in get_model
    raise NotImplementedError(FLASH_ATT_ERROR_MESSAGE.format("Sharded Qwen2"))
NotImplementedError: Sharded Qwen2 requires Flash Attention enabled models.

2024-03-13T15:34:11.255262Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-03-13T15:34:11.255822Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-03-13T15:34:11.256844Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 480, in get_model
    raise NotImplementedError(FLASH_ATT_ERROR_MESSAGE.format("Sharded Qwen2"))
NotImplementedError: Sharded Qwen2 requires Flash Attention enabled models.
```
3. According to Qwen's official description, they support Flash Attention(https://github.com/QwenLM/Qwen):
`If your device supports fp16 or bf16, we recommend installing [flash-attention](https://github.com/Dao-AILab/flash-attention) (we support flash attention 2 now.) for higher efficiency and lower memory usage. (flash-attention is optional and the project can run normally without installing it)`. 
4. TGI's docker image does not include flash attention. Should I add flash attention to TGI's mirror? 

### Expected behavior

According to the official description of TGI, V1.4.3 supports Qwen2. Therefore, the model loading error should not occur.
(https://github.com/huggingface/text-generation-inference/releases/tag/v1.4.3)

**Comment by majestichou** [comment]
I then tried to load the mistralaiMixtral-8x7B-Instruct-v0.1 model, which also supports Flash Attention, but got the same error.
```
[root@cturf163 models]# docker run -e USE_FLASH_ATTENTION=true --gpus 8 --rm -p 8080:80 -v /home/mnt/h00562948/llm-test/serving/data:/data 83fc1a31419c --model-id /data/models/mistralaiMixtral-8x7B-Instruct-v0.1
2024-03-13T15:36:05.173065Z  INFO text_generation_launcher: Args { model_id: "/data/models/mistralaiMixtral-8x7B-Instruct-v0.1", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "0c6b32dc662d", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }
2024-03-13T15:36:05.173160Z  INFO text_generation_launcher: Sharding model on 8 processes
2024-03-13T15:36:05.173369Z  INFO download: text_generation_launcher: Starting download process.
2024-03-13T15:36:07.895489Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2024-03-13T15:36:08.777779Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-03-13T15:36:08.778170Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-03-13T15:36:08.778340Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2024-03-13T15:36:08.779298Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2024-03-13T15:36:08.779609Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2024-03-13T15:36:08.779689Z  INFO shard-manager: text_generation_launcher: Starting shard rank=4
2024-03-13T15:36:08.782771Z  INFO shard-manager: text_generation_launcher: Starting shard rank=5
2024-03-13T15:36:08.783000Z  INFO shard-manager: text_generation_launcher: Starting shard rank=6
2024-03-13T15:36:08.785064Z  INFO shard-manager: text_generation_launcher: Starting shard rank=7
2024-03-13T15:36:12.117742Z  WARN text_generation_launcher: We're not using custom kernels.

2024-03-13T15:36:12.121093Z  WARN text_generation_launcher: We're not using custom kernels.

2024-03-13T15:36:12.122966Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-03-13T15:36:12.123620Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-03-13T15:36:12.126750Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-03-13T15:36:12.127479Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-03-13T15:36:12.155388Z  WARN text_generation_launcher: We're not using custom kernels.

2024-03-13T15:36:12.160412Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-03-13T15:36:12.160966Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-03-13T15:36:12.186835Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 430, in get_model
    raise NotImplementedError(FLASH_ATT_ERROR_MESSAGE.format("Sharded Mixtral"))
NotImplementedError: Sharded Mixtral requires Flash Attention enabled models.
```

**Comment by majestichou** [comment]
I know the problem, my GPU is A100, but I downloaded the docker image of the Rocm version. I re-downloaded the non-rocm mirror version and the weights loaded properly
`docker pull ghcr.io/huggingface/text-generation-inference:sha-8a5bcba`

**Comment by tostt** [comment]
> I re-downloaded the non-rocm mirror version and the weights loaded properly `docker pull ghcr.io/huggingface/text-generation-inference:sha-8a5bcba`

Thank you. I had the same problem. Your solution worked.
However, it seems that image tagged `sha-8a5bcba` is the last working non-rocm image in this situation.
All later non-rocm images, from the one tagged `sha-0d9917f`, also send the error `Could not import Flash Attention enabled models: CUDA is not available`, altough CUDA is indeed available as shown with the `nvidia-smi` command.

**Comment by swaggy-TN** [comment]
Hi, I am using CLI directly to serve a local Qwen2 model and I encountered the same error.

**Comment by majestichou** [comment]
> I re-downloaded the non-rocm mirror version and the weights loaded properly

I re-downloaded the non-rocm mirror version and the weights loaded properly

**Comment by majestichou** [comment]
> Hi, I am using CLI directly to serve a local Qwen2 model and I encountered the same error.

I re-downloaded the non-rocm mirror version and the weights loaded properly

**Comment by swaggy-TN** [comment]
Yes I saw it, but I used CLI instead of docker. Do you know which branch or commit correspond to the non-rocm mirror version of your docker image?
