### ISSUE TITLE
Concurrent grammar and non-grammar requests

### ISSUE THREAD

**Issue by Johnno1011** [huggingface/text-generation-inference#1661]
### System Info

1.4.3 and https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference/192173353?tag=sha-0d72af5

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Steps to reproduce:
1 - While true grammar text generation request.
2 - At the same time, in another process, run a non-grammar text generation request.
3 - Both fail with a server error.

TGI container logs:
```
2024-03-21T09:01:53.354872Z ERROR text_generation_launcher: Method Decode encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 146, in Decode
    batch = self.model.batch_type.concatenate(batches)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 593, in concatenate
    next_token_chooser = HeterogeneousNextTokenChooser.from_pb(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/tokens.py", line 471, in from_pb
    return HeterogeneousNextTokenChooser(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/tokens.py", line 269, in __init__
    HeterogeneousGrammarLogitProcessor(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/logits_process.py", line 558, in __init__
    fsm = GrammarLogitProcessor._cached_compile_fsm(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/logits_process.py", line 518, in _cached_compile_fsm
    fsm = RegexFSM(schema, tokenizer)
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 121, in __init__
    self.states_to_token_maps, self.empty_token_ids = create_states_mapping(
  File "/opt/conda/lib/python3.10/site-packages/outlines/caching.py", line 74, in wrapper
    result = cached_function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 103, in create_states_mapping
    regex_fsm, _ = make_deterministic_fsm(regex_pattern.to_fsm().reduce())
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/regex.py", line 165, in make_deterministic_fsm
    new_alphabet = BetterAlphabet(new_symbol_mapping)
  File "/opt/conda/lib/python3.10/site-packages/outlines/fsm/regex.py", line 17, in __init__
    assert anything_else in self._symbol_mapping
AssertionError

2024-03-21T09:01:53.358415Z ERROR batch{batch_size=2}:decode:decode{size=2}:decode{size=2}: text_generation_client: router/client/src/lib.rs:33: Server error: 
2024-03-21T09:01:53.359712Z ERROR compat_generate{default_return_full_text=true compute_type=Extension(ComputeType("1-nvidia-geforce-rtx-4090"))}:generate{parameters=GenerateParameters { best_of: Some(1), temperature: None, repetition_penalty: Some(1.2), frequency_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(1024), return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None, top_n_tokens: None, grammar: None }}:generate:generate_stream:infer:send_error: text_generation_router::infer: router/src/infer.rs:705: Request failed during generation: Server error: 
2024-03-21T09:01:53.359751Z ERROR compat_generate{default_return_full_text=true compute_type=Extension(ComputeType("1-nvidia-geforce-rtx-4090"))}:generate{parameters=GenerateParameters { best_of: Some(1), temperature: None, repetition_penalty: Some(1.2), frequency_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(1024), return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None, top_n_tokens: None, grammar: Some(Json(Object {"properties": Object {"age": Object {"title": String("Age"), "type": String("integer")}, "name": Object {"title": String("Name"), "type": String("string")}}, "required": Array [String("name"), String("age")], "title": String("Test"), "type": String("object")})) }}:generate:generate_stream:infer:send_error: text_generation_router::infer: router/src/infer.rs:705: Request failed during generation: Server error:
```

### Expected behavior

Concurrent grammar and non-grammar requests working smoothly as expected.

**Comment by jacksmithy1** [comment]
I have had this error too with text generation inference v1.4.3.

**Comment by johnpytch** [comment]
Also had this with v1.4.3, crashes my app because I am doing async requests with grammar and no grammar... is this fixed in the newest release?

**Comment by WuLindong1997** [comment]
docker  ghcr.io/huggingface/text-generation-inference:1.4.4
Encountered the same problem as above.

**Comment by maziyarpanahi** [comment]
So this PR solved multiple concurrent grammar requests, but not a mix of Grammar with none Grammar? https://github.com/huggingface/text-generation-inference/pull/1610

**Comment by Johnno1011** [comment]
That's correct. Looks like @drbh just opened a PR to address this today! :)
https://github.com/huggingface/text-generation-inference/pull/1676

> So this PR solved multiple concurrent grammar requests, but not a mix of Grammar with none Grammar? #1610

**Comment by drbh** [comment]
closing since this is fixed by https://github.com/huggingface/text-generation-inference/pull/1676

**Comment by Johnno1011** [comment]
Confirmed fix, great job guys and thanks!
