### ISSUE TITLE
protobuf version

### ISSUE THREAD

**Issue by lcw99** [huggingface/text-generation-inference#172]
after installed(using make install), protobuf is upgraded 4.xx, but I have following error. If I down grade protobuff to 3.20.x it just works. on latest update, following error is not displayed and just starting shard faild with no error message.

```
2023-04-13T00:59:16.794030Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-04-13T00:59:16.794558Z  INFO text_generation_launcher: Starting shard 0
2023-04-13T00:59:16.794631Z  INFO text_generation_launcher: Starting shard 1
2023-04-13T00:59:21.600031Z ERROR text_generation_launcher: Shard 0 failed to start:
Traceback (most recent call last):
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9.egg/transformers/utils/import_utils.py", line 1125, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9.egg/transformers/modeling_utils.py", line 37, in <module>
    from .deepspeed import deepspeed_config, is_deepspeed_zero3_enabled
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9.egg/transformers/deepspeed.py", line 38, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/accelerate/accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/accelerate/tracking.py", line 40, in <module>
    from torch.utils import tensorboard
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/chang/anaconda3/envs/hf39/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

**Comment by OlivierDehaene** [comment]
This seems to be an issue with your local setup.
I tried installing on a fresh VM and with a new python environment and both worked without hiccups.

You can also use the official docker image with you want to be sure to always run on a stable install.

**Comment by comaniac** [comment]
I get the same issue and don't really think that's because of my local setup. I didn't use the docker image because I'm not working on a CUDA platform. Instead, I setup a conda environment and build from source without CUDA extension. After getting this error, I also manually downgraded protobuf to 3.20.3, and this is what pip complained:

```
text-generation-server 0.6.0 requires protobuf<5.0.0,>=4.21.7, but you have protobuf 3.20.3 which is incompatible.
Successfully installed protobuf-3.20.3
```

So something seems have to be fixed such as the requirement of text-generation-server?
