### ISSUE TITLE
Running inference on AMD/ROCm and TGI 2.0.0

### ISSUE THREAD

**Issue by aminnsabet** [huggingface/text-generation-inference#1746]
### System Info

AMD 250, Rocm 6, TGI 2.0.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

`docker run --device /dev/kfd --device /dev/dri --shm-size 1g -p 8080:80  -v $volume:/data ghcr.io/huggingface/text-generation-inference:2.0.0-rocm --model-id  NousResearch/Llama-2-7b-hf`

### Expected behavior

```
2024-04-15T14:03:19.035250Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 71, in serve
    from text_generation_server import server

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 16, in <module>
    from text_generation_server.models.vlm_causal_lm import VlmCausalLMBatch

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/vlm_causal_lm.py", line 14, in <module>
    from text_generation_server.models.flash_mistral import (

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 18, in <module>
    from text_generation_server.models.custom_modeling.flash_mistral_modeling import (

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 29, in <module>
    from text_generation_server.utils import paged_attention, flash_attn

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/paged_attention.py", line 4, in <module>
    from vllm._C import cache_ops, ops
```

**Comment by fxmarty** [comment]
@aminnsabet Please try again on `ghcr.io/huggingface/text-generation-inference:2.0.4-rocm`, or better yet the upcoming release.
