### ISSUE TITLE
Support offline running

### ISSUE THREAD

**Issue by daixiang0** [huggingface/text-generation-inference#1754]
### Feature request

I want to use tgi to run some model in offline mode, but tgi always try to download even with cache.

I do not dive into code but I think it may try to download latest version and compare version to  decide whether download or not.

### Motivation

Add option to skip version comparation and use cache directly.

### Your contribution

I can help do test, if acceptable, I can dive into codes and try to implement it.

**Comment by maziyarpanahi** [comment]
I am going to avoid creating a similar issue. I am also interested to see if it was possible for TGU+I to avoid going to check the latest online, or at least, not result in a hard exception if the local model already exists. 

For example:

```
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-6620db9a-458ace6319f547fc24f90361;41c7c781-8ec8-4da4-b734-9d419ce163c7)

Repository Not Found for url: https://huggingface.co/api/models/microsoft/WizardLM-2-7B.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
```

The recent issue with `microsoft/WizardLM-2-7B` model. I have this model already downloaded, loaded, used with in TGI. But now it tries to check the latest online and results in hard exception. 


Using the local path instead of the model's name also doesn't work. It results in another issue:

```
024-04-18T08:42:58.103346Z  INFO text_generation_launcher: Sharding model on 4 processes
2024-04-18T08:42:58.103448Z  INFO download: text_generation_launcher: Starting download process.
2024-04-18T08:43:04.007263Z ERROR download: text_generation_launcher: Download encountered an error:
Traceback (most recent call last):

Error: DownloadError
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 129, in download_weights
    utils.weight_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 151, in weight_files
    filenames = weight_hub_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 110, in weight_hub_files
    info = api.model_info(model_id, revision=revision)

  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)

  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/maziyar/.cache/huggingface/hub/models--microsoft--WizardLM-2-7B/'. Use `repo_type` argument if needed.
```

So there is no way to use TGI with some offline functionalities when the model is missing online or the model is a local fine-tuned.

**Comment by maziyarpanahi** [comment]
I'll answer for my first part, `-e HF_HUB_OFFLINE=1 `  should disable looking for model on the Hub and look in the cached directory instead.

**Comment by daixiang0** [comment]
I am not sure the missing token file would effect the accuracy:
```
# docker run -e HF_HUB_OFFLINE=1 --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.4 --model-id $model
2024-04-19T09:13:00.728780Z  INFO text_generation_launcher: Args { model_id: "HuggingFaceH4/zephyr-7b-beta", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "f11339b7953e", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }
2024-04-19T09:13:00.728889Z  INFO download: text_generation_launcher: Starting download process.
2024-04-19T09:13:02.670825Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2024-04-19T09:13:03.030751Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-04-19T09:13:03.030923Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-04-19T09:13:06.252033Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-19T09:13:06.300040Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: CUDA is not available

2024-04-19T09:13:12.554149Z  INFO shard-manager: text_generation_launcher: Shard ready in 9.522552975s rank=0
2024-04-19T09:13:12.554175Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2024-04-19T09:13:12.640350Z  INFO text_generation_launcher: Starting Webserver
2024-04-19T09:13:12.684340Z  INFO text_generation_router: router/src/main.rs:181: Using the Hugging Face API
2024-04-19T09:13:12.684365Z  INFO hf_hub: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hf-hub-0.3.2/src/lib.rs:55: Token file not found "/root/.cache/huggingface/token"
2024-04-19T09:13:13.118830Z  WARN text_generation_router: router/src/main.rs:216: Could not retrieve model info from the Hugging Face hub.
2024-04-19T09:13:13.118846Z  INFO text_generation_router: router/src/main.rs:242: Using the Hugging Face API to retrieve tokenizer config
2024-04-19T09:13:13.120016Z  WARN text_generation_router: router/src/main.rs:272: no pipeline tag found for model HuggingFaceH4/zephyr-7b-beta
2024-04-19T09:13:13.127492Z  INFO text_generation_router: router/src/main.rs:291: Warming up model
2024-04-19T09:13:25.836246Z  WARN text_generation_router: router/src/main.rs:306: Model does not support automatic max batch total tokens
2024-04-19T09:13:25.836264Z  INFO text_generation_router: router/src/main.rs:328: Setting max batch total tokens to 16000
2024-04-19T09:13:25.836269Z  INFO text_generation_router: router/src/main.rs:329: Connected
2024-04-19T09:13:25.836272Z  WARN text_generation_router: router/src/main.rs:343: Invalid hostname, defaulting to 0.0.0.0
```

**Comment by rushikesh988** [comment]
I was able to run with this method. Although this doesn't seem to be best way to do it. 

```
model=/data
volume=~/models_hf/8b_pre_trained_hf/

docker run -e HF_HUB_OFFLINE=1 --gpus all --shm-size 1g -p 9000:80 \
-v $volume:/data  \
ghcr.io/huggingface/text-generation-inference:2.0.1 \
--model-id $model \
--max-total-tokens 4092 \
--max-input-length 3200 \
--max-batch-prefill-tokens 3200
```

**Comment by drbh** [comment]
offline mode is now fully supported via this PR: https://github.com/huggingface/text-generation-inference/pull/1789
