### ISSUE TITLE
Have installed flash-attn and flash-attn-v2 but output 'Flash Attention is not installed' when using Medusa

### ISSUE THREAD

**Issue by syGOAT** [huggingface/text-generation-inference#1778]
### System Info

version: https://github.com/huggingface/text-generation-inference/releases/tag/v2.0.0
have run `make install-flash-attention`, `make install-flash-attention-v2-cuda`, `make install-vllm-cuda`
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L20                     On  |   00000000:65:01.0 Off |                  Off |
| N/A   30C    P8             34W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA L20                     On  |   00000000:67:01.0 Off |                  Off |
| N/A   31C    P8             35W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA L20                     On  |   00000000:69:01.0 Off |                  Off |
| N/A   30C    P8             35W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA L20                     On  |   00000000:6B:01.0 Off |                  Off |
| N/A   30C    P8             35W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA L20                     On  |   00000000:6F:01.0 Off |                  Off |
| N/A   31C    P8             35W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA L20                     On  |   00000000:71:01.0 Off |                  Off |
| N/A   30C    P8             35W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA L20                     On  |   00000000:73:01.0 Off |                  Off |
| N/A   30C    P8             33W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA L20                     On  |   00000000:75:01.0 Off |                  Off |
| N/A   29C    P8             33W /  350W |       0MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. input `text-generation-launcher --model-id /root/autodl-tmp/model/commandrplus-medusa --speculate 3 --num-shard 8 --sharded true --port 8000`
2. output
```
2024-04-20T07:20:42.025726Z  INFO text_generation_launcher: Args { model_id: "/root/autodl-tmp/model/commandrplus-medusa", revision: None, validation_workers: 2, sharded: Some(true), num_shard: Some(8), quantize: None, speculate: Some(3), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_tokens: None, max_input_length: None, max_total_tokens: None, waiting_served_ratio: 1.2, max_batch_prefill_tokens: None, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, cuda_graphs: None, hostname: "0.0.0.0", port: 8000, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }
2024-04-20T07:20:42.025796Z  INFO text_generation_launcher: Default `max_input_tokens` to 4095
2024-04-20T07:20:42.025801Z  INFO text_generation_launcher: Default `max_total_tokens` to 4096
2024-04-20T07:20:42.025803Z  INFO text_generation_launcher: Default `max_batch_prefill_tokens` to 4145
2024-04-20T07:20:42.025805Z  INFO text_generation_launcher: Using default cuda graphs [1, 2, 4, 8, 16, 32]
2024-04-20T07:20:42.025808Z  INFO text_generation_launcher: Sharding model on 8 processes
2024-04-20T07:20:42.025881Z  INFO download: text_generation_launcher: Starting download process.
2024-04-20T07:20:45.205520Z  INFO text_generation_launcher: Files for parent /root/autodl-tmp/model/c4ai-command-r-plus are already present on the host. Skipping download.

2024-04-20T07:20:45.729021Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-04-20T07:20:45.729218Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2024-04-20T07:20:45.729219Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-04-20T07:20:45.729343Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2024-04-20T07:20:45.729923Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2024-04-20T07:20:45.730027Z  INFO shard-manager: text_generation_launcher: Starting shard rank=5
2024-04-20T07:20:45.730039Z  INFO shard-manager: text_generation_launcher: Starting shard rank=6
2024-04-20T07:20:45.730041Z  INFO shard-manager: text_generation_launcher: Starting shard rank=4
2024-04-20T07:20:45.731189Z  INFO shard-manager: text_generation_launcher: Starting shard rank=7
2024-04-20T07:20:49.203122Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.227076Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.234256Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.235016Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.306170Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.306233Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.306825Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.308958Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.329699Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.329957Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.329988Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.330014Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.330291Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.331806Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.334307Z ERROR text_generation_launcher: exllamav2_kernels not installed.

2024-04-20T07:20:49.337252Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.337288Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.337288Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.338029Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.338064Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.338074Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.339061Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.339802Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.352816Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.355461Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.357804Z  WARN text_generation_launcher: We're not using custom kernels.

2024-04-20T07:20:49.359972Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.360703Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.363124Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.363903Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.365193Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`

2024-04-20T07:20:49.366006Z  WARN text_generation_launcher: Could not import Mamba: No module named 'mamba_ssm'

2024-04-20T07:20:49.734329Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/utils/flash_attn.py", line 24, in <module>
    import flash_attn_2_cuda

ImportError: /root/autodl-tmp/miniconda3/envs/tgi/lib/python3.10/site-packages/flash_attn-2.5.6-py3.10-linux-x86_64.egg/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/utils/flash_attn.py", line 31, in <module>
    raise ImportError(

ImportError: Flash Attention V2 is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention v2 with `cd server && make install install-flash-attention-v2-cuda`


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/root/autodl-tmp/miniconda3/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/cli.py", line 71, in serve
    from text_generation_server import server

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/server.py", line 16, in <module>
    from text_generation_server.models.vlm_causal_lm import VlmCausalLMBatch

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/models/vlm_causal_lm.py", line 14, in <module>
    from text_generation_server.models.flash_mistral import (

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/models/flash_mistral.py", line 18, in <module>
    from text_generation_server.models.custom_modeling.flash_mistral_modeling import (

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 29, in <module>
    from text_generation_server.utils import paged_attention, flash_attn

  File "/root/autodl-tmp/feng_workspace/text-generation-inference/server/text_generation_server/utils/flash_attn.py", line 47, in <module>
    raise ImportError(

ImportError: Flash Attention is not installed.
Use the official Docker image (ghcr.io/huggingface/text-generation-inference:latest) or install flash attention with `cd server && make install install-flash-attention`
 rank=2
2024-04-20T07:20:49.832789Z ERROR text_generation_launcher: Shard 2 failed to start
2024-04-20T07:20:49.832810Z  INFO text_generation_launcher: Shutting down shards
2024-04-20T07:20:49.875798Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
2024-04-20T07:20:49.887586Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=7
2024-04-20T07:20:49.888044Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=6
2024-04-20T07:20:49.894905Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=5
2024-04-20T07:20:49.895431Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=4
2024-04-20T07:20:49.895877Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=3
2024-04-20T07:20:49.956490Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=1
Error: ShardCannotStart
```
3. But when running `pip show flash_attn`
```
Name: flash_attn
Version: 2.5.6
Summary: Flash Attention: Fast and Memory-Efficient Exact Attention
Home-page: https://github.com/Dao-AILab/flash-attention
Author: Tri Dao
Author-email: trid@cs.stanford.edu
License: 
Location: /root/autodl-tmp/miniconda3/envs/tgi/lib/python3.10/site-packages/flash_attn-2.5.6-py3.10-linux-x86_64.egg
Requires: einops, ninja, packaging, torch
Required-by: 
```
4. Maybe `make install-flash-attention-v2-cuda` would not be run and I only need to run `make install-flash-attention`? I ran both of them. 

### Expected behavior

Because of the output of `pip show flash_attn` had `Name: flash_attn Version: 2.5.6`, the model should be deployed. Maybe `make install-flash-attention-v2-cuda` would not be run and I only need to run `make install-flash-attention`? I ran both of them.

**Comment by shuaills** [comment]
You need to re-install vllm and flash-attention-v2
`cd text-generation-inference/server
rm -rf vllm
make install-vllm-cuda

rm -rf flash-attention-v2
make install-flash-attention-v2-cuda`

They forgot to add this to the release notes about local installs.
#1738
I tried this and solved my problem.

**Comment by Desmond819** [comment]
how long it takes to make install-flash-attention-v2-cuda`? It takes forever for me

**Comment by syGOAT** [comment]
@shuaills I re-installed flash-attn-2 and it was solved. Maybe it was just a installation problem.
