### ISSUE TITLE
docker-compose throws `flash attention is not installed` error

### ISSUE THREAD

**Issue by retzero** [huggingface/text-generation-inference#2064]
### System Info

Docker mage: `ghcr.io/huggingface/text-generation-inference:2.0`
GPU: A100
Ubuntu 22.04.2 LTS
Docker version 26.0.0, build 2ae903e
docker-compose version 1.29.2,

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Plain docker command works fine but `docker-compose` failed.
Can you please guide me how to resolve this error?

### OK - `docker`
```
docker run --gpus 0,1  --shm-size 1g -p 8080:80 -v $PWD/data:/data -d ghcr.io/huggingface/text-generation-inference:2.0 --model-id /da
ta/our_model
```

### NOK - `docker-compose`
```
---

version: '3.7'
services:
  inference-chat:
    image: ghcr.io/huggingface/text-generation-inference:2.0
    ports:
      - 8080:80
    volumes:
      - ${PWD}/data:/data
    command:
      - "--model-id"
      - "/data/our_model"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu]
    shim_size: 1g
networks:
  default:
    driver: bridge
```

- Error
```
inference-chat_1  | 2024-06-13T12:25:49.886902Z  INFO text_generation_launcher: Using default cuda graphs [1, 2, 4, 8, 16, 32]
inference-chat_1  | 2024-06-13T12:25:49.886906Z  INFO text_generation_launcher: Sharding model on 2 processes
inference-chat_1  | 2024-06-13T12:25:49.887020Z  INFO download: text_generation_launcher: Starting download process.
inference-chat_1  | 2024-06-13T12:25:52.590785Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
inference-chat_1  | 
inference-chat_1  | 2024-06-13T12:25:53.190319Z  INFO download: text_generation_launcher: Successfully downloaded weights.
inference-chat_1  | 2024-06-13T12:25:53.190639Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
inference-chat_1  | 2024-06-13T12:25:53.190680Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
inference-chat_1  | 2024-06-13T12:25:55.978980Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: cannot import name 'FastLayerNorm' from 'text_generation_server.layers.layernorm' (/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/layernorm.py)
inference-chat_1  | 
inference-chat_1  | 2024-06-13T12:25:56.005450Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: cannot import name 'FastLayerNorm' from 'text_generation_server.layers.layernorm' (/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/layernorm.py)
inference-chat_1  | 
inference-chat_1  | 2024-06-13T12:25:56.894808Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
inference-chat_1  | 
inference-chat_1  | The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
inference-chat_1  | There was a problem when trying to write in your cache folder (/data). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
inference-chat_1  | The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
inference-chat_1  | Traceback (most recent call last):
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/bin/text-generation-server", line 8, in <module>
inference-chat_1  |     sys.exit(app())
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 71, in serve
inference-chat_1  |     from text_generation_server import server
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 17, in <module>
inference-chat_1  |     from text_generation_server.models.pali_gemma import PaliGemmaBatch
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/pali_gemma.py", line 5, in <module>
inference-chat_1  |     from text_generation_server.models.vlm_causal_lm import (
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/vlm_causal_lm.py", line 14, in <module>
inference-chat_1  |     from text_generation_server.models.flash_mistral import (
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 18, in <module>
inference-chat_1  |     from text_generation_server.models.custom_modeling.flash_mistral_modeling import (
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 30, in <module>
inference-chat_1  |     from text_generation_server.utils import paged_attention, flash_attn
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/flash_attn.py", line 293, in <module>
inference-chat_1  |     raise NotImplementedError("flash attention is not installed")
inference-chat_1  | 
inference-chat_1  | NotImplementedError: flash attention is not installed
inference-chat_1  |  rank=1
inference-chat_1  | 2024-06-13T12:25:56.895566Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
inference-chat_1  | 
inference-chat_1  | The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
inference-chat_1  | There was a problem when trying to write in your cache folder (/data). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
inference-chat_1  | The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
inference-chat_1  | Traceback (most recent call last):
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/bin/text-generation-server", line 8, in <module>
inference-chat_1  |     sys.exit(app())
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 71, in serve
inference-chat_1  |     from text_generation_server import server
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 17, in <module>
inference-chat_1  |     from text_generation_server.models.pali_gemma import PaliGemmaBatch
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/pali_gemma.py", line 5, in <module>
inference-chat_1  |     from text_generation_server.models.vlm_causal_lm import (
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/vlm_causal_lm.py", line 14, in <module>
inference-chat_1  |     from text_generation_server.models.flash_mistral import (
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 18, in <module>
inference-chat_1  |     from text_generation_server.models.custom_modeling.flash_mistral_modeling import (
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 30, in <module>
inference-chat_1  |     from text_generation_server.utils import paged_attention, flash_attn
inference-chat_1  | 
inference-chat_1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/flash_attn.py", line 293, in <module>
inference-chat_1  |     raise NotImplementedError("flash attention is not installed")
inference-chat_1  | 
inference-chat_1  | NotImplementedError: flash attention is not installed
inference-chat_1  |  rank=0
inference-chat_1  | 2024-06-13T12:25:56.993889Z ERROR text_generation_launcher: Shard 1 failed to start
inference-chat_1  | 2024-06-13T12:25:56.993908Z  INFO text_generation_launcher: Shutting down shards
inference-chat_1  | Error: ShardCannotStart
test-inference-chat_1 exited with code 1
```

### Expected behavior

Run same as plain docker command.

**Comment by LysandreJik** [comment]
Hey! I've tried reproducing it locally, but unfortunately, I can't manage to do so. I don't have you model ID, but I see it seems to fail on the mistral import, so I designed the following docker compose file with `mistral-community/Mistral-7B-v0.2`:

```
version: '3.7'
services:
  inference-chat:
    image: ghcr.io/huggingface/text-generation-inference:2.0
    ports:
      - 8080:80
    volumes:
      - /home/ubuntu/data:/data
    command:
      - "--model-id"
      - "mistral-community/Mistral-7B-v0.2"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
networks:
  default:
    driver: bridge
```

I don't have any difference between using raw docker and docker compose, and it doesn't fail at the flash attention step. I'm using an A10G GPU which is the same generation as your A100 GPU.

Can you maybe try with the checkpoint above to see if it fails for you, to see if we identify whether the problem comes from a specific architecture or not?

**Comment by retzero** [comment]
@LysandreJik 
Thank you for the feedback.
This works for me.
```diff
+    environment:
+      CUDA_VISIBLE_DEVICES: "0,1"

//

-            device_ids: ['0', '1']
+            count: all
```

I'm closing this ticket.

**Comment by LysandreJik** [comment]
Awesome :raised_hands:
