### ISSUE TITLE
Unable to load the local model file into LoRA adaptors

### ISSUE THREAD

**Issue by mhou7712** [huggingface/text-generation-inference#2143]
### System Info

`
text-generation-launcher 2.1.0
`

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Execute the following statement inside of ghcr.io/huggingface/text-generation-inference:2.1.0:

`
text-generation-launcher --hostname 0.0.0.0 -p 5029 -e 
        --lora-adapters "/var/spool/llm_models/checkpoint-576" 
        --model-id "/var/spool/llm_models/Mistral-7B-v0.1_032124" --cuda-memory-fraction 0.90 --max-total-tokens 5000 --max-input-length 4096
`

where "/var/spool/llm_models/Mistral-7B-v0.1_032124" and "/var/spool/llm_models/checkpoint-576" are the local filesystem.

The log and error message are shown below:

`
2024-06-28T22:38:37.606983Z  INFO text_generation_launcher: Args {
    model_id: "/var/spool/llm_models/Mistral-7B-v0.1_032124",
    revision: None,
    validation_workers: 2,
    sharded: None,
    num_shard: None,
    quantize: None,
    speculate: None,
    dtype: None,
    trust_remote_code: false,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: Some(
        4096,
    ),
    max_total_tokens: Some(
        5000,
    ),
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: None,
    max_batch_total_tokens: None,
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: None,
    hostname: "0.0.0.0",
    port: 5029,
    shard_uds_path: "/tmp/text-generation-server",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: Some(
        "/data",
    ),
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 0.9,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    otlp_service_name: "text-generation-inference.router",
    cors_allow_origin: [],
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: true,
    max_client_batch_size: 4,
    lora_adapters: Some(
        "/var/spool/llm_models/checkpoint-576",
    ),
}
2024-06-28T22:38:37.607480Z  INFO text_generation_launcher: Default `max_batch_prefill_tokens` to 4146
2024-06-28T22:38:37.607491Z  INFO text_generation_launcher: Using default cuda graphs [1, 2, 4, 8, 16, 32]
2024-06-28T22:38:37.607705Z  INFO download: text_generation_launcher: Starting download process.
2024-06-28T22:38:40.422554Z  INFO text_generation_launcher: Detected system cuda
2024-06-28T22:38:42.803387Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
2024-06-28T22:38:43.815171Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-06-28T22:38:43.815615Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-06-28T22:38:46.949677Z  INFO text_generation_launcher: Detected system cuda
2024-06-28T22:38:49.127548Z  WARN text_generation_launcher: LoRA adapters are enabled. This is an experimental feature and may not work as expected.
2024-06-28T22:38:53.826828Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-06-28T22:39:03.854669Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-06-28T22:39:13.862108Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-06-28T22:39:23.871495Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-06-28T22:39:33.955301Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-06-28T22:39:43.964370Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2024-06-28T22:39:44.362823Z  INFO text_generation_launcher: Loading adapter weights into model: /var/spool/llm_models/checkpoint-576
2024-06-28T22:39:44.607361Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 106, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 297, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 256, in serve_inner
    model.load_adapter(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/model.py", line 214, in load_adapter
    ) = load_and_merge_adapters(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/adapter.py", line 53, in load_and_merge_adapters
    return load_module_map(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/adapter.py", line 173, in load_module_map
    adapter_filenames = hub._cached_adapter_weight_files(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 25, in _cached_adapter_weight_files
    d = _get_cached_revision_directory(adapter_id, revision)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 108, in _get_cached_revision_directory
    file_download.repo_folder_name(repo_id=model_id, repo_type="model")
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/var/spool/llm_models/checkpoint-576'. Use `repo_type` argument if needed.
`

It seems that adaptor does not recognize "/var/spool/llm_models/checkpoint-576" is the local filesystem.

If I execute the following command without adaptor:

`
text-generation-launcher --hostname 0.0.0.0 -p 5029 -e 
        --model-id "/var/spool/llm_models/Mistral-7B-v0.1_032124" --cuda-memory-fraction 0.90 --max-total-tokens 5000 --max-input-length 4096
`

The base model is loaded without an issue.

### Expected behavior

Can we have the adaptor to load the model file from the local filesystem likes  "--model-id " does?

**Comment by mhou7712** [comment]
I tried the example as the web example for LoRA:

`
text-generation-launcher --hostname 0.0.0.0 -p 5029 -e 
        --lora-adapters "predibase/customer_support" 
        --model-id "/var/spool/llm_models/Mistral-7B-v0.1_032124" --cuda-memory-fraction 0.90 --max-total-tokens 5000 --max-input-length 4096
`

It worked fine.    

So, the adaptor can  load model file from repo but not from local.

**Comment by Egelvein** [comment]
+, the same problem

**Comment by flozi00** [comment]
Are you using docker enviroments ?

**Comment by mhou7712** [comment]
yes and downloaded from "ghcr.io/huggingface/text-generation-inference:2.1.0".

Question: can the adaptor load model files from local instead repo?  Thanks.

**Comment by mhou7712** [comment]
Please compare the following two command lines:

LoRA with repo:
`
text-generation-launcher --hostname 0.0.0.0 -p 5029 -e  --lora-adapters "predibase/customer_support"  --model-id "/var/spool/llm_models/Mistral-7B-v0.1_032124" --cuda-memory-fraction 0.90 --max-total-tokens 5000 --max-input-length 4096
`

LoRA with local:
`
text-generation-launcher --hostname 0.0.0.0 -p 5029 -e  --lora-adapters "/var/spool/llm_models/checkpoint-576"  --model-id "/var/spool/llm_models/Mistral-7B-v0.1_032124" --cuda-memory-fraction 0.90 --max-total-tokens 5000 --max-input-length 4096
`

"LoRA with repo" works with me and "/var/spool/llm_models/Mistral-7B-v0.1_032124" is visible inside the container for the base model, and the same volume "/var/spool/llm_models/" is visible for "LoRA with local".  Yes ,"checkpoint-576" is accessible under "/var/spool/llm_models"  inside the container.

Thanks for asking and I did check all model files are available inside container.

**Comment by bwhartlove** [comment]
+1 same issue

**Comment by newsbreakDuadua9** [comment]
same issue here

**Comment by mhou7712** [comment]
@newsbreakDuadua9 a quick question if adaptor_id is not a repo then adaptor assumes something (I mean something can be the local filesystem directory or it does not exist), right?
Thanks.

**Comment by mhou7712** [comment]
@flozi00 I am wondering that this issue can be assigned with the adaptor expert so he/she can help us for looking into the issue.
Thanks.

**Comment by mhou7712** [comment]
Greeting @drbh,  please let me know if any information that I can provide in order to get this issue moved forward.  Thanks.

**Comment by drbh** [comment]
Hi @mhou7712 thanks for opening this issue. Currently the lora feature only supports adapter_ids, however there is a PR open includes the ability to load a lora from a local directory https://github.com/huggingface/text-generation-inference/pull/2193 along with other refactors/updates. Once merged this issue should be resolved.

for example local loras can be specificed with like `name=/path,name2=/path`

```bash
text-generation-launcher \
--hostname 0.0.0.0 \
-p 5029 \
-e  \
--lora-adapters myadapter=/var/spool/llm_models/checkpoint-576  \
--model-id /var/spool/llm_models/Mistral-7B-v0.1_032124 \
--cuda-memory-fraction 0.90 \
--max-total-tokens 5000 \
--max-input-length 4096
```

**Comment by mhou7712** [comment]
Hi @drbh , thanks for getting back to me.

Reviewed the example about --lora-adaptors, it is wonderful to have an adaptor_id per the directory. 

Can I assume the following configuration will be implemented when I have multi adaptor_ids?

`
text-generation-launcher \
--hostname 0.0.0.0 \
-p 5029 \
-e  \
--lora-adapters myadapter=/var/spool/llm_models/checkpoint-576,myadapter1=/var/spool/llm_models/checkpoint-577 \
--model-id /var/spool/llm_models/Mistral-7B-v0.1_032124 \
--cuda-memory-fraction 0.90 \
--max-total-tokens 5000 \
--max-input-length 4096
`

Again, thanks a lots!!

**Comment by drbh** [comment]
@mhou7712 yep that is correct!

**Comment by mhou7712** [comment]
Hi @Narsil, I would like to follow-up when we are going to have the next release included https://github.com/huggingface/text-generation-inference/commit/071842ee0b26d45dd0cda30dde4df77678c26b7d?  Thanks.

**Comment by mhou7712** [comment]
Hi @drbh,  I have tried the v2.2.0 build with the following command:

`

text-generation-launcher --hostname 0.0.0.0 -p 5029 -e \\
    --lora-adapters llm_sql_inference=/var/spool/llm_models/md1fttrain/checkpoint-6770,llm_reasoning=/var/spool/llm_models/md2fttrain/checkpoint-360 \\
    --model-id "/var/spool/llm_models/Meta-Llama-3-8B-Instruct"

`

`

xpu-smi:
N/A
2024-07-24T13:05:58.718927Z  INFO text_generation_launcher: Args {
    model_id: "/var/spool/llm_models/Meta-Llama-3-8B-Instruct",
    revision: None,
    validation_workers: 2,
    sharded: None,
    num_shard: None,
    quantize: None,
    speculate: None,
    dtype: None,
    trust_remote_code: false,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: None,
    max_total_tokens: None,
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: None,
    max_batch_total_tokens: None,
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: None,
    hostname: "0.0.0.0",
    port: 5029,
    shard_uds_path: "/tmp/text-generation-server",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: Some(
        "/data",
    ),
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 1.0,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    otlp_service_name: "text-generation-inference.router",
    cors_allow_origin: [],
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: true,
    max_client_batch_size: 4,
    lora_adapters: Some(
        "llm_sql_inference=/var/spool/llm_models/md1fttrain/checkpoint-6770,llm_reasoning=/var/spool/llm_models/md2fttrain/checkpoint-360",
    ),
    disable_usage_stats: false,
    disable_crash_reports: false,
}
2024-07-24T13:05:58.720021Z  INFO text_generation_launcher: Model supports up to 16384 but tgi will now set its default to 4096 instead. This is to save VRAM by refusing large prompts in order to allow more users on the same hardware. You can increase that size using `--max-batch-prefill-tokens=16434 --max-total-tokens=16384 --max-input-tokens=16383`.
2024-07-24T13:05:58.720043Z  INFO text_generation_launcher: Default `max_input_tokens` to 4095
2024-07-24T13:05:58.720048Z  INFO text_generation_launcher: Default `max_total_tokens` to 4096
2024-07-24T13:05:58.720053Z  INFO text_generation_launcher: Default `max_batch_prefill_tokens` to 4145
2024-07-24T13:05:58.720058Z  INFO text_generation_launcher: Using default cuda graphs [1, 2, 4, 8, 16, 32]
2024-07-24T13:05:58.720295Z  INFO download: text_generation_launcher: Starting check and download process for /var/spool/llm_models/Meta-Llama-3-8B-Instruct
2024-07-24T13:06:02.459860Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
2024-07-24T13:06:03.226757Z  INFO download: text_generation_launcher: Successfully downloaded weights for /var/spool/llm_models/Meta-Llama-3-8B-Instruct
2024-07-24T13:06:03.226887Z  INFO download: text_generation_launcher: Starting check and download process for llm_sql_inference=/var/spool/llm_models/md1fttrain/checkpoint-6770
2024-07-24T13:06:08.155920Z ERROR download: text_generation_launcher: Download encountered an error:
2024-07-24 13:06:05.742 | INFO     | text_generation_server.utils.import_utils:<module>:75 - Detected system cuda
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 160, in download_weights
    utils.weight_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 187, in weight_files
    filenames = weight_hub_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 146, in weight_hub_files
    info = api.model_info(model_id, revision=revision)

  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)

  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(

huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'llm_sql_inference=/var/spool/llm_models/md1fttrain/checkpoint-6770'. Use `repo_type` argument if needed.

Error: DownloadError

`

Thanks.

**Comment by drbh** [comment]
Hi @mhou7712 thanks for the follow up, incidentally the lora updates were not included in the recent release since other changes were priority. 

The PR to enable local models https://github.com/huggingface/text-generation-inference/pull/2193 should be merged soon. Apologies for the delay!

**Comment by mhou7712** [comment]
Still waiting the next release for testing

**Comment by momozzing** [comment]
same issue here +1

Lora adapter still in local cannot be loaded.

**Comment by mhou7712** [comment]
Still waiting the next release for testing...

**Comment by momozzing** [comment]
> Still waiting the next release for testing...

Are you trying vLLM?? 
I solved this problem using vLLM..

**Comment by kalzbra** [comment]
Hi @momozzing 
Do you mind sharing how you've solved the problem. thanks.

**Comment by mhou7712** [comment]
Hi @momozzing, yes,  I have tried vLLM and it works for me.  And, it is the reason that TGI can support it.  Thanks.

**Comment by mhou7712** [comment]
Hi @kalzbra, there is an example of vLLM:

```
python3 -m vllm.entrypoints.openai.api_server \
    --served-model-name base_model_name \
    --model <path_of_base_model> \
    --enable-lora --lora-modules <lora_name_1>=<path_of_lora_1> <lora_name_2>=<path_of_lora_2>
```

**Comment by kalzbra** [comment]
@momozzing 
Thanks.

TGI version 2.3.0 is out today but still unable to load local Lora adapters.

**Comment by mhou7712** [comment]
Tired in v2.3.0 and revired TGI args:

```
2024-09-23T17:54:41.494818Z  INFO text_generation_launcher: Args {
    model_id: "/var/spool/llm_models/Meta-Llama-3-8B-Instruct",
    revision: None,
    validation_workers: 2,
    sharded: None,
    num_shard: None,
    quantize: None,
    speculate: None,
    dtype: None,
    trust_remote_code: false,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: Some(
        4096,
    ),
    max_total_tokens: Some(
        5000,
    ),
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: None,
    max_batch_total_tokens: None,
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: None,
    hostname: "0.0.0.0",
    port: 5029,
    shard_uds_path: "/tmp/llm_base_model",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: None,
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 0.9,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    otlp_service_name: "text-generation-inference.router",
    cors_allow_origin: [],
    api_key: None,
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: true,
    max_client_batch_size: 4,
    lora_adapters: Some(
        "llm_sql_inference=/var/spool/llm_models/md1fttrain/checkpoint-6770,llm_reasoning=/var/spool/llm_models/md2fttrain/checkpoint-360",
    ),
    usage_stats: On,
}
```

With test LoRA with adaptor_id=llm_sql_inference:

```
$ curl 105.144.47.72:30529/generate     -X POST     -H 'Content-Type: application/json'     -d '{
  "inputs": "Hello who are you?",
  "parameters": {
    "max_new_tokens": 40,
    "adapter_id": "llm_sql_inference"
  }
}' -s | jq -r '.'
{
  "generated_text": " I'm a 22 year old student from the UK. I'm studying computer science and I'm really interested in AI and machine learning. I'm also a bit of a gamer and I love playing"
}

```

With test LoRA with adaptor_id=llm_reasoning:

```
$ curl 105.144.47.72:30529/generate     -X POST     -H 'Content-Type: application/json'     -d '{
  "inputs": "Hello who are you?",
  "parameters": {
    "max_new_tokens": 40,
    "adapter_id": "llm_reasoning"
  }
}' -s | jq -r '.'
{
  "generated_text": " I'm a 25 year old guy from the UK, I'm a bit of a tech enthusiast and I love playing video games. I'm also a bit of a movie buff and I love watching"
}
```

@drbh , thanks for the changes....

**Comment by mhou7712** [comment]
Hi @drbh, another quick question:  is there a way to list the LoRA adapters in the REST API call (I remembered the previous TGI release is able to do so, or I may be wrong)?  Likes:

```
$ curl 105.144.47.72:30529/v1/models -s | jq -r '.'
{
  "object": "list",
  "data": [
    {
      "id": "/var/spool/llm_models/Meta-Llama-3-8B-Instruct",
      "object": "model",
      "created": 0,
      "owned_by": "/var/spool/llm_models/Meta-Llama-3-8B-Instruct"
    }
  ]
}
```

Should I create another issue to address the different concern?  

Thanks.
