### ISSUE TITLE
error warming up cohere/aya-23-35b model: error in `reshape_and_cache` function with TGI 2.1.1

### ISSUE THREAD

**Issue by Jason-CKY** [huggingface/text-generation-inference#2199]
### System Info

`ghcr.io/huggingface/text-generation-inference:2.1.1` docker image
running on 2 nvidia H100s

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Run the docker image with the following environment variables:

* MODEL_ID: "CohereForAI/aya-23-35B"
* REVISION: "31d6fd858f20539a55401c7ad913086f54d9ca2c"
* MAX_BATCH_PREFILL_TOKENS: "8192"
* MAX_INPUT_TOKENS: "8191"
* MAX_TOTAL_TOKENS: "8192"
* MAX_CONCURRENT_REQUESTS: "300"
* MAX_STOP_SEQUENCES: "55"

Run into error when warming up model.
Similar error as #1738

```
Method Warmup encountered an error.
Traceback (most recent call last):
	File "/opt/conda/bin/text-generation-server", line 8, in <module>
		sys.exit(app())
	File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
        return get_command(self)(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
        return _main(
    File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main    
        rv = self.invoke(ctx)
    File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    ...
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 125, in Warmup
        max_supported_total_tokens = self.model.warmup(batch)
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 985, in warmup
        _, batch, _ = self.generate_token(batch)
    File "/opt/conda/lib/python3.10/site-packages/contextlib.py", line 79, in inner
        return func(*args, **kwds)
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1253, in generate_token
       out, speculative_logits = self.forward(batch, adapter_data)
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1178, in forward
        logits, speculative_logits = self.model.forward(
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_cohere_modeling.py", line 521, in forward
        hidden_states = self.model(    
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_cohere_modeling.py", line 470, in forward
        hidden_states, residual = layer(
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_cohere_modeling.py", line 397, in forward
        attn_output = self.self_attn(
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_cohere_modeling.py", line 289, in forward
        reshape_and_cache(key, value, kv_cache[0], kv_cache[1], slots)
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/attention/cuda.py", line 31, in reshape_and_cache
        cache_ops.reshape_and_cache(
TypeError: reshape_and_cache(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor, arg5: str, arg6: float) -> None

Invoked with: tensor([[[ ....], [...], [bunch of 0 tensors]]])
```

### Expected behavior

No errors when warming up model

**Comment by OlivierDehaene** [comment]
Fixed by #2249
