### ISSUE TITLE
ModuleNotFoundError: No module named 'rotary_emb'

### ISSUE THREAD

**Issue by lcw99** [huggingface/text-generation-inference#225]
How can I install 'rotary_emb'?

```
2023-04-24T06:19:19.330017Z  WARN shard-manager: text_generation_launcher: Could not import Flash Attention enabled models
Traceback (most recent call last):
  File "/home/chang/anaconda3/envs/hf-tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/chang/anaconda3/envs/hf-tgi/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/chang/AI/llm/text-generation-inference/server/text_generation_server/cli.py", line 51, in serve
    from text_generation_server import server
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/chang/AI/llm/text-generation-inference/server/text_generation_server/server.py", line 12, in <module>
    from text_generation_server.cache import Cache
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/chang/AI/llm/text-generation-inference/server/text_generation_server/cache.py", line 3, in <module>
    from text_generation_server.models.types import Batch
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> File "/home/chang/AI/llm/text-generation-inference/server/text_generation_server/models/__init__.py", line 32, in <module>
    from text_generation_server.models.flash_neox import FlashNeoX, FlashNeoXSharded
  File "/home/chang/AI/llm/text-generation-inference/server/text_generation_server/models/flash_neox.py", line 11, in <module>
    from text_generation_server.models.custom_modeling.flash_neox_modeling import (
  File "/home/chang/AI/llm/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 33, in <module>
    import rotary_emb
ModuleNotFoundError: No module named 'rotary_emb'

```

**Comment by OlivierDehaene** [comment]
```shell
cd server && make install-flash-attention
```
