### ISSUE TITLE
DeepSeek-Coder-V2-Lite-Instruct-AWQ

### ISSUE THREAD

**Issue by Ichigo3766** [huggingface/text-generation-inference#2267]
I am trying to load the model (TechxGenus/DeepSeek-Coder-V2-Lite-Instruct-AWQ) but getting error:

```2024-07-21T17:57:41.086016Z ERROR text_generation_launcher: Shard 0 failed to start
2024-07-21T17:57:41.086044Z  INFO text_generation_launcher: Shutting down shards
2024-07-21T17:57:41.089467Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=1
2024-07-21T17:57:41.089511Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=1
2024-07-21T17:57:41.089599Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

2024-07-21 17:57:35.804 | INFO     | text_generation_server.utils.import_utils:<module>:75 - Detected system cuda
/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
You are using a model of type deepseek_v2 to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
[rank2]: Traceback (most recent call last):

[rank2]:   File "/opt/conda/bin/text-generation-server", line 8, in <module>
[rank2]:     sys.exit(app())

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 118, in serve
[rank2]:     server.serve(

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 297, in serve
[rank2]:     asyncio.run(

[rank2]:   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
[rank2]:     return loop.run_until_complete(main)

[rank2]:   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[rank2]:     return future.result()

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 231, in serve_inner
[rank2]:     model = get_model(

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 485, in get_model
[rank2]:     return FlashCausalLM(

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 898, in __init__
[rank2]:     model = model_class(prefix, config, weights)

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 764, in __init__
[rank2]:     self.model = DeepseekV2Model(

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 703, in __init__
[rank2]:     [

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 704, in <listcomp>
[rank2]:     DeepseekV2Layer(

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 626, in __init__
[rank2]:     self.self_attn = DeepseekV2Attention(

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 256, in __init__
[rank2]:     weight=weights.get_weights(f"{prefix}.kv_a_proj_with_mqa"),

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 339, in get_weights
[rank2]:     return self.weights_loader.get_weights(self, prefix)

[rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/gptq/__init__.py", line 236, in get_weights
[rank2]:     return GPTQWeight(

[rank2]: TypeError: GPTQWeight.__init__() missing 1 required positional argument: 'use_awq_kernel'```

**Comment by Ichigo3766** [comment]
I added the argument manually to see if it loads like:
```
return GPTQWeight(
    qweight=qweight,
    qzeros=qzeros,
    scales=scales,
    g_idx=g_idx,
    bits=self.bits,
    groupsize=self.groupsize,
    use_exllama=use_exllama,
    use_awq_kernel=True,  # Added this line
)
```

But from here, i get the error:

```
[rank1]:   File "/opt/conda/bin/text-generation-server", line 8, in <module>
[rank1]:     sys.exit(app())

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 118, in serve
[rank1]:     server.serve(

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 297, in serve
[rank1]:     asyncio.run(

[rank1]:   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
[rank1]:     return loop.run_until_complete(main)

[rank1]:   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[rank1]:     return future.result()

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 231, in serve_inner
[rank1]:     model = get_model(

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 485, in get_model
[rank1]:     return FlashCausalLM(

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 898, in __init__
[rank1]:     model = model_class(prefix, config, weights)

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 764, in __init__
[rank1]:     self.model = DeepseekV2Model(

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 703, in __init__
[rank1]:     [

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 704, in <listcomp>
[rank1]:     DeepseekV2Layer(

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 640, in __init__
[rank1]:     self.mlp = DeepseekV2MLP(

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 411, in __init__
[rank1]:     self.down_proj = TensorParallelRowLinear.load(

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/tensor_parallel.py", line 200, in load
[rank1]:     weight = weights.get_weights_row(prefix)

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 387, in get_weights_row
[rank1]:     return self.weights_loader.get_weights_row(self, prefix)

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/gptq/__init__.py", line 515, in get_weights_row
[rank1]:     qzeros = weights.get_sharded(f"{prefix}.qzeros", dim=0)

[rank1]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 269, in get_sharded
[rank1]:     size % world_size == 0

[rank1]: AssertionError: The choosen size 171 is not compatible with sharding on 4 shards
 rank=1
Error: ShardCannotStart
```
