### ISSUE TITLE
LLaMA Models "on the Hub doesn't have a tokenizer"

### ISSUE THREAD

**Issue by ScientiaEtVeritas** [huggingface/text-generation-inference#238]
I'm running into the following error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Model ..." on the Hub doesn't have a tokenizer"', router/src/main.rs:101:70
```

using `text-generation-launcher --model-id <model>--num-shard 1 --quantize`

for a local path to 13B LLaMA weights (after conversion using the HF script), but I also get the same error when using `chavinlo/alpaca-13b` or `TheBloke/vicuna-13B-1.1-HF` from the Hub.

I'm on the most recent commit of the main branch (45344244cf194c89c94fdbdfc1bdca724c7df4e5). I don't seem to have the problem when loading and using the model in transformers directly.

**Comment by OlivierDehaene** [comment]
Are you sure you are on the latest commit? [Because line 101 is a blank line.](https://github.com/huggingface/text-generation-inference/blob/main/router/src/main.rs#L101)

Have you re-compiled the router?

**Comment by ScientiaEtVeritas** [comment]
So, I updated to b9ae7e5da19573de3d9e727884f6609df04f935d and successfully ran `make install` which now leads me to this

```
2023-04-27T11:48:27.805118Z  INFO text_generation_launcher: Starting Webserver
2023-04-27T11:48:28.987839Z ERROR text_generation_client: router/client/src/lib.rs:39: Could not connect to Text Generation server: transport error
thread 'main' panicked at 'unable to parse model info: Error("missing field `id`", line: 1, column: 62)', router/src/main.rs:275:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: text_generation_router::get_model_info::{{closure}}
   4: text_generation_router::main::{{closure}}
             at ./router/src/main.rs:148:89
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/park.rs:283:31
   9: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/context.rs:315:13
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  11: tokio::runtime::runtime::Runtime::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/runtime.rs:304:45
  12: text_generation_router::main
             at ./router/src/main.rs:121:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-04-27T11:48:29.207509Z ERROR text_generation_launcher: Webserver Crashed
```

As I did some further experiments, that error doesn't seem to be limited to LLaMA models, I get the same for `text-generation-launcher --model-id facebook/galactica-6.7b --num-shard 1`

**Comment by ScientiaEtVeritas** [comment]
Minor update: I tried it with a new conda environment, new rust insallation, new github clone -- and it seems it'll always run into this some variation of this `ConnectionError`, `transport error` now -- that I'm not sure of how to fix it:

```
2023-04-28T17:06:15.281755Z  INFO text_generation_launcher: Starting Webserver
2023-04-28T17:06:15.696385Z ERROR text_generation_client: router/client/src/lib.rs:39: Could not connect to Text Generation server: transport error
thread 'main' panicked at 'Could not connect to server: Connection("transport error")', router/src/main.rs:163:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::expect
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1047:23
   4: text_generation_router::main::{{closure}}
             at ./textgen/router/src/main.rs:161:38
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/park.rs:283:31
   9: tokio::runtime::context::BlockingRegionGuard::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/context.rs:315:13
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  11: tokio::runtime::runtime::Runtime::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/runtime.rs:304:45
  12: text_generation_router::main
             at ./textgen/router/src/main.rs:121:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-04-28T17:06:15.883627Z ERROR text_generation_launcher: Webserver Crashed
```
