### ISSUE TITLE
Each process is one gpu

### ISSUE THREAD

**Issue by philschmid** [huggingface/text-generation-inference#2432]
### System Info

ghcr.io/huggingface/text-generation-inference:2.2.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```bash
sudo docker run --gpus all -ti -p 8080:80 \
  -e MODEL_ID=meta-llama/Meta-Llama-3-8B-Instruct \
  -e NUM_SHARD=2 \
  -e MAX_INPUT_TOKENS=1562 \
  -e MAX_TOTAL_TOKENS=2048 \
  -e CUDA_VISIBLE_DEVICES=0,1 \
  -e HF_TOKEN=$(cat ~/.cache/huggingface/token) \
  ghcr.io/huggingface/text-generation-inference:2.2.0
```

### Expected behavior

Running llama 3 8b on 2 GPUs.  My understanding was that the number of heads must be divisble by the number of GPUs. This should mean for 8b. I can deploy on 1, 2, 4 or 8 GPUs. But when i try to launch it with TGI 2.2.0 with num_shard > 1.  

Error:

```bash
2024-08-19T14:20:27.516759Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
2024-08-19 14:20:24.479 | INFO     | text_generation_server.utils.import_utils:<module>:75 - Detected system cuda
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 118, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 297, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 231, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 706, in get_model
    return FlashCausalLM(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 846, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/dist.py", line 52, in initialize_torch_distributed
    assert WORLD_SIZE <= torch.cuda.device_count(), "Each process is one gpu"
AssertionError: Each process is one GPU
```

**Comment by philschmid** [comment]
>`assert WORLD_SIZE <= torch.cuda.device_count(), "Each process is one gpu"`
> This means you're trying ot shard on a host that doesn't have enough GPUs
