### ISSUE TITLE
OpenGVLab/InternVL2-8B model support

### ISSUE THREAD

**Issue by dhandhalyabhavik** [huggingface/text-generation-inference#2445]
### Model description

I am not sure these new models from OpenGVLab are supported here.

[OpenGVLab/InternVL2-8B](https://huggingface.co/collections/OpenGVLab/internvl-20-667d3961ab5eb12c7ed1463e)

After executing docker run, I got following error,

```
2024-08-22 05:51:08.649 | INFO     | text_generation_server.utils.import_utils:<module>:75 - Detected system cuda
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 118, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 297, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 231, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 1117, in get_model
    raise ValueError(f"Unsupported model type {model_type}")

ValueError: Unsupported model type internvl_chat
 rank=0
2024-08-22T05:51:12.673589Z ERROR text_generation_launcher: Shard 0 failed to start
2024-08-22T05:51:12.673618Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

Please add support, these are the best performing open-source models.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by ErikKaum** [comment]
Hi @dhandhalyabhavik 👋 

Thank yo for the request. At the moment we're quite constrained on bandwidth so we can't unfortunately satisfy all requests.  But for example if many other people also need this model in TGI (e.g. by adding the 👍 emoji to the issue) we know better how to prioritize.

Also if you have time & passion feel free to open a PR. I'll try to give you guidance on how to proceed with implementing the model.

**Comment by leonyufeng** [comment]
Hi @ErikKaum, I'm also interested in using this InternVL2 model.
I do have time & passion to implementing the model. Would you please give me guidance on how to proceed?

**Comment by ErikKaum** [comment]
Hi @leonyufeng 👋 

Glad to hear!

Basically on the python side the models are implemented in the text-generation-server under the [models](https://github.com/huggingface/text-generation-inference/tree/main/server/text_generation_server/models) directory, this is most likely where the implementation of the mode itself would go.

The additionally you'd need to update the configs in the [routing layer](https://github.com/huggingface/text-generation-inference/blob/0aa66d693a85faed268be50ab8e662cf5516be30/router/src/config.rs#L144) such that the added model type is recongnized.

This is of course very high level, but it should help to point you in the right direction and especially help you find previous model implementations. Which serve as a good guide.

Additional resources:
- Developing with nix. The fastest and most hasslefree way of developing TGI is using [nix](https://github.com/huggingface/text-generation-inference/tree/main/nix), if you're not familiar don't worry -- you can develop without nix, no issue, it just makes things nicer and faster.
- TGI internal architecture might be helpful: https://huggingface.co/docs/text-generation-inference/architecture

Does this help you get started?
