### ISSUE TITLE
TGI fails to run Llama 3.1-405B with AMD 8 X MI300x

### ISSUE THREAD

**Issue by Bihan** [huggingface/text-generation-inference#2613]
### System Info

Runtime environment:

```
Target: x86_64-unknown-linux-gnu
Cargo version: 1.79.0
Commit sha: a379d5536bb2de55154dc09c3a1f24ce58cb7df5
Docker label: sha-a379d55-rocm
nvidia-smi:
N/A
xpu-smi:
N/A
```
The full command line used that causes issues: `text-generation-launcher --port 8000 --num-shard 8 --sharded true`
Model being used: `meta-llama/Llama-3.1-405B-Instruct`
Hardware used: `AMD MI300x, 8 nos`
rocm-smi
```
============================================ ROCm System Management Interface ============================================
====================================================== Concise Info ======================================================
Device  Node  IDs              Temp        Power     Partitions          SCLK    MCLK    Fan  Perf  PwrCap  VRAM%  GPU%  
              (DID,     GUID)  (Junction)  (Socket)  (Mem, Compute, ID)                                                  
==========================================================================================================================
0       2     0x74a1,   55354  48.0°C      140.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
1       3     0x74a1,   41632  40.0°C      135.0W    NPS1, SPX, 0        131Mhz  900Mhz  0%   auto  750.0W  0%     0%    
2       4     0x74a1,   47045  44.0°C      136.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
3       5     0x74a1,   60169  48.0°C      144.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
4       6     0x74a1,   56024  46.0°C      138.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
5       7     0x74a1,   705    42.0°C      136.0W    NPS1, SPX, 0        131Mhz  900Mhz  0%   auto  750.0W  0%     0%    
6       8     0x74a1,   59108  51.0°C      144.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
7       9     0x74a1,   10985  43.0°C      137.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
==========================================================================================================================
================================================== End of ROCm SMI Log ===================================================

```

Docker Image Used:`ghcr.io/huggingface/text-generation-inference:sha-a379d55-rocm`

Deployment: Using [dstack](https://dstack.ai/) 

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

1. Use Image:ghcr.io/huggingface/text-generation-inference:sha-a379d55-rocm
2. Set Environment Variables as follows: 

>  ROCM_USE_FLASH_ATTN_V2_TRITON=true

>  TRUST_REMOTE_CODE=true

>  MODEL_ID=meta-llama/Meta-Llama-3.1-405B-Instruct

3. Use command `text-generation-launcher --port 8000 --num-shard 8 --sharded true`

Output:
```
INFO text_generation_launcher: Args {
    model_id: "meta-llama/Llama-3.1-405B-Instruct",
    revision: None,
    validation_workers: 2,
    sharded: Some(
        true,
    ),
    num_shard: Some(
        8,
    ),
    quantize: None,
    speculate: None,
    dtype: None,
    trust_remote_code: true,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: None,
    max_total_tokens: None,
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: None,
    max_batch_total_tokens: None,
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: None,
    hostname: "ENC1-CLS01-SVR13",
    port: 8000,
    shard_uds_path: "/tmp/text-generation-server",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: Some(
        "/data",
    ),
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 1.0,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    otlp_service_name: "text-generation-inference.router",
    cors_allow_origin: [],
    api_key: None,
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: false,
    max_client_batch_size: 4,
    lora_adapters: None,
    usage_stats: On,
}
2024-10-05T15:45:08.650573Z  INFO hf_hub: Token file not found "/root/.cache/huggingface/token"    
2024-10-05T15:45:08.835369Z  INFO text_generation_launcher: Default `max_input_tokens` to 4095
2024-10-05T15:45:08.835389Z  INFO text_generation_launcher: Default `max_total_tokens` to 4096
2024-10-05T15:45:08.835400Z  INFO text_generation_launcher: Default `max_batch_prefill_tokens` to 4145
2024-10-05T15:45:08.835409Z  INFO text_generation_launcher: Using default cuda graphs [1, 2, 4, 8, 16, 32]
2024-10-05T15:45:08.835422Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `meta-llama/Llama-3.1-405B-Instruct` do not contain malicious code.
2024-10-05T15:45:08.835432Z  INFO text_generation_launcher: Sharding model on 8 processes
2024-10-05T15:45:08.835650Z  INFO download: text_generation_launcher: Starting check and download process for meta-llama/Llama-3.1-405B-Instruct
2024-10-05T15:45:11.886526Z  INFO text_generation_launcher: Download file: model-00001-of-00191.safetensors
.....
.....
2024-10-05T15:57:50.354168Z  INFO text_generation_launcher: Download: [191/191] -- ETA: 0
2024-10-05T15:57:51.332740Z  INFO download: text_generation_launcher: Successfully downloaded weights for meta-llama/Llama-3.1-405B-Instruct
2024-10-05T15:57:51.333073Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-10-05T15:57:51.333116Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
.....
....
2024-10-05T15:59:21.578641Z  INFO shard-manager: text_generation_launcher: Shard ready in 90.240321203s rank=7
2024-10-05T15:59:21.581956Z  INFO shard-manager: text_generation_launcher: Shard ready in 90.246451478s rank=3
2024-10-05T15:59:21.592356Z  INFO shard-manager: text_generation_launcher: Shard ready in 90.254550639s rank=6
2024-10-05T15:59:21.634978Z  INFO shard-manager: text_generation_launcher: Shard ready in 90.298778091s rank=2
2024-10-05T15:59:21.648308Z  INFO text_generation_launcher: Starting Webserver
2024-10-05T15:59:21.669533Z  INFO text_generation_router_v3: backends/v3/src/lib.rs:89: Warming up model
2024-10-05T15:59:55.978197Z  INFO text_generation_launcher: PyTorch TunableOp (https://github.com/fxmarty/pytorch/tree/2.3-patched/aten/src/ATen/cuda/tunable) is enabled. The warmup may take several minutes, picking the ROCm optimal matrix multiplication kernel for the target lengths 32, 16, 8, 4, 2, 1, with typical 5-8% latency improvement for small sequence lengths. The picked GEMMs are saved in the file /data/tunableop_meta-llama-Llama-3.1-405B-Instruct_tp8_rank0.csv. To disable TunableOp, please launch TGI with `PYTORCH_TUNABLEOP_ENABLED=0`.
2024-10-05T15:59:55.978266Z  INFO text_generation_launcher: Warming up TunableOp for seqlen=32
2024-10-05T16:01:49.444524Z  INFO text_generation_launcher: Warming up TunableOp for seqlen=16
2024-10-05T16:03:02.205916Z  INFO text_generation_launcher: Warming up TunableOp for seqlen=8
2024-10-05T16:04:17.672054Z  INFO text_generation_launcher: Warming up TunableOp for seqlen=4
2024-10-05T16:05:31.138920Z  INFO text_generation_launcher: Warming up TunableOp for seqlen=2
2024-10-05T16:06:44.725610Z  INFO text_generation_launcher: Warming up TunableOp for seqlen=1
2024-10-05T16:06:53.338427Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
 ...
 
2024-10-05T16:06:53.738797Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 109, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 274, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 120, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 111, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 123, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1177, in warmup
    self.tunableop_warmup(seqlen)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1214, in tunableop_warmup
    self.model.forward(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 556, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 496, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 401, in forward
    mlp_output = self.mlp(normed_attn_res_output, adapter_data)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 329, in forward
    _custom_C.LLMM_Silu(
RuntimeError: CUDA kernel failed : 1
2024-10-05T16:06:53.739391Z ERROR warmup{max_input_length=4095 max_prefill_tokens=4145 max_total_tokens=4096 max_batch_size=None}:warmup: text_generation_router_v3::client: backends/v3/src/client/mod.rs:54: Server error: CANCELLED
2024-10-05T16:06:53.761675Z ERROR warmup{max_input_length=4095 max_prefill_tokens=4145 max_total_tokens=4096 max_batch_size=None}:warmup: text_generation_router_v3::client: backends/v3/src/client/mod.rs:54: Server error: CANCELLED
2024-10-05T16:06:53.785713Z ERROR warmup{max_input_length=4095 max_prefill_tokens=4145 max_total_tokens=4096 max_batch_size=None}:warmup: text_generation_router_v3::client: backends/v3/src/client/mod.rs:54: Server error: CANCELLED
2024-10-05T16:06:53.806908Z ERROR warmup{max_input_length=4095 max_prefill_tokens=4145 max_total_tokens=4096 max_batch_size=None}:warmup: text_generation_router_v3::client: backends/v3/src/client/mod.rs:54: Server error: CANCELLED
2024-10-05T16:06:53.814493Z ERROR warmup{max_input_length=4095 max_prefill_tokens=4145 max_total_tokens=4096 max_batch_size=None}:warmup: text_generation_router_v3::client: backends/v3/src/client/mod.rs:54: Server error: CANCELLED
2024-10-05T16:06:53.883206Z ERROR warmup{max_input_length=4095 max_prefill_tokens=4145 max_total_tokens=4096 max_batch_size=None}:warmup: text_generation_router_v3::client: backends/v3/src/client/mod.rs:54: Server error: CANCELLED
Error: Backend(Warmup(Generation("CANCELLED")))
2024-10-05T16:06:53.931557Z ERROR text_generation_launcher: Webserver Crashed
2024-10-05T16:06:53.931601Z  INFO text_generation_launcher: Shutting down shards
2024-10-05T16:06:53.940379Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=0
2024-10-05T16:06:53.940413Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=4
2024-10-05T16:06:53.942031Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=0
2024-10-05T16:06:53.942342Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=4
2024-10-05T16:06:53.945673Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=2
2024-10-05T16:06:53.947574Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=2
2024-10-05T16:06:53.981199Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=7
2024-10-05T16:06:53.982519Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=7
2024-10-05T16:06:53.995985Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=3
2024-10-05T16:06:53.997562Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=3
2024-10-05T16:06:54.003363Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=1
2024-10-05T16:06:54.004490Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=1
2024-10-05T16:06:54.005049Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=6
2024-10-05T16:06:54.006701Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=6
2024-10-05T16:06:54.017297Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=5
2024-10-05T16:06:54.018644Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=5
2024-10-05T16:06:54.745412Z  INFO shard-manager: text_generation_launcher: shard terminated rank=0
2024-10-05T16:06:54.745427Z  INFO shard-manager: text_generation_launcher: shard terminated rank=4
2024-10-05T16:06:54.784348Z  INFO shard-manager: text_generation_launcher: shard terminated rank=7
2024-10-05T16:06:54.805009Z  INFO shard-manager: text_generation_launcher: shard terminated rank=1
2024-10-05T16:06:54.807276Z  INFO shard-manager: text_generation_launcher: shard terminated rank=6
2024-10-05T16:06:54.848181Z  INFO shard-manager: text_generation_launcher: shard terminated rank=2
2024-10-05T16:06:54.898173Z  INFO shard-manager: text_generation_launcher: shard terminated rank=3
2024-10-05T16:06:54.919214Z  INFO shard-manager: text_generation_launcher: shard terminated rank=5
Error: WebserverFailed

```

### Expected behavior

Webserver runs

**Comment by mht-sharma** [comment]
Fixed in https://github.com/huggingface/text-generation-inference/pull/2579
