### ISSUE TITLE
ModuleNotFoundError: No module named 'jmespath'

### ISSUE THREAD

**Issue by cswaney** [huggingface/text-generation-inference#2669]
### System Info

Image: `ghcr.io/huggingface/text-generation-inference:2.3.0`
  - Arch: `amd64`
  - Revision: `169178b937d0c4173b0fdcd6bf10a858cfe4f428`

Model: `meta-llama/Llama-3.2-1B`
  - Revision: `221e3535e1ac4840bdf061a12b634139c84e144c`

Hardware:
  - Nvidia A100

Deployment:
  - Offline HPC (Slurm)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

With internet connected, run:
```
apptainer pull docker://ghcr.io/huggingface/text-generation-inference:2.3.0
```

Make sure that model files have been downloaded from Hugging Face. Then, with internet disconnected, run:
```
apptainer instance run --nv \
  --bind $HOME/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B:/data \
  text-generation-inference_2.3.0.sif \
  tgi-test \
  --model-id /data/snapshots/221e3535e1ac4840bdf061a12b634139c84e144c \
  --port 8080 \
```

Check the logs:
```
unable to refresh ld cache, not a big deal in most cases
2024-10-18T15:28:43.361348Z  INFO text_generation_launcher: Args {
    model_id: "/data/snapshots/221e3535e1ac4840bdf061a12b634139c84e144c",
    revision: None,
    validation_workers: 2,
    sharded: None,
    num_shard: None,
    quantize: None,
    speculate: None,
    dtype: None,
    trust_remote_code: false,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: None,
    max_total_tokens: None,
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: None,
    max_batch_total_tokens: None,
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: None,
    hostname: "della8.princeton.edu",
    port: 8080,
    shard_uds_path: "/tmp/text-generation-server",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: None,
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 1.0,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    otlp_service_name: "text-generation-inference.router",
    cors_allow_origin: [],
    api_key: None,
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: false,
    max_client_batch_size: 4,
    lora_adapters: None,
    usage_stats: On,
}
2024-10-18T15:28:43.367127Z  INFO text_generation_launcher: Model supports
 up to 131072 but tgi will now set its default to 4096 instead. This is to save VRAM by refusing la
rge prompts in order to allow more users on the same hardware. You can increase that size using `--
max-batch-prefill-tokens=131122 --max-total-tokens=131072 --max-input-tokens=131071`.
2024-10-18T15:28:43.367137Z  INFO text_generation_launcher: Using attentio
n flashinfer - Prefix caching true
2024-10-18T15:28:43.367144Z  INFO text_generation_launcher: Default `max_i
nput_tokens` to 4095
2024-10-18T15:28:43.367146Z  INFO text_generation_launcher: Default `max_t
otal_tokens` to 4096
2024-10-18T15:28:43.367154Z  INFO text_generation_launcher: Default `max_b
atch_prefill_tokens` to 4145
2024-10-18T15:28:43.367157Z  INFO text_generation_launcher: Using default 
cuda graphs [1, 2, 4, 8, 16, 32]
2024-10-18T15:28:43.367266Z  INFO download: text_generation_launcher:
 Starting check and download process for /data/snapshots/221e3535e1ac4840bdf061a12b634139c84e144c
2024-10-18T15:28:48.847863Z ERROR download: text_generation_launcher:
 Download encountered an error: 
2024-10-18 11:28:46.629 | INFO     | text_generation_server.utils.import_utils:<module>:75 - Detect
ed system cuda
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 5, in <module>
    from text_generation_server.cli import app
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/cli.py", line 10, in <module
>
    from text_generation_server.utils.adapter import parse_lora_adapters
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/utils/__init__.py", line 4, 
in <module>
    from text_generation_server.utils.peft import download_and_unload_peft
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/utils/peft.py", line 7, in <
module>
    from peft import AutoPeftModelForCausalLM, AutoPeftModelForSeq2SeqLM
  File "/opt/conda/lib/python3.11/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/opt/conda/lib/python3.11/site-packages/peft/auto.py", line 31, in <module>
    from .config import PeftConfig
  File "/opt/conda/lib/python3.11/site-packages/peft/config.py", line 23, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "/opt/conda/lib/python3.11/site-packages/peft/utils/__init__.py", line 23, in <module>
    from .other import (
  File "/opt/conda/lib/python3.11/site-packages/peft/utils/other.py", line 21, in <module>
    import accelerate
  File "/opt/conda/lib/python3.11/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/opt/conda/lib/python3.11/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, s
ave_custom_state
  File "/opt/conda/lib/python3.11/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/opt/conda/lib/python3.11/site-packages/accelerate/utils/__init__.py", line 177, in <module
>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/opt/conda/lib/python3.11/site-packages/accelerate/utils/bnb.py", line 29, in <module>
    from ..big_modeling import dispatch_model, init_empty_weights
  File "/opt/conda/lib/python3.11/site-packages/accelerate/big_modeling.py", line 24, in <module>
    from .hooks import (
  File "/opt/conda/lib/python3.11/site-packages/accelerate/hooks.py", line 30, in <module>
    from .utils.other import recursive_getattr
  File "/opt/conda/lib/python3.11/site-packages/accelerate/utils/other.py", line 29, in <module>
    from ..commands.config.default import write_basic_config  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/accelerate/commands/config/__init__.py", line 19, i
n <module>
    from .config import config_command_parser
  File "/opt/conda/lib/python3.11/site-packages/accelerate/commands/config/config.py", line 25, in 
<module>
    from .sagemaker import get_sagemaker_input
  File "/opt/conda/lib/python3.11/site-packages/accelerate/commands/config/sagemaker.py", line 35, 
in <module>
    import boto3  # noqa: F401
    ^^^^^^^^^^^^
  File "/home/ddss/.local/lib/python3.11/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/ddss/.local/lib/python3.11/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/ddss/.local/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/ddss/.local/lib/python3.11/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/ddss/.local/lib/python3.11/site-packages/botocore/waiter.py", line 16, in <module>
    import jmespath
ModuleNotFoundError: No module named 'jmespath'
```

### Expected behavior

Server starts successfully.

**Comment by cswaney** [comment]
Solved. Apptainer automatically mounts `$HOME`, which happened to have `boto3` installed.
