### ISSUE TITLE
Triton Error [CUDA]

### ISSUE THREAD

**Issue by paulcx** [huggingface/text-generation-inference#2776]
### System Info

docker version: ghcr.io/huggingface/text-generation-inference:sha-d2ed52f
model: Qwen2.5-1.5B-Instruct (tested on Qwen2.5-32B-Instruct as well)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

[2m2024-11-25T00:40:00.676287Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Args {
    model_id: "/data/Qwen2.5-1.5B-Instruct",
    revision: None,
    validation_workers: 2,
    sharded: None,
    num_shard: None,
    quantize: None,
    speculate: None,
    dtype: None,
    kv_cache_dtype: None,
    trust_remote_code: false,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: None,
    max_total_tokens: Some(
        4096,
    ),
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: None,
    max_batch_total_tokens: None,
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: None,
    hostname: "b9f3e9de148d",
    port: 9096,
    shard_uds_path: "/tmp/text-generation-server",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: None,
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 1.0,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    otlp_service_name: "text-generation-inference.router",
    cors_allow_origin: [],
    api_key: None,
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: false,
    max_client_batch_size: 4,
    lora_adapters: None,
    usage_stats: On,
    payload_limit: 2000000,
}
[2m2024-11-25T00:40:03.256866Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Using attention flashinfer - Prefix caching true
[2m2024-11-25T00:40:03.256899Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Default `max_batch_prefill_tokens` to 4096
[2m2024-11-25T00:40:03.256907Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Using default cuda graphs [1, 2, 4, 8, 16, 32]
[2m2024-11-25T00:40:03.257124Z[0m [32m INFO[0m [1mdownload[0m: [2mtext_generation_launcher[0m[2m:[0m Starting check and download process for /data/Qwen2.5-1.5B-Instruct
[2m2024-11-25T00:40:08.600662Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Files are already present on the host. Skipping download.
[2m2024-11-25T00:40:09.300122Z[0m [32m INFO[0m [1mdownload[0m: [2mtext_generation_launcher[0m[2m:[0m Successfully downloaded weights for /data/Qwen2.5-1.5B-Instruct
[2m2024-11-25T00:40:09.300502Z[0m [32m INFO[0m [1mshard-manager[0m: [2mtext_generation_launcher[0m[2m:[0m Starting shard [2m[3mrank[0m[2m=[0m0[0m
[2m2024-11-25T00:40:13.669264Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Using prefix caching = True
[2m2024-11-25T00:40:13.669313Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Using Attention = flashinfer
[2m2024-11-25T00:40:19.332116Z[0m [32m INFO[0m [1mshard-manager[0m: [2mtext_generation_launcher[0m[2m:[0m Waiting for shard to be ready... [2m[3mrank[0m[2m=[0m0[0m
[2m2024-11-25T00:40:20.030204Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Using experimental prefill chunking = False
[2m2024-11-25T00:40:20.162799Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Server started at unix:///tmp/text-generation-server-0
[2m2024-11-25T00:40:20.232856Z[0m [32m INFO[0m [1mshard-manager[0m: [2mtext_generation_launcher[0m[2m:[0m Shard ready in 10.908165895s [2m[3mrank[0m[2m=[0m0[0m
[2m2024-11-25T00:40:20.307718Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Starting Webserver
[2m2024-11-25T00:40:20.437441Z[0m [32m INFO[0m [2mtext_generation_router_v3[0m[2m:[0m [2mbackends/v3/src/lib.rs[0m[2m:[0m[2m125:[0m Warming up model
[2m2024-11-25T00:40:20.485532Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Using optimized Triton indexing kernels.
[2m2024-11-25T00:40:23.480722Z[0m [31mERROR[0m [2mtext_generation_launcher[0m[2m:[0m Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/cli.py", line 117, in serve
    server.serve(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/server.py", line 315, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/opt/conda/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.11/site-packages/text_generation_server/interceptor.py", line 24, in intercept
    return await response
  File "/opt/conda/lib/python3.11/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 120, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.11/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 111, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/server.py", line 144, in Warmup
    self.model.warmup(batch, max_input_tokens, max_total_tokens)
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/models/flash_causal_lm.py", line 1540, in warmup
    _, _batch, _ = self.generate_token(batch)
  File "/opt/conda/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/models/flash_causal_lm.py", line 1909, in generate_token
    out, speculative_logits = self.forward(batch, adapter_data)
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/models/flash_causal_lm.py", line 1783, in forward
    block_tables = block_tables_to_ragged(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/models/metadata_kernels.py", line 80, in block_tables_to_ragged
    triton_block_tables_to_ragged[grid](
  File "/opt/conda/lib/python3.11/site-packages/triton/runtime/jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/triton/runtime/jit.py", line 691, in run
    kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata, launch_metadata,
  File "/opt/conda/lib/python3.11/site-packages/triton/compiler/compiler.py", line 381, in __getattribute__
    self._init_handles()
  File "/opt/conda/lib/python3.11/site-packages/triton/compiler/compiler.py", line 376, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.active.utils.load_binary(
RuntimeError: Triton Error [CUDA]: device-side assert triggered
[2m2024-11-25T00:40:23.481245Z[0m [31mERROR[0m [1mwarmup[0m[1m{[0m[3mmax_input_length[0m[2m=[0mNone [3mmax_prefill_tokens[0m[2m=[0m4096 [3mmax_total_tokens[0m[2m=[0mSome(4096) [3mmax_batch_size[0m[2m=[0mNone[1m}[0m[2m:[0m[1mwarmup[0m[2m:[0m [2mtext_generation_router_v3::client[0m[2m:[0m [2mbackends/v3/src/client/mod.rs[0m[2m:[0m[2m45:[0m Server error: Triton Error [CUDA]: device-side assert triggered
Error: Backend(Warmup(Generation("Triton Error [CUDA]: device-side assert triggered")))
[2m2024-11-25T00:40:23.512842Z[0m [31mERROR[0m [2mtext_generation_launcher[0m[2m:[0m Webserver Crashed
[2m2024-11-25T00:40:23.512876Z[0m [32m INFO[0m [2mtext_generation_launcher[0m[2m:[0m Shutting down shards
[2m2024-11-25T00:40:23.535487Z[0m [32m INFO[0m [1mshard-manager[0m: [2mtext_generation_launcher[0m[2m:[0m Terminating shard [2m[3mrank[0m[2m=[0m0[0m
[2m2024-11-25T00:40:23.536831Z[0m [32m INFO[0m [1mshard-manager[0m: [2mtext_generation_launcher[0m[2m:[0m Waiting for shard to gracefully shutdown [2m[3mrank[0m[2m=[0m0[0m
[2m2024-11-25T00:40:23.837105Z[0m [32m INFO[0m [1mshard-manager[0m: [2mtext_generation_launcher[0m[2m:[0m shard terminated [2m[3mrank[0m[2m=[0m0[0m

### Expected behavior

What caused this error of Triton Error [CUDA] and how to fix it?

**Comment by OlivierDehaene** [comment]
Can you dump your `nvidia-smi`?

**Comment by paulcx** [comment]
> Can you dump your `nvidia-smi`?

| GPU   | Name           | Persistence-M | Bus-Id              | Disp.A | Volatile Uncorr. ECC | GPU-Util | Compute M. | MIG M. |
|-------|----------------|---------------|---------------------|--------|-----------------------|----------|------------|--------|
|       |                |               |                     |        |                       |          |            |        |
| 0     | NVIDIA RTX A6000 | On           | 00000000:35:00.0   | Off    | Off                   | 0%       | Default    | N/A    |

| Fan | Temp | Perf | Pwr:Usage/Cap | Memory-Usage         |
|-----|------|------|---------------|----------------------|
| 30% | 31C  | P8   | 24W / 300W    | 44977MiB / 49140MiB |

**Comment by Eva-Music** [comment]
Can you show your docker command? I have the similar issue, but with Qwen2.5-7B-Instruct

**Comment by paulcx** [comment]
After removing --max-total-tokens 4096 from the docker command line and getting it to work again, what's going on with new update?  @OlivierDehaene

**Comment by edwardzjl** [comment]
> After removing `--max-total-tokens 4096` from the docker command line and getting it to work again, what's going on with new update? @OlivierDehaene
> 
> Additionally, I noticed that in the recently released image v3.0, when I remove the `--max-total-tokens 4096` option, the Maximum input tokens defaults to 102638, which is quite remarkable. How is this achieved with the same vram?

This works, removing `--max-total-tokens` and my server starts. Thanks!
