### ISSUE TITLE
Unable to find NVIDIA device driver running on Kubernetes

### ISSUE THREAD

**Issue by tgaddair** [huggingface/text-generation-inference#291]
### System Info

When running on Kubernetes using the latest image and attempting to run through the tutorial with bloom-560m, it looks like PyTorch is unable to detect the GPU.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

Create a simple deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-inference-deployment
  labels:
    app: text-generation-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-generation-inference
  template:
    metadata:
      labels:
        app: text-generation-inference
    spec:
      containers:
      - name: text-generation-inference
        image: ghcr.io/huggingface/text-generation-inference:latest
        args: ["--model-id", "bigscience/bloom-560m", "--num-shard", "1"]
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "5"
            ephemeral-storage: 100Gi
            memory: 27360Mi
            nvidia.com/gpu: "1"
          requests:
            cpu: "5"
            ephemeral-storage: 100Gi
            memory: 27360Mi
            nvidia.com/gpu: "1"
      volumes:
      - name: shm
        emptyDir:
         medium: Memory
         sizeLimit: 1Gi
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
```

Attempting to run inference will fail, as GPUs are unavailable:

```
$ curl 127.0.0.1:8080/generate \                                                  
    -X POST \   
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17}}' \
    -H 'Content-Type: application/json'
{"error":"Request failed during generation: Server error: attention_scores_2d must be a CUDA tensor","error_type":"generation"}
```

Stack trace from the logs:

```
File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 20, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 63, in Prefill
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 516, in generate_token
    logits, past = self.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 500, in forward
    outputs = self.model.forward(
  File "/usr/src/transformers/src/transformers/models/bloom/modeling_bloom.py", line 956, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/src/transformers/src/transformers/models/bloom/modeling_bloom.py", line 816, in forward
    outputs = block(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/src/transformers/src/transformers/models/bloom/modeling_bloom.py", line 456, in forward
    attn_outputs = self.self_attention(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/src/transformers/src/transformers/models/bloom/modeling_bloom.py", line 337, in forward
    context_layer, present, attention_probs = fused_bloom_attention_cuda.forward(
RuntimeError: attention_scores_2d must be a CUDA tensor
```

SSHing into the pod, you can see that the installed version of PyTorch is unable to find the GPU device:

```
$ kubectl exec -it text-generation-inference-deployment-98974cc65-dc544 -- /bin/bash
root@text-generation-inference-deployment-98974cc65-dc544:/usr/src# python -c "import torch; torch.tensor([1]).cuda()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

`nvidia-smi` shows the device, but no CUDA version:

```
$ nvidia-smi
Sat May  6 19:04:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   25C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

If I instead run this deployment using nvidia's cuda 11.8 runtime image as a base, there are no issues, so I suspect it may be some incompatibility between this custom image and perhaps the [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin). This is running on an EKS cluster with Kubernetes v1.23.

### Expected behavior

The inference request should have succeeded, and the GPU device should be visible when running on Kubernetes.

**Comment by OlivierDehaene** [comment]
Your nvidia driver is extremely old (almost 2 years old?). Can you try with a more recent AMI?
We are running on eks in our prod.
Nevertheless I will look into why the official nvidia image works.

**Comment by tgaddair** [comment]
Hi @OlivierDehaene, thanks for looking into this.

To give you a little more context on this issue: the reason we were using this AMI is that it's the latest official GPU AMI provided by EKS (`amazon/amazon-eks-gpu-node-1.24-v20230501`). We're now in the process of building a custom AMI for exactly this reason, but since this is the default in EKS, I think it's likely a lot of other users will run into the same issue (and the driver version is [officially supported](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) for CUDA 11.8, so it should work in theory).

I did try running on a different k8s cluster (not EKS, microk8s) with newer drivers, but ran into a different issue during model initialization that causes the pod to crash loop:

```
2023-05-06T22:06:37.389530Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 120, in get_model
    return BLOOM(model_id, revision, quantize=quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/bloom.py", line 53, in __init__
    super(BLOOM, self).__init__(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 466, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
  File "/usr/src/transformers/src/transformers/models/auto/auto_factory.py", line 468, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/src/transformers/src/transformers/modeling_utils.py", line 2729, in from_pretrained
    max_memory = get_balanced_memory(
  File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 361, in get_balanced_memory
    max_memory = get_max_memory(max_memory)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 286, in get_max_memory
    _ = torch.tensor([0], device=i)
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Here's the `nvidia-smi` result in this container:

```
$ nvidia-smi
Sat May  6 22:09:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A5000    On   | 00000000:A1:00.0 Off |                  Off |
| 30%   32C    P8    17W / 230W |      1MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

As you can see, it's picking up CUDA 11.6 instead of N/A, which seems consistent with the new error message (can find drivers, but library versions are incompatible). Hope that helps.

**Comment by noyoshi** [comment]
Hi @OlivierDehaene! I did some more investigation done around this. 

Tried getting this to work in a GKE cluster, which has newer NVIDIA drivers than EKS. 

Using the same deployment that @tgaddair posted earlier, I was able to start the pod, but again, I encountered the same errors: 

```
root@noah-text-generation-inference-deployment-7fcdfc9dfb-pz8gj:/usr/local/nvidia/bin# curl 127.0.0.1:80/generate -X POST -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17}}'  -H 'Content-Type: application/json'
{"error":"Request failed during generation: Server error: attention_scores_2d must be a CUDA tensor","error_type":"generation"}root@noah-text-generation-inference-deployment-7fcdfc9dfb-pz8gj:/usr/local/nvidia/bin#
```

I then checked the CUDA version that python was picking up - 
```
>>> print(torch.version.cuda)
11.8
>>>
```

Which seems fine, however, checking nvidia-smi still showed 
```
root@noah-text-generation-inference-deployment-7fcdfc9dfb-pz8gj:/usr/local/nvidia/bin# LD_PRELOAD=/usr/local/nvidia/lib64/libnvidia-ml.so ./nvidia-smi
Mon May  8 20:01:26 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P0    45W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Looks like this is using the much newer driver version `525.60.13`. 

Do you happen to know the nvidia driver version installed on your prod nodes, or any other details around this AMI? Thanks!

**Comment by tgaddair** [comment]
Rolling back to the `v0.5.0` image (which uses nvidia 11.8 runtime as a base) worked successfully on `g5` aws instance in EKS.

**Comment by OlivierDehaene** [comment]
It seems that the NVIDIA env vars were not added to the correct docker target...
#297 should have fixed the issue. 
Can you try with this image and tell me if the issue persists? Thanks!

**Comment by OlivierDehaene** [comment]
It seems that the NVIDIA env vars were not added to the correct docker target...
#297 should have fixed the issue.
Can you try this docker image and tell me if the problem persists? Thanks!
ghcr.io/huggingface/text-generation-inference:sha-e9b01b3

**Comment by tgaddair** [comment]
Thanks for following up @OlivierDehaene! I tried out the image, but it looks like there's still an issue that occurs during container initialization:

```
Normal   Pulled     6s (x2 over 24s)  kubelet  Container image "ghcr.io/huggingface/text-generation-inference:sha-e9b01b3" already present on machine
  Warning  Failed     6s                kubelet  Error: failed to create containerd task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=GPU-952cbbbe-9e9c-ab17-d849-a8f5561968e7,GPU-39141a84-a78c-2053-a839-367821e0b978 --compute --utility --require=cuda>=11.8 --pid=33590 /run/containerd/io.containerd.runtime.v1.linux/k8s.io/text-generation-inference/rootfs]
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.8, please update your driver to a newer version, or use an earlier cuda container: unknown
  Warning  BackOff  5s (x4 over 23s)  kubelet  Back-off restarting failed container
```

I'm guessing CUDA isn't detected in the environment despite it having been installed via conda.

**Comment by OlivierDehaene** [comment]
No this is an error from the nvidia container runtime.
See [this](https://github.com/NVIDIA/nvidia-container-runtime):

> NVIDIA_REQUIRE_CUDA
> The version of the CUDA toolkit used by the container. If the version of the NVIDIA driver is insufficient to run this version of CUDA, the container will not be started.

**Comment by OlivierDehaene** [comment]
...
I want to go full linus torvalds

**Comment by tgaddair** [comment]
@OlivierDehaene good news is that when we tested this in our cluster with newer device drivers, it did finally work, so looks like at this point the problem is legitimately that the drivers are too old.

```
root@text-generation-inference-deployment-57b5884fdd-dt4n9:/usr/src# nvidia-smi
Tue May  9 17:49:18 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    51W / 400W |   2269MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

```
curl 127.0.0.1:80/generate -X POST -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17}}' -H 'Content-Type: application/json'
{"generated_text":" Deep learning is a new type of machine learning that is used in many different fields,"}
```

Happy to close out this issue if you're fine with requiring newer device drivers. Might be worth calling this out in the README for other folks in the future.

**Comment by sam-h-bean** [comment]
I found that using the Bottlerocket OS was the way to go to run modern ML workloads on GPU.

**Comment by paulcx** [comment]
I have a question that which cuda is used in container? the host one or cuda builded in container itself?

**Comment by OlivierDehaene** [comment]
The cuda shipped with the image.
However it requires the host nvidia drivers to be compatible with this cuda version.

@tgaddair, sorry to bother you again but if you have the time, can you try sha-a6c18c3?

**Comment by paulcx** [comment]
After I updated image from sha-593a563 to sha-a6c18c3, all response seems to be incorrect like:
```
data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

```

**Comment by tgaddair** [comment]
Hi @OlivierDehaene, not a bother at all, thanks for continuing to look into this!

I tried out this latest image with the older nodes, and am now getting a different error during container initialization:

```
2023-05-12T04:34:00.336770Z ERROR text_generation_launcher: Shard 0 failed to start:
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 120, in get_model
    return BLOOM(model_id, revision, quantize=quantize)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/bloom.py", line 53, in __init__
    super(BLOOM, self).__init__(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 466, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(

  File "/usr/src/transformers/src/transformers/models/auto/auto_factory.py", line 468, in from_pretrained
    return model_class.from_pretrained(

  File "/usr/src/transformers/src/transformers/modeling_utils.py", line 2729, in from_pretrained
    max_memory = get_balanced_memory(

  File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 361, in get_balanced_memory
    max_memory = get_max_memory(max_memory)

  File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 286, in get_max_memory
    _ = torch.tensor([0], device=i)
Error: ShardCannotStart

RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by paulcx** [comment]
> Hi @OlivierDehaene, not a bother at all, thanks for continuing to look into this!
> 
> 
> 
> I tried out this latest image with the older nodes, and am now getting a different error during container initialization:
> 
> 
> 
> ```
> 
> 2023-05-12T04:34:00.336770Z ERROR text_generation_launcher: Shard 0 failed to start:
> 
> Traceback (most recent call last):
> 
> 
> 
>   File "/opt/conda/bin/text-generation-server", line 8, in <module>
> 
>     sys.exit(app())
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
> 
>     server.serve(model_id, revision, sharded, quantize, uds_path)
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
> 
>     asyncio.run(serve_inner(model_id, revision, sharded, quantize))
> 
> 
> 
>   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
> 
>     return loop.run_until_complete(main)
> 
> 
> 
>   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
> 
>     return future.result()
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
> 
>     model = get_model(model_id, revision, sharded, quantize)
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 120, in get_model
> 
>     return BLOOM(model_id, revision, quantize=quantize)
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/bloom.py", line 53, in __init__
> 
>     super(BLOOM, self).__init__(
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 466, in __init__
> 
>     self.model = AutoModelForCausalLM.from_pretrained(
> 
> 
> 
>   File "/usr/src/transformers/src/transformers/models/auto/auto_factory.py", line 468, in from_pretrained
> 
>     return model_class.from_pretrained(
> 
> 
> 
>   File "/usr/src/transformers/src/transformers/modeling_utils.py", line 2729, in from_pretrained
> 
>     max_memory = get_balanced_memory(
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 361, in get_balanced_memory
> 
>     max_memory = get_max_memory(max_memory)
> 
> 
> 
>   File "/opt/conda/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 286, in get_max_memory
> 
>     _ = torch.tensor([0], device=i)
> 
> Error: ShardCannotStart
> 
> 
> 
> RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
> 
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> 
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> 
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> ```

try use disable custom kernel parameter at starting container? It seems the old gpu is not supported for these cuda kernels.

**Comment by OlivierDehaene** [comment]
I reverted to using nvidia/cuda:11.8.0-base-ubuntu20.04 as a base image. If the problem persists, feel free to post it and I will re-open.

**Comment by vvsotnikov** [comment]
I'm having this problem with image `ghcr.io/huggingface/text-generation-inference:sha-d31562f` (aka 0.7.0) and launch parameters `"--model-id", "ehartford/WizardLM-7B-Uncensored", "--max-total-tokens", "2048", "--port", "8001"`
