### ISSUE TITLE
Inference issue data:{"error":"Request failed during generation: Server error: tensors used as indices must be long, byte or bool tensors","error_type":"generation"}

### ISSUE THREAD

**Issue by NoJster** [huggingface/text-generation-inference#369]
### System Info

The error as specified in the title occurs with various nvidia/cuda configurations 530/12.1 530/11.8 470/11.4 etc. and with various version of pythia (sft-1 and sft-4) and starcoder. It does not occur with bloomz-7b1.

Querying with curl

`curl 127.0.0.1:8080/generate_stream -X POST -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17}}' -H 'Content-Type: application/json'`

Tried downloading/updating weights, pulled models from HF from scratch, makes no difference.

Any pointers would be highly appreciated!

*****************************************************************************************
OS: Ubuntu 22.04 LTS (applies equally to 20.04 LTS)

== text_generation_launcher: Runtime environment: ==
Target: x86_64-unknown-linux-gnu
Cargo version: 1.65.0
Commit sha: d31562f300ee8cd44b3ead667a9f260d6a762f7a
Docker label: N/A
nvidia-smi:
Thu May 25 12:18:29 2023
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |

== model being used ==
{
  "model_id": "OpenAssistant/oasst-sft-1-pythia-12b",
  "model_sha": "293df535fe7711a5726987fc2f17dfc87de452a1",
  "model_dtype": "torch.float16",
  "model_device_type": "cuda",
  "model_pipeline_tag": "text-generation",
  "max_concurrent_requests": 128,
  "max_best_of": 2,
  "max_stop_sequences": 4,
  "max_input_length": 1000,
  "max_total_tokens": 1512,
  "waiting_served_ratio": 1.2,
  "max_batch_total_tokens": 32000,
  "max_waiting_tokens": 20,
  "validation_workers": 2,
  "version": "0.7.0",
  "sha": "d31562f300ee8cd44b3ead667a9f260d6a762f7a",
  "docker_label": null
}

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

`curl 127.0.0.1:8080/generate_stream -X POST -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17}}' -H 'Content-Type: application/json'`

### Expected behavior

An answer, rather than an error (:

**Comment by danny980521** [comment]
I had encountered the same issue with `llama` as well. There is no problem when `max_new_tokens` is set to 1, but the issue occurs when it's set to >=2.
cc: @OlivierDehaene

**Comment by OlivierDehaene** [comment]
@danny980521, do you encounter the issue with the docker image? or using a local install?
On a sidenote, please do not tag us directly. We already receive enough notifications :)

**Comment by OlivierDehaene** [comment]
Can one of you provide the full stack trace?

**Comment by danny980521** [comment]
I apologize for directly tagging you. I encountered the issue with a local installation.
And here is my full stack trace.
```
Traceback (most recent call last):
  File "/data/private/text-generation-inference/run_server.py", line 4, in <module>
    response = client.generate("hello!!", max_new_tokens=2, truncate=5)
  File "/opt/conda/envs/eval/lib/python3.8/site-packages/text_generation/client.py", line 145, in generate
    raise parse_error(resp.status_code, payload)
text_generation.errors.GenerationError: Request failed during generation: Server error: tensors used as indices must be long, byte or bool tensors
```

**Comment by OlivierDehaene** [comment]
Do you also have the stack from the server?

**Comment by danny980521** [comment]
here is the full stack from the server.
```
2023-05-26T11:10:03.269106Z ERROR shard-manager: text_generation_launcher: Method Decode encountered an error.                                                                                    
Traceback (most recent call last):                                                                                                                                                                
  File "/opt/conda/envs/tgi/bin/text-generation-server", line 8, in <module>                                                                                                                      
    sys.exit(app())                                                                                                                                                                               
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__                                                                                                     
    return get_command(self)(*args, **kwargs)                                                                                                                                                     
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1130, in __call__                                                                                                    
    return self.main(*args, **kwargs)                                                                                                                                                             
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main                                                                                                         
    return _main(                                                                                                                                                                                 
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main                                                                                                        
    rv = self.invoke(ctx)                                                                                                                                                                         
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1657, in invoke                                                                                                      
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/cli.py", line 67, in serve
    server.serve(model_id, revision, sharded, quantize, trust_remote_code, uds_path)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 157, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize, trust_remote_code))
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/interceptor.py", line 20, in intercept
    return await response
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 90, in Decode
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/envs/tgi/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 473, in generate_token
    out, present = self.forward(
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 448, in forward
    return self.model.forward(
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 444, in forward
    hidden_states, present = self.model(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 392, in forward
    hidden_states, residual = layer(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 273, in forward
    attn_output = self.self_attn(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 168, in forward
    layer_past[layer_past_present_indices] = qkv_rot[:, 1:]
IndexError: tensors used as indices must be long, byte or bool tensors
 rank=2
2023-05-26T11:10:03.269236Z ERROR shard-manager: text_generation_launcher: Method Decode encountered an error.
Traceback (most recent call last):
  File "/opt/conda/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/cli.py", line 67, in serve
    server.serve(model_id, revision, sharded, quantize, trust_remote_code, uds_path)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 157, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize, trust_remote_code))
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/interceptor.py", line 20, in intercept
    return await response
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 90, in Decode
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/envs/tgi/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 473, in generate_token
    out, present = self.forward(
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 448, in forward
    return self.model.forward(
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 444, in forward
    hidden_states, present = self.model(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 392, in forward
    hidden_states, residual = layer(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 273, in forward
    attn_output = self.self_attn(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 168, in forward
    layer_past[layer_past_present_indices] = qkv_rot[:, 1:]
IndexError: tensors used as indices must be long, byte or bool tensors
 rank=3
2023-05-26T11:10:03.269136Z ERROR shard-manager: text_generation_launcher: Method Decode encountered an error.
Traceback (most recent call last):
  File "/opt/conda/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/cli.py", line 67, in serve
    server.serve(model_id, revision, sharded, quantize, trust_remote_code, uds_path)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 157, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize, trust_remote_code))
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/interceptor.py", line 20, in intercept
    return await response
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 90, in Decode
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/envs/tgi/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 473, in generate_token
    out, present = self.forward(
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 448, in forward
    return self.model.forward(                                                                                                                                                                    
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 444, in forward                              
    hidden_states, present = self.model(                                                                                                                                                          
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                                                     
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 392, in forward
    hidden_states, residual = layer(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 273, in forward
    attn_output = self.self_attn(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 168, in forward
    layer_past[layer_past_present_indices] = qkv_rot[:, 1:]
IndexError: tensors used as indices must be long, byte or bool tensors
 rank=1
2023-05-26T11:10:03.269252Z ERROR batch{batch_size=1}:decode:decode{size=1}:decode{size=1}: text_generation_client: router/client/src/lib.rs:33: Server error: tensors used as indices must be lon
g, byte or bool tensors
2023-05-26T11:10:03.269341Z ERROR batch{batch_size=1}:decode:decode{size=1}:decode{size=1}: text_generation_client: router/client/src/lib.rs:33: Server error: tensors used as indices must be lon
g, byte or bool tensors
2023-05-26T11:10:03.269380Z ERROR batch{batch_size=1}:decode:decode{size=1}:decode{size=1}: text_generation_client: router/client/src/lib.rs:33: Server error: tensors used as indices must be lon
g, byte or bool tensors
2023-05-26T11:10:03.269463Z ERROR batch{batch_size=1}:decode:decode{size=1}:decode{size=1}: text_generation_client: router/client/src/lib.rs:33: Server error: tensors used as indices must be lon
g, byte or bool tensors
2023-05-26T11:10:03.269386Z ERROR shard-manager: text_generation_launcher: Method Decode encountered an error.
Traceback (most recent call last):
  File "/opt/conda/envs/tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/cli.py", line 67, in serve
    server.serve(model_id, revision, sharded, quantize, trust_remote_code, uds_path)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 157, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize, trust_remote_code))
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/envs/tgi/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/interceptor.py", line 20, in intercept
    return await response
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/server.py", line 90, in Decode
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/envs/tgi/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 473, in generate_token
    out, present = self.forward(
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/flash_causal_lm.py", line 448, in forward
    return self.model.forward(
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 444, in forward
    hidden_states, present = self.model(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 392, in forward
    hidden_states, residual = layer(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 273, in forward
    attn_output = self.self_attn(
  File "/opt/conda/envs/tgi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/broca-inference2/text-generation-inference/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 168, in forward
    layer_past[layer_past_present_indices] = qkv_rot[:, 1:]
IndexError: tensors used as indices must be long, byte or bool tensors
 rank=0
2023-05-26T11:10:03.270062Z ERROR HTTP request{otel.name=POST / http.client_ip= http.flavor=1.1 http.host=gpu-cloud-anode44.dakao.io:21118 http.method=POST http.route=/ http.scheme=HTTP http.tar
get=/ http.user_agent=python-requests/2.28.2 otel.kind=server trace_id=99104e8ccb878ae59ff93f9fc46a9c9a}:compat_generate{default_return_full_text=Extension(false)}:generate{parameters=GeneratePa
rameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: 2, return_full_text: Some(false), stop: [], tr
uncate: Some(5), watermark: false, details: true, seed: None }}:generate{request=GenerateRequest { inputs: "hello!!", parameters: GenerateParameters { best_of: None, temperature: None, repetitio
n_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: 2, return_full_text: Some(false), stop: [], truncate: Some(5), watermark: false, details: true, seed
: None } }}:generate_stream{request=GenerateRequest { inputs: "hello!!", parameters: GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, ty
pical_p: None, do_sample: false, max_new_tokens: 2, return_full_text: Some(false), stop: [], truncate: Some(5), watermark: false, details: true, seed: None } }}:infer:send_error: text_generation
_router::infer: router/src/infer.rs:533: Request failed during generation: Server error: tensors used as indices must be long, byte or bool tensors
```

**Comment by njhill** [comment]
I also hit this error in the past. There's just one cast to `long` needed in each of the flash modeling impls.

i.e. change [this](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py#L374) line from
```python
layer_past_present_indices = cu_seqlens[1:] - 1
````
to
```python
layer_past_present_indices = (cu_seqlens[1:] - 1).long()
```


I think it's a pytorch 1.x thing. @NoJster @danny980521 I'm guessing you aren't using pytorch 2.0?

**Comment by danny980521** [comment]
@njhill You're absolutely right. I had pytorch 1.13.1+cu117 installed, and thanks to the method you suggested, I successfully resolved the error :) 
Thank you so much for your help!
