### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name'

### ISSUE THREAD

**Issue by 929359291** [huggingface/text-generation-inference#422]
### System Info
V100 double 32G，centos8
ghcr.io/huggingface/text-generation-inference:0.8  python 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker run --gpus all --shm-size 1g -p 8080:80 ghcr.io/huggingface/text-generation-inference:0.8 --model-id /data/bloom-560m --num-shard 2

2023-06-07T03:20:36.098949Z  INFO text_generation_launcher: Args { model_id: "/data/bloom-560m", revision: None, sharded: None, num_shard: Some(2), quantize: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: None, waiting_served_ratio: 1.2, max_batch_total_tokens: 32000, max_waiting_tokens: 20, port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, env: false }
2023-06-07T03:20:36.098978Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-06-07T03:20:36.099072Z  INFO text_generation_launcher: Starting download process.
2023-06-07T03:20:38.101003Z ERROR text_generation_launcher: Download encountered an error: Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 96, in download_weights
    utils.weight_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 92, in weight_files
    filenames = weight_hub_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 25, in weight_hub_files
    info = api.model_info(model_id, revision=revision)

  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)

  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/bloom-560m'. Use `repo_type` argument if needed.

### Expected behavior

docker run --gpus all --shm-size 1g -p 8080:80 ghcr.io/huggingface/text-generation-inference:0.8 --model-id /data/bloom-560m --num-shard 2

my model in local dir /data/bloom-560m,  system is centos8

**Comment by 929359291** [comment]
no docker, only run cli is ok， command is `text-generation-launcher --model-id /data/bloom-560m --num-shard 2 --port 8080`

**Comment by 929359291** [comment]
please help me，i'm crazzy....emm

**Comment by Narsil** [comment]
> please help me，i'm crazzy....emm

This is not a discussion forum.
`/data/xxx`  is a directory, you forgot to mount your drive on you docker run.
