### ISSUE TITLE
assert in_features % self.tp_world_size == 0 AssertionError when sharding Falcon-40b over 3 A100 GPUs

### ISSUE THREAD

**Issue by jxv96** [huggingface/text-generation-inference#518]
### System Info

```shell
model=tiiuae/falcon-40b-instruct
num_shard=3
volume=$PWD/data

podman run -e RUST_BACKTRACE=full -e CUDA_VISIBLE_DEVICES=0,1,2 -e NVIDIA_VISIBLE_DEVICES=0,1,2 --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:0.8 --model-id $model  --sharded true --num-shard $num_shard --env
```
```text
Target: x86_64-unknown-linux-gnu
Cargo version: 1.69.0
Commit sha: e7248fe90e27c7c8e39dd4cac5874eb9f96ab182
Docker label: sha-e7248fe
nvidia-smi:
Fri Jun 30 14:45:02 2023
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  NVIDIA A100-PCIE-40GB           Off| 00000000:17:00.0 Off |                    0 |
   | N/A   25C    P0               32W / 250W|    123MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   1  NVIDIA A100-PCIE-40GB           Off| 00000000:65:00.0 Off |                    0 |
   | N/A   25C    P0               34W / 250W|      0MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+
   |   2  NVIDIA A100-PCIE-40GB           Off| 00000000:CA:00.0 Off |                    0 |
   | N/A   24C    P0               33W / 250W|      0MiB / 40960MiB |      0%      Default |
   |                                         |                      |             Disabled |
   +-----------------------------------------+----------------------+----------------------+

   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   +---------------------------------------------------------------------------------------+

``` 

~~~text
...
You are using a model of type RefinedWeb to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 67, in serve
    server.serve(model_id, revision, sharded, quantize, trust_remote_code, uds_path)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize, trust_remote_code))

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize, trust_remote_code)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 209, in get_model
    return FlashRWSharded(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_rw.py", line 147, in __init__
    model = FlashRWForCausalLM(config, self.process_group)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 720, in __init__
    self.transformer = FlashRWModel(config, process_group)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 598, in __init__
    [

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 599, in <listcomp>
    FlashRWLargeLayer(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 499, in __init__
    self.self_attention = FlashRWLargeAttention(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 257, in __init__
    self.dense = TensorParallelRowLinear(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 106, in __init__
    assert in_features % self.tp_world_size == 0

AssertionError


2023-06-30T14:45:14.139758Z  INFO text_generation_launcher: Shutting down shards
2023-06-30T14:45:14.322191Z  INFO text_generation_launcher: Shard 2 terminated
Error: ShardCannotStart

~~~

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Run container with `num_shard=3`,

```bash
model=tiiuae/falcon-40b-instruct
num_shard=3
volume=$PWD/data

podman run -e RUST_BACKTRACE=full -e CUDA_VISIBLE_DEVICES=0,1,2 -e NVIDIA_VISIBLE_DEVICES=0,1,2 --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:0.8 --model-id $model  --sharded true --num-shard $num_shard --env
```

When running with `num_shard=2`, it works, but then there is not enough memory to load the complete model. 

### Expected behavior

Run successfully when using three shards. 

It works when I directly load the model from a conda evironment using three GPUs:

~~~python
model = "tiiuae/falcon-40b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model)
pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
    device_map="auto",
)
~~~

Thank you in advance for any help!

**Comment by OlivierDehaene** [comment]
device_map="auto" runs the model using Pipeline Paralleism, not Tensor Parallelism. To use TP, the linear layers inside the models needs to be divided evenly between the shards, in this case this is not possible hence the error.

**Comment by jxv96** [comment]
Thank you for the explanation, this makes it clear.
