### ISSUE TITLE
Support Chatglm2-6b model

### ISSUE THREAD

**Issue by exceedzhang** [huggingface/text-generation-inference#524]
### Model description

text-generation-inference not support chatglm!
<img width="1113" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/4583537/7ed2f897-3ee3-4854-867f-2bedbcd26395">

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/THUDM/chatglm2-6b/

**Comment by Narsil** [comment]
Use `--trust-remote-code` as this model is not supported by `transformers`.

**Comment by exceedzhang** [comment]
I use --trust-remote-code but error，how can I fix it？ @Narsil 
<img width="1460" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/4583537/942c8d89-8526-458e-9cb8-6fe19bfc2d6d">

<img width="1446" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/4583537/8ccdbe6c-416a-461c-88f7-a37546ca860e">

**Comment by Narsil** [comment]
Chatlm is not officially supported, so it's a best effort from here.

I think putting a debugger at the location of your issue should help you solve what's going on.

**Comment by exceedzhang** [comment]
debugger information:

2023-07-03T13:15:24.814502Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096 max_total_tokens=16000}:warmup{max_input_length=1024 max_prefill_tokens=4096 max_total_tokens=16000}: text_generation_client: router/client/src/lib.rs:33: Server error: Could not infer dtype of NoneType
thread 'main' panicked at 'Unable to warmup model: Generation("Could not infer dtype of NoneType")', router/src/main.rs:213:18
stack backtrace:
   0:     0x55a2e81d1cea - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a2e81d1cea - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a2e81d1cea - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55a2e81d1cea - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55a2e81f90ff - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x55a2e81ce1e5 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x55a2e81d1ab5 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55a2e81d1ab5 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55a2e81d2f1e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x55a2e81d2cc5 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x55a2e81d347e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x55a2e81d3379 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x55a2e81d2156 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55a2e81d30d2 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x55a2e7829d23 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x55a2e782a1d3 - core::result::unwrap_failed::h8090202169109f9c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
  16:     0x55a2e79af422 - core::result::Result<T,E>::expect::h107bf597fb9d7a73
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1046:23
  17:     0x55a2e79af422 - text_generation_router::main::{{closure}}::h02296edf7749110e
                               at /root/autodl-tmp/text-generation-inference/router/src/main.rs:206:13
  18:     0x55a2e79aac21 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::hd63ef71f335b984e
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:63
  19:     0x55a2e79aac21 - tokio::runtime::coop::with_budget::hfd9013e526c6ac79
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
  20:     0x55a2e79aac21 - tokio::runtime::coop::budget::h95ceaf15efc21644
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
  21:     0x55a2e79aac21 - tokio::runtime::park::CachedParkThread::block_on::hb1f07c31d05b226a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:31
  22:     0x55a2e7a5badb - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h8b2c722f250ff0ee
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/blocking.rs:66:9
  23:     0x55a2e7ae077a - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h3e2fdef4a37277a8
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  24:     0x55a2e7ae077a - tokio::runtime::context::runtime::enter_runtime::h9ff9a82800a2e679
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  25:     0x55a2e79e8deb - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h88c29e6efd1274f3
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  26:     0x55a2e7aab187 - tokio::runtime::runtime::Runtime::block_on::h14a5c4fb44462add
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:313:45
  27:     0x55a2e797c590 - text_generation_router::main::ha0d7c469aa27caee
                               at /root/autodl-tmp/text-generation-inference/router/src/main.rs:147:5
  28:     0x55a2e7af0e63 - core::ops::function::FnOnce::call_once::hc6a947be4cdd48f3
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  29:     0x55a2e7af0e63 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf6f976d0ae8935ce
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  30:     0x55a2e7a5b5a9 - std::rt::lang_start::{{closure}}::h598be0702f6533c6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  31:     0x55a2e81c808e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  32:     0x55a2e81c808e - std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  33:     0x55a2e81c808e - std::panicking::try::hd8a722c09d156a53
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  34:     0x55a2e81c808e - std::panic::catch_unwind::hd2ca07971cf0119b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  35:     0x55a2e81c808e - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  36:     0x55a2e81c808e - std::panicking::try::do_call::hf47aa1aa005e5f1a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  37:     0x55a2e81c808e - std::panicking::try::h73d246b2423eaf4e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  38:     0x55a2e81c808e - std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  39:     0x55a2e81c808e - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  40:     0x55a2e7a5b59e - std::rt::lang_start::hfa5ef1a2c4b8a33d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
  41:     0x7f066e5ec083 - __libc_start_main
  42:     0x55a2e782a3ee - _start
  43:                0x0 - <unknown>
2023-07-03T13:15:25.065902Z ERROR text_generation_launcher: Webserver Crashed
2023-07-03T13:15:25.065927Z  INFO text_generation_launcher: Shutting down shards
2023-07-03T13:15:25.294424Z  INFO text_generation_launcher: Shard 0 terminated
Error: WebserverFailed

**Comment by exceedzhang** [comment]
I found the reason for the service startup failure，because Could not find a **fast tokenizer** implementation for /root/autodl-tmp/chatglm2-6b/

(text-generation-inference) root@autodl-container-d8e411a48c-0b5a11d6:~/autodl-tmp# text-generation-launcher --model-id  /root/autodl-tmp/chatglm2-6b/ --trust-remote-code --disable-custom-kernels --port 6006 --max-input-length 32768 --max-batch-prefill-tokens 32768 --max-batch-total-tokens 32768 --max-total-tokens 32768
2023-07-03T13:42:25.689613Z  INFO text_generation_launcher: Args { model_id: "/root/autodl-tmp/chatglm2-6b/", revision: None, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 32768, max_total_tokens: 32768, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 32768, max_batch_total_tokens: 32768, max_waiting_tokens: 20, port: 6006, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: true, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-07-03T13:42:25.689778Z  INFO text_generation_launcher: Starting download process.
2023-07-03T13:42:27.170568Z  INFO download: text_generation_launcher: Files are already present on the host. Skipping download.

2023-07-03T13:42:27.492040Z  INFO text_generation_launcher: Successfully downloaded weights.
2023-07-03T13:42:27.492090Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `/root/autodl-tmp/chatglm2-6b/` do not contain malicious code.
2023-07-03T13:42:27.492101Z  WARN text_generation_launcher: Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
2023-07-03T13:42:27.492469Z  INFO text_generation_launcher: Starting shard 0
2023-07-03T13:42:29.707668Z  WARN shard-manager: text_generation_launcher: We're not using custom kernels.
 rank=0
2023-07-03T13:42:37.501988Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-03T13:42:43.993281Z  INFO shard-manager: text_generation_launcher: Server started at unix:///tmp/text-generation-server-0
 rank=0
2023-07-03T13:42:44.006741Z  INFO text_generation_launcher: Shard 0 ready in 16.51354959s
2023-07-03T13:42:44.106728Z  INFO text_generation_launcher: Starting Webserver
2023-07-03T13:42:44.114087Z  WARN text_generation_router: router/src/main.rs:155: Could not find a fast tokenizer implementation for /root/autodl-tmp/chatglm2-6b/
2023-07-03T13:42:44.114117Z  WARN text_generation_router: router/src/main.rs:158: Rust input length validation and truncation is disabled
2023-07-03T13:42:44.114122Z  WARN text_generation_router: router/src/main.rs:183: no pipeline tag found for model /root/autodl-tmp/chatglm2-6b/
2023-07-03T13:42:44.118343Z  INFO text_generation_router: router/src/main.rs:205: Warming up model
2023-07-03T13:42:44.392724Z ERROR shard-manager: text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/root/miniconda3/envs/text-generation-inference/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/server.py", line 166, in serve
    asyncio.run(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/interceptor.py", line 20, in intercept
    return await response
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/server.py", line 57, in Warmup
    batch = self.model.batch_type.from_pb(
  File "/root/autodl-tmp/text-generation-inference/server/text_generation_server/models/seq2seq_lm.py", line 121, in from_pb
    torch.tensor(tokenizer.bos_token_id, device=device)
RuntimeError: Could not infer dtype of NoneType
 rank=0

**Comment by exceedzhang** [comment]
chatglm2-6b model load tokenizer like this:
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)

@Narsil How can I fix it?
