### ISSUE TITLE
text_generation_launcher: Method Warmup encountered an error: `RuntimeError: CUDA error: operation not permitted when stream is capturing` with v0.8.2

### ISSUE THREAD

**Issue by FerdinandZhong** [huggingface/text-generation-inference#526]
### System Info

OS version: Ubantu 18.04.1
GPU: Rtx 2080
Nvidia & Cuda: 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

The issue will happen with the latest release (v0.8.2) when running the command with my Rtx 2080 cards (due to lack of machine, not sure if the more advanced cards with higher version nvidia driver will have the same issue):
`text-generation-launcher --model-id /root/model_assets/bloomz-560m --num-shard 1 --port 5000 --disable-custom-kernels`

with detailed error message as shown below:
```
2023-07-01T15:40:28.372499Z ERROR shard-manager: text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/root/text-generation-inference/server/text_generation_server/utils/logits_process.py", line 53, in __call__
    local_scores = warper(None, local_scores)
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 182, in __call__
    scores = scores / self.temperature
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/server-env/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/text-generation-inference/server/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/root/text-generation-inference/server/text_generation_server/server.py", line 166, in serve
    asyncio.run(
  File "/root/miniconda3/envs/server-env/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/server-env/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/root/miniconda3/envs/server-env/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/root/miniconda3/envs/server-env/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/root/miniconda3/envs/server-env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/root/text-generation-inference/server/text_generation_server/interceptor.py", line 20, in intercept
    return await response
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/root/text-generation-inference/server/text_generation_server/server.py", line 60, in Warmup
    self.model.warmup(batch, request.max_total_tokens)
  File "/root/text-generation-inference/server/text_generation_server/models/model.py", line 62, in warmup
    self.generate_token(batch)
  File "/root/miniconda3/envs/server-env/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/root/text-generation-inference/server/text_generation_server/models/causal_lm.py", line 576, in generate_token
    next_token_id, logprobs = next_token_chooser(
  File "/root/text-generation-inference/server/text_generation_server/utils/tokens.py", line 71, in __call__
    scores, next_logprob = self.static_warper(scores)
  File "/root/text-generation-inference/server/text_generation_server/utils/logits_process.py", line 57, in __call__
    self.static_next_logprob = torch.log_softmax(
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/torch/cuda/graphs.py", line 173, in __exit__
    self.cuda_graph.capture_end()
  File "/root/miniconda3/envs/server-env/lib/python3.9/site-packages/torch/cuda/graphs.py", line 79, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

 rank=0
2023-07-01T15:40:28.372763Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096 max_total_tokens=16000}:warmup{max_input_length=1024 max_prefill_tokens=4096 max_total_tokens=16000}: text_generation_client: router/client/src/lib.rs:33: Server error: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

thread 'main' panicked at 'Unable to warmup model: Generation("CUDA error: operation failed due to a previous error during capture\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n")', router/src/main.rs:213:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-01T15:40:28.537767Z ERROR text_generation_launcher: Webserver Crashed
2023-07-01T15:40:28.537810Z  INFO text_generation_launcher: Shutting down shards
2023-07-01T15:40:28.865893Z  INFO text_generation_launcher: Shard 0 terminated
Error: WebserverFailed
```
However, when I downgraded back to `v0.8.1`, the error didn't happen and the framework works fine.

### Expected behavior

The simple sample shall work correctly as v0.8.1.

If older version of nvidia driver is not supported by 0.8.2, i think it might be better to add the information into the README

**Comment by amazingkmy** [comment]
+1
i have a same problem
