### ISSUE TITLE
[Bug] Example code test failed

### ISSUE THREAD

**Issue by jiangjiajun** [huggingface/text-generation-inference#549]
### System Info

Example in the document https://github.com/huggingface/text-generation-inference/blob/main/clients/python/README.md is not working.
```
from text_generation import InferenceAPIClient

client = InferenceAPIClient("bigscience/bloomz")
text = client.generate("Why is the sky blue?").generated_text
print(text)
# ' Rayleigh scattering'

# Token Streaming
text = ""
for response in client.generate_stream("Why is the sky blue?"):
    if not response.token.special:
        text += response.token.text

print(text)
# ' Rayleigh scattering'
```

It will throw the following error message
```
Traceback (most recent call last):
  File "/jiangjiajun/work/test.py", line 3, in <module>
    client = InferenceAPIClient("bigscience/bloomz")
  File "/jiangjiajun/miniconda/lib/python3.10/site-packages/text_generation/inference_api.py", line 106, in __init__
    raise NotSupportedError(repo_id)
text_generation.errors.NotSupportedError: Model `bigscience/bloomz` is not available for inference with this client.
Use `huggingface_hub.inference_api.InferenceApi` instead.
```

### Information

- [ ] Docker
- [x] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

Run the example code will reproduce the problem.

### Expected behavior

Expect print the generated text.

**Comment by jiangjiajun** [comment]
I found out that this "bigscience/bloomz" is currently unavailable, but I have replaced it with "google/flan-t5-xxl" successfully.
