### ISSUE TITLE
No suitable name to keep for saving: Hermes-Falcon-7b-2k

### ISSUE THREAD

**Issue by GemsFord** [huggingface/text-generation-inference#622]
### System Info

<img width="791" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/35967121/36ff8258-84ef-41b8-85d7-bc11b906064b">

### Information

- [x] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

Args { model_id: "conceptofmind/Hermes-Falcon-7b-2k", revision: None, validation_workers: 2, sharded: None, num_shard: Some(2), quantize: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "a9b3fd080b6f", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }

Error:

2023-07-17T16:31:34.284891930+03:00 2023-07-17T13:31:34.284644Z  INFO text_generation_launcher: Args { model_id: "conceptofmind/Hermes-Falcon-7b-2k", revision: None, validation_workers: 2, sharded: None, num_shard: Some(2), quantize: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "a9b3fd080b6f", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-07-17T16:31:34.284991217+03:00 2023-07-17T13:31:34.284700Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `conceptofmind/Hermes-Falcon-7b-2k` do not contain malicious code.
2023-07-17T16:31:34.285026050+03:00 2023-07-17T13:31:34.284709Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-07-17T16:31:34.285041618+03:00 2023-07-17T13:31:34.284851Z  INFO text_generation_launcher: Starting download process.
2023-07-17T16:31:39.368781721+03:00 2023-07-17T13:31:39.368429Z  WARN download: text_generation_launcher: No safetensors weights found for model conceptofmind/Hermes-Falcon-7b-2k at revision None. Downloading PyTorch weights.
2023-07-17T16:31:39.368857039+03:00 
2023-07-17T16:31:39.515157087+03:00 2023-07-17T13:31:39.514908Z  INFO download: text_generation_launcher: Download file: pytorch_model.bin
2023-07-17T16:31:39.515195282+03:00 
2023-07-17T16:35:01.982917168+03:00 2023-07-17T13:35:01.982574Z  INFO download: text_generation_launcher: Downloaded /data/models--conceptofmind--Hermes-Falcon-7b-2k/snapshots/0d084d8ff7307fabe9728ef31d0fd34b45ab9df6/pytorch_model.bin in 0:03:22.
2023-07-17T16:35:01.982972856+03:00 
2023-07-17T16:35:01.982983525+03:00 2023-07-17T13:35:01.982866Z  INFO download: text_generation_launcher: Download: [1/1] -- ETA: 0
2023-07-17T16:35:01.982988395+03:00 
2023-07-17T16:35:01.983409360+03:00 2023-07-17T13:35:01.983214Z  WARN download: text_generation_launcher: No safetensors weights found for model conceptofmind/Hermes-Falcon-7b-2k at revision None. Converting PyTorch weights to safetensors.
2023-07-17T16:35:01.983427931+03:00 
2023-07-17T16:35:12.188563055+03:00 Error: DownloadError
2023-07-17T16:35:12.188610538+03:00 2023-07-17T13:35:12.188082Z ERROR text_generation_launcher: Download encountered an error: Traceback (most recent call last):
2023-07-17T16:35:12.188720747+03:00 
2023-07-17T16:35:12.188728418+03:00   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-07-17T16:35:12.188735692+03:00     sys.exit(app())
2023-07-17T16:35:12.188742193+03:00 
2023-07-17T16:35:12.188748099+03:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 182, in download_weights
2023-07-17T16:35:12.188754916+03:00     utils.convert_files(local_pt_files, local_st_files, discard_names)
2023-07-17T16:35:12.188761017+03:00 
2023-07-17T16:35:12.188767344+03:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 106, in convert_files
2023-07-17T16:35:12.188788478+03:00     convert_file(pt_file, sf_file, discard_names)
2023-07-17T16:35:12.188795439+03:00 
2023-07-17T16:35:12.188801429+03:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 68, in convert_file
2023-07-17T16:35:12.188807796+03:00     to_removes = _remove_duplicate_names(loaded, discard_names=discard_names)
2023-07-17T16:35:12.188813847+03:00 
2023-07-17T16:35:12.188819663+03:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 32, in _remove_duplicate_names
2023-07-17T16:35:12.188860393+03:00     raise RuntimeError(
2023-07-17T16:35:12.188868826+03:00 
2023-07-17T16:35:12.188894885+03:00 RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'transformer.h.14.self_attention.query_key_value.weight', 'transformer.h.24.input_layernorm.weight', 'transformer.h.12.input_layernorm.bias', 'transformer.h.20.input_layernorm.bias', 'transformer.h.23.mlp.dense_h_to_4h.weight', 'transformer.h.10.input_layernorm.bias', 'transformer.h.1.mlp.dense_h_to_4h.weight', 'transformer.h.25.input_layernorm.weight', 'transformer.h.22.input_layernorm.bias', 'transformer.h.26.mlp.dense_4h_to_h.weight', 'transformer.h.13.mlp.dense_4h_to_h.weight', 'transformer.h.11.input_layernorm.weight', 'transformer.h.13.self_attention.query_key_value.weight', 'transformer.h.22.mlp.dense_4h_to_h.weight', 'transformer.h.9.self_attention.dense.weight', 'transformer.h.4.self_attention.dense.weight', 'transformer.h.10.input_layernorm.weight', 'transformer.h.27.self_attention.query_key_value.weight', 'transformer.h.28.self_attention.dense.weight', 'transformer.h.22.input_layernorm.weight', 'transformer.h.31.self_attention.dense.weight', 'transformer.h.17.input_layernorm.bias', 'transformer.h.1.input_layernorm.bias', 'transformer.h.28.mlp.dense_4h_to_h.weight', 'transformer.h.9.mlp.dense_h_to_4h.weight', 'transformer.h.9.input_layernorm.bias', 'transformer.h.12.self_attention.dense.weight', 'transformer.h.12.input_layernorm.weight', 'transformer.h.6.mlp.dense_4h_to_h.weight', 'transformer.h.3.self_attention.query_key_value.weight', 'transformer.h.18.input_layernorm.bias', 'transformer.h.25.input_layernorm.bias', 'transformer.h.0.input_layernorm.weight', 'transformer.h.4.input_layernorm.bias', 'transformer.h.16.self_attention.query_key_value.weight', 'transformer.h.2.self_attention.query_key_value.weight', 'transformer.h.31.input_layernorm.bias', 'transformer.h.15.mlp.dense_h_to_4h.weight', 'transformer.h.27.mlp.dense_h_to_4h.weight', 'transformer.h.21.mlp.dense_h_to_4h.weight', 'transformer.h.11.mlp.dense_4h_to_h.weight', 'transformer.h.22.self_attention.dense.weight', 'transformer.h.14.input_layernorm.weight', 'transformer.h.14.input_layernorm.bias', 'transformer.h.2.self_attention.dense.weight', 'transformer.h.19.self_attention.dense.weight', 'transformer.h.2.mlp.dense_4h_to_h.weight', 'transformer.h.21.self_attention.query_key_value.weight', 'transformer.h.30.self_attention.query_key_value.weight', 'transformer.h.31.mlp.dense_h_to_4h.weight', 'transformer.h.8.self_attention.dense.weight', 'transformer.h.7.input_layernorm.weight', 'transformer.h.13.mlp.dense_h_to_4h.weight', 'transformer.h.23.self_attention.dense.weight', 'transformer.h.24.self_attention.dense.weight', 'transformer.h.0.mlp.dense_4h_to_h.weight', 'transformer.h.17.self_attention.dense.weight', 'transformer.h.15.mlp.dense_4h_to_h.weight', 'transformer.h.5.mlp.dense_h_to_4h.weight', 'transformer.h.25.mlp.dense_4h_to_h.weight', 'lm_head.weight', 'transformer.h.12.self_attention.query_key_value.weight', 'transformer.h.20.self_attention.query_key_value.weight', 'transformer.h.2.mlp.dense_h_to_4h.weight', 'transformer.h.29.mlp.dense_h_to_4h.weight', 'transformer.h.20.mlp.dense_4h_to_h.weight', 'transformer.h.19.input_layernorm.weight', 'transformer.h.28.input_layernorm.bias', 'transformer.h.7.input_layernorm.bias', 'transformer.h.8.mlp.dense_h_to_4h.weight', 'transformer.h.3.self_attention.dense.weight', 'transformer.h.20.self_attention.dense.weight', 'transformer.h.2.input_layernorm.bias', 'transformer.h.15.input_layernorm.bias', 'transformer.h.18.self_attention.query_key_value.weight', 'transformer.h.16.mlp.dense_h_to_4h.weight', 'transformer.h.21.input_layernorm.bias', 'transformer.h.26.mlp.dense_h_to_4h.weight', 'transformer.h.15.self_attention.dense.weight', 'transformer.h.28.self_attention.query_key_value.weight', 'transformer.ln_f.bias', 'transformer.h.30.input_layernorm.bias', 'transformer.h.6.input_layernorm.weight', 'transformer.h.9.mlp.dense_4h_to_h.weight', 'transformer.h.10.mlp.dense_4h_to_h.weight', 'transformer.h.7.mlp.dense_4h_to_h.weight', 'transformer.h.10.self_attention.query_key_value.weight', 'transformer.h.3.mlp.dense_4h_to_h.weight', 'transformer.h.10.self_attention.dense.weight', 'transformer.h.14.mlp.dense_4h_to_h.weight', 'transformer.h.21.self_attention.dense.weight', 'transformer.h.18.self_attention.dense.weight', 'transformer.h.23.mlp.dense_4h_to_h.weight', 'transformer.h.17.self_attention.query_key_value.weight', 'transformer.h.22.mlp.dense_h_to_4h.weight', 'transformer.h.1.self_attention.query_key_value.weight', 'transformer.h.1.input_layernorm.weight', 'transformer.h.15.input_layernorm.weight', 'transformer.h.0.self_attention.dense.weight', 'transformer.h.4.input_layernorm.weight', 'transformer.h.19.self_attention.query_key_value.weight', 'transformer.h.27.input_layernorm.weight', 'transformer.h.31.input_layernorm.weight', 'transformer.h.5.mlp.dense_4h_to_h.weight', 'transformer.h.13.input_layernorm.bias', 'transformer.h.17.mlp.dense_h_to_4h.weight', 'transformer.h.11.mlp.dense_h_to_4h.weight', 'transformer.h.31.self_attention.query_key_value.weight', 'transformer.h.11.self_attention.query_key_value.weight', 'transformer.h.19.mlp.dense_4h_to_h.weight', 'transformer.h.1.self_attention.dense.weight', 'transformer.h.5.self_attention.query_key_value.weight', 'transformer.h.6.self_attention.dense.weight', 'transformer.h.12.mlp.dense_h_to_4h.weight', 'transformer.h.27.input_layernorm.bias', 'transformer.h.29.self_attention.dense.weight', 'transformer.h.30.input_layernorm.weight', 'transformer.h.24.mlp.dense_4h_to_h.weight', 'transformer.h.0.self_attention.query_key_value.weight', 'transformer.h.4.self_attention.query_key_value.weight', 'transformer.h.14.self_attention.dense.weight', 'transformer.h.16.input_layernorm.bias', 'transformer.h.18.input_layernorm.weight', 'transformer.h.26.input_layernorm.bias', 'transformer.ln_f.weight', 'transformer.h.3.input_layernorm.weight', 'transformer.h.22.self_attention.query_key_value.weight', 'transformer.h.6.input_layernorm.bias', 'transformer.h.24.input_layernorm.bias', 'transformer.h.25.mlp.dense_h_to_4h.weight', 'transformer.h.29.input_layernorm.bias', 'transformer.h.23.self_attention.query_key_value.weight', 'transformer.h.30.mlp.dense_h_to_4h.weight', 'transformer.h.16.input_layernorm.weight', 'transformer.h.3.mlp.dense_h_to_4h.weight', 'transformer.h.11.input_layernorm.bias', 'transformer.h.7.self_attention.query_key_value.weight', 'transformer.h.18.mlp.dense_h_to_4h.weight', 'transformer.h.16.self_attention.dense.weight', 'transformer.h.4.mlp.dense_4h_to_h.weight', 'transformer.h.1.mlp.dense_4h_to_h.weight', 'transformer.h.0.mlp.dense_h_to_4h.weight', 'transformer.h.26.self_attention.query_key_value.weight', 'transformer.h.19.input_layernorm.bias', 'transformer.h.28.mlp.dense_h_to_4h.weight', 'transformer.h.17.input_layernorm.weight', 'transformer.h.13.self_attention.dense.weight', 'transformer.h.21.input_layernorm.weight', 'transformer.h.14.mlp.dense_h_to_4h.weight', 'transformer.h.7.mlp.dense_h_to_4h.weight', 'transformer.h.8.input_layernorm.bias', 'transformer.h.26.self_attention.dense.weight', 'transformer.h.24.mlp.dense_h_to_4h.weight', 'transformer.h.18.mlp.dense_4h_to_h.weight', 'transformer.h.31.mlp.dense_4h_to_h.weight', 'transformer.h.2.input_layernorm.weight', 'transformer.h.30.self_attention.dense.weight', 'transformer.h.16.mlp.dense_4h_to_h.weight', 'transformer.h.5.self_attention.dense.weight', 'transformer.h.5.input_layernorm.weight', 'transformer.h.19.mlp.dense_h_to_4h.weight', 'transformer.h.25.self_attention.dense.weight', 'transformer.h.15.self_attention.query_key_value.weight', 'transformer.h.9.input_layernorm.weight', 'transformer.h.29.self_attention.query_key_value.weight', 'transformer.h.6.self_attention.query_key_value.weight', 'transformer.h.30.mlp.dense_4h_to_h.weight', 'transformer.h.0.input_layernorm.bias', 'transformer.h.21.mlp.dense_4h_to_h.weight', 'transformer.h.6.mlp.dense_h_to_4h.weight', 'transformer.h.11.self_attention.dense.weight', 'transformer.h.4.mlp.dense_h_to_4h.weight', 'transformer.h.24.self_attention.query_key_value.weight', 'transformer.h.27.mlp.dense_4h_to_h.weight', 'transformer.h.29.mlp.dense_4h_to_h.weight', 'transformer.h.23.input_layernorm.bias', 'transformer.h.25.self_attention.query_key_value.weight', 'transformer.h.26.input_layernorm.weight', 'transformer.h.9.self_attention.query_key_value.weight', 'transformer.h.5.input_layernorm.bias', 'transformer.h.8.self_attention.query_key_value.weight', 'transformer.h.12.mlp.dense_4h_to_h.weight', 'transformer.h.23.input_layernorm.weight', 'transformer.h.7.self_attention.dense.weight', 'transformer.word_embeddings.weight', 'transformer.h.8.mlp.dense_4h_to_h.weight', 'transformer.h.29.input_layernorm.weight', 'transformer.h.3.input_layernorm.bias', 'transformer.h.8.input_layernorm.weight', 'transformer.h.17.mlp.dense_4h_to_h.weight', 'transformer.h.10.mlp.dense_h_to_4h.weight', 'transformer.h.20.input_layernorm.weight', 'transformer.h.13.input_layernorm.weight', 'transformer.h.20.mlp.dense_h_to_4h.weight', 'transformer.h.28.input_layernorm.weight', 'transformer.h.27.self_attention.dense.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.
2023-07-17T16:35:12.188944861+03:00 
2023-07-17T16:35:12.188952358+03:00 

### Expected behavior

To run conceptofmind/Hermes-Falcon-7b-2k

**Comment by GemsFord** [comment]
Model : psmathur/orca_mini_7b

System Info : ![image](https://github.com/huggingface/text-generation-inference/assets/35967121/c3687d06-5c7a-42ae-9c0c-12e1e0b1a5fb)

Error:

`2023-07-17T16:59:10.255289263+03:00 2023-07-17T13:59:10.255063Z  INFO text_generation_launcher: Args { model_id: "psmathur/orca_mini_7b", revision: None, validation_workers: 2, sharded: None, num_shard: Some(2), quantize: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "88aa1a988731", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-07-17T16:59:10.255328206+03:00 2023-07-17T13:59:10.255113Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `psmathur/orca_mini_7b` do not contain malicious code.
2023-07-17T16:59:10.255333440+03:00 2023-07-17T13:59:10.255120Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-07-17T16:59:10.255337442+03:00 2023-07-17T13:59:10.255233Z  INFO text_generation_launcher: Starting download process.
2023-07-17T16:59:13.422691845+03:00 2023-07-17T13:59:13.422321Z  INFO download: text_generation_launcher: Files are already present on the host. Skipping download.
2023-07-17T16:59:13.422785816+03:00 
2023-07-17T16:59:13.860472370+03:00 2023-07-17T13:59:13.860107Z  INFO text_generation_launcher: Successfully downloaded weights.
2023-07-17T16:59:13.860921201+03:00 2023-07-17T13:59:13.860681Z  INFO text_generation_launcher: Starting shard 0
2023-07-17T16:59:13.860950119+03:00 2023-07-17T13:59:13.860784Z  INFO text_generation_launcher: Starting shard 1
2023-07-17T16:59:17.252648473+03:00 2023-07-17T13:59:17.252372Z  WARN shard-manager: text_generation_launcher: We're not using custom kernels.
2023-07-17T16:59:17.252705939+03:00  rank=0
2023-07-17T16:59:17.257294593+03:00 2023-07-17T13:59:17.257109Z  WARN shard-manager: text_generation_launcher: We're not using custom kernels.
2023-07-17T16:59:17.257335075+03:00  rank=1
2023-07-17T16:59:23.873664329+03:00 2023-07-17T13:59:23.873435Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-17T16:59:23.873726500+03:00 2023-07-17T13:59:23.873435Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-17T16:59:33.942805649+03:00 2023-07-17T13:59:33.942646Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-17T16:59:33.942852525+03:00 2023-07-17T13:59:33.942699Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-17T16:59:36.617422672+03:00 2023-07-17T13:59:36.617230Z  INFO shard-manager: text_generation_launcher: Server started at unix:///tmp/text-generation-server-1
2023-07-17T16:59:36.617457437+03:00  rank=1
2023-07-17T16:59:36.645956528+03:00 2023-07-17T13:59:36.645618Z  INFO text_generation_launcher: Shard 1 ready in 22.782538955s
2023-07-17T16:59:36.662550387+03:00 2023-07-17T13:59:36.662288Z  INFO shard-manager: text_generation_launcher: Server started at unix:///tmp/text-generation-server-0
2023-07-17T16:59:36.662582339+03:00  rank=0
2023-07-17T16:59:36.746092952+03:00 2023-07-17T13:59:36.745825Z  INFO text_generation_launcher: Shard 0 ready in 22.88359261s
2023-07-17T16:59:36.780844683+03:00 2023-07-17T13:59:36.780618Z  INFO text_generation_launcher: Starting Webserver
2023-07-17T16:59:36.971478373+03:00 2023-07-17T13:59:36.971210Z  WARN text_generation_router: router/src/main.rs:165: Could not find a fast tokenizer implementation for psmathur/orca_mini_7b
2023-07-17T16:59:36.971514515+03:00 2023-07-17T13:59:36.971238Z  WARN text_generation_router: router/src/main.rs:168: Rust input length validation and truncation is disabled
2023-07-17T16:59:36.971523722+03:00 2023-07-17T13:59:36.971246Z  WARN text_generation_router: router/src/main.rs:324: `--revision` is not set
2023-07-17T16:59:36.971531136+03:00 2023-07-17T13:59:36.971252Z  WARN text_generation_router: router/src/main.rs:325: We strongly advise to set it to a known supported commit.`
