### ISSUE TITLE
opt-6.7bloading with   weight model.decoder.embed_tokens.weight does not exist

### ISSUE THREAD

**Issue by h1shen** [huggingface/text-generation-inference#641]
### System Info

Container version: text-generation-inference:sha-b4024ed
OS: Ubuntu18.04
model: facebook/opt-6.7b,
hardware (GPU): NVIDIA A10 24GB

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

When running the following command in CLI:
docker run -itd   --gpus all --shm-size 1g -p 8080:80  -v /data:/data ghcr.io/huggingface/text-generation-inference:sha-b4024ed --model-id facebook/opt-6.7b  --num-shard 1

### Expected behavior

2023-07-19T08:39:46.416963Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 166, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 133, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 270, in get_model
    return OPTSharded(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/opt.py", line 58, in __init__
    model = OPTForCausalLM(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/opt_modeling.py", line 748, in __init__
    self.model = OPTModel(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/opt_modeling.py", line 690, in __init__
    self.decoder = OPTDecoder(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/opt_modeling.py", line 439, in __init__
    self.embed_tokens = TensorParallelEmbedding(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 280, in __init__
    weight = weights.get_sharded(f"{prefix}.weight", dim=0)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 73, in get_sharded
    filename, tensor_name = self.get_filename(tensor_name)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 49, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight model.decoder.embed_tokens.weight does not exist
 rank=0
2023-07-19T08:39:46.832711Z ERROR text_generation_launcher: Shard 0 failed to start
2023-07-19T08:39:46.832725Z ERROR text_generation_launcher: Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 166, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 133, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 270, in get_model
    return OPTSharded(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/opt.py", line 58, in __init__
    model = OPTForCausalLM(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/opt_modeling.py", line 748, in __init__
    self.model = OPTModel(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/opt_modeling.py", line 690, in __init__
    self.decoder = OPTDecoder(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/opt_modeling.py", line 439, in __init__
    self.embed_tokens = TensorParallelEmbedding(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 280, in __init__
    weight = weights.get_sharded(f"{prefix}.weight", dim=0)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 73, in get_sharded
    filename, tensor_name = self.get_filename(tensor_name)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 49, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")

RuntimeError: weight model.decoder.embed_tokens.weight does not exist

**Comment by abhinavkulkarni** [comment]
Yes, facing the same issue here with `facebook/opt-350m`.

**Comment by Narsil** [comment]
These models seem to have unconventional naming it seems (they are more than a year old.).

`facebook/opt-1.3b` works fine, can you confirm ?

**Comment by abhinavkulkarni** [comment]
Hey @Narsil,

For `facebook/opt-1.3b`, I encounter the following error:

```
Traceback (most recent call last):

  File "/opt/anaconda3/envs/text-generation-inference/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/cli.py", line 78, in serve
    server.serve(

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/server.py", line 180, in serve
    asyncio.run(

  File "/opt/anaconda3/envs/text-generation-inference/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/anaconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/server.py", line 137, in serve_inner
    model = get_model(

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/__init__.py", line 240, in get_model
    return OPTSharded(

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/opt.py", line 58, in __init__
    model = OPTForCausalLM(config, weights)

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 748, in __init__
    self.model = OPTModel(config, weights)

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 690, in __init__
    self.decoder = OPTDecoder(config, weights)

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 469, in __init__
    [

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 470, in <listcomp>
    OPTDecoderLayer(layer_id, config, weights)

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 318, in __init__
    self.self_attn = OPTAttention(

  File "/home/abhinav/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 133, in __init__
    embed_dim = config.embed_dim

  File "/opt/anaconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)

AttributeError: 'OPTConfig' object has no attribute 'embed_dim'
```

The command I used was the following:

```
text-generation-launcher --model-id facebook/opt-1.3b --num-shard 1 --port 8080
```

**Comment by Narsil** [comment]
I just saw this and this unrelated PR contains the fix: https://github.com/huggingface/text-generation-inference/pull/671

**Comment by Narsil** [comment]
Hopefully it should land soon.

For the non standard tensor naming, we're hesitant to add the surface. This is the first time it pops up, and for a small and somewhat old model. It's really just because tensors are name `decoder.embed_....` instead of  `model.decoder.embed_..`.

`transformers` has a lot of tweaks in code to be able to load a lot of variants, but this is backward compatibility at play.
Something which we can at least for some time ignore for now.
