### ISSUE TITLE
Launcher is not able to run the model even after model is completely downloaded when not connected to internet

### ISSUE THREAD

**Issue by rishabh10gpt** [huggingface/text-generation-inference#645]
### System Info

The lancher works when the machine is connected to internet, it downloads the model stores it locally. But when the internet is not connected it is not able to use the downloaded model. 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I am using singularity in place of docker, it is quite similar to docker and uses the docker image to use the container.
Command:  singularity run --nv -B $PWD/data:/data ./text-generation-inference.sif --model-id bigscience/bloom-560m --num-shard 1

### Expected behavior

singularity run --nv -B $PWD/data:/data ./text-generation-inference.sif --model-id bigscience/bloom-560m --num-shard 1
2023-07-19T09:24:15.645969Z  INFO text_generation_launcher: Args { model_id: "bigscience/bloom-560m", revision: None, validation_workers: 2, sharded: None, num_shard: Some(1), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "0.0.0.0", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-07-19T09:24:15.646043Z  INFO text_generation_launcher: Starting download process.
2023-07-19T09:24:18.450138Z ERROR text_generation_launcher: Download encountered an error: Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connection.py", line 200, in _new_conn
    sock = connection.create_connection(

  File "/opt/conda/lib/python3.9/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/opt/conda/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connection.py", line 604, in connect
    self.sock = sock = self._new_conn()

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e

urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f0f46a4b940>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(

  File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(

  File "/opt/conda/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bigscience/bloom-560m (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0f46a4b940>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 109, in download_weights
    utils.weight_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 96, in weight_files
    filenames = weight_hub_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 25, in weight_hub_files
    info = api.model_info(model_id, revision=revision)

  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1603, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)

  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)

  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bigscience/bloom-560m (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0f46a4b940>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)"))

Error: DownloadError

**Comment by Narsil** [comment]
This looks like a DNS error, not sure what we can do about it.

`--net=host` might help here.
If you have the model already locally (which seems to be the case) then `HF_HUB_OFFLINE=1` might help too (this should disable every network call in `hugginface_hub` library.

**Comment by rishabh10gpt** [comment]
Hey @Narsil thanks for the reply! 
I have tried exporting HF_HUB_OFFLINE=1, this still doesn't work.

**Comment by Narsil** [comment]
Have you change the moedl id to the local folder (within the docker ?)

**Comment by rishabh10gpt** [comment]
Yeah, the same code works just as in i connect the internet and it stops working as the internet is disconnected.

**Comment by Narsil** [comment]
Are you sure it's not a network mounted disk and killing network also kills your disk ?

All the stacktrace you provide suggest the docker is looking for a remote id, not a  local directory.

**Comment by rishabh10gpt** [comment]
Yeah i am sure, i replicated the same problem on a completely standalone machine.

**Comment by jtourille** [comment]
I have the same problem, I am also using singularity and I can't skip the download process no matter what. Even so I have the weights in a mounted folder on /data. It seems that it needs internet to realize that the weights are already downloaded.

**Comment by jtourille** [comment]
Nevermind, I found the solution.

**Comment by OlivierDehaene** [comment]
@jtourille, could you share your solution with the community here? Cheers!

**Comment by yeswhos** [comment]
Same issues here.

How to get access to the docker without going through the download phase?

**Comment by kunal0137** [comment]
Bumping @jtourille  - would you be able to share the solution on what needs to be done to run a model (already downloaded) when completely offline?

**Comment by jtourille** [comment]
Suppose you have a model downloaded in your home directory
```
CodeLlama-7b-hf/
├── config.json
├── generation_config.json
├── LICENSE
├── model-00001-of-00002.safetensors
├── model-00002-of-00002.safetensors
├── model.safetensors.index.json
├── pytorch_model-00001-of-00003.bin
├── pytorch_model-00002-of-00003.bin
├── pytorch_model-00003-of-00003.bin
├── pytorch_model.bin.index.json
├── README.md
├── special_tokens_map.json
├── tokenizer_config.json
├── tokenizer.json
├── tokenizer.model
└── USE_POLICY.md
```
With the last version of the image (1.0.3), you start the container by invoking:
```shell
singularity instance run --nv \
  --mount type=bind,src=/home/$USER,dst=/data \
  text-generation-inference-1.0.3.sif \
  codellama \
  --model-id=/data/CodeLlama-7b-hf \
  -p 8080
```
