### ISSUE TITLE
'NoneType' object has no attribute 'blocks'

### ISSUE THREAD

**Issue by vvsotnikov** [huggingface/text-generation-inference#649]
### System Info

```
2023-07-19T16:06:41.055285Z  INFO text_generation_launcher: Args { model_id: "TheBloke/WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16", revision: None, validation_workers: 2, sharded: None, num_shard: Some(1), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 8192, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "llm-worker-0", port: 8001, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-07-19T16:06:41.055408Z  INFO download: text_generation_launcher: Starting download process.
2023-07-19T16:06:43.508503Z  WARN text_generation_launcher: No safetensors weights found for model TheBloke/WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16 at revision None. Downloading PyTorch weights.

2023-07-19T16:06:43.612710Z  INFO text_generation_launcher: Download file: pytorch_model-00001-of-00003.bin

2023-07-19T16:07:17.608438Z  INFO text_generation_launcher: Downloaded /data/models--TheBloke--WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16/snapshots/453800a54e9915a2421bbbeb973948bb55776ec0/pytorch_model-00001-of-00003.bin in 0:00:33.

2023-07-19T16:07:17.608566Z  INFO text_generation_launcher: Download: [1/3] -- ETA: 0:01:06

2023-07-19T16:07:17.608934Z  INFO text_generation_launcher: Download file: pytorch_model-00002-of-00003.bin

2023-07-19T16:08:05.034334Z  INFO text_generation_launcher: Downloaded /data/models--TheBloke--WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16/snapshots/453800a54e9915a2421bbbeb973948bb55776ec0/pytorch_model-00002-of-00003.bin in 0:00:47.

2023-07-19T16:08:05.034419Z  INFO text_generation_launcher: Download: [2/3] -- ETA: 0:00:40.500000

2023-07-19T16:08:05.034770Z  INFO text_generation_launcher: Download file: pytorch_model-00003-of-00003.bin

2023-07-19T16:08:32.836076Z  INFO text_generation_launcher: Downloaded /data/models--TheBloke--WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16/snapshots/453800a54e9915a2421bbbeb973948bb55776ec0/pytorch_model-00003-of-00003.bin in 0:00:27.

2023-07-19T16:08:32.836206Z  INFO text_generation_launcher: Download: [3/3] -- ETA: 0

2023-07-19T16:08:32.836343Z  WARN text_generation_launcher: No safetensors weights found for model TheBloke/WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16 at revision None. Converting PyTorch weights to safetensors.

2023-07-19T16:09:53.045689Z  INFO text_generation_launcher: Convert: [1/3] -- Took: 0:01:19.647597

2023-07-19T16:11:39.036602Z  INFO text_generation_launcher: Convert: [2/3] -- Took: 0:01:45.990405

2023-07-19T16:12:34.656387Z  INFO text_generation_launcher: Convert: [3/3] -- Took: 0:00:55.619292

2023-07-19T16:12:35.083186Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-07-19T16:12:35.083469Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-07-19T16:12:45.134434Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:12:55.144426Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:13:05.154842Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:13:15.165115Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:13:25.175313Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:13:35.184884Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:13:45.195147Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:13:55.204998Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:14:05.215689Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:14:15.225941Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-07-19T16:14:20.612451Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-07-19T16:14:20.631146Z  INFO shard-manager: text_generation_launcher: Shard ready in 105.546858933s rank=0
2023-07-19T16:14:20.717265Z  INFO text_generation_launcher: Starting Webserver
2023-07-19T16:14:21.405372Z  WARN text_generation_router: router/src/main.rs:341: `--revision` is not set
2023-07-19T16:14:21.405402Z  WARN text_generation_router: router/src/main.rs:342: We strongly advise to set it to a known supported commit.
2023-07-19T16:14:21.566098Z  INFO text_generation_router: router/src/main.rs:363: Serving revision 453800a54e9915a2421bbbeb973948bb55776ec0 of model TheBloke/WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16
2023-07-19T16:14:21.571620Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-07-19T16:14:23.570780Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 169, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 60, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 750, in warmup
    + batch.blocks
AttributeError: 'NoneType' object has no attribute 'blocks'
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

To reproduce bug: `HF_MODEL_TRUST_REMOTE_CODE=1 docker run --gpus all --shm-size 1g -p 8080:80 --rm ghcr.io/huggingface/text-generation-inference:sha-5a1512c --model-id TheBloke/WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-fp16`

Seems like it was caused by this change: https://github.com/huggingface/text-generation-inference/commit/fe80f5360ca885af4c63a3f1db9f6786df7ebc76#diff-baea97a6bf4563abf0e105e4f8f4d0ee1c54b3e6098c0cfd1903faca24765977R750

### Expected behavior

No errors.

**Comment by Narsil** [comment]
PR above should solve your issue (the warmup happens to trigger EOS it seems).
