### ISSUE TITLE
Docker: No .safetensors weights found for model `meta-llama/Llama-2-7b`

### ISSUE THREAD

**Issue by hamelsmu** [huggingface/text-generation-inference#656]
### System Info

I'm using the docker container `docker run ghcr.io/huggingface/text-generation-inference`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
model="meta-llama/Llama-2-7b"
volume="/home/ubuntu/data"

docker run --gpus all --shm-size 50g -p 8081:80 -e HUGGING_FACE_HUB_TOKEN=xxxx -v $volume:/data ghcr.io/huggingface/text-generation-inference --model-id $model
```

After running this command I get this error

```
2023-07-20T05:18:07.587421Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-7b", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "109fcd191098", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-07-20T05:18:07.587552Z  INFO download: text_generation_launcher: Starting download process.
2023-07-20T05:18:09.692098Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 96, in weight_files
    filenames = weight_hub_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 37, in weight_hub_files
    raise EntryNotFoundError(

huggingface_hub.utils._errors.EntryNotFoundError: No .safetensors weights found for model meta-llama/Llama-2-7b and revision None.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 109, in download_weights
    utils.weight_files(model_id, revision, extension)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 101, in weight_files
    pt_filenames = weight_hub_files(model_id, revision, extension=".bin")

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 37, in weight_hub_files
    raise EntryNotFoundError(

huggingface_hub.utils._errors.EntryNotFoundError: No .bin weights found for model meta-llama/Llama-2-7b and revision None.
```

### Expected behavior

Any help is appreciated on how to run the docker container that doesn't result in the safe tensor error.

**Comment by rishu931997** [comment]
Try using `meta-llama/Llama-2-7b-hf` model. Huggingface has released TGI and huggingface compatible model for all Llamav2 versions.

**Comment by hamelsmu** [comment]
Thanks @rishu931997 that works!  BTW what are the `*-hf` models about exactly?  Is that written about somewhere?

**Comment by hamelsmu** [comment]
Thanks for being so kind and helping, really appreciate it

**Comment by rishu931997** [comment]
AFAIK Huggingface's AutoModelForCausalLM and transformers libraries still use the .bin models whereas the TGI converts the .bin models to safetensors (if not already present) and then use them for loading. I usually delete the .bin models file while running the model using TGI to save space. But you are right, it would be much more easier to handle things if only one type of model format were there.

**Comment by OlivierDehaene** [comment]
Meta uploaded the original weights from their own framework. Then we created the `-hf` variants for transformer compatibility.
