### ISSUE TITLE
build-flash-attention-v2 error!

### ISSUE THREAD

**Issue by exceedzhang** [huggingface/text-generation-inference#681]
### System Info

I build-flash-attention success, but build-flash-attention-v2 error!

<img width="1118" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/4583537/68294b63-4670-4b1c-8236-8a5aab334149">

<img width="1120" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/4583537/a538f390-1404-436a-93b8-80d1691e8cb3">

python 3.9
A5000 GPU 24GB
cuda 11.8

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

cd server
make install install-flash-attention-v2

### Expected behavior

Traceback (most recent call last):
  File "/root/autodl-tmp/text-generation-inference/server/flash-attention-v2/setup.py", line 201, in <module>
    setup(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
make: *** [Makefile-flash-att-v2:10: build-flash-attention-v2] Error 1

**Comment by OlivierDehaene** [comment]
My guess is that your driver is too old. This would be a better issue for https://github.com/Dao-AILab/flash-attention
