### ISSUE TITLE
RuntimeError: CUDA error: operation not supported Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions

### ISSUE THREAD

**Issue by gmlodm** [huggingface/text-generation-inference#691]
### System Info

My environment:

Ubuntu20.04, cuda 11.8 

Getting this error:

2023-07-24T15:21:23.871237Z  INFO text_generation_launcher: Args { model_id: "models/llama-2-70b/", revision: None, sharded: None, num_shard: Some(1), quantize: Some(Gptq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "1458b38990cc", port: 8080, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-07-24T15:21:23.871331Z  INFO text_generation_launcher: Starting download process.
2023-07-24T15:21:25.231878Z  INFO download: text_generation_launcher: Files are already present on the host. Skipping download.

2023-07-24T15:21:25.573080Z  INFO text_generation_launcher: Successfully downloaded weights.
2023-07-24T15:21:25.573252Z  INFO text_generation_launcher: Starting shard 0
2023-07-24T15:21:27.758299Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/app/server/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/app/server/text_generation_server/server.py", line 166, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/app/server/text_generation_server/server.py", line 133, in serve_inner
    model = get_model(
  File "/app/server/text_generation_server/models/__init__.py", line 215, in get_model
    return FlashLlama(
  File "/app/server/text_generation_server/models/flash_llama.py", line 65, in __init__
    model = FlashLlamaForCausalLM(config, weights)
  File "/app/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 371, in __init__
    self.model = FlashLlamaModel(config, weights)
  File "/app/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 306, in __init__
    self.embed_tokens = TensorParallelEmbedding(
  File "/app/server/text_generation_server/utils/layers.py", line 280, in __init__
    weight = weights.get_sharded(f"{prefix}.weight", dim=0)
  File "/app/server/text_generation_server/utils/weights.py", line 98, in get_sharded
    tensor = tensor.to(device=self.device)
RuntimeError: CUDA error: operation not supported
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

 rank=0
2023-07-24T15:21:28.275141Z ERROR text_generation_launcher: Shard 0 failed to start
2023-07-24T15:21:28.275179Z ERROR text_generation_launcher: /opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/opt/conda/lib/libcudart.so.11.0'), PosixPath('/opt/conda/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/app/server/text_generation_server/cli.py", line 78, in serve
    server.serve(

  File "/app/server/text_generation_server/server.py", line 166, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/app/server/text_generation_server/server.py", line 133, in serve_inner
    model = get_model(

  File "/app/server/text_generation_server/models/__init__.py", line 215, in get_model
    return FlashLlama(

  File "/app/server/text_generation_server/models/flash_llama.py", line 65, in __init__
    model = FlashLlamaForCausalLM(config, weights)

  File "/app/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 371, in __init__
    self.model = FlashLlamaModel(config, weights)

  File "/app/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 306, in __init__
    self.embed_tokens = TensorParallelEmbedding(

  File "/app/server/text_generation_server/utils/layers.py", line 280, in __init__
    weight = weights.get_sharded(f"{prefix}.weight", dim=0)

  File "/app/server/text_generation_server/utils/weights.py", line 98, in get_sharded
    tensor = tensor.to(device=self.device)

RuntimeError: CUDA error: operation not supported
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2023-07-24T15:21:28.275273Z  INFO text_generation_launcher: Shutting down shards

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

Install TGI locally
Use text-generation-launcher with a previously download model, in this case Llama 2 70B

### Expected behavior

I have access o 4 A100 80GB and when loading the model using  a normal python script there are no issues, but when trying to use tgi and the text generation launcher I find that error, any ideas of what can I be missing?

**Comment by Narsil** [comment]
Try uninstalling `bitsandbytes`? I've seen it cause more confusion that help.

I don't think it's the core issue but still. Are you using `CUDA_VISIBLE_DEVICES=`  to control the GPU to launch on ?

**Comment by Narsil** [comment]
Could have been fixed by this: https://github.com/huggingface/text-generation-inference/pull/689 if that was the case.

**Comment by OlivierDehaene** [comment]
I assume this is on `0.9.3`. Can you try `latest`?

**Comment by OlivierDehaene** [comment]
Are you on the latest commit then? If not can you pull and `make install`?
