### ISSUE TITLE
Not Enough CUDA Devices

### ISSUE THREAD

**Issue by schauppi** [huggingface/text-generation-inference#707]
### System Info

TGI: 0.9.3

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Hey Guys!

I am using TGI to serve TheBloke/Llama-2-13B-chat-GPTQ. It "works" with the following command: 

```
sudo docker run \
    -p 8080:80 \
    -e GPTQ_BITS=4 \
    -e GPTQ_GROUPSIZE=128 \
    --gpus all \
    --shm-size 1g \ 
    -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:latest \
    --model-id TheBloke/Llama-2-13B-chat-GPTQ \
    --max-input-length 4096 \
    --max-total-tokens 8192 \
    --quantize gptq \
    --num-shard 1
```

![Bildschirmfoto 2023-07-27 um 10 42 41](https://github.com/huggingface/text-generation-inference/assets/46676413/8c2eb9f3-5650-4d78-94f6-dc20a5d4d113)

when I am using --num-shard 2

![Bildschirmfoto 2023-07-27 um 10 44 37](https://github.com/huggingface/text-generation-inference/assets/46676413/5784f204-8dce-46b6-9c16-29e0200d3c0a)

when I try to shard the model above the two GPU´s with the following command I get this error message: 

```
sudo docker run -p 8080:80 \
    -e GPTQ_BITS=4 \
    -e GPTQ_GROUPSIZE=128 \
    -e SHARDED=true \
    --gpus all \
    --shm-size 1g \
    -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:latest \
    --model-id TheBloke/Llama-2-13B-chat-GPTQ \
    --max-input-length 4096 \
    --max-total-tokens 8192 \
    --quantize gptq 
```

![Bildschirmfoto 2023-07-27 um 10 46 31](https://github.com/huggingface/text-generation-inference/assets/46676413/6f01755a-11bc-4e11-8d7c-b9daa0607257)

am I missing something here?
I tried the same with the 70B Llama gptq model to shard it but I get an cuda-oom error bc its only detecting GPU:0.

### Expected behavior

Shard the model over the two/more gpu´s.

**Comment by Narsil** [comment]
Are you using `CUDA_VISIBLE_DEVICES` ? The last shared screen seems to suggest so, and that could limit the number of visible GPUs.

**Comment by schauppi** [comment]
Using the following command with CUDA_VISIBLE_DEVICES=0,1 in the env: 
```
sudo docker run -p 8080:80 \
    -e GPTQ_BITS=4 \
    -e GPTQ_GROUPSIZE=128 \
    -e SHARDED=true \
    -e CUDA_VISIBLE_DEVICES=0,1 \
    --gpus all \
    --shm-size 1g \
    -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:latest \
    --model-id TheBloke/Llama-2-13B-chat-GPTQ \
    --max-input-length 4096 \
    --max-total-tokens 8192 \
    --quantize gptq 
```
![Bildschirmfoto 2023-07-27 um 11 20 28](https://github.com/huggingface/text-generation-inference/assets/46676413/d789799a-1dce-499f-975d-af7e48bfaaca)

 leads to the same behavior as this command: 
```
sudo docker run \
    -p 8080:80 \
    -e GPTQ_BITS=4 \
    -e GPTQ_GROUPSIZE=128 \
    --gpus all \
    --shm-size 1g \ 
    -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:latest \
    --model-id TheBloke/Llama-2-13B-chat-GPTQ \
    --max-input-length 4096 \
    --max-total-tokens 8192 \
    --quantize gptq \
    --num-shard 2
```

**Comment by OlivierDehaene** [comment]
Indeed there is an issue with the parsing logic when using `all` for gpus. We always specify the number or device ids when using automatic shard number.

**Comment by schauppi** [comment]
ok - what could be an working parsing logic in this case? 

setting `--gpus 0,1` leads to following error: 

```
sudo docker run -p 8080:80 \
>     -e GPTQ_BITS=4 \
>     -e GPTQ_GROUPSIZE=128 \
>     -e SHARDED=true \
>     -e CUDA_VISIBLE_DEVICES=0,1 \
>     --gpus 0,1 \
>     --shm-size 1g \
>     -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:latest \
>     --model-id TheBloke/Llama-2-13B-chat-GPTQ \
>     --max-input-length 4096 \
>     --max-total-tokens 8192 \
>     --quantize gptq
2023-07-27T10:35:32.444977Z  INFO text_generation_launcher: Args { model_id: "TheBloke/Llama-2-13B-chat-GPTQ", revision: None, validation_workers: 2, sharded: Some(true), num_shard: None, quantize: Some(Gptq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 4096, max_total_tokens: 8192, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "ac9ce2167237", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-07-27T10:35:32.445031Z  INFO text_generation_launcher: Parsing num_shard from CUDA_VISIBLE_DEVICES/NVIDIA_VISIBLE_DEVICES
2023-07-27T10:35:32.445040Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-07-27T10:35:32.445223Z  INFO download: text_generation_launcher: Starting download process.
2023-07-27T10:35:33.978541Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-07-27T10:35:34.248768Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-07-27T10:35:34.249151Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-07-27T10:35:34.249173Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-07-27T10:35:36.479429Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
    return FlashLlama(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 31, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/dist.py", line 51, in initialize_torch_distributed
    assert WORLD_SIZE <= torch.cuda.device_count(), "Each process is one gpu"
AssertionError: Each process is one gpu

2023-07-27T10:35:36.482758Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
    return FlashLlama(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 31, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/dist.py", line 51, in initialize_torch_distributed
    assert WORLD_SIZE <= torch.cuda.device_count(), "Each process is one gpu"
AssertionError: Each process is one gpu

2023-07-27T10:35:36.952960Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 31, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/dist.py", line 51, in initialize_torch_distributed
    assert WORLD_SIZE <= torch.cuda.device_count(), "Each process is one gpu"

AssertionError: Each process is one gpu
 rank=1
2023-07-27T10:35:36.954279Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 31, in __init__
    self.process_group, rank, world_size = initialize_torch_distributed()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/dist.py", line 51, in initialize_torch_distributed
    assert WORLD_SIZE <= torch.cuda.device_count(), "Each process is one gpu"

AssertionError: Each process is one gpu
 rank=0
2023-07-27T10:35:37.052694Z ERROR text_generation_launcher: Shard 1 failed to start
2023-07-27T10:35:37.052733Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

**Comment by OlivierDehaene** [comment]
`--gpus 2` for 2 gpus or `--gpus '"device=0,1"'` for device ID 0 and 1.
You should remove the `CUDA_VISIBLE_DEVICES` env var.

**Comment by schauppi** [comment]
Unfortunately the same behavior as mentioned in previous comments with both commands `--gpus 2` or/and `--gpus '"device=0,1"'`.

this is the command: 

```
sudo docker run -p 8080:80 \
    -e GPTQ_BITS=4 \
    -e GPTQ_GROUPSIZE=128 \
    -e SHARDED=true \
    --gpus 2 \
    --shm-size 1g \
    -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:latest \
    --model-id TheBloke/Llama-2-13B-chat-GPTQ \
    --max-input-length 4096 \
    --max-total-tokens 8192 \
    --quantize gptq
```

![Bildschirmfoto 2023-07-27 um 15 02 07](https://github.com/huggingface/text-generation-inference/assets/46676413/b5e6ca98-f178-4275-9c92-5a68bb051a8c)

**Comment by OlivierDehaene** [comment]
What do you mean "Unfortunately"? That's the expected behaviour yes.

**Comment by schauppi** [comment]
Ok sry - then I have misunderstood something. Is it then possible to load Llama v2 70B GPTQ with my setup (two graphics cards with 24 GB VRAM each)?

**Comment by OlivierDehaene** [comment]
I don't think it will fit, no.

**Comment by schauppi** [comment]
@Narsil
I thought exllama in TGI supports GPU split like in Ooba WebUI. 30GB GPTQ model - 20GB split on GPU1 and 10GB split on GPU2. In Ooba WebUI I can load/use 70B GPTQ Llama v2 model this way.
But thanks for the clarification!

**Comment by schauppi** [comment]
> Closing as this seemed solved ?
> 
> > Llama v2 70B GPTQ
> 
> All your commands are referring to 13B-GPTQ, which should fit
> 
> 70B should fit 48GB of VRAM btw: https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ/tree/main (35GB weights). It's going to be tight, but it might work

It worked with the following command:

sudo docker run --rm    \
-p 8080:80     \
-e GPTQ_BITS=4     \
-e GPTQ_GROUPSIZE=128     \
--gpus all     \
--shm-size 5g     \
-v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:sha-bce5e22     \
--model-id /data/Llama-2-70B-chat-GPTQ \
--quantize gptq \
--num-shard 2
