### ISSUE TITLE
How to benchmark a warmed local model by docker

### ISSUE THREAD

**Issue by Laych7** [huggingface/text-generation-inference#765]
### System Info

Using the docker run to connected local model and it worked:
`docker run --rm --name tgi  --runtime=nvidia  --gpus all  -p 5001:5001  -v data/nfs/gdiist/model:/data  k8s-master:5000/text-generation-inference:0.9.3  --model-id /data/llama-7b-hf  --hostname 0.0.0.0  --port 5001 --dtype float16 `
```
2023-08-03T09:14:08.564776Z  INFO text_generation_launcher: Starting Webserver
2023-08-03T09:14:08.587895Z  WARN text_generation_router: router/src/main.rs:165: Could not find a fast tokenizer implementation for /data/llama-7b-hf
2023-08-03T09:14:08.587942Z  WARN text_generation_router: router/src/main.rs:168: Rust input length validation and truncation is disabled
2023-08-03T09:14:08.587953Z  WARN text_generation_router: router/src/main.rs:193: no pipeline tag found for model /data/llama-7b-hf
2023-08-03T09:14:08.595313Z  INFO text_generation_router: router/src/main.rs:212: Warming up model
2023-08-03T09:14:11.767661Z  INFO text_generation_router: router/src/main.rs:221: Connected


### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

And I can't use the `text-generation-benchmark` so I entered the Docker container and using the following command：
`docker exec -it tgi /bin/bash`
`text-generation-benchmark --tokenizer-name data/nfs/gdiist/model/llama-7b-hf`
There are errors reported as follows：
```
2023-08-03T09:23:25.437223Z  INFO text_generation_benchmark: benchmark/src/main.rs:126: Loading tokenizer
2023-08-03T09:23:25.437552Z  INFO text_generation_benchmark: benchmark/src/main.rs:135: Downloading tokenizer
2023-08-03T09:23:26.218104Z ERROR cached_path::cache: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cached-path-0.6.1/src/cache.rs:559: ETAG fetch for https://huggingface.co/data/nfs/gdiist/model/llama-7b-hf/resolve/main/tokenizer.json failed with fatal error    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Model \"data/nfs/gdiist/model/llama-7b-hf\" on the Hub doesn't have a tokenizer"', benchmark/src/main.rs:147:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

I want to know if it's the reason for using the local model or the lack of parameters？

### Expected behavior

1. Help me using benchmark tool after docker run
2. Tell me how to use 2 gpus to run a local model in docker run

Thanks！

**Comment by caiyesd** [comment]
1. After `docker exec -it tgi /bin/bash`, you should use `text-generation-benchmark --tokenizer-name /data/llama-7b-hf`
2. You can try `docker run --gpu '"device=0,1"' ....`     # 0 and 1 means to use the first and second GPU only.

**Comment by Laych7** [comment]
`text-generation-benchmark --tokenizer-name /data/llama-7b-hf`also don't work
```
2023-08-04T02:07:50.957007Z  INFO text_generation_benchmark: benchmark/src/main.rs:126: Loading tokenizer
2023-08-04T02:07:50.957694Z  INFO text_generation_benchmark: benchmark/src/main.rs:135: Downloading tokenizer
2023-08-04T02:07:53.820843Z ERROR cached_path::cache: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cached-path-0.6.1/src/cache.rs:559: ETAG fetch for https://huggingface.co//data/llama-7b-hf/resolve/main/tokenizer.json failed with fatal error    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Model \"/data/llama-7b-hf\" on the Hub doesn't have a tokenizer"', benchmark/src/main.rs:147:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by abhinavkulkarni** [comment]
@Laych7: https://github.com/huggingface/text-generation-inference/issues/760

**Comment by Laych7** [comment]
> @Laych7: #760

Okay, I see, but I'm using a local model and I want to know how to use `HUGGING_FACE_HUB_TOKEN`

**Comment by Narsil** [comment]
Hi @Laych7 ,

You're using a docker process, so all you've got to do is get on it (docker exec -it NAME /bin/bash)

And then `text-generation-benchmark --tokenizer-name /local/path` 

You cannot benchmark from outside the docker as the benchmark tool connects directly to the running GPUs.

**Comment by Oubaaa** [comment]
May I ask if you have solved this problem? I have encountered the same problem
