### ISSUE TITLE
llama2 70b can not quant with gptq

### ISSUE THREAD

**Issue by zhaohb** [huggingface/text-generation-inference#766]
### System Info

Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 7766fee9b15b6f600ee73db7f8bd72f7c62f335e
Docker label: sha-7766fee

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

now I am using text-generation-inference:latest image, and I use that command load llama2 70b model:
```shell
GPTQ_BITS=4 GPTQ_GROUPSIZE=-1 text-generation-launcher --model-id llama2/Llama-2-70b-hf/636f7c18d51ab7bf095aa35e68b5e76985ca527c/ --port 9009 --num-shard 4 --quantize gptq
```
but I get error:
```shell
2023-08-03T09:31:03.513539Z  INFO text_generation_launcher: Args { model_id: "llama2/Llama-2-70b-hf/636f7c18d51ab7bf095aa35e68b5e76985ca527c/", revision: None, validation_workers: 2, sharded: None, num_shard: Some(4), quantize: Some(Gptq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "xxx", port: 9009, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-03T09:31:03.513579Z  INFO text_generation_launcher: Sharding model on 4 processes
2023-08-03T09:31:03.513671Z  INFO download: text_generation_launcher: Starting download process.
2023-08-03T09:31:06.013645Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-03T09:31:06.416730Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-03T09:31:06.416930Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-03T09:31:06.416954Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-08-03T09:31:06.416989Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2023-08-03T09:31:06.417011Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2023-08-03T09:31:15.327809Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 116, in get_multi_weights_col
    [self.get_sharded(f"{p}.qweight", dim=1) for p in prefixes], dim=1
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 116, in <listcomp>
    [self.get_sharded(f"{p}.qweight", dim=1) for p in prefixes], dim=1
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 102, in get_sharded
    filename, tensor_name = self.get_filename(tensor_name)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 53, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight model.layers.0.self_attn.q_proj.qweight does not exist

During handling of the above exception, another exception occurred:
```

how to fix that?

### Expected behavior

llama2 model can be load with gptq.

**Comment by Narsil** [comment]
> llama2/Llama-2-70b-hf/636f7c18d51ab7bf095aa35e68b5e76985ca527c/

This seems to suggest you're trying to load the regular 70B as GPTQ, but GPTQ requires a specific set of weights.

Could you maybe dump the tensor names contained the the safetensors files in that directory ?

```
from safetensors.torch import load_file

weights = load_file(safetensors_filename)
print(weights.keys())
 ```
 
 You're likely to have several files in that directory

**Comment by zhaohb** [comment]
yes, several files in that directory:
```shell
LICENSE.txt                       model-00008-of-00015.safetensors  pytorch_model-00005-of-00029.bin  pytorch_model-00020-of-00029.bin
README.md                         model-00009-of-00015.safetensors  pytorch_model-00006-of-00029.bin  pytorch_model-00021-of-00029.bin
Responsible-Use-Guide.pdf         model-00010-of-00015.safetensors  pytorch_model-00007-of-00029.bin  pytorch_model-00022-of-00029.bin
USE_POLICY.md                     model-00011-of-00015.safetensors  pytorch_model-00008-of-00029.bin  pytorch_model-00023-of-00029.bin
added_tokens.json                 model-00012-of-00015.safetensors  pytorch_model-00009-of-00029.bin  pytorch_model-00024-of-00029.bin
config.json                       model-00013-of-00015.safetensors  pytorch_model-00010-of-00029.bin  pytorch_model-00025-of-00029.bin
generation_config.json            model-00014-of-00015.safetensors  pytorch_model-00011-of-00029.bin  pytorch_model-00026-of-00029.bin
llama_updates.patch               model-00015-of-00015.safetensors  pytorch_model-00012-of-00029.bin  pytorch_model-00027-of-00029.bin
model-00001-of-00015.safetensors  model.safetensors.index.json      pytorch_model-00013-of-00029.bin  pytorch_model-00028-of-00029.bin
model-00002-of-00015.safetensors  nohup.log                         pytorch_model-00014-of-00029.bin  pytorch_model-00029-of-00029.bin
model-00003-of-00015.safetensors  nohup.out                         pytorch_model-00015-of-00029.bin  pytorch_model.bin.index.json
model-00004-of-00015.safetensors  pytorch_model-00001-of-00029.bin  pytorch_model-00016-of-00029.bin  special_tokens_map.json
model-00005-of-00015.safetensors  pytorch_model-00002-of-00029.bin  pytorch_model-00017-of-00029.bin  tokenizer.json
model-00006-of-00015.safetensors  pytorch_model-00003-of-00029.bin  pytorch_model-00018-of-00029.bin  tokenizer.model
model-00007-of-00015.safetensors  pytorch_model-00004-of-00029.bin  pytorch_model-00019-of-00029.bin  tokenizer_config.json
```

So converting to gtpq quant isn't just a matter of adding command-line arguments, right？

**Comment by Narsil** [comment]
Better docs are coming https://github.com/huggingface/text-generation-inference/pull/740

Basically you need to generate the GTPQ model:

```
text-generation-server quantize MODEL_ID OUTPUT_DIR  # --help for all flags
```

This will create a new model you can use with the current CLI you are using.

Please be mindful that this script will likely work, but we've seen instances where the output model wasn't the best. Using existing `GPTQ` models, might be easier if you can: https://huggingface.co/models?search=gptq

We're looking into this, the current quantize script might entirely be outsourced if there's a better source for these.

**Comment by zhaohb** [comment]
@Narsil I can already get the model of llama270b quantized by int4, but I think it only supports int4, can we support int8 quantize?
thank you very much.

**Comment by Narsil** [comment]
@zhaohb this should have fixed it: https://github.com/huggingface/text-generation-inference/pull/785

Can you try latest docker to confirm ?

**Comment by nm-narasimha** [comment]
This issue still persists with TGI docker. For both GPTQ and AWQ Llama-2 models (we tried 70b), TGI could not initialize model objects and service. 

Error: weight model.layers.0.self_attn.q_proj.qweight does not exist

**Comment by Narsil** [comment]
@nm-narasimha Please open an issue with the entire template filled if you want help.
Information contained here is not enough to help you.
