### ISSUE TITLE
ModuleNotFoundError: No module named 'generate_pb2'

### ISSUE THREAD

**Issue by WhiteZz1** [huggingface/text-generation-inference#78]
When I execute the command `text-generation-launcher -- model-id bigscience/bloom-560m -- num-shard 1`, the following error occurs
`2023-02-20T04:52:55.905326Z ERROR text_generation_launcher: Download encountered an error: Traceback (most recent call last):
  File "/root/miniconda3/envs/my-env/bin/text-generation-server", line 5, in <module>
    from text_generation.cli import app
  File "/root/autodl-tmp/text-generation-inference/server/text_generation/cli.py", line 9, in <module>
    from text_generation import server, utils
  File "/root/autodl-tmp/text-generation-inference/server/text_generation/server.py", line 15, in <module>
    from text_generation.pb import generate_pb2_grpc, generate_pb2
  File "/root/autodl-tmp/text-generation-inference/server/text_generation/pb/generate_pb2_grpc.py", line 5, in <module>
    import generate_pb2 as generate__pb2
ModuleNotFoundError: No module named 'generate_pb2'`

**Comment by niguowei44** [comment]
can you tell me how to solve this peoblems?
Traceback (most recent call last):
  File "/root/rivermind-data/tgi_env/bin/text-generation-server", line 3, in <module>
    from text_generation_server.cli import app
  File "/root/rivermind-data/text-generation-inference/server/text_generation_server/cli.py", line 10, in <module>
    from text_generation_server.utils.adapter import parse_lora_adapters
  File "/root/rivermind-data/text-generation-inference/server/text_generation_server/utils/__init__.py", line 13, in <module>
    from text_generation_server.utils.tokens import (
  File "/root/rivermind-data/text-generation-inference/server/text_generation_server/utils/tokens.py", line 5, in <module>
    from text_generation_server.pb import generate_pb2
ImportError: cannot import name 'generate_pb2' from 'text_generation_server.pb' (unknown location)
