### ISSUE TITLE
What is the correct parameter combination for using dynamic RoPE scaling ?

### ISSUE THREAD

**Issue by hrushikesh198** [huggingface/text-generation-inference#782]
Hi Team, First of all thanks for the awesome piece of software !!

I want use `upstage/Llama-2-70b-instruct-v2` with `--max-input-length=8192 --max-total-tokens=10240` which originally supports`max_position_embeddings=4096`.

I tried passing the following command :

```
docker run -it --rm --gpus all --shm-size 80g --name llama2_70b_instruct_v2 -p 8560:80 -v ~/tgi_data:/data \
  ghcr.io/huggingface/text-generation-inference:sha-f91e9d2  --num-shard=8 \
  --model-id upstage/Llama-2-70b-instruct-v2 --revision 5f9c77b2c0397cf83d2f97740483f107c7109e8c \
  --dtype=float16 \
  --max-input-length=8192 --max-total-tokens=10240 --rope-scaling=dynamic --rope-factor=2.5 \
  --max-batch-prefill-tokens=40100 \
```
1. Does it look correct ?

Though this ended up with:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 727, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 825, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 813, in generate_token
    out = self.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 789, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 475, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 428, in forward
    cos, sin = self.layers[0].self_attn.rotary_emb.get_cos_sin(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 470, in get_cos_sin
    self._update_cos_sin_cache(dtype, position_ids.device, max_s)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 501, in _update_cos_sin_cache
    newbase = self.base * ((self.scaling_factor * seq_len / self.max_position_embeddings) - (self.scaling_factor - 1)) ** (self.dim / (self.dim - 2))
NameError: name 'seq_len' is not defined
```

2. Looks like typo in the code, should it have been `seqlen`  instead of `seq_len` ?

3. When I am using the above model without RoPE scaling on a 8xA100-40GB GPUs, it can churn out 1534 tokens per sec(TPS),  with an prompt heavy set up of ~883 input tokens, ~76 output tokens(best_of=1, so no hidden output tokens) per request. 
Is this expected performance or can I do better on the above set up?
FYI: tried fp16 on vllm, gptq(4bit), bitsandbytes(8bit) models all ended up with similar TPS.

**Comment by Narsil** [comment]
1. I think you don't need `factor` for dynamic most of the time (the factor will be applied, never tried myself, but my understanding is that it's not required).
2. Indeed https://github.com/huggingface/text-generation-inference/pull/783

> 3. Is this expected performance or can I do better on the above set up? 

I cannot tell you I haven't tried that particular setup. Performance measurements is always tricky and for actual loads I usually prefer live metrics from live systems rather than one off benchmarks. (Although those are super helpful understanding how your system behaves, I don't necessarily use them as a source of truth).

TPS is throughput and is really not what you want to be measuring imho. The critical measurement you want to be measuring is *latency* (that we usually refer to as `ms/token` and `text-generation-benchmark` will do just that.
Ideally you find the breaking point for memory-bound/compute-bound, and stop answering requests whenever you start becoming compute-bound (usually it's a number of stacked requests/tokens)

Throughput is important, but you generally don't want to have a running system close to throughput capacity, it will start to fall down rapidly whenever you get more load than throughput, so safety margins are important.
