### ISSUE TITLE
Cannot load LLaMA models saved with latest transformers

### ISSUE THREAD

**Issue by 0x1997** [huggingface/text-generation-inference#790]
### System Info

TGI: latest docker image.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

With this [PR](https://github.com/huggingface/transformers/pull/24998) merged, `inv_freq` tensors are not in the weights.

```
Shard complete standard error output:

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner

   model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 67, in __init__
    model = FlashLlamaForCausalLM(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 456, in __init__
    self.model = FlashLlamaModel(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 394, in __init__
    [

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 395, in <listcomp>
    FlashLlamaLayer(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 331, in __init__
    self.self_attn = FlashLlamaAttention(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 188, in __init__
    self.rotary_emb = PositionRotaryEmbedding.load(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 474, in load
    inv_freq = weights.get_tensor(f"{prefix}.inv_freq")

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 66, in get_tensor
    filename, tensor_name = self.get_filename(tensor_name)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 53, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist"

RuntimeError: weight model.layers.0.self_attn.rotary_emb.inv_freq does not exist
```

### Expected behavior

Create `inv_freq` tensors on the fly.

**Comment by monuminu** [comment]
even i am facing the same issue

**Comment by Narsil** [comment]
https://github.com/huggingface/text-generation-inference/pull/793

Fix in the works. Now we have to make sure this doesn't break older llama version (which current PR should). 
This `inv_freq` tensor is different on disk than what is calculated (no idea where the difference comes from). Therefore we should have a switch of some kind now.

**Comment by monuminu** [comment]
thank a lot.

**Comment by Narsil** [comment]
[sha-0e8b478](https://github.com/orgs/huggingface/packages/container/text-generation-inference/116722828?tag=sha-0e8b478)

Shoudl work, can you confirm ?

**Comment by 0x1997** [comment]
@Narsil Thanks. Currently blocked on #778 .
