### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by angel-luis** [huggingface/text-generation-inference#844]
### System Info

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti   WDDM  | 00000000:01:00.0  On |                  N/A |
| 26%   37C    P8              25W / 250W |    663MiB / 11264MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. `docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN -p 8080:80 -v "${PATH_DATA}:/data" ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id meta-llama/Llama-2-7b-chat-hf`

Full log:

```
2023-08-14 23:30:43 2023-08-14T21:30:43.980930Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-7b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "cac0f5610638", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-14 23:30:43 2023-08-14T21:30:43.981048Z  INFO download: text_generation_launcher: Starting download process.
2023-08-14 23:11:06 Error: ShardCannotStart
2023-08-14 23:30:46 2023-08-14T21:30:46.576644Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
2023-08-14 23:30:46 
2023-08-14 23:30:46 2023-08-14T21:30:46.884034Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-14 23:30:46 2023-08-14T21:30:46.884174Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-14 23:30:48 2023-08-14T21:30:48.728262Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2
2023-08-14 23:30:48 
2023-08-14 23:30:56 2023-08-14T21:30:56.766252Z ERROR text_generation_launcher: Error when initializing model
2023-08-14 23:30:56 Traceback (most recent call last):
2023-08-14 23:30:56   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-08-14 23:30:56     sys.exit(app())
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
2023-08-14 23:30:56     return get_command(self)(*args, **kwargs)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
2023-08-14 23:30:56     return self.main(*args, **kwargs)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
2023-08-14 23:30:56     return _main(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
2023-08-14 23:30:56     rv = self.invoke(ctx)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
2023-08-14 23:30:56     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
2023-08-14 23:30:56     return ctx.invoke(self.callback, **ctx.params)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
2023-08-14 23:30:56     return __callback(*args, **kwargs)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
2023-08-14 23:30:56     return callback(**use_params)  # type: ignore
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
2023-08-14 23:30:56     server.serve(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
2023-08-14 23:30:56     asyncio.run(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-08-14 23:30:56     return loop.run_until_complete(main)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
2023-08-14 23:30:56     self.run_forever()
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
2023-08-14 23:30:56     self._run_once()
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
2023-08-14 23:30:56     handle._run()
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
2023-08-14 23:30:56     self._context.run(self._callback, *self._args)
2023-08-14 23:30:56 > File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
2023-08-14 23:30:56     model = get_model(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
2023-08-14 23:30:56     return FlashLlama(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 67, in __init__
2023-08-14 23:30:56     model = FlashLlamaForCausalLM(config, weights)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 459, in __init__
2023-08-14 23:30:56     self.model = FlashLlamaModel(config, weights)
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 397, in __init__
2023-08-14 23:30:56     [
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 398, in <listcomp>
2023-08-14 23:30:56     FlashLlamaLayer(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 334, in __init__
2023-08-14 23:30:56     self.self_attn = FlashLlamaAttention(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 209, in __init__
2023-08-14 23:30:56     self.query_key_value = TensorParallelColumnLinear.load_multi(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 309, in load_multi
2023-08-14 23:30:56     weight = weights.get_multi_weights_col(
2023-08-14 23:30:56   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 138, in get_multi_weights_col
2023-08-14 23:30:56     weight = torch.cat(w, dim=dim)
2023-08-14 23:30:56 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 11.00 GiB total capacity; 10.89 GiB already allocated; 0 bytes free; 11.00 GiB allowed; 10.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2023-08-14 23:30:56 
2023-08-14 23:30:56 2023-08-14T21:30:56.892992Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-14 23:30:57 2023-08-14T21:30:57.693772Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
2023-08-14 23:30:57 
2023-08-14 23:30:57 You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
2023-08-14 23:30:57 Traceback (most recent call last):
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-08-14 23:30:57     sys.exit(app())
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
2023-08-14 23:30:57     server.serve(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
2023-08-14 23:30:57     asyncio.run(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-08-14 23:30:57     return loop.run_until_complete(main)
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2023-08-14 23:30:57     return future.result()
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
2023-08-14 23:30:57     model = get_model(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
2023-08-14 23:30:57     return FlashLlama(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 67, in __init__
2023-08-14 23:30:57     model = FlashLlamaForCausalLM(config, weights)
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 459, in __init__
2023-08-14 23:30:57     self.model = FlashLlamaModel(config, weights)
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 397, in __init__
2023-08-14 23:30:57     [
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 398, in <listcomp>
2023-08-14 23:30:57     FlashLlamaLayer(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 334, in __init__
2023-08-14 23:30:57     self.self_attn = FlashLlamaAttention(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 209, in __init__
2023-08-14 23:30:57     self.query_key_value = TensorParallelColumnLinear.load_multi(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 309, in load_multi
2023-08-14 23:30:57     weight = weights.get_multi_weights_col(
2023-08-14 23:30:57 
2023-08-14 23:30:57   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 138, in get_multi_weights_col
2023-08-14 23:30:57     weight = torch.cat(w, dim=dim)
2023-08-14 23:30:57 
2023-08-14 23:30:57 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 11.00 GiB total capacity; 10.89 GiB already allocated; 0 bytes free; 11.00 GiB allowed; 10.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2023-08-14 23:30:57  rank=0
2023-08-14 23:30:57 2023-08-14T21:30:57.793123Z ERROR text_generation_launcher: Shard 0 failed to start
2023-08-14 23:30:57 2023-08-14T21:30:57.793153Z  INFO text_generation_launcher: Shutting down shards
2023-08-14 23:30:57 Error: ShardCannotStart
```

### Expected behavior

I expect to work the 7b version of Llama2 as I have a 2080 TI with 11GB of VRAM.

**Comment by bloodsucker99** [comment]
I believe you need about 14gb to run a 7b HF. Try using the gptq version. You can even run a 13b model with gptq.

**Comment by angel-luis** [comment]
> I believe you need about 14gb to run a 7b HF. Try using the gptq version. You can even run a 13b model with gptq.

Thank you for your reply, I'm new with this and I've a couple of questions:
- Is better to use a quantized model like TheBloke models or use the command from Docker?
- There is any reference about VRAM on that models? I think I saw them on Reddit but I'm not sure

**Comment by phucdoitoan** [comment]
You can use --quantize tag with bitsandbytes or gptq to use quantized models for saving on VRAM (run text-generation-inference --help for more details).

If you use bitsandbytes, you can use the command. For GPTQ, I think you need to download model weights from TheBlock models beforehands. You can find more details in previous issues.

For VRAM, 4bit quantized models require VRAM of half the models size (7B => 3.5 GB, 13B => 7/8 GB)

**Comment by Narsil** [comment]
@angel-luis you can run 7b on 11GB of  VRAM, you have to reduce drastically your `--max-input-length`  and `--max-total-tokens`  in order to fit the VRAM.

This will limit the maximum amount of queries you're going to be able to do in parallel.

Quantization will also work fine, but quality may suffer.
