### ISSUE TITLE
Out of memory on 1xA100 for nf4-quantized-70b

### ISSUE THREAD

**Issue by 0xymoro** [huggingface/text-generation-inference#890]
### System Info

Single A100 from docker image on K8s GPU cloud, running nf4 quantized 70b Llama2.
Relevant parts of yaml/the command:
```
containers:
        - name: text-generation-container
          image: [ghcr.io/huggingface/text-generation-inference:sha-737d578](http://ghcr.io/huggingface/text-generation-inference:sha-737d578)
          args:
            [
              "--model-id",
              "/mnt/pvc/70b-model",
              "--quantize",
              "bitsandbytes-nf4",
              "--max-input-length",
              "3840",
              "--max-total-tokens",
              "4096",
              "--port",
              "80",
              "--max-concurrent-requests",
              "100",
            ]
          volumeMounts:
            - mountPath: /mnt/pvc
              name: model-data
            - mountPath: /dev/shm
              name: dshm
```

Logs
```
uter::server: router/src/server.rs:287: Success
2023-08-21T03:36:53.505435Z ERROR text_generation_launcher: Method Prefill encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 71, in Prefill
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 825, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 813, in generate_token
    out = self.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 789, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 478, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 437, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 381, in forward
    mlp_output = self.mlp(normed_attn_res_output)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 325, in forward
    gate_up_states = self.gate_up_proj(hidden_states)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 231, in forward
    return self.linear.forward(x)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 167, in forward
    out = bnb.matmul_4bit(
  File "/opt/conda/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, state).to(A.dtype).t(), bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 344.00 MiB (GPU 0; 79.15 GiB total capacity; 76.24 GiB already allocated; 338.56 MiB free; 79.15 GiB allowed; 77.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

2023-08-21T03:36:53.508540Z ERROR batch{batch_size=2}:prefill:prefill{id=16 size=2}:prefill{id=16 size=2}: text_generation_client: router/client/src/lib.rs:33: Server error: CUDA out of memory. Tried to allocate 344.00 MiB (GPU 0; 79.15 GiB total capacity; 76.24 GiB already allocated; 338.56 MiB free; 79.15 GiB allowed; 77.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Use nf4 quantization on some Llama 70b model
Run it on A100 like above
Curl simultaneous long requests at it

### Expected behavior

Max batch tokens should automatically infer the limit to not OOM, so this error shouldn't exist. Not sure if it has to do with nf4 quantization or some kind of overhead. I'm using the full 4096 token context of Llama 2, and it goes out of memory far before max tokens. 

Suspecting it's something from bitsandbytes from the error logs, but unsure what exactly.

**Comment by RonanKMcGovern** [comment]
70b in nf4 is going to be about 35 GB, so it's not that far from 40 GB VRAM... Is that potentially the issue?

**Comment by jerryMeng100** [comment]
Forgot to specify, this is a 80gb node. So it should still have plenty of room, I got a high max batch total like around 130k I believe.

**Comment by RonanKMcGovern** [comment]
What do you mean by "got a high max batch total like around 130k"?

How many concurrent requests are you running?

**Comment by jerryMeng100** [comment]
With flash attention, I see it infers max total batch tokens with respect to how much memory there is left on the GPU(s). With the amount of memory left the system thought 130k total tokens concurrently was workable.

I have a production service, it's servicing as many concurrent requests as it can (I don't quite see how many at once/at time of crash on the logs so can't say). But it's always running and batch processing requests.

**Comment by Narsil** [comment]
Does the bug happen without bnb ? If not maybe we should report upstream.
It's possible that bnb allocates it's own memory but during the warmup torch takes pretty much everything and therefore doesn't leave room for bnb internals ?

**Comment by Narsil** [comment]
Hacky fix if that's indeed the issue is to use `--cuda-memory-fraction 0.9` to force-keep some  free VRAM for bnb.

**Comment by luoziyong** [comment]
> Hacky fix if that's indeed the issue is to use `--cuda-memory-fraction 0.9` to force-keep some free VRAM for bnb.

This method does not solve the problem very well.

I noticed that warmup has applied for too much memory, which makes it easy to trigger Out of memory. It would be better to limit num_blocks value. maybe use `--max-batch-total-tokens`.

`
        free_memory = max(
            0, total_free_memory - (1 - MEMORY_FRACTION) * total_gpu_memory
        )

        num_blocks = (
            int(free_memory // total_cache_size)
            # Add batch.blocks as we allocated it above, so it is included in the peak memory.
            + CACHE_MANAGER.num_blocks
        )
`

**Comment by Narsil** [comment]
> - I noticed that warmup has applied for too much memory, which makes it easy to trigger Out of memory

Actually it prevents OOMs in production. We never run bnb because it's so slow, we keep it because it's convenient on constrained hardware where no GPTQ checkpoints exists, however GPTQ should be the way to go if you want correct latency.

The extra RAM usage of bnb is questionable I feel (especially if not triggered during warmup since this is where we're sending the largest matmul possible).

**Comment by luoziyong** [comment]
> > * I noticed that warmup has applied for too much memory, which makes it easy to trigger Out of memory
> 
> Actually it prevents OOMs in production. We never run bnb because it's so slow, we keep it because it's convenient on constrained hardware where no GPTQ checkpoints exists, however GPTQ should be the way to go if you want correct latency.
> 
> The extra RAM usage of bnb is questionable I feel (especially if not triggered during warmup since this is where we're sending the largest matmul possible).

I also encounter oom when using GPTQ for benchmark. My trick is to set a larger `--max-batch-prefill-tokens`, such as 32000, so that a larger batch of requests will be generated during warmup. Therefore, there is more available vram left. I think it may be that there is not enough vram reserved for tokenizer.

**Comment by Narsil** [comment]
@luoziyong GPTQ with exllama ? This shouldn't happen...

**Comment by luoziyong** [comment]
> @luoziyong GPTQ with exllama ? This shouldn't happen...

Yes, this is my command, the model is TheBloke/StableBeluga-7B-GPTQ

```python

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize gptq

text-generation-benchmark --sequence-length 1024 --decode-length 50 --tokenizer-name $model

```

**Comment by Narsil** [comment]
Oh `benchmark` bypasses the router so it can indeed cause oom. But the router should prevent issues.

Here I'm guessing having BS=32 with 1024 tokens is what kills it.

**Comment by luoziyong** [comment]
> Oh `benchmark` bypasses the router so it can indeed cause oom. But the router should prevent issues.
> 
> Here I'm guessing having BS=32 with 1024 tokens is what kills it.

Thanks, that's the reason! Benchmark use http never trigger oom.

**Comment by RonanKMcGovern** [comment]
Yeah I'm having the same issue with:
```
model=TheBloke/CodeLlama-7B-Instruct-GPTQ
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize gptq
```
I tried:
```
--max-batch-prefill-tokens 32000
```
and also:
```
--cuda-memory-fraction 0.9
```
This is a quantized Llama 7B model I'm running on a T4 (16 GB) GPU, so there should be lots of space.

And btw, there are no issues running bitsandbytes-nf4:
```
model=codellama/CodeLlama-7b-Instruct-hf
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize bitsandbytes-nf4
```

**Comment by RonanKMcGovern** [comment]
@Narsil any further info I can provide here to help diagnose?

**Comment by luoziyong** [comment]
@RonanKMcGovern  You can provide the server output and error message. 

The `--cuda-memory-fraction` doesn't have much effect on OOM, and the `--max-batch-prefill-tokens` only limit the total prefill batch tokens. if you use api the server will limit the prefill batch size, if you use benchmark the large prefill batch may cause OOM.

**Comment by RonanKMcGovern** [comment]
Sure, @luoziyong , here are the logs below. And the setup details are [above](https://github.com/huggingface/text-generation-inference/issues/890#issuecomment-1693965747)
```
2023-08-31T14:49:37.709899Z  INFO text_generation_router: router/src/main.rs:367: Serving revision 1c28ae8986f3a9aeee68c866f483ac408b94b545 of model TheBloke/CodeLlama-7B-Instruct-GPTQ
2023-08-31T14:49:37.724926Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-08-31T14:49:49.239172Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 727, in warmup
    _, batch = self.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 825, in generate_token
    raise e
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 813, in generate_token
    out = self.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 789, in forward
    return self.model.forward(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 478, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 437, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 381, in forward
    mlp_output = self.mlp(normed_attn_res_output)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 327, in forward
    return self.down_proj(self.act(gate_up_states[:, 0]) * gate_up_states[:, 1])
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/activations.py", line 150, in forward
    return nn.functional.silu(input)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/functional.py", line 2059, in silu
    return torch._C._nn.silu(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 60, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 729, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

2023-08-31T14:49:49.240979Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))
2023-08-31T14:49:49.303757Z ERROR text_generation_launcher: Webserver Crashed
2023-08-31T14:49:49.303785Z  INFO text_generation_launcher: Shutting down shards
2023-08-31T14:49:49.548458Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
Error: WebserverFailed
```

**Comment by luoziyong** [comment]
@RonanKMcGovern I don't know the reason. I test the gptq model on A10 gpu, it works fine.

**Comment by Narsil** [comment]
Have you tried disabling exllama `-e DISABLE_EXLLAMA=True` . I've managed to reproduce this bug on T4 (so relatively old GPU)

**Comment by RonanKMcGovern** [comment]
Yup @Narsil that allows me to run the gptq model with tgi (at least with curl commands). Thanks

**Comment by bruvduroiu** [comment]
> Yeah I'm having the same issue with:
> 
> ```
> model=TheBloke/CodeLlama-7B-Instruct-GPTQ
> volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run
> 
> docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize gptq
> ```
> 
> I tried:
> 
> ```
> --max-batch-prefill-tokens 32000
> ```
> 
> and also:
> 
> ```
> --cuda-memory-fraction 0.9
> ```
> 
> This is a quantized Llama 7B model I'm running on a T4 (16 GB) GPU, so there should be lots of space.
> 
> And btw, there are no issues running bitsandbytes-nf4:
> 
> ```
> model=codellama/CodeLlama-7b-Instruct-hf
> volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run
> 
> docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize bitsandbytes-nf4
> ```

Seeing the exact same issue on an NVIDIA T4 (EC2 `g4dn.xlarge` instance deployed into an EKS node pool).

Problem with GPTQ models but not BNB models.

TGI deployment current requests:

```
Limits:
cpu:             1
memory:          10Gi
nvidia.com/gpu:  1
Requests:
cpu:             10m
memory:          1Gi
nvidia.com/gpu:  1```

**Comment by RonanKMcGovern** [comment]
@bruvduroiu Have you tried disabling exllama  with '-e DISABLE_EXLLAMA=True' ?

Also, for gptq, make sure you have the latest transformers if running code-llama:
```
pip3 uninstall -y transformers
pip3 install git+https://github.com/huggingface/transformers.git
```

**Comment by bruvduroiu** [comment]
> @bruvduroiu Have you tried disabling exllama with '-e DISABLE_EXLLAMA=True' ?
> 
> Also, for gptq, make sure you have the latest transformers if running code-llama:
> 
> ```
> pip3 uninstall -y transformers
> pip3 install git+https://github.com/huggingface/transformers.git
> ```

Hi, for running TGI inside EKS I just stole the TGI image used for Sagemaker deployments, and ended up with this spec.


```yaml
    spec:
      containers:
      - env:
        - name: GPTQ_BITS
          value: "4"
        - name: GPTQ_GROUPSIZE
          value: "128"
        - name: HF_MODEL_ID
          value: TheBloke/llama2_7b_chat_uncensored-GPTQ
        - name: HF_MODEL_QUANTIZE
          value: gptq
        - name: SM_NUM_GPUS
          value: "1"
        - name: MAX_INPUT_LENGTH
          value: "1024"
        - name: MAX_TOTAL_TOKENS
          value: "2048"
        image: 763104351884.dkr.ecr.eu-west-1.amazonaws.com/huggingface-pytorch-tgi-inference:2.0.1-tgi0.9.3-gpu-py39-cu118-ubuntu20.04
        resources:
          limits:
            cpu: "3"
            memory: 14Gi
            nvidia.com/gpu: "1"
```

Turns out adding in the `GPTQ_{BITS,GROUPSIZE}` was the solution.

I didn't see a way to provide these environment variables in `ghcr.io/huggingface/text-generation-inference`. Am I missing something?
