### ISSUE TITLE
thread 'main' panicked at 'error binding to 0.0.0.0:80

### ISSUE THREAD

**Issue by mse700** [huggingface/text-generation-inference#895]
### Feature request

I am to run the falcon-7b-instruct on a cluster. I have defined the following deployment. yaml file. 
```
containers:
      - name: text-generation-container
        image: ghcr.io/huggingface/text-generation-inference:1.0.1
        args:  ["--model-id", "/models/falcon-7b-instruct"]
        env:
          - name: TRANSFORMERS_CACHE
            value: /model_dir
          - name: RUST_BACKTRACE
            value: 'full'
        volumeMounts:
          - name: dap-llms
            mountPath: /dap-llms
        ports:
          - containerPort: 80
```

Model is downloaded and is in models folder saved. When running the deployment, the following error appears:

```
2023-08-21T12:42:00.277507Z  INFO download: text_generation_launcher: Starting download process.
2023-08-21T12:42:02.737621Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-21T12:42:03.179662Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-21T12:42:03.179851Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-21T12:42:11.115456Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-21T12:42:11.186159Z  INFO shard-manager: text_generation_launcher: Shard ready in 8.005763181s rank=0
2023-08-21T12:42:11.284787Z  INFO text_generation_launcher: Starting Webserver
2023-08-21T12:42:11.362980Z  WARN text_generation_router: router/src/main.rs:191: no pipeline tag found for model /dap-llms/falcon-7b-instruct
2023-08-21T12:42:11.366076Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-08-21T12:42:12.799080Z  INFO text_generation_router: router/src/main.rs:243: Setting max batch total tokens to 2973744
2023-08-21T12:42:12.799103Z  INFO text_generation_router: router/src/main.rs:244: Connected
2023-08-21T12:42:12.799109Z  WARN text_generation_router: router/src/main.rs:249: Invalid hostname, defaulting to 0.0.0.0
thread 'main' panicked at 'error binding to 0.0.0.0:80: error creating server listener: Permission denied (os error 13)', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/server.rs:79:13
stack backtrace:
   0:     0x564694a6cb7a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564694a6cb7a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564694a6cb7a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x564694a6cb7a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x564694a93f8f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x564694a69075 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x564694a6c945 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x564694a6c945 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x564694a6ddae - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x564694a6db55 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x564694a6e30e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x564694a6e209 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x564694a6cfe6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x564694a6df62 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x564694095d73 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x5646949b4746 - hyper::server::server::Server<hyper::server::tcp::AddrIncoming,()>::bind::{{closure}}::h9f053bcea612f79f
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/server.rs:79:13
  16:     0x5646949b4746 - core::result::Result<T,E>::unwrap_or_else::h99d9f7d093e9f83f
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1464:23
  17:     0x5646949b4746 - hyper::server::server::Server<hyper::server::tcp::AddrIncoming,()>::bind::h8b5e9c4b57ced87e
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/server.rs:78:24
  18:     0x5646943087d3 - text_generation_router::server::run::{{closure}}::h6c1c060143d372f8
                               at /usr/src/router/src/server.rs:746:9
  19:     0x5646943087d3 - text_generation_router::main::{{closure}}::h244e8c765637c4e4
                               at /usr/src/router/src/main.rs:277:17
  20:     0x5646943024d3 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::hcf567e20152bfacb
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/park.rs:282:63
  21:     0x5646943024d3 - tokio::runtime::coop::with_budget::h2b741aeb7ce05a53
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/coop.rs:107:5
  22:     0x5646943024d3 - tokio::runtime::coop::budget::h09bd8bae1c9555fa
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/coop.rs:73:5
  23:     0x5646943024d3 - tokio::runtime::park::CachedParkThread::block_on::h358847dd700085b1
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/park.rs:282:31
  24:     0x56469432894e - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::ha023ebad65ac91b8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/context/blocking.rs:66:9
  25:     0x56469409ab83 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::hc128ba458e8e7923
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  26:     0x56469409ab83 - tokio::runtime::context::runtime::enter_runtime::ha0fba3747075bb03
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/context/runtime.rs:65:16
  27:     0x5646941d72f0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h5cc481d45f659c18
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  28:     0x56469417d23d - tokio::runtime::runtime::Runtime::block_on::h1f5dddb9120b5743
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/runtime.rs:349:45
  29:     0x5646940cdcff - text_generation_router::main::h9f574b653de04870
                               at /usr/src/router/src/main.rs:156:5
  30:     0x5646941edef3 - core::ops::function::FnOnce::call_once::h3abb177ca72e9851
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  31:     0x5646941edef3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h242542a113dd8b28
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  32:     0x5646941edf35 - std::rt::lang_start::{{closure}}::h9368e0b8ab32a532
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  33:     0x564694a62eee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  34:     0x564694a62eee - std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  35:     0x564694a62eee - std::panicking::try::hd8a722c09d156a53
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  36:     0x564694a62eee - std::panic::catch_unwind::hd2ca07971cf0119b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  37:     0x564694a62eee - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  38:     0x564694a62eee - std::panicking::try::do_call::hf47aa1aa005e5f1a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  39:     0x564694a62eee - std::panicking::try::h73d246b2423eaf4e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  40:     0x564694a62eee - std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  41:     0x564694a62eee - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  42:     0x5646941edf1e - std::rt::lang_start::h2f487392a54e0b35
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
  43:     0x7fef407c6083 - __libc_start_main
  44:     0x56469409643a - _start
  45:                0x0 - <unknown>
2023-08-21T12:42:13.686841Z ERROR text_generation_launcher: Webserver Crashed
2023-08-21T12:42:13.686864Z  INFO text_generation_launcher: Shutting down shards
2023-08-21T12:42:13.920050Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
Error: WebserverFailed
```

I would appreciate a solution.

### Motivation

I have not found the answer of my problem in similar issues e.g [here](https://github.com/huggingface/text-generation-inference/issues/830)

### Your contribution

Yes

**Comment by Narsil** [comment]
You're binding to port 80, this requires admin privileges.
