### ISSUE TITLE
Docker build killed while running setup.py

### ISSUE THREAD

**Issue by sohamparikh94** [huggingface/text-generation-inference#903]
### System Info

OS Version: Ventura 13.4.1 (c)

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

Run `docker build -f Dockerfile -t text-generation-inference .`

I see the following logs. It seems to fail because something went wrong in ninja
```
 => CANCELED [builder 10/10] RUN cargo build --release                                                         190.1s
------
 > [custom-kernels-builder 3/3] RUN python setup.py build:
#28 15.91 No CUDA runtime is found, using CUDA_HOME='/opt/conda'
#28 16.00 running build
#28 16.00 running build_ext
#28 16.36 /opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
#28 16.36   warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
#28 16.37 building 'custom_kernels.fused_bloom_attention_cuda' extension
#28 16.37 creating /usr/src/build
#28 16.38 creating /usr/src/build/temp.linux-x86_64-cpython-39
#28 16.38 creating /usr/src/build/temp.linux-x86_64-cpython-39/custom_kernels
#28 16.51 Emitting ninja build file /usr/src/build/temp.linux-x86_64-cpython-39/build.ninja...
#28 16.52 Compiling objects...
#28 16.52 Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
#28 408.2 [1/1] /opt/conda/bin/nvcc  -I/opt/conda/lib/python3.9/site-packages/torch/include -I/opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.9/site-packages/torch/include/TH -I/opt/conda/lib/python3.9/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.9 -c -c /usr/src/custom_kernels/fused_bloom_attention_cuda.cu -o /usr/src/build/temp.linux-x86_64-cpython-39/custom_kernels/fused_bloom_attention_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -arch=compute_80 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fused_bloom_attention_cuda -D_GLIBCXX_USE_CXX11_ABI=0
#28 408.2 FAILED: /usr/src/build/temp.linux-x86_64-cpython-39/custom_kernels/fused_bloom_attention_cuda.o 
#28 408.2 /opt/conda/bin/nvcc  -I/opt/conda/lib/python3.9/site-packages/torch/include -I/opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.9/site-packages/torch/include/TH -I/opt/conda/lib/python3.9/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.9 -c -c /usr/src/custom_kernels/fused_bloom_attention_cuda.cu -o /usr/src/build/temp.linux-x86_64-cpython-39/custom_kernels/fused_bloom_attention_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -arch=compute_80 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fused_bloom_attention_cuda -D_GLIBCXX_USE_CXX11_ABI=0
#28 408.2 /opt/conda/lib/python3.9/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
#28 408.2           detected during:
#28 408.2             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]" 
#28 408.2 (61): here
#28 408.2             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]" 
#28 408.2 /opt/conda/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h(77): here
#28 408.2 
#28 408.2 /opt/conda/lib/python3.9/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
#28 408.2           detected during:
#28 408.2             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]" 
#28 408.2 (61): here
#28 408.2             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]" 
#28 408.2 /opt/conda/lib/python3.9/site-packages/torch/include/ATen/core/qualified_name.h(73): here
#28 408.2 
#28 408.2 Killed
#28 408.2 ninja: build stopped: subcommand failed.
#28 408.6 Traceback (most recent call last):
#28 408.6   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
#28 408.7     subprocess.run(
#28 408.7   File "/opt/conda/lib/python3.9/subprocess.py", line 528, in run
#28 408.7     raise CalledProcessError(retcode, process.args,
#28 408.7 subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
#28 408.7 
#28 408.7 The above exception was the direct cause of the following exception:
#28 408.7 
#28 408.7 Traceback (most recent call last):
#28 408.7   File "/usr/src/setup.py", line 4, in <module>
#28 408.7     setup(
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
#28 408.7     return distutils.core.setup(**attrs)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
#28 408.7     return run_commands(dist)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#28 408.7     dist.run_commands()
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#28 408.7     self.run_command(cmd)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
#28 408.7     super().run_command(command)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#28 408.7     cmd_obj.run()
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
#28 408.7     self.run_command(cmd_name)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#28 408.7     self.distribution.run_command(command)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
#28 408.7     super().run_command(command)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#28 408.7     cmd_obj.run()
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
#28 408.7     _build_ext.run(self)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
#28 408.7     self.build_extensions()
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
#28 408.7     build_ext.build_extensions(self)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
#28 408.7     self._build_extensions_serial()
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
#28 408.7     self.build_extension(ext)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
#28 408.7     _build_ext.build_extension(self, ext)
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
#28 408.7     objects = self.compiler.compile(
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
#28 408.7     _write_ninja_file_and_compile_objects(
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
#28 408.7     _run_ninja_build(
#28 408.7   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
#28 408.7     raise RuntimeError(message) from e
#28 408.7 RuntimeError: Error compiling objects for extension
------
executor failed running [/bin/sh -c python setup.py build]: exit code: 1
```

### Expected behavior

the image builds without any error

**Comment by Narsil** [comment]
Sorry building the docker image is something we take care of and have no interest of maintaining on arbitrary envs.

Either use the local CLI or the released docker image.
