### ISSUE TITLE
UnpicklingError: could not find MARK

### ISSUE THREAD

**Issue by angel-luis** [huggingface/text-generation-inference#909]
### System Info

Windows 11

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
$NAME="Llama-2-13B-chat-GGML";
$AUTHOR="TheBloke";
$PATH_DATA="${PWD}/${NAME}";
docker run --name $NAME --gpus all --shm-size 1g -p 8080:80 -v "${PATH_DATA}:/data" ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id "${AUTHOR}/${NAME}"
```

The error:
```
2023-08-23 10:19:20 2023-08-23T08:19:20.910728Z  WARN text_generation_launcher: No safetensors weights found for model TheBloke/Llama-2-13B-chat-GGML at revision None. Converting PyTorch weights to safetensors.
2023-08-23 10:19:20 
2023-08-23 10:19:21 2023-08-23T08:19:21.848514Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):
2023-08-23 10:19:21 
2023-08-23 10:19:21   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-08-23 10:19:21     sys.exit(app())
2023-08-23 10:19:21 
2023-08-23 10:19:21   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 192, in download_weights
2023-08-23 10:19:21     utils.convert_files(local_pt_files, local_st_files, discard_names)
2023-08-23 10:19:21 
2023-08-23 10:19:21   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 106, in convert_files
2023-08-23 10:19:21     convert_file(pt_file, sf_file, discard_names)
2023-08-23 10:19:21 
2023-08-23 10:19:21   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 65, in convert_file
2023-08-23 10:19:21     loaded = torch.load(pt_file, map_location="cpu")
2023-08-23 10:19:21 
2023-08-23 10:19:21   File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 815, in load
2023-08-23 10:19:21     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
2023-08-23 10:19:21 
2023-08-23 10:19:21   File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 1033, in _legacy_load
2023-08-23 10:19:21     magic_number = pickle_module.load(f, **pickle_load_args)
2023-08-23 10:19:21 
2023-08-23 10:19:21 _pickle.UnpicklingError: could not find MARK
```

### Expected behavior

I'm trying to load a model without safetensors and I expect `text_generation_launcher` do that process for me.

**Comment by Narsil** [comment]
GGML format are not supported, you're looking for `-GPTQ` if you want quantization (and add `--quantize gptq` flag).
