### ISSUE TITLE
ValidationErrors running Llama-2-7b-chat-hf

### ISSUE THREAD

**Issue by andersRuge** [huggingface/text-generation-inference#914]
### System Info

I'm trying to run this command:

```
model=meta-llama/Llama-2-7b-chat-hf
token=<hf_token>
volume=$PWD/data
num_shard=1
quantize=bitsandbytes


docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize $quantize --num-shard $num_shard
```

Trying to query it using:

```
from text_generation import Client

client = Client("http://127.0.0.1:8080")
print(client.generate("What is Deep Learning?", max_new_tokens=20).generated_text)
```

And I get this error:
```
ValidationError                           Traceback (most recent call last)
/tmp/ipykernel_14959/2215116563.py in <module>
      2 
      3 client = Client("http://127.0.0.1:8080")
----> 4 print(client.generate("What is Deep Learning?", max_new_tokens=20).generated_text)
      5 
      6 #text = ""

/usr/local/lib/python3.10/dist-packages/text_generation/client.py in generate(self, prompt, do_sample, max_new_tokens, best_of, repetition_penalty, return_full_text, seed, stop_sequences, temperature, top_k, top_p, truncate, typical_p, watermark, decoder_input_details)
    148         if resp.status_code != 200:
    149             raise parse_error(resp.status_code, payload)
--> 150         return Response(**payload[0])
    151 
    152     def generate_stream(

/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 20 validation errors for Response
details -> tokens -> 0 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 1 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 2 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 3 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 4 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 5 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 6 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 7 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 8 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 9 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 10 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 11 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 12 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 13 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 14 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 15 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 16 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 17 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 18 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
details -> tokens -> 19 -> logprob
  none is not an allowed value (type=type_error.none.not_allowed)
```

I am trying to run it on a P100:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:01:00.0 Off |                    0 |
| N/A   28C    P0    25W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Steps to reproduce:

1. Spin up model: 
```
model=meta-llama/Llama-2-7b-chat-hf
token=<hf_token>
volume=$PWD/data
num_shard=1
quantize=bitsandbytes


docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize $quantize --num-shard $num_shard
```

2. Query it:
```
from text_generation import Client

client = Client("http://127.0.0.1:8080")
print(client.generate("What is Deep Learning?", max_new_tokens=20).generated_text)
```

### Expected behavior

I would expect a text output of some kind. Preferably answering the questions posed to the model.

**Comment by andersRuge** [comment]
Calling the endpoint from terminal yields the same result. E.g.

Calling
```
curl 127.0.0.1:8080/generate_stream \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
    -H 'Content-Type: application/json'
```

Yields:
```
curl 127.0.0.1:8080/generate_stream \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
    -H 'Content-Type: application/json'
data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":null,"details":null}

data:{"token":{"id":0,"text":"<unk>","logprob":null,"special":true},"generated_text":"","details":null}
```

**Comment by RonanKMcGovern** [comment]
can you check your docker logs?

'docker ps' to see the running containers

then

'docker logs < container name or number >'

**Comment by andersRuge** [comment]
Hi @RonanKMcGovern 

Here are the logs:

```
2023-08-24T12:32:48.759882Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-7b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: Some(1), quantize: Some(Bitsandbytes), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "567b65277267", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: true, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-24T12:32:48.760032Z  INFO download: text_generation_launcher: Starting download process.
2023-08-24T12:32:56.976915Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-24T12:32:57.896231Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-24T12:32:57.896854Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-24T12:33:01.228462Z  WARN text_generation_launcher: We're not using custom kernels.

2023-08-24T12:33:01.305283Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: GPU with CUDA capability 6 0 is not supported

2023-08-24T12:33:07.918577Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-24T12:33:17.941985Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-24T12:33:27.965235Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-24T12:33:32.411557Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-24T12:33:32.475463Z  INFO shard-manager: text_generation_launcher: Shard ready in 34.576565335s rank=0
2023-08-24T12:33:32.539929Z  INFO text_generation_launcher: Starting Webserver
2023-08-24T12:33:33.077535Z  WARN text_generation_router: router/src/main.rs:345: `--revision` is not set
2023-08-24T12:33:33.077565Z  WARN text_generation_router: router/src/main.rs:346: We strongly advise to set it to a known supported commit.
2023-08-24T12:33:33.289274Z  INFO text_generation_router: router/src/main.rs:367: Serving revision 08751db2aca9bf2f7f80d2e516117a53d7450235 of model meta-llama/Llama-2-7b-chat-hf
2023-08-24T12:33:33.306746Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-08-24T12:33:43.603004Z  WARN text_generation_router: router/src/main.rs:221: Model does not support automatic max batch total tokens
2023-08-24T12:33:43.603063Z  INFO text_generation_router: router/src/main.rs:243: Setting max batch total tokens to 16000
2023-08-24T12:33:43.603075Z  INFO text_generation_router: router/src/main.rs:244: Connected
2023-08-24T12:33:43.603087Z  WARN text_generation_router: router/src/main.rs:249: Invalid hostname, defaulting to 0.0.0.0
2023-08-24T12:37:04.989015Z  INFO HTTP request{otel.name=POST / http.client_ip= http.flavor=1.1 http.host=127.0.0.1:8080 http.method=POST http.route=/ http.scheme=HTTP http.target=/ http.user_agent=python-requests/2.25.1 otel.kind=server trace_id=3aaa52061cc38b8daec4654b40c0450f}:compat_generate{default_return_full_text=true}:generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: 20, return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None } total_time="3.71162094s" validation_time="897.344µs" queue_time="172.642µs" inference_time="3.710551454s" time_per_token="185.527572ms" seed="None"}: text_generation_router::server: router/src/server.rs:287: Success
```

**Comment by Narsil** [comment]
Do you have the same issue on other quantization schemes ? (not bitsandbytes).

Could be an issue in bnb kernel for that particular GPU ?

**Comment by andersRuge** [comment]
Hi @Narsil ,

Every other quantization scheme I tried: ["bitsandbytes-nf4", "bitsandbytes-fp4", "gptq"] causes an OOM error while warming up the model.

I am only able to load it using: "bitsandbytes". I am however able to run it like I normally would through ```transformers.AutoModelForCausalLM.from_pretrained```

With the following quantization:

```
bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=bfloat16
)
```
Any ideas as to what I can try?

**Comment by chris-aeviator** [comment]
confirming being affected by this while pulling tgi docker today, deploying llama 2 7b. Every other schema than 'bitsandbytes' errors in OOM and using the @huggingface/inference nodeJS client I receive a stream of <unk> tokens

**Comment by chris-aeviator** [comment]
it seems this is compute capability related, when spinning up the same configuration on a 1080 I get the UNK tokens when using an A10G I get correct text, both with --quantization bitsandbytes

**Comment by Narsil** [comment]
So most likely an issue to report upstream ?

**Comment by chris-aeviator** [comment]
That’s not the consequence I would take from what I’m seeing. Let’s see what OPs environment / hardware is

**Comment by Narsil** [comment]
Seems like a duplicate  of https://github.com/huggingface/text-generation-inference/issues/890#issuecomment-1692818807 actually..

**Comment by chris-aeviator** [comment]
@Narsil it turns out this seems to be rather a transformers/peft/accelerate issue with the version requirements currently used.

I'm able to successfully generate with quantize=bitsandbytes when using pip3 install git+https://github.com/huggingface/transformers[/bitsandbytes/accelerate] and changing TGI to do load_in_4bit instead of load_in_8_bit on a pascal GPU when loading from a local model.

https://github.com/ohmytofu-ai/tgi-angryface/blob/main/server/text_generation_server/models/causal_lm.py#L484

**Comment by andersRuge** [comment]
@chris-aeviator do you need feedback from me on my hardware / environtment setup? Or do you have a way to fix it, since you were able to replicate by changing your local setup?

**Comment by chris-aeviator** [comment]
The HF team needs to discuss their will to support last/ old gen hardware and enhancing TGI to support more inference types like 4 bit inference (8bit seems to play not well with many things HF & Pascal)  and most importantly testsuites that make sure these things are caught early on. I decided to start my own TGI since these all seem to be non-prio for HF, but a complete showstopper for me.

@andersRuge re-reading your OP it seems you are running into the Nvidia Pascal Gen. issues that I did, so feel free to work with my code, 4bit for Llama works there, as well as loading local LORAs ontop without merging them.

**Comment by Narsil** [comment]
> The HF team needs to discuss their will to support last/ old gen hardware and enhancing TGI

We simply don't.
We rely on flash-attention v1/2 + PagedAttention in order to make TGI fast. Those kernels are written against recent cuda/GPU.
There's nothing we can do about it. (Part of it might be writeable for old archs, but parts of those kernels actually make use of newer features.).

Old GPUs arch we try to have a graceful degradation, but rely on external tools (Bitsanbytes, flash, paged, exllama, gptq..) to declare what arch/GPU they support. They probably try there best to fail correctly and work correctly on that matrix.
That matrix is HARD to work with, as cuda/GPU versions match are really really hard to work with.

As for the original issue, if upgrading bitsandbytes fixes then maybe we should just fix that.

@andersRuge Can you try installing from source and upgrading bitsandbytes see if that works ?
https://github.com/huggingface/text-generation-inference#local-install

**Comment by ahmedbr** [comment]
> it seems this is compute capability related, when spinning up the same configuration on a 1080 I get the UNK tokens when using an A10G I get correct text, both with --quantization bitsandbytes

I'm getting empty generated_text when doing the above.

**Comment by andersRuge** [comment]
@Narsil I have tried running it locally, and get the following issue:

```
text-generation-launcher --model-id meta-llama/Llama-2-7b-chat-hf --port 8080 --quantize bitsandbytes
2023-08-30T09:29:28.958093Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-7b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Bitsandbytes), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "0.0.0.0", port: 8080, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-30T09:29:28.958439Z  INFO download: text_generation_launcher: Starting download process.
2023-08-30T09:29:31.841432Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-30T09:29:32.366623Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-30T09:29:32.367083Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-30T09:29:35.099777Z  WARN text_generation_launcher: We're not using custom kernels.

2023-08-30T09:29:35.103257Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'

2023-08-30T09:29:42.227872Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-30T09:29:42.283918Z  INFO shard-manager: text_generation_launcher: Shard ready in 9.915451698s rank=0
2023-08-30T09:29:42.383043Z  INFO text_generation_launcher: Starting Webserver
2023-08-30T09:29:42.649129Z  WARN text_generation_router: router/src/main.rs:349: `--revision` is not set
2023-08-30T09:29:42.649162Z  WARN text_generation_router: router/src/main.rs:350: We strongly advise to set it to a known supported commit.
2023-08-30T09:29:43.211058Z  INFO text_generation_router: router/src/main.rs:371: Serving revision 08751db2aca9bf2f7f80d2e516117a53d7450235 of model meta-llama/Llama-2-7b-chat-hf
2023-08-30T09:29:43.222241Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-08-30T09:29:51.742240Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/root/miniconda3/envs/text-generation-inference/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/aruge/text-generation-inference/server/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/home/aruge/text-generation-inference/server/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/home/aruge/text-generation-inference/server/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/home/aruge/text-generation-inference/server/text_generation_server/server.py", line 66, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/home/aruge/text-generation-inference/server/text_generation_server/models/model.py", line 59, in warmup
    self.generate_token(batch)
  File "/root/miniconda3/envs/text-generation-inference/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/aruge/text-generation-inference/server/text_generation_server/models/causal_lm.py", line 579, in generate_token
    batch_top_token_ids, batch_top_token_logprobs = batch_top_tokens(
  File "/home/aruge/text-generation-inference/server/text_generation_server/utils/tokens.py", line 368, in batch_top_tokens
    top_k = torch.topk(logprobs, k=top_n_ishes.max(), dim=1, sorted=True)
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

2023-08-30T09:29:51.747991Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
Error: Warmup(Generation("max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument."))
2023-08-30T09:29:51.803806Z ERROR text_generation_launcher: Webserver Crashed
2023-08-30T09:29:51.803861Z  INFO text_generation_launcher: Shutting down shards
2023-08-30T09:29:51.969319Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
Error: WebserverFailed
make: *** [Makefile:52: run-Llama-2-7b-chat-hf] Error 1
```

My pip freeze returns:

```
accelerate==0.20.3
aiohttp==3.8.5
aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.1.0
backoff==2.2.1
bitsandbytes==0.41.1
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
cmake==3.27.2
datasets==2.14.4
Deprecated==1.2.14
dill==0.3.7
einops==0.6.1
filelock==3.12.3
frozenlist==1.4.0
fsspec==2023.6.0
googleapis-common-protos==1.60.0
grpc-interceptor==0.15.3
grpcio==1.57.0
grpcio-reflection==1.57.0
grpcio-status==1.57.0
grpcio-tools==1.51.1
hf_transfer==0.1.3
huggingface-hub==0.16.4
idna==3.4
Jinja2==3.1.2
lit==16.0.6
loguru==0.6.0
MarkupSafe==2.1.3
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.15
mypy-protobuf==3.4.0
networkx==3.1
numpy==1.25.2
opentelemetry-api==1.15.0
opentelemetry-exporter-otlp==1.15.0
opentelemetry-exporter-otlp-proto-grpc==1.15.0
opentelemetry-exporter-otlp-proto-http==1.15.0
opentelemetry-instrumentation==0.36b0
opentelemetry-instrumentation-grpc==0.36b0
opentelemetry-proto==1.15.0
opentelemetry-sdk==1.15.0
opentelemetry-semantic-conventions==0.36b0
packaging==23.1
pandas==2.0.3
peft==0.4.0
Pillow==10.0.0
protobuf==4.24.2
psutil==5.9.5
pyarrow==13.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sympy==1.12
-e git+https://github.com/huggingface/text-generation-inference.git@5485c142e87a182f2eee713a6b056ee38bd901f5#egg=text_generation_server&subdirectory=server
texttable==1.6.7
tokenizers==0.13.3
torch==2.0.1+cu118
tqdm==4.66.1
transformers==4.30.2
triton==2.0.0
typer==0.6.1
types-protobuf==4.24.0.1
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4
wrapt==1.15.0
xxhash==3.3.0
yarl==1.9.2
```
I had to downgrade transformers to 4.30.2 to resolve this issue:

```
ValueError: Calling `cuda()` is not supported for `4-bit` or `8-bit` quantized models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
```

**Comment by Narsil** [comment]
That means you're not using flash and using `transformers` graceful downgrading.

The graceful downgrades are a "best effort". (Meaning we'll try to make it compatible, but we cannot and will not every possible configuration)

**Comment by andersRuge** [comment]
So what are my options? Different hardware? Enabling flash?

**Comment by Narsil** [comment]
Different hardware will work. (anything compute_cap >7.5 if I'm not mistaken for your command line).

Stick to docker, it keeps everything in the same place, meaning it should work better than the CLI in most cases (as it controls the entire environment except for host cuda). For instance the latest error you show is in `torch`. I'm not sure if it's because it's a special torch build or different install. We run our integration tests against the docker for instance.

Docker will use flash when available, downgrade itself when it doesn't work.
`make install-flash-attention` will work if you work locally (if the GPU allows).
