### ISSUE TITLE
Why can't load TheBloke/Wizard-Vicuna-30B-Uncensored-GPTQ?

### ISSUE THREAD

**Issue by angel-luis** [huggingface/text-generation-inference#920]
### System Info

Windows 11 but using Docker image

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
$NAME="Wizard-Vicuna-30B-Uncensored-GPTQ";
$AUTHOR="TheBloke";
docker run --name $NAME --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN -p 8080:80 -v "${PATH_DATA}:/data" ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id "${AUTHOR}/${NAME}" --max-total-tokens 4096
```

Also tried with `--quantize bitsandbytes` and `--quantize qptq` (that is the correct approach, but same error)

And also tried the previous version of the image `1.0.1`. 

The error I got:
```
2023-08-24T19:56:43.821694Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 185, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 67, in __init__
    model = FlashLlamaForCausalLM(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 459, in __init__
    self.model = FlashLlamaModel(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 397, in __init__
    [

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 398, in <listcomp>
    FlashLlamaLayer(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 334, in __init__
    self.self_attn = FlashLlamaAttention(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 209, in __init__
    self.query_key_value = TensorParallelColumnLinear.load_multi(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 309, in load_multi
    weight = weights.get_multi_weights_col(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 137, in get_multi_weights_col
    w = [self.get_sharded(f"{p}.weight", dim=0) for p in prefixes]

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 137, in <listcomp>
    w = [self.get_sharded(f"{p}.weight", dim=0) for p in prefixes]

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 102, in get_sharded
    filename, tensor_name = self.get_filename(tensor_name)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 53, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")

RuntimeError: weight model.layers.0.self_attn.q_proj.weight does not exist
```

### Expected behavior

I'm trying to learn every day but the info is overwhelming for me. I believe that it should work as the model includes the `safetensors` and the `config.json` includes the `quantization_config` settings required for TGI (the method, the bits...).

**Comment by Narsil** [comment]
You need `--quantize gptq`.

GPTQ models and non quantized don't have the same weights.

**Comment by angel-luis** [comment]
But is very weird because I've used that command, and I get the same error as when I use the bitsandbytes quantization or without any quantization. So it must be an error previously to the quantization.

**Comment by Narsil** [comment]
You shouldn't get the same error. .

The particular weight means it's searching for NON quantized weights (which are obviously missing on quantized ones)

**Comment by angel-luis** [comment]
For the purpose of research, this morning I have been trying to load some models. Very slow process as I have a limited internet connection.

In this case, it was weird so I deleted the model and container, and started the process again. Then the error message changed a bit:
```
ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 187, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 68, in __init__
    model = FlashLlamaForCausalLM(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 459, in __init__
    self.model = FlashLlamaModel(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 397, in __init__
    [

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 398, in <listcomp>
    FlashLlamaLayer(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 334, in __init__
    self.self_attn = FlashLlamaAttention(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 209, in __init__
    self.query_key_value = TensorParallelColumnLinear.load_multi(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 333, in load_multi
    weight = weights.get_multi_weights_col(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 129, in get_multi_weights_col
    w = [self.get_tensor(f"{p}.g_idx") for p in prefixes]

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 129, in <listcomp>
    w = [self.get_tensor(f"{p}.g_idx") for p in prefixes]

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 66, in get_tensor
    filename, tensor_name = self.get_filename(tensor_name)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 53, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")

RuntimeError: weight model.layers.0.self_attn.q_proj.g_idx does not exist
```

Unfortunately the error `g_idx does not exist` was repeated for many GPTQ models from TheBloke.

For models without quantize like `Open-Orca/OpenOrca-Platypus2-13B` after download it, it gives the error:
```
WARN text_generation_launcher: No safetensors weights found for model Open-Orca/OpenOrca-Platypus2-13B at revision None. Converting PyTorch weights to safetensors.

Error: DownloadError
ERROR download: text_generation_launcher: Download process was signaled to shutdown with signal 9:
```

Other models from `meta-llama` worked fine.

**Comment by angel-luis** [comment]
Sorry about merge two different errors in a single thread.

After some searching I've found that:
`Download process was signaled to shutdown with signal 9`
Is about lack of RAM. In my case, using WSL and by default assigns the 50% of the computer RAM, having 16GB of the 22 required. I've fixed that creating a `.wslconfig` with more RAM.

About the error `g_idx does not exist` I didn't found nothing. I don't even know what it means. 😅 I wish to know some terminology to try to fix some bugs but I think there aren't courses about this.

**Comment by Narsil** [comment]
Any chance you're using environment variables not the actual CLI flags, and use `:latest` not the actual tag ?

Colleague of mine hit this, and was just running a very old TGI version.
(Env variables are not checked like CLI, and old version just didn't have GTPQ support)

**Comment by angel-luis** [comment]
Same error; I've removed the environment variables as I don't need it in this case and also tried with the `:latest` tag.

**Comment by Narsil** [comment]
Ohh sorry I read too fast the *second* error you shared. 
`g_idx` missing is an issue with old quantization script from the bloke (at a time, where GPTQ wasn't very streamlined..

TGI expects this tensor to exist (it makes sharding MUCH easier to read).
Technically this tensor can be inferred, and it needs to be recreated for the kernel. It's just that now every new models do output this tensor, therefore TGI just relies on it.

**Comment by angel-luis** [comment]
Thank you very much! I close the issue so we can only use the latest uploaded models with TGI and there is no fix for that.
