### ISSUE TITLE
Cannot load larger CodeLlama models

### ISSUE THREAD

**Issue by spew** [huggingface/text-generation-inference#922]
### System Info

Using image ghcr.io/huggingface/text-generation-inference:latest with Id: sha256:e8c9985b0bbe3a4e745e3492cd5f4d71a2672f8afa41d1fb0ebab5233c6bc29b

### Information

- [x] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

I am able to use `text-generation-inference` to load the `CodeLlama-7b-hf` model. However, when using the `CodeLlama-13b-hf` or `CodeLlama-34b-hf` I see the following error:

```
2023-08-24T21:08:24.228883Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 192, in download_weights
    utils.convert_files(local_pt_files, local_st_files, discard_names)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 106, in convert_files
    convert_file(pt_file, sf_file, discard_names)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 68, in convert_file
    to_removes = _remove_duplicate_names(loaded, discard_names=discard_names)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 32, in _remove_duplicate_names
    raise RuntimeError(

RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'model.norm.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.
```

### Expected behavior

Expect the server to load the model properly.

**Comment by spew** [comment]
@Narsil since you recently changed something related to CodeLlama.

**Comment by theblackcat102** [comment]
Issue seems to be the validation phase on model.norm.weight tensor has some weird properties when calling _is_complete under [_remove_duplicate_names](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/utils/convert.py#L12)

```
>>> from safetensors.torch import save_file, load_file, _find_shared_tensors, _is_complete, storage_ptr, storage_size
>>> tensor = state_dict['model.norm.weight']
>>> tensor.data_ptr()
139976225415232
>>> storage_ptr(tensor)
139976094343232
>>> tensor.nelement() * _SIZE[tensor.dtype] == storage_size(tensor)
False
>>> tensor.nelement() * _SIZE[tensor.dtype]
16384
>>> storage_size(tensor)
262160384
>>> tensor.dtype
torch.bfloat16
>>> tensor.nelement()
8192
>>> tensor.untyped_storage().nbytes()
262160384
```

For one the storage size is bit weird on this tensor (way larger than ) listed

**Comment by theblackcat102** [comment]
A current workaround is simply convert the last shard yourself.

I have to download the entire repo, and run the last safetensor conversion myself

```
from safetensors.torch import save_file
save_file(state_dict, "path to checkpoint")
```

**Comment by Narsil** [comment]
Thanks for the report, we're looking into it, might be an issue with the original checkpoint here.

**Comment by skapadia-zalando** [comment]
For what it's worth it works for me now

**Comment by Narsil** [comment]
Yes the checkpoints were fixed. Thanks for the report and the ping. Closing now.

**Comment by JulesBelveze** [comment]
Hey all, I am hitting the same problem with `PygmalionAI/pygmalion-6b` and `PygmalionAI/pygmalion-2.7b`, when running the following command:
```
docker run \
  --gpus all \
  --shm-size 1g \
  -e HF_HUB_ENABLE_HF_TRANSFER=False \
  -e HUGGING_FACE_HUB_TOKEN=$token \
  -p 8080:80 \
  -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.1 \
  --model-id $model \
  --dtype=float16 \
  --disable-custom-kernels
```

see trace here:
```
....  WARN text_generation_launcher: No safetensors weights found for model PygmalionAI/pygmalion-6b at revision None. Converting PyTorch weights to safetensors.

Error: DownloadError
Downloading (…)l-00002-of-00002.bin: 100%|██████████| 5.94G/5.94G [01:17<00:00, 76.3MB/s]d an error:
Downloading (…)lve/main/config.json: 100%|██████████| 975/975 [00:00<00:00, 387kB/s]
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 192, in download_weights
    utils.convert_files(local_pt_files, local_st_files, discard_names)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 106, in convert_files
    convert_file(pt_file, sf_file, discard_names)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 68, in convert_file
    to_removes = _remove_duplicate_names(loaded, discard_names=discard_names)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/convert.py", line 32, in _remove_duplicate_names
    raise RuntimeError(

RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'transformer.wte.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.
```

However, it does work properly with `PygmalionAI/pygmalion-1.3b` which supports `SafeTensors`. Any recommendation @Narsil ?

**Comment by Narsil** [comment]
Try using `1.0.3` . Those odd checkpoints are usually generated by deepspeed which messes around with storage (which indeed regularly leads to unnecessary storage usage on disk).

`1.0.3` upgrade to `safetensors==0.3.3` which takes care of it (by looking more deeply into storage + tensor mess to ignore the unnecessary storage).

**Comment by JulesBelveze** [comment]
@Narsil getting the same error with `1.0.3`. Any guidance on how to fix the checkpoints?

**Comment by Narsil** [comment]
Simplest I recommend would be using `transformers`:

```
from transformers import pipeline
pipe = pipeline(model="PygmalionAI/pygmalion-6b')
pipe.save_pretrained(safe_serialization=True)
```

If that doesn't work you can always nuke everything

```
weights = torch.load("xx")
weights = weights = {k: v.clone().contiguous() for k, v in weights.items()}
save_file(weights, "new.safetensors")
```

This might lead to extra storage with unwanted tensors possibly (some tensors could end up being duplicates).

**Comment by JulesBelveze** [comment]
I'll look into that thanks 🤓

**Comment by JulesBelveze** [comment]
Hey @Narsil as you predicted it lead to tensor duplicates (the checkpoints size increased by almost a factor 2) 😥
