### ISSUE TITLE
`You are using a model of type llama to instantiate a model of type .`

### ISSUE THREAD

**Issue by Cyberes** [huggingface/text-generation-inference#929]
### System Info

Version: `ghcr.io/huggingface/text-generation-inference:latest`
Model: `TheBloke/MythoMax-L2-13B-GPTQ:gptq-4bit-128g-actorder_True`
GPU: Nvidia A4000
Ubuntu 22.04

### Issue

I'm trying to run the Docker container but encountering the error `You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.` during the "Warming up model" part and after  allocating 11GB of GPU memory.

I tried adding `-e GPTQ_BITS=4 -e GPTQ_GROUPSIZE=128` but that made no difference. I also did my research and read almost every issue on this repo but I don't think this problem has been encountered before.

Also tried adding `DISABLE_EXLLAMA=True`

### Docker Command
```
sudo docker run --gpus all --shm-size 5g -p 8183:80 \
        --runtime=nvidia \
        -v /storage/text-generation-inference/docker/data:/data ghcr.io/huggingface/text-generation-inference:latest \
        --model-id TheBloke/MythoMax-L2-13B-GPTQ --revision gptq-4bit-128g-actorder_True \
        --quantize gptq    
```

### Logs
<details>
  <summary>Command Ouput</summary>

```
2023-08-26T23:55:35.854791Z  INFO text_generation_launcher: Args { model_id: "TheBloke/MythoMax-L2-13B-GPTQ", revision: Some("gptq-4bit-128g-actorder_True"), validation_workers: 2, sharded: None, num_shard: Some(1), quantize: Some(Gptq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "9f8054981ef0", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-26T23:55:35.855120Z  INFO download: text_generation_launcher: Starting download process.
2023-08-26T23:55:42.115911Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-26T23:55:42.966478Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-26T23:55:42.967019Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-26T23:55:50.341447Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.506312Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.558788Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.631771Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.684478Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.755956Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.808272Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.878371Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.930356Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:50.999522Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.058761Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.140228Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.197339Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.277385Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.333274Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.412191Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.468466Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.544203Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.598740Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.673087Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.738228Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.829787Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.899165Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:51.986018Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.053955Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.140754Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.201983Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.284596Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.347910Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.429569Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.495493Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.580749Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.649547Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.735419Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.798945Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.881939Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.948323Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:52.991872Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-26T23:55:53.039310Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.111628Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.199440Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.265831Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.352812Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.421639Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.507330Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.576358Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.663294Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.729889Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.817077Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.887240Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:53.971477Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.031414Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.110964Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.169305Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.243262Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.300053Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.390297Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.449249Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.522054Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.578900Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.653837Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.708822Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.782192Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.836983Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.909894Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:54.966976Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.040961Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.098204Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.171750Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.230459Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.308081Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.366400Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.442389Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.500467Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.575549Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.633376Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.712977Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.769988Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.847992Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.906371Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:55.980776Z  INFO text_generation_launcher: Using exllama kernels

2023-08-26T23:55:57.879732Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-26T23:55:57.900250Z  INFO shard-manager: text_generation_launcher: Shard ready in 14.931675025s rank=0
2023-08-26T23:55:57.987600Z  INFO text_generation_launcher: Starting Webserver
2023-08-26T23:55:59.443055Z  INFO text_generation_router: router/src/main.rs:367: Serving revision 48caaecfc0ca83f44d056a3f46d4c1661bbea1e7 of model TheBloke/MythoMax-L2-13B-GPTQ
2023-08-26T23:55:59.452758Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-08-26T23:56:11.299165Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: transport error
Error: Warmup(Generation("transport error"))
2023-08-26T23:56:11.411063Z ERROR text_generation_launcher: Webserver Crashed
2023-08-26T23:56:11.411132Z  INFO text_generation_launcher: Shutting down shards
2023-08-26T23:56:11.424793Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors. rank=0
2023-08-26T23:56:11.424860Z ERROR shard-manager: text_generation_launcher: Shard process was signaled to shutdown with signal 4 rank=0
```

</details>

Sometimes I don't get the `Shard complete standard error output` message.

### Information

- [X] Docker
- [x] The CLI directly

**Comment by Narsil** [comment]
Can you include the full stacktrace. All the messages you share are actually non issues (just warnings).

Signal 4 means illegal instruction. It's probably linked to the GPU underuse and/or cuda version. Do you mind sharing those ?

**Comment by Cyberes** [comment]
I don't have a stack trace, unfortunately. The logs I provided is the only output I get.

**Comment by Narsil** [comment]
Does this happen on every model like `TheBloke/starcoder-GPTQ` too ?

You can also try `-e DISABLE_EXLLAMA=True` in your command line.

Disabling exllama will leave only the triton kernel for GPTQ, which hopefully has better support.
I'm guessing it could be a bug in exllama.

**Comment by Cyberes** [comment]
Okay, making progress. `TheBloke/starcoder-GPTQ` loads with and without `-e DISABLE_EXLLAMA=True`. A different test model, `TheBloke/CodeLlama-7B-GPTQ`,  does not load.

I'm going to page @TheBloke since I know he's interested in TGI compatibility and there may be something odd going on.

**Comment by Cyberes** [comment]
Issue I noticed while watching the console, may or may not be related:

```2023-08-29T22:08:38.683211Z ERROR batch{batch_size=1}:prefill:prefill{id=4 size=1}:prefill{id=4 size=1}: text_generation_client: router/client/src/lib.rs:33: Server error: Unexpected <cl
ass 'RuntimeError'>: CUDA error: device-side assert triggered                                                                                                                             
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.                                                                                                                       
                                                                                             
2023-08-29T22:08:38.687697Z ERROR text_generation_launcher: Method ClearCache encountered an error.                                                                                       
Traceback (most recent call last):                                                                                                                                                        
  File "/opt/conda/bin/text-generation-server", line 8, in <module>                                                                                                                       
    sys.exit(app())                                                                                                                                                                       
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__                                                                                                      
    return get_command(self)(*args, **kwargs)                                         
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__                                                                                            [84/1887]
    return self.main(*args, **kwargs)                                                                                                                                                       File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main                                                                                                              return _main(                                                                                                                                                                           File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main                                                                                                             rv = self.invoke(ctx)                                                                                                                                                                   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke                                                                                                       
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                               
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke                                                                                                       
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                        
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke                                                                                                        
    return __callback(*args, **kwargs)                                                                                                                                                    
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper                                                                                                       
    return callback(**use_params)  # type: ignore                                                                                                                                         
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve                                                                                          
    server.serve(                                                                                                                                                                         
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve                                                                                      
    asyncio.run(                              
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run                                                                                                                     
    return loop.run_until_complete(main)                                                                                                                                                  
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete                                                                                                 
    self.run_forever()                                                                       
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever                                                                                                        
    self._run_once()                                                                                                                                                                      
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once                                                                                                         
    handle._run()                                                                                                                                                                         
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run                                                                                                                     
    self._context.run(self._callback, *self._args)           
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method                                                                 [56/1887]
    return await self.intercept(                                                                                                                                                          > File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept                                                                                  return await response                                                                                                                                                                   File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor                                                             raise error                                                                                                                                                                             File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor                                                         
    return await behavior(request_or_iterator, context)                                                                                                                                   
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 43, in ClearCache                                                                                  
    self.cache.delete(request.id)                                                                                                                                                         
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cache.py", line 26, in delete                                                                                       
    torch.cuda.empty_cache()                                                                                                                                                              
  File "/opt/conda/lib/python3.9/site-packages/torch/cuda/memory.py", line 133, in empty_cache                                                                                            
    torch._C._cuda_emptyCache()                                                                                                                                                           
RuntimeError: CUDA error: device-side assert triggered                                                                                                                                    
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.                                                                                                                       
                                                                                                                                                                                          
                                              
2023-08-29T22:08:38.689348Z ERROR batch{batch_size=1}:prefill:clear_cache{batch_id=Some(4)}:clear_cache{batch_id=Some(4)}: text_generation_client: router/client/src/lib.rs:33: Server err
or: Unexpected <class 'RuntimeError'>: CUDA error: device-side assert triggered                                                                                                           
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Narsil** [comment]
All this seems to be in your hardware/cuda setup.

Possibly linked to the flash/gptq/exllama kernels but it's impossible to say anything without further information.
Also if you can reproduce the faulty kernel with `CUDA_LAUNCH_BLOCKING=1` the stacktrace will become useful (currently it's meaningless because of the async nature of cuda).

**Comment by Cyberes** [comment]
But my hardware/cuda setup is an A4000 with your Docker image. As the lead dev, you should be interested in making sure your software works in your provided Docker image on an enterprise card.

Anyway, I reviewed my logs and found that **a specific set of parameters crashes the server** about 75% of the time:

```json
{
  "inputs": "What is Deep Learning?",
  "parameters": {
    "max_new_tokens": 1024,
    "repetition_penalty": 1.1,
    "seed": null,
    "stop": ["\nUser:", "\n### Instruction:", "\n### 2 to 3 Paragraph Response (engaging, natural, authentic, descriptive, creative, dialog):", "\nundefined"],
    "temperature": 0.7,
    "top_k": 100,
    "top_p": 0.95,
    "typical_p": 0.999,
    "watermark": false,
    "do_sample": true,
    "return_full_text": false,
    "details": true
  }
}
```

I've noticed that if it doesn't crash on the first specific request, it will crash on the second.


Here's the `CUDA_LAUNCH_BLOCKING=1` debug:

```
2023-08-30T17:01:31.723571Z ERROR text_generation_launcher: Method Decode encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 109, in Decode
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 834, in generate_token
    next_input_ids, next_token_logprobs = batch.next_token_chooser(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/tokens.py", line 229, in __call__
    scores = warper(input_ids, scores)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/logits_process.py", line 352, in __call__
    sorted_indices_to_remove = sorted_scores > sorted_scores.gather(
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2023-08-30T17:01:31.725491Z ERROR batch{batch_size=11}:decode:decode{size=11}:decode{size=11}: text_generation_client: router/client/src/lib.rs:33: Server error: Unexpected <class 'RuntimeError'>: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2023-08-30T17:01:31.730155Z ERROR text_generation_launcher: Method ClearCache encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 43, in ClearCache
    self.cache.delete(request.id)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cache.py", line 26, in delete
    torch.cuda.empty_cache()
  File "/opt/conda/lib/python3.9/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2023-08-30T17:01:31.731668Z ERROR batch{batch_size=11}:decode:clear_cache{batch_id=Some(21)}:clear_cache{batch_id=Some(21)}: text_generation_client: router/client/src/lib.rs:33: Server error: Unexpected <class 'RuntimeError'>: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2023-08-30T17:01:31.731771Z ERROR HTTP request{otel.name=POST /generate http.client_ip= http.flavor=1.1 http.host=172.0.2.140:6000 http.method=POST http.route=/generate http.scheme=HTTP http.target=/generate http.user_agent=curl/7.81.0 otel.kind=server trace_id=62516c6179fd3f06cbc7b026737eb727}:generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: 20, return_full_text: None, stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: None }}:generate{request=GenerateRequest { inputs: "What is Deep Learning?", parameters: GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: 20, return_full_text: None, stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: None } }}:generate_stream{request=GenerateRequest { inputs: "What is Deep Learning?", parameters: GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: 20, return_full_text: None, stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: None } }}:infer:send_error: text_generation_router::infer: router/src/infer.rs:554: Request failed during generation: Server error: Unexpected <class 'RuntimeError'>: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by Cyberes** [comment]
I spun up an A4000 with the TGI Docker container on Vast and got the same error, so it isn't just my machine.

After looking at the `HeterogeneousTypicalLogitsWarper` class, I set `typical_p` to a lower value (`0.99` instead of `0.999`) and the server did not crash. So, when `typical_p` is very close to 1 the warper is trying to keep only the most typical tokens but there might not be enough tokens left to generate a new token, especially if `max_new_tokens` is large.

**Comment by Narsil** [comment]
I think  your assumption about typical_p is correct.

In general extreme values of sampling tend to cause issues (temperature = 1e-4 is another one that comes to mind).

**Comment by Cyberes** [comment]
The main concern is that once the server hits this runtime error, all subsequent requests also trigger this error (even if the parameters are acceptable). Could the server maybe gracefully handle this so that it doesn't need to be restarted whenever a bad parameter is sent?

**Comment by Cyberes** [comment]
Checked dmesg and saw this:
```
traps: text-generation[1713525] trap invalid opcode ip:7fb007be3a0e sp:7ffff8a730a0 error:0 in rotary_emb.cpython-39-x86_64-linux-gnu.so[7fb007bd3000+1d000]
```

99% sure it's an AVX2 issue on this older CPU. I'm trying to load the model onto the GPU, so why is PyTorch trying to use AVX2? I previously got illegal instruction errors when I was trying to load models onto the CPU.
