### ISSUE TITLE
Code Llama error in AWS

### ISSUE THREAD

**Issue by WaterKnight1998** [huggingface/text-generation-inference#939]
### System Info

I am deploying CodeLlama with Sagemaker option.

The stacktrace I get is the following:
```


2023-08-28T16:49:18.489+02:00CopiarTraceback (most recent call last):  File "/opt/conda/bin/text-generation-server", line 8, in <module>    sys.exit(app())  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__    return get_command(self)(*args, **kwargs)  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__    return self.main(*args, **kwargs)  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main    return _main(  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main    rv = self.invoke(ctx)  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke    return _process_result(sub_ctx.command.invoke(sub_ctx))  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke    return ctx.invoke(self.callback, **ctx.params)  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke    return __callback(*args, **kwargs)  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper    return callback(**use_params)  # type: ignore  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve    server.serve(  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 175, in serve    asyncio.run(  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run    return loop.run_until_complete(main)  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete    self.run_forever()  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever    self._run_once()  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once    handle._run()  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run    self._context.run(self._callback, *self._args) | Traceback (most recent call last): File "/opt/conda/bin/text-generation-server", line 8, in <module> sys.exit(app()) File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__ return get_command(self)(*args, **kwargs) File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main return _main( File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main rv = self.invoke(ctx) File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper return callback(**use_params) # type: ignore File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve server.serve( File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 175, in serve asyncio.run( File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete self.run_forever() File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever self._run_once() File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once handle._run() File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run self._context.run(self._callback, *self._args)
-- | --
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

```python
import json
import sagemaker
import boto3
from sagemaker.huggingface import HuggingFaceModel, get_huggingface_llm_image_uri

try:
	role = sagemaker.get_execution_role()
except ValueError:
	iam = boto3.client('iam')
	role = iam.get_role(RoleName='sagemaker_execution_role')['Role']['Arn']

# Hub Model configuration. https://huggingface.co/models
hub = {
	'HF_MODEL_ID':'codellama/CodeLlama-34b-hf',
	'SM_NUM_GPUS': json.dumps(1)
}



# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
	image_uri=get_huggingface_llm_image_uri("huggingface",version="0.9.3"),
	env=hub,
	role=role, 
)

# deploy model to SageMaker Inference


predictor = huggingface_model.deploy(
	initial_instance_count=1,
	instance_type="ml.g5.2xlarge",
	container_startup_health_check_timeout=300,
  )
  
# send request
predictor.predict({
	"inputs": "My name is Clara and I am",
})
```

### Expected behavior

Endpoint should be deployed without errors.

**Comment by WaterKnight1998** [comment]
Got this issue while running locally in my computer:
```
/opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 197, in get_model
    return CausalLM(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 470, in __init__
    tokenizer = AutoTokenizer.from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 699, in from_pretrained
    raise ValueError(

ValueError: Tokenizer class CodeLlamaTokenizer does not exist or is not currently imported.
```

**Comment by Narsil** [comment]
Sagemaker doesn't have a release supporting codellama yet, please bear with us (release process always takes a lot of time)

**Comment by WaterKnight1998** [comment]
> Sagemaker doesn't have a release supporting codellama yet, please bear with us (release process always takes a lot of time)

It is supported in 1.0.2? So for example if i run in my kubernetes cluster it should work??

**Comment by Narsil** [comment]
Only `[sha-211b54a](https://github.com/orgs/huggingface/packages/container/text-generation-inference/122544029?tag=sha-211b54a)` at the moment.

We're releasing 1.0.3 as we speak.

**Comment by Narsil** [comment]
https://github.com/huggingface/text-generation-inference/pull/941

**Comment by WaterKnight1998** [comment]
@Narsil thank you for the information, I was trying 34B with 2xA100 using `ghcr.io/huggingface/text-generation-inference:1.0.2` and following args `["--model-id", "codellama/CodeLlama-34b-hf", "--disable-custom-kernels"]`

Results where not very good

**Comment by Narsil** [comment]
Please use `[sha-211b54a](https://github.com/orgs/huggingface/packages/container/text-generation-inference/122544029?tag=sha-211b54a)` . Codellama was released after 1.0.2. 1.0.3 will include codellama modifications.

**Comment by WaterKnight1998** [comment]
@Narsil and the argument `--disable-custom-kernels` isok?

**Comment by WaterKnight1998** [comment]
@Narsil any parameter that helps for inference? My results with `instruct-34B` are worse than the ones from [hc.co/chat](hc.co/chat)

**Comment by WaterKnight1998** [comment]
Thank you for sharing, I am going to check in detail. I tested the following parameters that I saw in netwrosk requests of WebUI, but is not working much better...
```
"parameters":{"max_new_tokens":1500, "temperature": 0.1, "repetition_penalty": 1.2, "top_p": 0.95, "top_k":50, "truncate":1000}
```
