### ISSUE TITLE
JSONDecodeError - with text_generation.Client

### ISSUE THREAD

**Issue by mse700** [huggingface/text-generation-inference#967]
### Feature request

Hello,

I have deployed falcon-40b. it works with API POST Requests when I use the documentation using URL.xxx/docs but there is an error with python request with the following code (in official READ ME):

```
from text_generation import Client

client = Client("http://link-to-deployt-url.xxx:5000/")
# print(client.generate("What is Deep Learning?", max_new_tokens=20).generated_text)

text = ""
for response in client.generate_stream("who are you?", max_new_tokens=200):
    if not response.token.special:
        text += response.token.text
print(text)
``` 

Error:
```
/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/j539180/IdeaProjects/untitled/chainlit_chatbot.py", line 19, in <module>
    print(falcon_llm("What is Deep Learning?"))
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/langchain/llms/base.py", line 806, in __call__
    self.generate(
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/langchain/llms/base.py", line 602, in generate
    output = self._generate_helper(
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/langchain/llms/base.py", line 504, in _generate_helper
    raise e
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/langchain/llms/base.py", line 491, in _generate_helper
    self._generate(
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/langchain/llms/base.py", line 981, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/langchain/llms/huggingface_text_gen_inference.py", line 163, in _call
    res = self.client.generate(prompt, **invocation_params)
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/text_generation/client.py", line 147, in generate
    payload = resp.json()
  File "/Users/j539180/IdeaProjects/untitled/work_venv/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

### Motivation

I am seeking for the solution

### Your contribution

Contribute

**Comment by Narsil** [comment]
Try looking at what happens when you generate the same request.

It could be many things here, for instance you cannot resolve the DNS where you are running the python.

**Comment by mse700** [comment]
It works as expected when using the request per documentation using browser. But the same DNS will result in [JSONDecodeError](https://github.com/huggingface/text-generation-inference/issues/967#top) error when using the python. The python is installed locally and has no problem with the DNS. It seems there is a problem with the response coming from the Model Endpoint. I am trying to use the  [HuggingFaceTextGenInference](https://python.langchain.com/docs/integrations/llms/huggingface_textgen_inference) but due to the above-mentioned problem it does not work.
![grafik](https://github.com/huggingface/text-generation-inference/assets/94875663/132c6772-f901-4ce0-9607-e51e79293ae9)

![grafik](https://github.com/huggingface/text-generation-inference/assets/94875663/992c9dfc-7a15-47e3-b692-9d6dbbe2bdc9)

**Comment by chainesanbuenaventura** [comment]
@mse700 did you find the solution? please share it here. thanks :)

**Comment by mse700** [comment]
Hi,
The Problem is that the proxy was enabled for our internal network. Then the URL was not responding, then the json reponse was empty. do you have an enabled proxy in your network??
