### ISSUE TITLE
The model download is incomplete, only three safetensors files were downloaded.

### ISSUE THREAD

**Issue by MochiXu** [huggingface/text-generation-inference#982]
### System Info

The model id is `meta-llama/llama-2-13b-chat-hf`
Here is docker log:
```
2023-09-06T02:08:31.646111506Z 2023-09-06T02:08:31.645947Z  INFO text_generation_launcher: Args { model_id: "meta-llama/llama-2-13b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: Some(1), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 4096, max_total_tokens: 4097, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: Some(4097), max_waiting_tokens: 20, hostname: "c330fb0de9e0", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-09-06T02:08:31.646186349Z 2023-09-06T02:08:31.646121Z  INFO download: text_generation_launcher: Starting download process.
2023-09-06T02:08:35.161237678Z 2023-09-06T02:08:35.161035Z  INFO text_generation_launcher: Download file: model-00001-of-00003.safetensors
2023-09-06T02:08:35.161258698Z 
2023-09-06T02:10:00.736042155Z 2023-09-06T02:10:00.735776Z  INFO text_generation_launcher: Downloaded /data/models--meta-llama--llama-2-13b-chat-hf/snapshots/0ba94ac9b9e1d5a0037780667e8b219adde1908c/model-00001-of-00003.safetensors in 0:01:25.
2023-09-06T02:10:00.736076750Z 
2023-09-06T02:10:00.736128799Z 2023-09-06T02:10:00.736041Z  INFO text_generation_launcher: Download: [1/3] -- ETA: 0:02:50
2023-09-06T02:10:00.736152033Z 
2023-09-06T02:10:00.736542576Z 2023-09-06T02:10:00.736470Z  INFO text_generation_launcher: Download file: model-00002-of-00003.safetensors
2023-09-06T02:10:00.736555089Z 
2023-09-06T02:11:28.381679070Z 2023-09-06T02:11:28.381350Z  INFO text_generation_launcher: Downloaded /data/models--meta-llama--llama-2-13b-chat-hf/snapshots/0ba94ac9b9e1d5a0037780667e8b219adde1908c/model-00002-of-00003.safetensors in 0:01:27.
2023-09-06T02:11:28.381719737Z 
2023-09-06T02:11:28.381732341Z 2023-09-06T02:11:28.381645Z  INFO text_generation_launcher: Download: [2/3] -- ETA: 0:01:26.500000
2023-09-06T02:11:28.381736138Z 
2023-09-06T02:11:28.382063190Z 2023-09-06T02:11:28.381947Z  INFO text_generation_launcher: Download file: model-00003-of-00003.safetensors
2023-09-06T02:11:28.382081094Z 
2023-09-06T02:12:23.012324254Z 2023-09-06T02:12:23.012114Z  INFO text_generation_launcher: Downloaded /data/models--meta-llama--llama-2-13b-chat-hf/snapshots/0ba94ac9b9e1d5a0037780667e8b219adde1908c/model-00003-of-00003.safetensors in 0:00:54.
2023-09-06T02:12:23.012356996Z 
2023-09-06T02:12:23.012363809Z 2023-09-06T02:12:23.012271Z  INFO text_generation_launcher: Download: [3/3] -- ETA: 0
2023-09-06T02:12:23.012365813Z 
2023-09-06T02:12:23.472754748Z 2023-09-06T02:12:23.472553Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-06T02:12:23.473008871Z 2023-09-06T02:12:23.472876Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-06T02:12:26.554700134Z 2023-09-06T02:12:26.554479Z ERROR text_generation_launcher: Error when initializing model
2023-09-06T02:12:26.554729209Z Traceback (most recent call last):
2023-09-06T02:12:26.554732395Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 487, in http_get
2023-09-06T02:12:26.554736072Z     download(url, temp_file.name, max_files, chunk_size, headers=headers)
2023-09-06T02:12:26.554739198Z Exception: No content length
2023-09-06T02:12:26.554741823Z 
2023-09-06T02:12:26.554759487Z The above exception was the direct cause of the following exception:
2023-09-06T02:12:26.554762643Z 
2023-09-06T02:12:26.554765087Z Traceback (most recent call last):
2023-09-06T02:12:26.554767662Z   File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
2023-09-06T02:12:26.554770197Z     resolved_config_file = cached_file(
2023-09-06T02:12:26.554773273Z   File "/opt/conda/lib/python3.9/site-packages/transformers/utils/hub.py", line 428, in cached_file
2023-09-06T02:12:26.554775728Z     resolved_file = hf_hub_download(
2023-09-06T02:12:26.554780607Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2023-09-06T02:12:26.554783092Z     return fn(*args, **kwargs)
2023-09-06T02:12:26.554785576Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
2023-09-06T02:12:26.554788051Z     http_get(
2023-09-06T02:12:26.554790526Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 496, in http_get
2023-09-06T02:12:26.554793151Z     raise RuntimeError(
2023-09-06T02:12:26.554795786Z RuntimeError: An error occurred while downloading using `hf_transfer`. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better error handling.
2023-09-06T02:12:26.554798962Z 
2023-09-06T02:12:26.554801296Z During handling of the above exception, another exception occurred:
2023-09-06T02:12:26.554803831Z 
2023-09-06T02:12:26.554806125Z Traceback (most recent call last):
2023-09-06T02:12:26.554808560Z   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-09-06T02:12:26.554810954Z     sys.exit(app())
2023-09-06T02:12:26.554813429Z   File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
2023-09-06T02:12:26.554815944Z     return get_command(self)(*args, **kwargs)
2023-09-06T02:12:26.554818409Z   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
2023-09-06T02:12:26.554820843Z     return self.main(*args, **kwargs)
2023-09-06T02:12:26.554823749Z   File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
2023-09-06T02:12:26.554826203Z     return _main(
2023-09-06T02:12:26.554828678Z   File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
2023-09-06T02:12:26.554831113Z     rv = self.invoke(ctx)
2023-09-06T02:12:26.554833547Z   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
2023-09-06T02:12:26.554837315Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-09-06T02:12:26.554839899Z   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
2023-09-06T02:12:26.554842635Z     return ctx.invoke(self.callback, **ctx.params)
2023-09-06T02:12:26.554845400Z   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
2023-09-06T02:12:26.554848285Z     return __callback(*args, **kwargs)
2023-09-06T02:12:26.554851171Z   File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
2023-09-06T02:12:26.554854076Z     return callback(**use_params)  # type: ignore
2023-09-06T02:12:26.554856782Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
2023-09-06T02:12:26.554859356Z     server.serve(
2023-09-06T02:12:26.554861841Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
2023-09-06T02:12:26.554864647Z     asyncio.run(
2023-09-06T02:12:26.554867522Z   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-09-06T02:12:26.554870347Z     return loop.run_until_complete(main)
2023-09-06T02:12:26.554873293Z   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
2023-09-06T02:12:26.554875978Z     self.run_forever()
2023-09-06T02:12:26.554878433Z   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
2023-09-06T02:12:26.554880958Z     self._run_once()
2023-09-06T02:12:26.554883432Z   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
2023-09-06T02:12:26.554885857Z     handle._run()
2023-09-06T02:12:26.554888301Z   File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
2023-09-06T02:12:26.554894533Z     self._context.run(self._callback, *self._args)
2023-09-06T02:12:26.554897439Z > File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
2023-09-06T02:12:26.554899893Z     model = get_model(
2023-09-06T02:12:26.554904142Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 119, in get_model
2023-09-06T02:12:26.554906767Z     config_dict, _ = PretrainedConfig.get_config_dict(
2023-09-06T02:12:26.554909221Z   File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
2023-09-06T02:12:26.554911646Z     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-09-06T02:12:26.554914080Z   File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 696, in _get_config_dict
2023-09-06T02:12:26.554916505Z     raise EnvironmentError(
2023-09-06T02:12:26.554919841Z OSError: Can't load the configuration of 'meta-llama/llama-2-13b-chat-hf'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'meta-llama/llama-2-13b-chat-hf' is the correct path to a directory containing a config.json file
2023-09-06T02:12:26.554923037Z 
2023-09-06T02:12:27.077433908Z 2023-09-06T02:12:27.077215Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
2023-09-06T02:12:27.077482160Z 
2023-09-06T02:12:27.077485877Z Traceback (most recent call last):
2023-09-06T02:12:27.077489033Z 
2023-09-06T02:12:27.077491568Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 487, in http_get
2023-09-06T02:12:27.077494473Z     download(url, temp_file.name, max_files, chunk_size, headers=headers)
2023-09-06T02:12:27.077497279Z 
2023-09-06T02:12:27.077499613Z Exception: No content length
2023-09-06T02:12:27.077503090Z 
2023-09-06T02:12:27.077505374Z 
2023-09-06T02:12:27.077507678Z The above exception was the direct cause of the following exception:
2023-09-06T02:12:27.077510163Z 
2023-09-06T02:12:27.077512427Z 
2023-09-06T02:12:27.077514752Z Traceback (most recent call last):
2023-09-06T02:12:27.077517206Z 
2023-09-06T02:12:27.077519511Z   File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
2023-09-06T02:12:27.077522076Z     resolved_config_file = cached_file(
2023-09-06T02:12:27.077524480Z 
2023-09-06T02:12:27.077526805Z   File "/opt/conda/lib/python3.9/site-packages/transformers/utils/hub.py", line 428, in cached_file
2023-09-06T02:12:27.077529269Z     resolved_file = hf_hub_download(
2023-09-06T02:12:27.077531694Z 
2023-09-06T02:12:27.077533988Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2023-09-06T02:12:27.077536443Z     return fn(*args, **kwargs)
2023-09-06T02:12:27.077538908Z 
2023-09-06T02:12:27.077541232Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
2023-09-06T02:12:27.077543677Z     http_get(
2023-09-06T02:12:27.077546392Z 
2023-09-06T02:12:27.077548726Z   File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 496, in http_get
2023-09-06T02:12:27.077551201Z     raise RuntimeError(
2023-09-06T02:12:27.077554237Z 
2023-09-06T02:12:27.077556621Z RuntimeError: An error occurred while downloading using `hf_transfer`. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better error handling.
2023-09-06T02:12:27.077559737Z 
2023-09-06T02:12:27.077562032Z 
2023-09-06T02:12:27.077564346Z During handling of the above exception, another exception occurred:
2023-09-06T02:12:27.077566811Z 
2023-09-06T02:12:27.077569075Z 
2023-09-06T02:12:27.077571379Z Traceback (most recent call last):
2023-09-06T02:12:27.077573754Z 
2023-09-06T02:12:27.077576068Z   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-09-06T02:12:27.077578453Z     sys.exit(app())
2023-09-06T02:12:27.077580938Z 
2023-09-06T02:12:27.077583282Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
2023-09-06T02:12:27.077596056Z     server.serve(
2023-09-06T02:12:27.077598922Z 
2023-09-06T02:12:27.077601266Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
2023-09-06T02:12:27.077603781Z     asyncio.run(
2023-09-06T02:12:27.077606196Z 
2023-09-06T02:12:27.077608530Z   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-09-06T02:12:27.077611105Z     return loop.run_until_complete(main)
2023-09-06T02:12:27.077613620Z 
2023-09-06T02:12:27.077615914Z   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2023-09-06T02:12:27.077618389Z     return future.result()
2023-09-06T02:12:27.077620783Z 
2023-09-06T02:12:27.077624310Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
2023-09-06T02:12:27.077626915Z     model = get_model(
2023-09-06T02:12:27.077629350Z 
2023-09-06T02:12:27.077631724Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 119, in get_model
2023-09-06T02:12:27.077634439Z     config_dict, _ = PretrainedConfig.get_config_dict(
2023-09-06T02:12:27.077636884Z 
2023-09-06T02:12:27.077639238Z   File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
2023-09-06T02:12:27.077641713Z     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-09-06T02:12:27.077644108Z 
2023-09-06T02:12:27.077646402Z   File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 696, in _get_config_dict
2023-09-06T02:12:27.077648827Z     raise EnvironmentError(
2023-09-06T02:12:27.077651792Z 
2023-09-06T02:12:27.077654668Z OSError: Can't load the configuration of 'meta-llama/llama-2-13b-chat-hf'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'meta-llama/llama-2-13b-chat-hf' is the correct path to a directory containing a config.json file
2023-09-06T02:12:27.077662543Z  rank=0
2023-09-06T02:12:27.176246626Z 2023-09-06T02:12:27.176057Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-06T02:12:27.176256575Z Error: ShardCannotStart
2023-09-06T02:12:27.176278847Z 2023-09-06T02:12:27.176081Z  INFO text_generation_launcher: Shutting down shards
```

### Information

- [x] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

I use [runpod](https://www.runpod.io/console/pods) to create docker container.
```
docker run -d --gpus all \
    --shm-size 1g \
    -e HUGGING_FACE_HUB_TOKEN=XXXXXX \
    -p 8080:80 \
    -e NUM_SHARD=1 \
    -e MAX_TOTAL_TOKENS=4097 \
    -e MAX_INPUT_LENGTH=4096 \
    -e MAX_BATCH_TOTAL_TOKENS=4097 \
    -v $volume:/data ghcr.io/huggingface/text-generation-inference \
    --model-id meta-llama/llama-2-13b-chat-hf
```

### Expected behavior

I expected the container start successfully.

**Comment by Narsil** [comment]
Seems like a network error, try again maybe ?
