### ISSUE TITLE
waiting for shard to be ready ..rank=0 for meta-llama/Llama-2-70b-chat-h

### ISSUE THREAD

**Issue by kbmlcoding** [huggingface/text-generation-inference#995]
### System Info

os version: Centos 7 with 4 Tesla GPU
model: meta-llama/Llama-2-70b-chat-h
output of nvidia-smi:

 NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   24C    P0    53W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1B:00.0 Off |                    0 |
| N/A   27C    P0    53W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:3D:00.0 Off |                    0 |
| N/A   27C    P0    55W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:3E:00.0 Off |                    0 |
| N/A   25C    P0    56W / 300W |      0MiB / 32768MiB |      2%      Default |
|                               |                      |                  N/A 

---command ran:
docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id $model

2023-09-07T15:47:12.896585Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-70b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "c31b30cf8302", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-09-07T15:47:12.896710Z  INFO download: text_generation_launcher: Starting download process.
2023-09-07T15:47:23.277707Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-09-07T15:47:24.809848Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-07T15:47:24.810027Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-07T15:47:34.823654Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:47:35.033143Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: GPU with CUDA capability 7 0 is not supported

2023-09-07T15:47:44.837068Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:47:54.849468Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:48:04.861188Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:48:14.873847Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:48:24.885718Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:48:34.897555Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:48:44.909524Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-09-07T15:48:48.260924Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 197, in get_model
    return CausalLM(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 527, in __init__
    super(CausalLM, self).__init__(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/model.py", line 39, in __init__
    self.check_initialized()
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/model.py", line 95, in check_initialized
    raise RuntimeError(
RuntimeError: found uninitialized parameters in model CausalLM: ['model.layers.74.self_attn.q_proj.weight', 'model.layers.74.self_attn.k_proj.weight', 'model.layers.74.self_attn.v_proj.weight', 'model.layers.74.self_attn.o_proj.weight', 'model.layers.74.mlp.gate_proj.weight', 'model.layers.74.mlp.up_proj.weight', 'model.layers.74.mlp.down_proj.weight', 'model.layers.74.input_layernorm.weight', 'model.layers.74.post_attention_layernorm.weight', 'model.layers.75.self_attn.q_proj.weight', 'model.layers.75.self_attn.k_proj.weight', 'model.layers.75.self_attn.v_proj.weight', 'model.layers.75.self_attn.o_proj.weight', 'model.layers.75.mlp.gate_proj.weight', 'model.layers.75.mlp.up_proj.weight', 'model.layers.75.mlp.down_proj.weight', 'model.layers.75.input_layernorm.weight', 'model.layers.75.post_attention_layernorm.weight', 'model.layers.76.self_attn.q_proj.weight', 'model.layers.76.self_attn.k_proj.weight', 'model.layers.76.self_attn.v_proj.weight', 'model.layers.76.self_attn.o_proj.weight', 'model.layers.76.mlp.gate_proj.weight', 'model.layers.76.mlp.up_proj.weight', 'model.layers.76.mlp.down_proj.weight', 'model.layers.76.input_layernorm.weight', 'model.layers.76.post_attention_layernorm.weight', 'model.layers.77.self_attn.q_proj.weight', 'model.layers.77.self_attn.k_proj.weight', 'model.layers.77.self_attn.v_proj.weight', 'model.layers.77.self_attn.o_proj.weight', 'model.layers.77.mlp.gate_proj.weight', 'model.layers.77.mlp.up_proj.weight', 'model.layers.77.mlp.down_proj.weight', 'model.layers.77.input_layernorm.weight', 'model.layers.77.post_attention_layernorm.weight', 'model.layers.78.self_attn.q_proj.weight', 'model.layers.78.self_attn.k_proj.weight', 'model.layers.78.self_attn.v_proj.weight', 'model.layers.78.self_attn.o_proj.weight', 'model.layers.78.mlp.gate_proj.weight', 'model.layers.78.mlp.up_proj.weight', 'model.layers.78.mlp.down_proj.weight', 'model.layers.78.input_layernorm.weight', 'model.layers.78.post_attention_layernorm.weight', 'model.layers.79.self_attn.q_proj.weight', 'model.layers.79.self_attn.k_proj.weight', 'model.layers.79.self_attn.v_proj.weight', 'model.layers.79.self_attn.o_proj.weight', 'model.layers.79.mlp.gate_proj.weight', 'model.layers.79.mlp.up_proj.weight', 'model.layers.79.mlp.down_proj.weight', 'model.layers.79.input_layernorm.weight', 'model.layers.79.post_attention_layernorm.weight', 'model.norm.weight', 'lm_head.weight']

2023-09-07T15:48:54.620357Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|██████████| 15/15 [01:03<00:00,  4.25s/it]
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 197, in get_model
    return CausalLM(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py", line 527, in __init__
    super(CausalLM, self).__init__(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/model.py", line 39, in __init__
    self.check_initialized()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/model.py", line 95, in check_initialized
    raise RuntimeError(

RuntimeError: found uninitialized parameters in model CausalLM: ['model.layers.74.self_attn.q_proj.weight', 'model.layers.74.self_attn.k_proj.weight', 'model.layers.74.self_attn.v_proj.weight', 'model.layers.74.self_attn.o_proj.weight', 'model.layers.74.mlp.gate_proj.weight', 'model.layers.74.mlp.up_proj.weight', 'model.layers.74.mlp.down_proj.weight', 'model.layers.74.input_layernorm.weight', 'model.layers.74.post_attention_layernorm.weight', 'model.layers.75.self_attn.q_proj.weight', 'model.layers.75.self_attn.k_proj.weight', 'model.layers.75.self_attn.v_proj.weight', 'model.layers.75.self_attn.o_proj.weight', 'model.layers.75.mlp.gate_proj.weight', 'model.layers.75.mlp.up_proj.weight', 'model.layers.75.mlp.down_proj.weight', 'model.layers.75.input_layernorm.weight', 'model.layers.75.post_attention_layernorm.weight', 'model.layers.76.self_attn.q_proj.weight', 'model.layers.76.self_attn.k_proj.weight', 'model.layers.76.self_attn.v_proj.weight', 'model.layers.76.self_attn.o_proj.weight', 'model.layers.76.mlp.gate_proj.weight', 'model.layers.76.mlp.up_proj.weight', 'model.layers.76.mlp.down_proj.weight', 'model.layers.76.input_layernorm.weight', 'model.layers.76.post_attention_layernorm.weight', 'model.layers.77.self_attn.q_proj.weight', 'model.layers.77.self_attn.k_proj.weight', 'model.layers.77.self_attn.v_proj.weight', 'model.layers.77.self_attn.o_proj.weight', 'model.layers.77.mlp.gate_proj.weight', 'model.layers.77.mlp.up_proj.weight', 'model.layers.77.mlp.down_proj.weight', 'model.layers.77.input_layernorm.weight', 'model.layers.77.post_attention_layernorm.weight', 'model.layers.78.self_attn.q_proj.weight', 'model.layers.78.self_attn.k_proj.weight', 'model.layers.78.self_attn.v_proj.weight', 'model.layers.78.self_attn.o_proj.weight', 'model.layers.78.mlp.gate_proj.weight', 'model.layers.78.mlp.up_proj.weight', 'model.layers.78.mlp.down_proj.weight', 'model.layers.78.input_layernorm.weight', 'model.layers.78.post_attention_layernorm.weight', 'model.layers.79.self_attn.q_proj.weight', 'model.layers.79.self_attn.k_proj.weight', 'model.layers.79.self_attn.v_proj.weight', 'model.layers.79.self_attn.o_proj.weight', 'model.layers.79.mlp.gate_proj.weight', 'model.layers.79.mlp.up_proj.weight', 'model.layers.79.mlp.down_proj.weight', 'model.layers.79.input_layernorm.weight', 'model.layers.79.post_attention_layernorm.weight', 'model.norm.weight', 'lm_head.weight']
 rank=0
2023-09-07T15:48:54.711663Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-07T15:48:54.711709Z  INFO text_generation_launcher: Shutting down shards

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Centos 7 with Tesla V100 gpu card 32 GB
model=meta-llama/Llama-2-70b-chat-h
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id $model

### Expected behavior

it should start the inference server as per the documentation guidelines

**Comment by Narsil** [comment]
You don't have enough memory to load everything.

Use a more recent card to get flash attention support (and therefore sharding too).

Also this is pretty worrying: 
```
found uninitialized parameters in model CausalLM: ['model.layers.74.self_attn.q_proj.weight', 'model.layers.74.self_attn.k_proj.weight', 'model.layers.74.self_attn.v_proj.weight', 'model.layers.74.self_attn.o_proj.weight', 
``` 

Seems like your files are somehow incomplete  (the safetensors files should contain those tensors, and those should be loaded onto the model, even if offloaded automatically with accelerate).

**Comment by kbmlcoding** [comment]
@Narsil so i need atleast 129G GPU memory or more based on below size of 70b llama model correct? any workaround that you can suggest so i can still use 70B llama2
129G	/data01/data/models--meta-llama--Llama-2-70b-chat-hf

i am not yet sure why some tensor files are incomplete as text-generation-inference only downloaded those files and i have encountered no errors during downloading those

**Comment by Narsil** [comment]
> i am not yet sure why some tensor files are incomplete as text-generation-inference only downloaded those files and i have encountered no errors during downloading those

Then that probably means it's just because accelerate had to offload them to disk

V100 + 32GB of VRAM is not enough to run 70b. You would need to use a GPTQ version of it and I still think you need a bigger GPU.
